### ISSUE TITLE
What happened?

### ISSUE THREAD

**Issue by ylluminate** [radareorg/cutter#1]
After our last thread regarding getting Homebrew in place and resolving the Travis issues with the question of what needs to be done in order to get Travis moving, I meandered over to see what may be going on and found the thread to be gone. After close inspection I discovered that the project had been moved / forked over here. While this seems appropriate, I had hoped that we could get some insight as to why this move was made and some of those threads we were discussing issues on vanished.

**Comment by Maijin** [comment]
@ylluminate yes the repo doesn't require @hteso to proceed, I'm currently checking travis for creating releases for linux, I'll see osx after.

**Comment by ylluminate** [comment]
Thanks, let me know if you need some help @Maijin. It should be pretty straightforward.

**Comment by Maijin** [comment]
yes I will need your assistance once the release is deployed to put that in brew I have no idea how, If you can join the telegram channel that'd ease

**Comment by Maijin** [comment]
https://t.me/iaito

**Comment by ylluminate** [comment]
Got an IRC bridge? Prefer to not use Telegram...

**Comment by Maijin** [comment]
Well @pancake @trufae can maybe look at this.
Just go buy a crappy sim

**Comment by radare** [comment]
Yeah will do soon or late.

**Comment by ylluminate** [comment]
Looks like you're getting this. I just found the dmg that was built @Maijin.

**Comment by Maijin** [comment]
yes I just produced one Linux and one dmg

**Comment by Maijin** [comment]
Can you try ? I think graph is broken but the app should launch

**Comment by ylluminate** [comment]
Yes, the app does launch:
![image](https://cl.ly/3m2T3d0K2z3M/Image%202017-09-27%20at%2011.06.30%20AM.png)

**Comment by Maijin** [comment]
yes this is known issue - graph doesn't work, the rest works fine.

**Comment by Maijin** [comment]
IRC now #cutter on irc.freenode.net

**Comment by ylluminarious** [comment]
@ylluminate @Maijin I see that there is discussion here about having this program in Homebrew. Just wanted to let you guys know that there is a [Homebrew Cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/cutter.rb) available.
