### ISSUE TITLE
Docker image appears to be broken

### ISSUE THREAD

**Issue by kidmose** [radareorg/cutter#1001]
**Environment information**
* Operating System: Linux Mint 18.2
* Cutter version: 1.7.2
* File format: N/A

**Describe the bug**
The docker image appear broken:

    error: exec: "/opt/cutter/build/Cutter": stat /opt/cutter/build/Cutter: no such file or directory

**To Reproduce**
1. Clone from git (`2b6e28d Clean build.sh and add install choice (#1000)`)
2. cd to `cutter/docker`
3. `make run`

**Expected behavior**
Cutter to launch in from docker, through X forwarding

**Screenshots**
N/A

**Additional context**

Terminal transcript with error:

    username@username-laptop ~/git-reps/cutter/docker $ make run 
    XSOCK=/tmp/.X11-unix && \
    XAUTH=/tmp/r2cutter_tmp.YXD.xauth && \
    xauth nlist $DISPLAY | sed -e 's/^..../ffff/' | xauth -f $XAUTH nmerge - && \
    chmod 644 $XAUTH && \
    touch /home/username/git-reps/cutter/docker/radare2rc && \
    mkdir -p /home/username/git-reps/cutter/docker/r2-config && \
    mkdir -p /home/username/git-reps/cutter/docker/sharedFolder && \
    sudo docker run \
    	-it \
    	--name cutter \
    	--cap-add=SYS_PTRACE \
    	-e DISPLAY=$DISPLAY \
    	-e XAUTHORITY=$XAUTH \
    	-e LOCAL_USER_ID=1000 \
    	-e LOCAL_GROUP_ID=1000 \
    	-v $XSOCK:$XSOCK:ro \
    	-v $XAUTH:$XAUTH \
    	 \
    	-v /home/username/git-reps/cutter/docker/sharedFolder:/var/sharedFolder \
    	-v /home/username/git-reps/cutter/docker/radare2rc:/home/r2/.radare2rc \
    	-v /home/username/git-reps/cutter/docker/r2-config:/home/r2/.config/radare2 \
    	radareorg/cutter:latest  && \
    rm $XAUTH
    Unable to find image 'radareorg/cutter:latest' locally
    latest: Pulling from radareorg/cutter
    5940862bcfcd: Pull complete 
    a496d03c4a24: Pull complete 
    5d5e0ccd5d0c: Pull complete 
    ba24b170ddf1: Pull complete 
    27481012795e: Pull complete 
    ed4f27bb706f: Pull complete 
    fbd30b0e5347: Pull complete 
    6005bd90b9bb: Pull complete 
    86483db98258: Pull complete 
    b1ee6545c691: Pull complete 
    Digest: sha256:4d47a8da29ef4c6357224553cde2b893f792d9e1ffd867ef3dc0add3be51e149
    Status: Downloaded newer image for radareorg/cutter:latest
    Cutter: Starting with UID:GID 1000:1000
    usermod: no changes
    usermod: no changes
    error: exec: "/opt/cutter/build/Cutter": stat /opt/cutter/build/Cutter: no such file or directory
    Makefile:37: recipe for target 'run' failed
    make: *** [run] Error 1

**Comment by kidmose** [comment]
I guess this might have slipped through because `build.sh` return ok with failure;
https://github.com/radareorg/cutter/blob/master/build.sh#L89 
(An because no test of docker image I guess too :))

**Comment by ITAYC0HEN** [comment]
@ps1337 , maybe you can help with this? :)

**Comment by ps1337** [comment]
Alright, I'll look into it :) thanks!

**Comment by xarkes** [comment]
Closed in #1054. Thanks :)
