### ISSUE TITLE
HexdumpWidget starts printing data from non-aligned address

### ISSUE THREAD

**Issue by pelijah** [radareorg/cutter#101]
HexdumpWidget starts printing data from non-aligned address. This looks ugly and leads to problems at adresses = 0 and 0xffffffffffffffff.

**Comment by xarkes** [comment]
What's the difference with #100?

**Comment by pelijah** [comment]
@xarkes, in #100 HexdumpWidget just continues printing data after reaching beginning of address space. Fix of bug #100 is impossible without fixing #101.
