### ISSUE TITLE
Add 'pdr' as decompiler option in the pseudocode window

### ISSUE THREAD

**Issue by radare** [radareorg/cutter#1038]
We need a way to display all the basic blocks of a function in Cutter, maybe just adding pdr in there is enough

**Comment by radare** [comment]
Also a rightclick in the functions widget may have an option to "display basic blocks" or "function information" in a dialog that we can copypaste that info if we need it. (or copy into clipboard as json?)

**Comment by ITAYC0HEN** [comment]
how pdr is decompiler? isn't it recursive disassemble?

**Comment by radare** [comment]
I think he wants a way to hold the output of a command that shows the function in a single place. Like pdf or pdr or pdsf

I also missed that but we cant consider those commands to be decompiling at all

**Comment by ITAYC0HEN** [comment]
This won't be implemented as part of cutter. Can be done as a plugin if someone wants it
