### ISSUE TITLE
Hasnext option not being observed

### ISSUE THREAD

**Issue by resech** [radareorg/cutter#1047]
**Environment information**
* Operating System: Windows 7 x64
* Cutter version: 1.7.3
* File format: DLL

**Describe the bug**
It doesn't look like the hasnext option under advanced analysis is working as intended.

**To Reproduce**
1. Drag the slider to advanced (far right).
2. Check the 'Continue analysis after each function (e! anal.hasnext)' option.
3. Click Ok.
4. Check the output of 'e anal.hasnext' in the console tab.

**Expected behavior**
I'd expect it to be set to True when the option was checked but it appears to be false regardless of the option being set or not.

**Additional context**
If I open a file without analysis (slider to the left) and set the hasnext option to true in the console and perform a standard analysis (aaa), I get a different number of functions returned with `afl~?`, which I expect. This makes me think it isn't an issue with the bundled version of radare.

**Comment by ITAYC0HEN** [comment]
Thank you for reporting this! This issue was really important and I'm surprised no one noticed this before.
This is now fixed :)
