### ISSUE TITLE
Debug layout is gone

### ISSUE THREAD

**Issue by xarkes** [radareorg/cutter#1050]
While debugging, the "reset layout" should reset to debug layout, or maybe we should rename reset to "default layout" and add a new item named "debug layout".

**Comment by ITAYC0HEN** [comment]
I prefer reset to return to debug layout

**Comment by fcasal** [comment]
Fixed in https://github.com/radareorg/cutter/commit/fec84f29419cc0b4b571fda6084c7d7e17ac5a31 but this probably should be cherrypicked to master since in fixes other issues with the debug/emul layout
