### ISSUE TITLE
Start debug button doesn't work

### ISSUE THREAD

**Issue by xarkes** [radareorg/cutter#1052]
Opened /bin/ls without any IO prefix (file://) and with analysis disabled.
When pressing start debug I get a:
```
File '' does not have executable permissions.
```

**Comment by fcasal** [comment]
Can't reproduce opening with `Cutter -A 0 /bin/ls`

**Comment by xarkes** [comment]
It's actually a bug in radare.
@trufae said `file://` was equivalent to nothing as a prefix, but it seems to be wrong actually.
Steps to reproduce:
```
r2 -c "ood" /bin/ls
```
vs
```
r2 -c "ood" file:///bin/ls
```

**Comment by xarkes** [comment]
Issue in radare2: https://github.com/radare/radare2/issues/13391
