### ISSUE TITLE
Continue until main doesn't work

### ISSUE THREAD

**Issue by xarkes** [radareorg/cutter#1053]
Tried to debug /bin/ls after analysis.
Start debug works, but when I hit the "continue until main" button, it just sends me to an invalid location.

**Comment by xarkes** [comment]
After exiting, you can get pretty graphs like this one:
![2019-01-03-135434_932x869_scrot](https://user-images.githubusercontent.com/10772605/50638735-22b35a80-0f5f-11e9-89c5-701c9981b3c7.png)

**Comment by xarkes** [comment]
From my understanding, the reason for that is that flags (symbols, function names, etc.) are set to a specific offset. However, when debugging PIE (almost every executable is position independent nowadays...) the old map is removed (hence the `invalid` instructions), the new maps are set depending on ASLR (`0x55xxxxxxxxxx` something on my machine) and the flags remain at the same location.
So AFAICT it is a bug in radare2, and I don't think of any smart fix right now.

**Comment by xarkes** [comment]
Related issue in radare2: https://github.com/radare/radare2/issues/13390

**Comment by radare** [comment]
we can merge the pr gthat rebases the breakpoints on the current program and this will work. but the idea was to design a proper solutioni that doesnt depends on just the main executable.

if thats blocking for u i would suggest you applying custom patches in cutter until the proper fix is available in r2land

**Comment by xarkes** [comment]
I don't think it's worth spending time doing custom patches.
I agree with designing a proper solution, is there a pad opened (or something) so that we can discuss it?

**Comment by ITAYC0HEN** [comment]
I cannot reproduce anymore. Is it fixed for you as well?

**Comment by yossizap** [comment]
This was fixed a long time
