### ISSUE TITLE
Fix/move/remove features in sidebar

### ISSUE THREAD

**Issue by thestr4ng3r** [radareorg/cutter#106]
This sidebar can be accessed by the right button in the toolbar:

![cutter_sidebar](https://user-images.githubusercontent.com/1460997/32915020-d090e9d4-cb17-11e7-9bcc-506dd026830a.png)

It is fixed to the right, which goes against the approach to have everything dockable and a lot is not implemented yet, so I think it should be removed while moving its useful parts somewhere else:

- [ ] Script part is not implemented at all => remove
- [ ] Calculator can be useful and is trivially implemented with CutterCore::math(), so maybe move it to an own QDockWidget
- [ ] Assembler/Disassembler works and could be useful too, what should we do with that?
- [ ] Quick Actions (order as in the layout):
  - The up arrow does nothing
  - Switching tab bars between top/bottom: not something you would use frequently, so if it is needed at all, it should not be somewhere in a menu
  - Toggle console: hides/shows the MainWindow's centralWidget, because that is where the console is, not a QDockWidget. Imo it would be better to hide it always and make the console a QDockWidget instead. Then it can be positioned freely as well. (not possible now)
  - Switch dark theme: Probably enough to have that in the menu.
  - Toggle responsiveness: same as above
  - Refresh all: Could theoretically be moved to the toolbar, but should ideally not be needed by the user anyway => just remove?
  - Lock/unlock interface: same as switching tab bars
  - Gear button at the bottom does nothing

**Comment by Maijin** [comment]
For 1.0 release I'd kill it actually

**Comment by XVilka** [comment]
Not sure about the actual need of the sidebar, yes. Remove script, since anyway it should be done another way - may be popping up the IPython console.

**Comment by thestr4ng3r** [comment]
removed it for 1.0.
