### ISSUE TITLE
Everything is Right2Left in GUI

### ISSUE THREAD

**Issue by Agent1101** [radareorg/cutter#1098]
**Environment information**
* Operating System: Windows 7 x64
* Cutter version: 1.7.3
* File format: exe

**Describe the bug**
I just loaded file and see what I did see! How can I change to Left2Right? should I change my system local? damn!

**Screenshots**
https://cdn1.imggmi.com/uploads/2019/1/12/1c4515b12ad1c95355f60101157286d2-full.png

**Comment by thestr4ng3r** [comment]
Qt adjusts itself to the system. What kind of locale settings do you have set in Windows? Is it rtl in general or is Cutter detecting it wrong?
