### ISSUE TITLE
If double click doesn't lead to a function -> Display Disassembly

### ISSUE THREAD

**Issue by Maijin** [radareorg/cutter#111]
Cutter should check If double click lead to a function, if not it should Display Disassembly not empty graph like:

![image](https://user-images.githubusercontent.com/1408600/33281563-f6948f50-d3a5-11e7-8e17-6ea11cdeaf5e.png)

**Comment by xarkes** [comment]
More precisely, it should check if there's a function, and if not switch to the other view when trying to display a graph, because you can still seek to a non function using other views.
