### ISSUE TITLE
Display destination instruction in "X-Refs from current address" in Sidebar

### ISSUE THREAD

**Issue by thestr4ng3r** [radareorg/cutter#113]
Currently only displays the current instruction, which is kind of useless.

**Comment by Maijin** [comment]
I'd remove that sidebar functionality as there is already `x` shortcut

**Comment by thestr4ng3r** [comment]
Couldn't there theoretically be multiple xrefs from? Also I think it is nice to have an overview for users who don't know there is the shortcut.
