### ISSUE TITLE
Add a widget to hold a list of buttons with an associated command to run

### ISSUE THREAD

**Issue by radare** [radareorg/cutter#1130]
This way we can easily have a list of commands you use to do, for example, analyzing a function or toggling a configuration variable. having a button in some panel or in the toolbar it will be useful.

Possible uses (and maybe default buttons setup):

* Toggle asm.bytes `e!asm.bytes`
* Analyze function recursively `afr`
* Dump current function to file

**Comment by xarkes** [comment]
Closing as this can be easily made as a plugin, and there's no real need to have it inside Cutter Core.
