### ISSUE TITLE
Grouping nodes 

### ISSUE THREAD

**Issue by XVilka** [radareorg/cutter#1134]
Good example of this kind of interface is here:

![image](https://user-images.githubusercontent.com/203261/51510536-63a0df80-1e38-11e9-824f-b169791e3e9e.png)

See corresponding radare2 bugs:

- https://github.com/radare/radare2/issues/12847
- https://github.com/radare/radare2/issues/2952
- https://github.com/radare/radare2/issues/6967

**Comment by Maijin** [comment]
Duplicate of #506
