### ISSUE TITLE
Add proper white theme for Cutter

### ISSUE THREAD

**Issue by xarkes** [radareorg/cutter#1136]
Default Cutter configuration is to use the native theme (GTK, whatever, ...) and so our default color theme is not very pretty.
Although it can be switched in the panel options, I think that we should find a way to dark if the native theme is light (all Windows user native theme is light) or dark, and have a default theme for each one, because it should just be fine by default.

**Comment by XVilka** [comment]
Dark, light... What about going even further and just selecting a base color, so you can set it to black (Dark), white (Light), yellow, pink or blue? And calculate all shades based on this color.
