### ISSUE TITLE
can not run the docker correctly 

### ISSUE THREAD

**Issue by tfrnghub** [radareorg/cutter#1138]
root1@ubuntu:~$ docker image list
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
radareorg/cutter    latest              c00c6a238c81        3 weeks ago         1.41GB

root1@ubuntu:~$  docker run -it radareorg/cutter
Cutter: Starting with UID:GID :
usermod: invalid user ID 'r2'
Usage: usermod [options] LOGIN

Options:
  -c, --comment COMMENT         new value of the GECOS field
  -d, --home HOME_DIR           new home directory for the user account
  -e, --expiredate EXPIRE_DATE  set account expiration date to EXPIRE_DATE
  -f, --inactive INACTIVE       set password inactive after expiration
                                to INACTIVE
  -g, --gid GROUP               force use GROUP as new primary group
  -G, --groups GROUPS           new list of supplementary GROUPS
  -a, --append                  append the user to the supplemental GROUPS
                                mentioned by the -G option without removing
                                him/her from other groups
  -h, --help                    display this help message and exit
  -l, --login NEW_LOGIN         new value of the login name
  -L, --lock                    lock the user account
  -m, --move-home               move contents of the home directory to the
                                new location (use only with -d)
  -o, --non-unique              allow using duplicate (non-unique) UID
  -p, --password PASSWORD       use encrypted password for the new password
  -R, --root CHROOT_DIR         directory to chroot into
  -s, --shell SHELL             new login shell for the user account
  -u, --uid UID                 new UID for the user account
  -U, --unlock                  unlock the user account
  -v, --add-subuids FIRST-LAST  add range of subordinate uids
  -V, --del-subuids FIRST-LAST  remove range of subordinate uids
  -w, --add-subgids FIRST-LAST  add range of subordinate gids
  -W, --del-subgids FIRST-LAST  remove range of subordinate gids
  -Z, --selinux-user SEUSER     new SELinux user mapping for the user account

error: exec: "/opt/cutter/build/Cutter": stat /opt/cutter/build/Cutter: no such file or directory

**Comment by ITAYC0HEN** [comment]
Yo yo, @ps1337 our Docker guy - can you have a look here? :P
I know nothing about containers :))

**Comment by ps1337** [comment]
Thanks, I'm looking into it

**Comment by ps1337** [comment]
@tfrnghub if you want you can try it now by building the image locally using `make build-nc` after `cd` in to the `docker` folder. Cheers.

**Comment by gaasedelen** [comment]
FYI, I tried to pull & run from dockerhub today and the old (or broken) build still appears to be up.

```
doom@ubuntu:~$ sudo docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
radareorg/cutter    latest              c00c6a238c81        3 months ago        1.41GB

doom@ubuntu:~$ sudo docker run radareorg/cutter
Cutter: Starting with UID:GID :
usermod: invalid user ID 'r2'
Usage: usermod [options] LOGIN

Options:
  -c, --comment COMMENT         new value of the GECOS field
  -d, --home HOME_DIR           new home directory for the user account
  -e, --expiredate EXPIRE_DATE  set account expiration date to EXPIRE_DATE
  -f, --inactive INACTIVE       set password inactive after expiration
                                to INACTIVE
  -g, --gid GROUP               force use GROUP as new primary group
  -G, --groups GROUPS           new list of supplementary GROUPS
  -a, --append                  append the user to the supplemental GROUPS
                                mentioned by the -G option without removing
                                him/her from other groups
  -h, --help                    display this help message and exit
  -l, --login NEW_LOGIN         new value of the login name
  -L, --lock                    lock the user account
  -m, --move-home               move contents of the home directory to the
                                new location (use only with -d)
  -o, --non-unique              allow using duplicate (non-unique) UID
  -p, --password PASSWORD       use encrypted password for the new password
  -R, --root CHROOT_DIR         directory to chroot into
  -s, --shell SHELL             new login shell for the user account
  -u, --uid UID                 new UID for the user account
  -U, --unlock                  unlock the user account
  -v, --add-subuids FIRST-LAST  add range of subordinate uids
  -V, --del-subuids FIRST-LAST  remove range of subordinate uids
  -w, --add-subgids FIRST-LAST  add range of subordinate gids
  -W, --del-subgids FIRST-LAST  remove range of subordinate gids
  -Z, --selinux-user SEUSER     new SELinux user mapping for the user account

error: exec: "/opt/cutter/build/Cutter": stat /opt/cutter/build/Cutter: no such file or directory

```

This is on a fresh ubuntu 18.04 desktop VM.

**Comment by ps1337** [comment]
docker hub says `This repository doesn't have any autobuilds` o.O

Can someone with access to the build chain look into this?

**Comment by xarkes** [comment]
Oh indeed, here you can see the last log: https://pastebin.com/mDEZrrM4

**Comment by ITAYC0HEN** [comment]
@ps1337 what is your insights on this one? :)
you think it is solved?

**Comment by ps1337** [comment]
Heyo,

yes this is solved since we have a new docker image.

Greetings 

-----Original Message-----

**Comment by ITAYC0HEN** [comment]
Thanks mate! closing this issue then
