### ISSUE TITLE
Do something with PreviewWidget

### ISSUE THREAD

**Issue by thestr4ng3r** [radareorg/cutter#114]
Mini-Graph was removed and Pseudocode doesn't work anymore. I don't know what the Preview Tab inside it should do exactly do.

In my opinion, we should simple disable it for 1.0.

![bildschirmfoto vom 2017-11-28 15-27-07](https://user-images.githubusercontent.com/1460997/33324693-a43bfc7e-d450-11e7-9a87-1033462459e6.png)

**Comment by xarkes** [comment]
Yes I agree we can simply kill it.
