### ISSUE TITLE
dir.projects doesn't change

### ISSUE THREAD

**Issue by bqlyhy** [radareorg/cutter#1148]
(win10x64, radare2_msvc_64-3.2.1,  Cutter-v1.7.4-x64.Windows)

When in "open file" window "projects" tab, press the "select" button and choose another path won't change `dir.projects`, it remains last time used path or default path. And projects won't be listed when using a custom `dir.projects`. 
sorry for the broken English.

--- 
**Fixed:**
_Is there an option to show code xrefs comments( just like "pd" after "aaa" in no gui radare2 e.g [; CODE XREFS from fcn.006714e0 (+0x1a88, +0x1a9a)]) in disassembly and graph view?
I know we can press "x" key to show xrefs when select an address. But it will be better to know where code xrefs happens in (nofunc) area._

----

**Comment by xarkes** [comment]
Hello,
> Is there an option to show code xrefs comments( just like "pd" after "aaa" in no gui radare2 e.g [; CODE XREFS from fcn.006714e0 (+0x1a88, +0x1a9a)]) in disassembly and graph view?

Well it seems the option is missing from the option panel, but yes there is, you can set `e asm.xrefs = true` in the console to activate it, and it should work (at least in the disassembly widget).

> Another small problem, when in "open file" window "projects" tab, press the "select" button and choose other path won't change dir.projects, it remains last time used path or default path . And projects won't be listed when use a custom dir.projects.

Hmm I see, we should add an option to change the path :)

**Comment by ITAYC0HEN** [comment]
first issue closed in #1150

**Comment by Coualafool** [comment]
Hello, I encountered the same problem when I try to change the default access path of Cutter but I have not found solutions. Have you found one?

**Comment by Maijin** [comment]
Projects are currently not usable and work in progress as they requires huge refactoring in radare2 side.
