### ISSUE TITLE
String display off by one error

### ISSUE THREAD

**Issue by oliv3r** [radareorg/cutter#1151]
**Environment information**
* Operating System: Debian Linux Buster
* Cutter version: 1.7.4
* File format: elf

**Describe the bug**
A decoded string has some fuzz appended. It appears that it's always the last character from the string. So I think that the UI copies/overwrites the string as the 'str.' prefix is 1 longer then the two quotes in the final string?

**To Reproduce**
1. Go to 'any function that has some strings in it'
2. Click on 'pesuedocode & refresh'
3. Scroll down to 'the string in question'

**Expected behavior**
No extra characters after the closing quote (unless \0 is intended, and then it should be listed as \0)

**Screenshots**
![image](https://user-images.githubusercontent.com/1245341/51981083-3a183180-2492-11e9-87ad-783aa0bb69ef.png)

**Comment by oliv3r** [comment]
Actually, it's the pseudocode widget, I think so yes, and yes :)
[spi2k7.zip](https://github.com/radareorg/cutter/files/2813072/spi2k7.zip)

Find attached the binary, you can see it stright in main the function is really short so should spot several instances easily :)

**Comment by xarkes** [comment]
The bug is in `pseudo.c` inside radare2 code base.

**Comment by xarkes** [comment]
Tracking it in radare2 repository now. Closing this.

**Comment by radare** [comment]
its fixed now
