### ISSUE TITLE
"Start debug" is broken on Windows

### ISSUE THREAD

**Issue by xarkes** [radareorg/cutter#1162]
I tried on Windows 10 64 bits (1809) and this is the result:
![2019-02-04-171431_1912x1007_scrot](https://user-images.githubusercontent.com/10772605/52221079-ad5de100-28a0-11e9-9c83-3ea1add9f220.png)

As you can see, the registers panel is empty, the backtrace panel is empty, the seek is wrong, etc.
In addition to that, Cutter takes approximately 5 seconds to respond after clicking the button (same when clicking on stop) while it should be instantaneous.

**Comment by ITAYC0HEN** [comment]
Unrelated: what happened to the theme? shouldn't happen. Can you reproduce and open an issue?

**Comment by xarkes** [comment]
It is the same issue as that https://github.com/radareorg/cutter/issues/1161.

**Comment by yossizap** [comment]
I merged the debug branch with upstream in my fork and couldn't replicate the issue on Windows 10 64bits, might have been fixed by changes in radare/cutter?
