### ISSUE TITLE
Replace QSyntaxHighlighter with KSyntaxHighlighting 

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/cutter#1170]
Currently, Cutter uses QSyntaxHighlighter as its code highlighter in several places. These places include the function's prototype and decompiler output. There is no doubt, QSyntaxHighlighter is ugly. Very ugly. It is so ugly that even QT Creators doesn't use it. We better get rid of it asap.
Kate editor's syntax highlighter, [KSyntaxHighlighting](https://api.kde.org/frameworks/syntax-highlighting/html/index.html), is the de facto code highlighter framework for QT applications. [QT Creator uses it](https://kate-editor.org/2016/11/15/ksyntaxhighlighting-a-new-syntax-highlighting-framework/) KDE, and other famous open-source software.

**Describe the solution you'd like**
In the first step, implement KSyntaxHighlighting inside Cutter and replace QSyntaxHighlighter with it. Later, choose a theme that fits both dark and light QT themes. Then, ship few themes with Cutter and add a dialog to the Appearance Option Dialog to let the user choose their favorite theme. 

![image](https://user-images.githubusercontent.com/20182642/52398869-32284500-2ac3-11e9-91d6-a21e271ead0d.png)

![image](https://user-images.githubusercontent.com/20182642/52398863-2c326400-2ac3-11e9-9a06-fe8182d96bc5.png)

![image](https://user-images.githubusercontent.com/20182642/52398859-29377380-2ac3-11e9-9be3-1fd57f0e9a36.png)

![image](https://user-images.githubusercontent.com/20182642/52398851-23419280-2ac3-11e9-97b5-eef9c79f76f2.png)

**Comment by dmknght** [comment]
will KSyntax will fix highlight issue, which hasn't completely fixed?

**Comment by ITAYC0HEN** [comment]
which highlight issue?

**Comment by dmknght** [comment]
This one #798

**Comment by ITAYC0HEN** [comment]
Ahh no, this isn't the same highlighting. Syntax Highlighting will color programming language code as we have in our Decompiler and in our Function prototype. We talk about the colors of the text, not a selection of it by the mouse. As you have in any other IDE

**Comment by ITAYC0HEN** [comment]
Thanks @thestr4ng3r this is now fixed
