### ISSUE TITLE
Disappearing Text when asm.describe is enabled

### ISSUE THREAD

**Issue by securitykitten** [radareorg/cutter#1176]
**Environment information**
* Operating System:  Fedora 29 x64
* Cutter version:  1.7.4 (appimage) 
* File format: NES Rom

**Describe the bug**
Lines disappear when scrolling through a function with asm.describe set to True.  The lines do not disappear when asm.describe is set to False.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open the following binary with default options  [hackingtime.zip](https://github.com/radareorg/cutter/files/2842405/hackingtime.zip)
2. Browse to `fcn.000082f1` in the disassembly Window
3. Scroll to the end of the function to verify that no problem exists
4. Browse back to the top of the function, this time select "Show opcode description (asm.describe)" under preferences.
5.  Now attempt to scroll.  Text should disappear.

**Expected behavior**
Scroll through function with asm.describe enabled.

**Screenshots**
![peek 2019-02-07 14-46](https://user-images.githubusercontent.com/5833122/52438485-5c8bf980-2ae7-11e9-91ee-d047e21b18a4.gif)

**Comment by xarkes** [comment]
If you started Cutter from console, I bet you have some warnings and/or errors.
Could you please paste the logs here? Thanks.

**Comment by securitykitten** [comment]
Sure thing, sorry about that.

I think the line that you're interested in is:

`Failed to parse JSON for command "agJ 0x000082f1": unterminated object`
and
`Failed to parse JSON for command "pdJ 27 @ 33532": unterminated object`

Full log here:
[output.txt](https://github.com/radareorg/cutter/files/2842509/output.txt)

**Comment by a1ext** [comment]
Probably duplicate of #1137

**Comment by a1ext** [comment]
Yeah, exactly. Problem is on radare2-side, CC @radare

**Comment by ITAYC0HEN** [comment]
r2 fails to parse the json object

**Comment by a1ext** [comment]
R2 serializes json in wrong way

**Comment by philipmnelson** [comment]
So, did r2 change the way it parses JSON recently?

**Comment by ITAYC0HEN** [comment]
This is now fixed. Please let me know if the problem still occurs with the latest Cutter and radare2 :)
As usual, thank you so much for reporting

**Comment by ITAYC0HEN** [comment]
hey @securitykitten :) Can you please reach me out on Telegram\Twitter\Email? I couldn't find anyway to ping you
