### ISSUE TITLE
Hashes in Overview missing

### ISSUE THREAD

**Issue by Maijin** [radareorg/cutter#1179]
**Describe the bug**

<img width="572" alt="image" src="https://user-images.githubusercontent.com/1408600/52503503-2772ca80-2bff-11e9-872f-31efa6cc69d4.png">

**Expected behavior**
Hash are displayed in overview

**Additional context**
Hashes moved from `iIj` command to `iFj`, however the current JSON is incorrect, the command must be properly rewritten using pj.c in radare2.

**Comment by philipmnelson** [comment]
Working on this issue, this is in the dashboard widget, correct?

**Comment by Maijin** [comment]
yes

**Comment by philipmnelson** [comment]
I'm actually gonna have to leave this one to work on. I'm still trying to grok pj.c in radare2.

**Comment by Maijin** [comment]
Example of refactoring can be found here - https://github.com/radare/radare2/pull/12822/files#diff-9a7bcc9d9f9b6439c4d8b9301f1d46ccL888 nothing fancy.

**Comment by philipmnelson** [comment]
Is [this](https://github.com/radare/radare2/pull/13025) related?

**Comment by Maijin** [comment]
In progress here https://github.com/radare/radare2/pull/12989/files

**Comment by ITAYC0HEN** [comment]
pr merged. Can we close this? @Maijin

**Comment by philipmnelson** [comment]
I tried building r2 with the merged pr and I'm still getting incorrectly serialized json. I don't think we can close it yet.

**Comment by ITAYC0HEN** [comment]
did you update r2 submodulke?

**Comment by Maijin** [comment]
Indeed the r2 fix is not good enough and Cutter will also need to be updated after to use iFj. So no we can't close yet

**Comment by philipmnelson** [comment]
I did update the submodule. The pr wasn't the right fix for this issue.

**Comment by Maijin** [comment]
The command is under `itj` see:

```
[0x1000011ec]> itj
{"values":"md5 dd111f5744e87c6eedd5f978833a0cdb\nsha1 1461b5d708822709d40337192c84ba1bed4f6622"}
[0x1000011ec]>
```

**Comment by xarkes** [comment]
`RBinInfo->hashes` is a char* which imho sucks so I don't know what a proper fix would be.
Maybe make `hashes` a HashMap?

**Comment by a1ext** [comment]
Waiting for the next r2 release to update submodule and fix this issue
