### ISSUE TITLE
Homebrew Release

### ISSUE THREAD

**Issue by alichtman** [radareorg/cutter#1182]
It'd be awesome if you could install this with:

`$ brew cask install cutter` or `$ brew cask install radare2-cutter`

The advantages of installing with homebrew, from the perspective of the user, are:

1. It makes staying on top of updates super easy
2. It provides for a very portable development environment

**Comment by ndaprela** [comment]
You can: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/cutter.rb

**Comment by alichtman** [comment]
Oh cool! This should be added to the README.
