### ISSUE TITLE
Use QSettings IniFormat instead of NativeFormat	when releasing Cutter 1.8

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/cutter#1183]
While in Linux, the location of Cutter.conf is quite comfortable (`$HOME/.config/OrgName/AppName`), on Windows machines, the settings are saved into the Registry in this way:

![image](https://user-images.githubusercontent.com/20182642/52621707-a80c2200-2eb0-11e9-9457-b3687fb4e29d.png)

In my opinion, saving settings to the registry -- instead of a file -- is not comfortable to tweak manually or to share with others or between computers. This is why I suggest using `QSettings::IniFormat`.

Doing this would save the settings file to:
**Unix and Mac OS X:** $HOME/.config/cutter.ini 
**Windows:** %APPDATA%\cutter.ini

-----
Although it requires to modify a single line to make this change, this will cause issues to current users that would lose their settings. This is why we need to only introduce these changes in a major subversion, which is 1.8. Until then, we will track this issue here.

----

**Further reading:**
[Qt - QSettings Class Reference](https://doc.qt.io/qt-5/qsettings.html)

**Comment by Maijin** [comment]
I also +1 .ini for sharing capability :)

**Comment by a1ext** [comment]
+1
P.S. we have to preserve user settings during switch to the new format

**Comment by philipmnelson** [comment]
Also +1
But we can't break user settings during switch as @a1ext mentioned.

**Comment by XVilka** [comment]
Just providing a small python/native tool for migration should be enough and easier probably.
