### ISSUE TITLE
Double click in CommentsWidget does not work in nested mode

### ISSUE THREAD

**Issue by thestr4ng3r** [radareorg/cutter#119]
CommentsWidget has a second mode where it displays comments in a tree (right click -> vertical).
Double click does not work from there.

**Comment by xarkes** [comment]
Is the nested view even useful?
It looks like you just have to add a slot named on_nestedCmtsTreeWidget_itemDoubleClicked so it autoconnects to the .ui and somehow manager to retrieve the offset from the first column.
