### ISSUE TITLE
The graph does not detect functions.

### ISSUE THREAD

**Issue by JorgeTebruski** [radareorg/cutter#1197]
**Environment information**
* Operating System: windows 10
* Cutter version: 1.7.4
* Radare2 version:  r2-3.2.1-341-g821a53374
* File format: pe
 * Arch: x86
 * Type: EXEC (Executable file)

**Describe the bug**
The graph does not detect functions, but the disassembly normally detects.

**To Reproduce**
1. Open any executable file
2. Select any function
3. Go to the graph

**Expected behavior**
The graph correctly shows the function.

**Screenshots**
![anotacao 2019-02-15 012625](https://user-images.githubusercontent.com/38569298/52832695-ca748a00-30c0-11e9-9555-2148af9485ea.jpg)

**Additional context**
Downloaded from AppVeyor and the problem occurs after the commit https://github.com/radareorg/cutter/commit/fe49aa8e13e159996e62294ae602c1d29ca42f38

**Comment by Adikso** [comment]
Yes, there was a "blind" change. @thestr4ng3r is already working to fix this but still thanks for reporting ;)

**Comment by ITAYC0HEN** [comment]
fixed :)
