### ISSUE TITLE
Do something with SDB Browser

### ISSUE THREAD

**Issue by thestr4ng3r** [radareorg/cutter#120]
![bildschirmfoto vom 2017-12-02 20-19-41](https://user-images.githubusercontent.com/1460997/33518986-2a263502-d79e-11e7-813e-0d3da1ac0fb9.png)
It is kind of an unnecessary feature for 1.0 imo, so we could theoretically just disable/remove it.
But since it seems to work more or less (do a complete refresh to see contents) maybe it is also easy to fix and make stable.

**Comment by xarkes** [comment]
Nah I think it might be useful, and I think it's very easy to fix.
