### ISSUE TITLE
View content of defined types (structs, enums, ...)

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/cutter#1207]
Add the option to view the contents of types, structs, enums, etc

This probably can be done with `tsc`, `ttc`, `tuc`, etc, though it would be even better to format the output in C-style (indention, etc)
```
[0x00000000]> "td struct foo {char* a; int b;}"
[0x00000000]> tsc foo
struct foo {char * a; int32_t b;};
```

This should be done when double clicking a Type and also in a context menu (right-click).

Syntax highlighting should be applied

**Comment by Maijin** [comment]
Maybe instead could add an intermediary windows for the export capability

**Comment by ITAYC0HEN** [comment]
Export is for all types while this is a simpler view of a single one

![image](https://user-images.githubusercontent.com/20182642/53106330-7b54ac00-353b-11e9-9bc7-2a685c6f9530.png)

**Comment by Maijin** [comment]
Then that's a bug, export should be defined by the selected one and we should have export all

**Comment by ITAYC0HEN** [comment]
We can have 3 things

1. Right click (anywhere) - > export all
2. Right click on a single type - > export type. This should also work on multi-selection and will export all the selected types
3. Right click on a type -> View Type - will show a dialog with the Type contents as well as two buttons for "Edit" and "Export"

@m0nk3ydluffy your opinion here please

**Comment by m0nk3ydluffy** [comment]
Currently we only have the option to export all the types. It would be nice to implement the features in the way @ITAYC0HEN has described. This would require some changes in r2 side since the commands like `tsc` etc. do not give output for a single type.
I would like to work on this issue and #1208 since both are related.

**Comment by Maijin** [comment]
@m0nk3ydluffy go ahead

**Comment by Maijin** [comment]
Please prioritize this one though: https://github.com/radareorg/cutter/issues/1073. It's nice to be able to edit, export etc. But the main objective for this panel is to be able to edit the disassembly, without #1073 the whole purpose of this panel is quite useless 👍

**Comment by ITAYC0HEN** [comment]
indeed :)

**Comment by m0nk3ydluffy** [comment]
@Maijin Cool. I'll work on those issues first.
