### ISSUE TITLE
Improve rename shortcut

### ISSUE THREAD

**Issue by xarkes** [radareorg/cutter#1211]
Currently to rename a function one must press "Shift + N" while I think "N" is better.
Also I think the item in the menu should be "Rename" and handle automatically if it's a function, a local variable, etc.

- [ ] Move `Shift+N` to `N` shortcut
- [ ] Merge `Y` "Rename local" into `N` "rename" shortcut
- [ ] Merge "Add flag" to `N` when focusing on a line of code with no symbol

I think this will greatly improve the UX and reduce UI noise (delete 2 items from the context menu which is already big enouh IMHO)

**Comment by Kezii** [comment]
Also, it should give a warning if the name you typed already exists
And, the popup window should open with the text already selected, so you don't have to delete the old name and then type the new name

**Comment by ITAYC0HEN** [comment]
This can be an Issue when there is a flag\fcn reference in the first line of a funciton. Pressing N is used to rename function. Shift+N to ranme flags. But currently if you will click on the first instruction of  af function it will consider it as you clicked the function description (name, prototype, etc)

**Comment by xarkes** [comment]
Hello, I updated the original issue to better detail my request.
I think this will improve the UX and reduce UI noise (i.e. remove two menus from the context menu which is already quite big)

**Comment by xarkes** [comment]
Closed in #2468
