### ISSUE TITLE
Segfault upon docking two graphs together

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/cutter#1216]
**Environment information**
* Operating System: Linux
* Cutter version: Newest
* File format: Any

**Describe the bug**
Upon opening two graph widgets and docking them together to the main window, Cutter is receiving a segfault. @Vane11ope reproduced the bug and will be responsible to fix it

**To Reproduce**
1. Open a binary in Cutter
2. Go to graph widget which is in the main dock
3. Go to Windows > Add extra... > Graph
4. Dock the new graph with the old one
5. Cutter freezes and Segfault

You can follow the steps in the gif below.

**Expected behavior**
Everything should go smoothly

**Screenshots**
![2019-02-24_10-07-25](https://user-images.githubusercontent.com/20182642/53296787-0a9fdf00-381c-11e9-9b08-8868d06fc76c.gif)

**Comment by xarkes** [comment]
The fix in #1218 breaks the spacebar shortcut.
So find another way to fix it before release, thanks :-)
