### ISSUE TITLE
Couple of issues regarding Graph Overview

### ISSUE THREAD

**Issue by Vane11ope** [radareorg/cutter#1221]
Env: Ubuntu 16.04 LTS

1. Overview does not update its contents when seek changed with Graph closing.
2. Overview will be gone completely after 
---
how-to:
1. go to disas
2. seek to somewhere else where no function is detected
3. go to Graph
4. seek to somewhere else where Graph exists

gif would tell you more anyway so let me just attach gifs for them quickly.

![gifrecord_2019-02-27_193421](https://user-images.githubusercontent.com/29271244/53484831-17485f80-3ac8-11e9-9fd4-475346039dbf.gif)
![gifrecord_2019-02-27_193451](https://user-images.githubusercontent.com/29271244/53484843-1b747d00-3ac8-11e9-9b0f-a7cbfcae2d4a.gif)

**Comment by Vane11ope** [comment]
3. Also, even though you close Graph Overview with "x" button, it will show up anyway when you manipulate Graph, which isn't expected behavior at all. Once you close Graph Overview, it should keep being closed until you explicitly open it in Menu.

**Comment by ITAYC0HEN** [comment]
issue: moving Graph Overview to other place will break sync
