### ISSUE TITLE
Inaccuracy while using the debugger

### ISSUE THREAD

**Issue by Sinnan-Khowaja** [radareorg/cutter#1222]
**Environment information**
a fresh VM with:
cutter
x64dbg
and executable i wanna analyze

* Operating System:
Host OS: Ubuntu 18.04
Guest OS: Windows7_x86-64

* Cutter version:
1.7.4

* File format:
PE+

**Describe the bug**
when i emulate my executable to use with the debugger a particular register is calculated incorrectly

**To Reproduce**
i don't really know if i am doing things right
but here is what i did
1..i select my file into cutter (everything works fine)
2..i want to debug the executable so i start emulation
3..i set a break point on the instruction "jmp R11"
4..i hit continue
5..the program jumps to the instruction
6..only for me to find that at the instruction (or before it) "jmp R11" R11 has been calculated incorrectly
the program jumps to an address which is just filled with invalid instructions and hangs cutter, is way too far away and is random (but it jumps to the same place every time)
7..i try the same with x64dbg and it calculates R11 just fine and jumps to good instruction (one that makes sense)

**Expected behavior**
i want cutter to jump as x64dbg does because the program keeps running good with x64dbg and i can actually continue with correct execution

**Screenshots**
If applicable, add screenshots to help explain your problem. >.< Alrighty!
setting a breakpoint on "jmp R11"
![x64dbg1](https://user-images.githubusercontent.com/41991434/53488950-94b4a580-3ab1-11e9-9ef2-96cfe5fe8aaf.png)

R11 points to a VALID instructions
![x64dbg2](https://user-images.githubusercontent.com/41991434/53488951-967e6900-3ab1-11e9-82ff-8ff11e6c0e98.png)

JMP to correct place
![x64dbg3](https://user-images.githubusercontent.com/41991434/53488955-97af9600-3ab1-11e9-9944-560f983d34db.png)

emulation started
![cutter2](https://user-images.githubusercontent.com/41991434/53488963-9c744a00-3ab1-11e9-8197-59e3e6d82106.png)

so far so good
![cutter3](https://user-images.githubusercontent.com/41991434/53488965-9e3e0d80-3ab1-11e9-9a1d-ce1a038b32df.png)

stops at the desired instruction (also good)
![cutter4](https://user-images.githubusercontent.com/41991434/53488967-a0a06780-3ab1-11e9-874d-1c16a905ace3.png)

R11 is crazy
![cutter5](https://user-images.githubusercontent.com/41991434/53488971-a26a2b00-3ab1-11e9-8e9f-8f57878869e2.png)

HANGS

**Additional context**
EXTREME NOOB HERE. just started using cutter. am currently learning

**Comment by Adikso** [comment]
Currently there is only emulation in cutter and it is not the same thing as debugger.
It is just interpreting instructions, any complex things/calls to libraries etc don't work.

**Comment by Sinnan-Khowaja** [comment]
i see any plans to maybe add it?

**Comment by Maijin** [comment]
Currently, there is no debugging option in Cutter. This is a work-in-progress and we hope to release a beta-feature in the near future 😃 .

You can track and check if you want to contribute the following Project - https://github.com/radareorg/cutter/projects/1

**Comment by Sinnan-Khowaja** [comment]
thanks
