### ISSUE TITLE
import r2pipe not working in jupyter 

### ISSUE THREAD

**Issue by moizali2134** [radareorg/cutter#1225]
module not found
![capture](https://user-images.githubusercontent.com/48052668/53498593-6d1d0780-3ac8-11e9-87e5-33b5e488a9c0.PNG)
plz help its urgent

**Comment by Maijin** [comment]
Use `import cutter`

**Comment by Maijin** [comment]
And please respect template for bug report.

**Comment by moizali2134** [comment]
the script i am using is from securitykitten  unstacking string and i also type import cutter still same error

**Comment by Maijin** [comment]
You must use the template to report error otherwise we won't be able to help further.

**Comment by moizali2134** [comment]
sorry but plz pass me the for that
