### ISSUE TITLE
Reset settings is broken

### ISSUE THREAD

**Issue by xarkes** [radareorg/cutter#123]
Start Cutter then View->Reset Settings
The colors are broken in the disassembly widget.
Reset Settings should set the default values for everything.

**Comment by thestr4ng3r** [comment]
Should it reset the asm options (and other r2 vars) too? It would be easy to do by calling `e-` followed by `CutterCore::setSettings()` and maybe update AsmOptionsDialog if it is open.

**Comment by Maijin** [comment]
Definitely +1 for the full reset
