### ISSUE TITLE
import r2pipe module not found  but all ready install

### ISSUE THREAD

**Issue by moizali2134** [radareorg/cutter#1233]
**Environment information**
* Operating System: linux and windows 10 both
* Cutter version: 1.7.1 and 1.7.4
* File format: elf 

**Describe the bug**
i just want to decrypt string in elf but the python script does not run in jupyter like screen screenshot below
plz help 
![capture](https://user-images.githubusercontent.com/48052668/53652253-41398780-3c6a-11e9-9e18-38514ff969c1.PNG)

**Comment by xarkes** [comment]
We can't guess what your python script is so the error is not really helpful by itself.
Anyway did you install r2pipe?
On linux you have to type `r2pm -i r2pipe-py` to get r2pipe for Python.

**Comment by pelijah** [comment]
1) We distribute stanalone Python bunde with Windows version of Cutter. It loads modules from the subdirectory `python36`.
2) I am not sure that r2-pipe can be used in connection with Cutter.

**Comment by moizali2134** [comment]
> We can't guess what your python script is so the error is not really helpful by itself.
> Anyway did you install r2pipe?
> On linux you have to type `r2pm -i r2pipe-py` to get r2pipe for Python.

**=bash: r2pm: command not found
**

**Comment by ITAYC0HEN** [comment]
try with `pip install r2pipe` please :)

**Comment by Maijin** [comment]
Closing as no answer from initial requester
