### ISSUE TITLE
Rewrite Cutter as a Qt Creator fork.

### ISSUE THREAD

**Issue by GravisZro** [radareorg/cutter#1236]
I suggest that instead of reinventing the wheel to build Cutter into a passable IDE that instead an existing and well developed IDE be used as the basis of Cutter.  Qt Creator is a sophisticated IDE with excellent project management, plugin support and most importantly, extensive debugging (for execution, the editor and plugins).  The smart choice would be to fork Qt Creator, use it's already developed parts, each of which are implemented as plugins rather than part of a monolithic whole and port over what's missing from existing code.

I know a lot of work has gone into Cutter but I think it has fundamental deficiencies that have already been addressed by Qt Creator and only need customization.

[All about modding Qt Creator](https://doc-snapshots.qt.io/qtcreator-extending/)
[Demonstrates useful plugin functionality](https://doc-snapshots.qt.io/qtcreator-extending/first-plugin.html)
[Documentation of primary Qt Creator plugins](https://doc-snapshots.qt.io/qtcreator-extending/qtcreator-api.html) (incomplete but useful)

**Comment by ITAYC0HEN** [comment]
Thank you very much :)
We will indeed take a better look at Creator's code and try to find things that can be used for our needs. Reusing an already existing and working code is something we highly believe in so we appreciate it :)

We will also give a better think of making Cutter more modular using the concepts presented in QtCreator.

At this time, we have no intentions of rewriting Cutter above Qt Creator base. Thank you again
