### ISSUE TITLE
Add prototype of function

### ISSUE THREAD

**Issue by Maijin** [radareorg/cutter#125]
Add prototype of function in display, requires https://github.com/radare/radare2/issues/8785

**Comment by sivaramaaa** [comment]
I have now implemented (afcf command) the functionality from radare2 side, this should be useful to fix this issue 

```
[0x000036a0]> afcf sym.imp.ioctl

int ioctl(int fd, unsigned long request)

[0x000036a0]> afcf @ 0x000036a0

char *getenv(const char *name)
```

**Comment by xarkes** [comment]
From my point of view it only works with import functions, am I right?

**Comment by sivaramaaa** [comment]
Yup u are r8 for now !

**Comment by Maijin** [comment]
Actually for not imports or existing we can do something like

int cdecl sym.func.100003ea4(int arg_8h)

using information from `afi` for the calling convention and the arguments, the return type `int` can be added as a placeholder while this is worked on this in r2/radeco.

**Comment by Vane11ope** [comment]
i take this btw if anyone does not mind

**Comment by Maijin** [comment]
ping @Vane11ope ?

**Comment by Vane11ope** [comment]
on it now sorry.
