### ISSUE TITLE
Clustering functions by size

### ISSUE THREAD

**Issue by XVilka** [radareorg/cutter#1252]
It is quite often you need to find the biggest functions in the binary to check them first, especially things like dispatchers or decoders.

So we should think on how to do best representation/clustering the functions based on the:
- [ ] size
- [ ] external calls (to think about also the ability to group the functions that call one particular external library call)
- [ ] xreferences (to filter out "utility" functions first, ones called the most often)
- [ ] switch table size

**Comment by Maijin** [comment]
Can't you use the sort in the function panel for that?

**Comment by xarkes** [comment]
Yeah I think sort does what you want.

**Comment by XVilka** [comment]
Does it cover all 4 features?

**Comment by Maijin** [comment]
@XVilka try please and let us know which one is not covered. We are using info from afij so if this is not there you'll have to open an issue or add that information on radare2 side.

**Comment by XVilka** [comment]
I tried, seems everything covered. Should be enough for now, if I will get the idea on how to improve the sort, I will create a new bug. What bothers me is only the size of the widget - it is too long, too much information, maybe hiding some of the columns should be possible.
