### ISSUE TITLE
Better UI for arrows in Disassembly

### ISSUE THREAD

**Issue by Maijin** [radareorg/cutter#1257]
**Is your feature request related to a problem? Please describe.**

The arrow in the disassembly are ASCII, they can be improved to be integrated in the UI.

**Describe the solution you'd like**

Switch from arrows from the raw disassembly to Arrows drawed by Cutter

**Comment by XVilka** [comment]
Is this a duplicate of https://github.com/radareorg/cutter/issues/933 ?

**Comment by Maijin** [comment]
Your issue is going to be splitted

**Comment by XVilka** [comment]
Ok, good, just don't forget all items from it, please.

**Comment by xarkes** [comment]
So I am marking this as a duplicate of #413.
