### ISSUE TITLE
Ability to show r2 "system" comments in the graph

### ISSUE THREAD

**Issue by Maijin** [radareorg/cutter#126]
Ability to show r2 "system" comments in the graph:

![image](https://user-images.githubusercontent.com/1408600/33530216-cbc8fa6e-d87c-11e7-9e9c-a2786d2e6e50.png)

vs

![image](https://user-images.githubusercontent.com/1408600/33530218-d1b54e0a-d87c-11e7-87f4-a11ec173b00c.png)

**Comment by xarkes** [comment]
I didn't check but I think this require some addition in the radare2 code base.

**Comment by Maijin** [comment]
Not yet fixed @thestr4ng3r

**Comment by thestr4ng3r** [comment]
@Maijin Can you give an example where the comment shows up in disasm, but not in graph? `asm.calls` for example seems to be disabled by default on startup. If I manually enable it, it works for me.

**Comment by thestr4ng3r** [comment]
By the way, `asm.dwarf` is disabled for graph in r2. Would it make sense to enable that for graph in cutter?

**Comment by Maijin** [comment]
I tried with asm.calls enable too, it's showing up in the disassembly but not in graph :/ (OSX)

**Comment by Maijin** [comment]
Ok I cleaned everything on my side and now it works, the reset pref doesn't work really well
