### ISSUE TITLE
Pressing <space> in Disassembly view should open Graph if closed (and vice versa)

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/cutter#1268]
**Is your feature request related to a problem? Please describe.**
When the user presses the <kbd>space</kbd> key in the Disassembly widget and the Graph widget is closed, nothing happens. Same for when clicking <kbd>space</kbd> in Graph when Disassembly widget is closed.

**Describe the solution you'd like**
If <kbd>space</kbd> was clicked in either disassembly or graph widgets, the other widget should be opened by Cutter if it is closed.

**Comment by AntonReborn** [comment]
I'll do it
