### ISSUE TITLE
Capitalize != CamelCase

### ISSUE THREAD

**Issue by trufae** [radareorg/cutter#127]
<img width="267" alt="screen shot 2017-12-04 at 12 23 54" src="https://user-images.githubusercontent.com/6431515/33550458-59763d9c-d8ee-11e7-8b26-6bce74059457.png">

**Comment by Maijin** [comment]
Next time use github pencil :p

**Comment by xarkes** [comment]
Haha right.

**Comment by radare** [comment]
:p
