### ISSUE TITLE
Add `emu.str` configuration option to preferences window

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/cutter#1275]
**Describe the solution you'd like**

Add `emu.str` configuration option to preferences window. This should be DISABLED by default since `emu.str` is too verbose.

**Comment by Maijin** [comment]
Duplicate of #1276

**Comment by radare** [comment]
Maybe too verbose for x86. For arm is mandatory. And without that var u dont resolve the fcn call args
