### ISSUE TITLE
Fix default fonts on Windows/OsX

### ISSUE THREAD

**Issue by radare** [radareorg/cutter#129]
with e scr.utf8=true..

[ttf.zip](https://github.com/radareorg/cutter/files/1526853/ttf.zip)

<img width="613" alt="screen shot 2017-12-04 at 12 37 47" src="https://user-images.githubusercontent.com/917142/33551041-55c18506-d8f0-11e7-85c9-929f9a9fbbdb.png">
<img width="681" alt="screen shot 2017-12-04 at 12 35 47" src="https://user-images.githubusercontent.com/917142/33551044-5b264fae-d8f0-11e7-8374-3eb2c891a850.png">

**Comment by radare** [comment]
Seems like there are some issues on windows with default fonts

![2017-12-04 12 45 54](https://user-images.githubusercontent.com/917142/33551258-16c9c02e-d8f1-11e7-94d4-dd3d1ebcbb99.jpg)

**Comment by XVilka** [comment]
Note, that on HiDPI screens on Windows Cutter uses different fonts in different parts of the window, so looks bad.

**Comment by xarkes** [comment]
So @pelijah said it was fixed. At least on Windows. Can anyone confirm on OsX?
Or should we add a default font for all platforms?
There is already `Incosolata-Regular.ttf` and `Anonymous Pro.ttf` in `src/fonts`.
Are they bundled in the AppImage, dmg, .exe ?

**Comment by xarkes** [comment]
Closing this as it seems fixed on OsX too.
