### ISSUE TITLE
Theme editor - Instant preview

### ISSUE THREAD

**Issue by Maijin** [radareorg/cutter#1290]
**Is your feature request related to a problem? Please describe.**

Right now it is hard to determine the changes when modifying a theme.

**Describe the solution you'd like**

Add the ability to preview the changes from the theme directly to the graph and disassembly when modifying the theme.

**Describe alternatives you've considered**

**Additional context**

**Comment by ITAYC0HEN** [comment]
Implemented by @optizone in the new Theme Editor :) Good job!
