### ISSUE TITLE
Theme Editor - Export/Import theme

### ISSUE THREAD

**Issue by Maijin** [radareorg/cutter#1291]
**Is your feature request related to a problem? Please describe.**

Right now it is not possible to save and import theme.

**Describe the solution you'd like**

Add a button to export and a button to import a theme in the Theme editor preference.

**Describe alternatives you've considered**

**Additional context**

**Comment by karliss** [comment]
Implemented together with new theme editor ?

**Comment by Maijin** [comment]
@optizone is that done? if yes we can close.

**Comment by optizone** [comment]
Yep, can be closed
