### ISSUE TITLE
Disassembly/Graph widget - Different font for function names

### ISSUE THREAD

**Issue by Maijin** [radareorg/cutter#1295]
**Is your feature request related to a problem? Please describe.**

Function names have the same font as the rest of the disassembly.

**Describe the solution you'd like**

Ability to use a different and configurable font for function names.

**Comment by ITAYC0HEN** [comment]
why?

**Comment by Maijin** [comment]
I think it was related to color:

per @pelijah 

<img width="383" alt="image" src="https://user-images.githubusercontent.com/1408600/58368812-5a14aa80-7ef2-11e9-9603-9b710f2ac127.png">

**Comment by Maijin** [comment]
if it's done feel free to close it
