### ISSUE TITLE
Ability to text-select disassembly without selecting reflines and addresses

### ISSUE THREAD

**Issue by Maijin** [radareorg/cutter#1297]
**Is your feature request related to a problem? Please describe.**

Currently, all disassembly output is a text - disasm itself, offsets, and reflines.
So when you want to select multiline text, you select also offsets and reflines characters along with the disasm text.

**Describe the solution you'd like**

Both reflines and offsets (and bytes if shown) should reside in "separate" parts of the widget and not selectable with mouse, when doing multiline select.

**Comment by ITAYC0HEN** [comment]
a WIP by @xarkes

**Comment by ITAYC0HEN** [comment]
Done with jmp\ref-lines by @xarkes.
I don't think that we want to separate the lines and bytes from the widget -- if people want to copy only the disas they can either :

1. Copy with addresses and then remove them with any modern IDE
2. Disable asm.offsets and asm.bytes from the Preferences window and then copy
3. Use the integrated console
