### ISSUE TITLE
Add Hotkeys for "Undo Seek" and "Redo Seek" menu options

### ISSUE THREAD

**Issue by Maijin** [radareorg/cutter#1299]
**Is your feature request related to a problem? Please describe.**

Shortcut for undo and redo seek are missing

**Describe the solution you'd like**

Add Hotkeys for "Undo Seek" and "Redo Seek" menu options

**Comment by philipmnelson** [comment]
Working on this one right now! Just wondering what keys I should bind to. I'm thinking C-z for undo and C-r for redo since that is the usual binding for most programs.

**Comment by karliss** [comment]
How about QKeySequence::Back and QKeySequence::Forward ?

**Comment by philipmnelson** [comment]
You know, that sounds better actually, since that's essentially what these do. Thanks!

**Comment by ITAYC0HEN** [comment]
I think that <kbd>ESC</kbd> is already there for "undo seek"

**Comment by philipmnelson** [comment]
> I think that ESC is already there for "undo seek"
It is. Is there a good reason to add another hotkey for "undo seek" other than proximity on the keyboard?

**Comment by ITAYC0HEN** [comment]
@maijin

**Comment by Maijin** [comment]
Well if undo seek is done, only remain redo seek then if not already done

**Comment by karliss** [comment]
* Undo seek currently is handled in certain widgets like disassembly not globally
* Undo seek/redo seek actions in main window are duplicated, it should be possible add single action in multiple menu.

**Comment by philipmnelson** [comment]
Where would be the best place to add a hotkey for redo seek then?

**Comment by karliss** [comment]
Try adding something like `ui->actionForward->setShortcut(QKeySequence::Forward);` to mainwindow.

While on it I also recommend deduplicating the action and leaving one which has more details (actionForward/actionBack). Not sure if it can be done through GUI editor but it's straight forward by editing .ui file, because action definition and adding it to menu are two seperate tags.

**Comment by philipmnelson** [comment]
That works, where is the best place in mainwindow to add this?
