### ISSUE TITLE
Dark theme doesnt changes Qt Theme, only widgets one

### ISSUE THREAD

**Issue by radare** [radareorg/cutter#130]
<img width="1680" alt="screen shot 2017-12-04 at 12 21 59" src="https://user-images.githubusercontent.com/917142/33551100-926113dc-d8f0-11e7-9b8e-b1d9ec145d67.png">

**Comment by xarkes** [comment]
We've discussed about this already I think. We decided that the OS is responsible for the windows colors, so for instance if you want a dark theme you can for instance call cutter like this `GTK_THEME=Adwaita:dark ./cutter`

**Comment by radare** [comment]
not sure how mac can do that because there’s no way to theme mac officially, and it’s not based on gtk or qt

**Comment by xarkes** [comment]
I don't know if it is possible so yeah maybe Cutter should also handle the windows colors.

**Comment by nezza** [comment]
I checked and experimented a bit with theming, changing the window colors is not support by Qt apparently except if we want to roll our own window decoration all together - which means reimplementing a lot of stuff you get by default from the OS.

**Comment by xarkes** [comment]
We have to take a decision about this.

**Comment by xarkes** [comment]
So I've been thinking about this and maybe we should use some Qt themes (like this one for example) https://github.com/ColinDuquesnoy/QDarkStyleSheet and force it so it does not take care of any OS environment variable (like GTK dark themes etc.)
I don't know if it is a good way of doing this but at least both themes would be available for everybody and won't have any glitches (as seen in many screenshots, especially for the dark theme)

**Comment by Maijin** [comment]
And this seems maintained so +1

**Comment by xarkes** [comment]
Fixed in https://github.com/radareorg/cutter/commit/d878e5055e45991466337e592229394e7ba808f8

**Comment by Maijin** [comment]
Can you do a PR?
