### ISSUE TITLE
mulss show incorrectly when ams.pseudo enable

### ISSUE THREAD

**Issue by clouds56** [radareorg/cutter#1300]
Environment information

Operating System: Windows 10 x64
Cutter version: Version 1.7.4 Using r2-3.2.1-123-gbbe5c2a31
File format: pe64
Describe the bug

Open Edit->Preferences, in the tab Assembly->Style:
1. check asm.pseudo (uncheck asm.esil)
2. choose intel as asm.syntax

asm.pesudo enabled, it rendered wrong expression
![asm.pseudo enabled](https://user-images.githubusercontent.com/730813/54474412-53492780-481f-11e9-961a-adbbba9737fa.png)
with it disabled
![asm.pseudo disabled](https://user-images.githubusercontent.com/730813/54474418-6b20ab80-481f-11e9-8aa0-677cd078abb9.png)

the bug CONFUSED me whole night why it squared and some register is unused!!

Additional information
op bytes: f3410f59ca

**Comment by Maijin** [comment]
Greetings @clouds56,

Thanks for your bug report, we noticed that you didn't follow the bug report template. By doing so, the information you have provided aren't complete (missing version information etc.). Could you please edit your message and use the template that can be found here https://github.com/radareorg/cutter/blob/master/.github/ISSUE_TEMPLATE/bug_report.md.

Could you also add the byte of this specific opcode so we can attempt to reproduce this issue.

**Comment by Maijin** [comment]
This is fixed in r2 side, it will be fixed in cutter for next release.
