### ISSUE TITLE
Make build Cutter on Windows easier

### ISSUE THREAD

**Issue by a1ext** [radareorg/cutter#1305]
**Describe the solution you'd like**

I'd like to build Cutter with python plugins support by issuing one-two commands in console like `prepare_r2.bat && build.bat`

**Describe alternatives you've considered**

Currently I have to prepare full line of a command like this, not convenient:

![image](https://user-images.githubusercontent.com/14978853/54477283-8e475d00-4817-11e9-9e70-a711d5d05d94.png)

**Comment by pelijah** [comment]
I see that some options are presented twice.

**Comment by thestr4ng3r** [comment]
Check out https://github.com/radareorg/cutter/pull/1674 This can potentially solve this. We also might want to consider adding cutter-deps in a similar way, so cmake automatically fetches it if desired.
