### ISSUE TITLE
Windows UI freeze on start

### ISSUE THREAD

**Issue by optizone** [radareorg/cutter#1309]
**Environment information**
* Operating System: Windows
* Cutter version: 1.7.4
* File format: N/A

**Describe the bug**

When starting to analyze on Windows UI freeze appears.
![apky](https://user-images.githubusercontent.com/42874998/54478608-0bc59a00-4825-11e9-907e-655cd5988ffa.gif)

This also happens if you choose "Do not open any file":
![apky (1)](https://user-images.githubusercontent.com/42874998/54478662-d79ea900-4825-11e9-855c-369b4c57acd3.gif)

**Additional context**
But on Linux there are no such an issue.
![Peek 2019-03-16 20-00](https://user-images.githubusercontent.com/42874998/54478705-3fed8a80-4826-11e9-87da-5ff821b3c15f.gif)

@xarkes said that apparently it is because Windows loads Python DLL's after first usage, so we should load it at the start (like we do with SSL DLL's)

**Comment by pelijah** [comment]
OpenSSL DLL is loaded by Qt via LoadLibrary.

**Comment by optizone** [comment]
> OpenSSL DLL is loaded by Qt via LoadLibrary.

Maybe. But there are more than just OpenSSL, so there is a [hack](https://github.com/radareorg/cutter/blob/master/src/CutterApplication.cpp#L39) in `CutterApplication` constructor that triggers OS to load **all** libs needed. And that happens without freeze when if there is no such a hack first network request takes 1 second +- 60ms and freezes UI.

I can not explain why this hack does not give same 1 second freeze, but it's a fact.

**Comment by pelijah** [comment]
The problem is not in a lazy DLL loading. Cutter freezes due to Jupyter module. You can delete `python36\site-packages` dir to confirm this.

**Comment by optizone** [comment]
Is there any way to load it before UI launches?

**Comment by pelijah** [comment]
I think it would be better to delay this: https://github.com/radareorg/cutter/blob/master/src/widgets/JupyterWidget.cpp#L42

**Comment by xarkes** [comment]
Closed in https://github.com/radareorg/cutter/pull/1398.
