### ISSUE TITLE
Too much margins in the loading dialog

### ISSUE THREAD

**Issue by radare** [radareorg/cutter#131]
<img width="469" alt="screen shot 2017-12-04 at 12 42 45" src="https://user-images.githubusercontent.com/917142/33551143-b105a82a-d8f0-11e7-9e79-6629bb5d9f9d.png">

**Comment by xorb0ss** [comment]
How's this?
The buttons are now also inline with the "Select new file" section


_Left is after. Right is before_
![screenshot from 2017-12-04 22-05-20](https://user-images.githubusercontent.com/9213716/33578982-256188fc-d940-11e7-8398-5c8287baf858.png)

Arch Linux + GNOME
I'll create a pull request if it looks alright

**Comment by xarkes** [comment]
The issue is not very visible on Linux. Will it fix the behaviour on OsX?

**Comment by xorb0ss** [comment]
Exactly. Shall I create a pull request regardless? It should've reduced the margins on OSX too - not sure by how much is the problem. @xarkes

**Comment by xarkes** [comment]
Yep anyway it won't be worst I believe.
