### ISSUE TITLE
Can't open more than one window

### ISSUE THREAD

**Issue by radare** [radareorg/cutter#132]
Seems like there can be only 1 instance of Cutter

**Comment by xorb0ss** [comment]
Can't reproduce this in Linux. Got 2 instances of Cutter running with different files
`Linux 4.13.12-1-ARCH #1 SMP PREEMPT Wed Nov 8 11:54:06 CET 2017 x86_64 GNU/Linux
`

**Comment by xarkes** [comment]
If anyone on OsX can confirm this? (I suspect radare using OsX)

**Comment by Maijin** [comment]
When you do a new in mac-osx, it's calling the quit/save before popping the open dialog

**Comment by xarkes** [comment]
Yes on Linux too
