### ISSUE TITLE
Cannot mix incompatible Qt library (version 0x50906) with this library (version 0x50902) Abort (core dumped)

### ISSUE THREAD

**Issue by kevinyuan** [radareorg/cutter#1323]
**Environment information**
* Operating System: CentOS Linux release 7.6.1810 (Core)   3.10.0-957.1.3.el7.x86_64 
* Cutter version: Cutter-v1.7.4-x64.Linux.AppImage

**Describe the bug**

When I run the tool, it reports:

Cannot mix incompatible Qt library (version 0x50906) with this library (version 0x50902) Abort (core dumped)

**Comment by xarkes** [comment]
Do you have any special environment variable set?
Something like `LD_LIBRARY_PATH`?

**Comment by ITAYC0HEN** [comment]
Closing since we got no response from OP.
In case this is still happening to you, please re0open this issue
