### ISSUE TITLE
Xrefs dialog opens in a screen corner, instead of center of parent widget

### ISSUE THREAD

**Issue by a1ext** [radareorg/cutter#1337]
**Environment information**
* Operating System: Windows 7
* Cutter version: Version 1.8.0 Using r2-3.3.0
* File format: PE

**Describe the bug**

X-refs dialog appears in my screen's corner. Is far as I know, there are few other dialogs behave the same (need to check)

**To Reproduce**

1. open any binary
2. find any symbol which 100% has references and select it by mouse (in disasm widget)
3. press `X` key
4. X-refs dialog should appear in a screen corner

![image](https://user-images.githubusercontent.com/14978853/54692168-9b28c100-4b35-11e9-9da5-7cd45b6afa5d.png)

**Expected behavior**

Any windows have to appear at parent's (MainWindow) center

**Comment by RomeuG** [comment]
Very odd...

In QDialog it says:
```
Note that QDialog (and any other widget that has type Qt::Dialog) uses the parent widget slightly differently from other classes in Qt. A dialog is always a top-level widget, but if it has a parent, its default location is centered on top of the parent's top-level widget (if it is not top-level itself). It will also share the parent's taskbar entry.
```

Maybe Windows overrides that behavior?

**Comment by a1ext** [comment]
dunno, RenameDialog has such effect as well, but if I call rename by using context menu - it shows somewhere next to the cursor... I think problems with dialog centering can be only on MAC. On windows it must work, that means there is some problem in code

**Comment by a1ext** [comment]
Tested on Windows and X-Refs dialog doesn't center on parent window, but it centers on the screen. I don't think this is the right behavior
