### ISSUE TITLE
XRefs dialog has broken arrows in the middle

### ISSUE THREAD

**Issue by a1ext** [radareorg/cutter#1339]
**Environment information**
* Operating System: Windows 7
* Cutter version: Version 1.8.0 Using r2-3.3.0
* File format: PE

**Describe the bug**

Xrefs dialog shows broken arrows, probably bug in `pd--` command:

![image](https://user-images.githubusercontent.com/14978853/54695194-8f8bc900-4b3a-11e9-9677-e2571d2f2f84.png)

Probably we have to force `e asm.lines=false` while getting disasm preview

**To Reproduce**

1. open any binary
2. find any symbol which 100% has references and select it by mouse (in disasm widget)
3. press X key
4. go through refs list and find any which has an arrows intersecting the reference instruction (should be in the middle), arrows will stop displaying below it

**Expected behavior**

There are two options:
- Arrows have to be shown properly (requires r2 fix)
- disable arrows as suggested above

**Comment by ITAYC0HEN** [comment]
I vote yes for disabling "e asm.lines=false". This will also remove the whole empty spaces from the left.
I would also suggest disabling `asm.bytes` for the preview.

These two together will allow us to narrow the Preview pane and expand the left pane (so users can see the full instruction)

**Comment by thestr4ng3r** [comment]
Right, it is a bug in r2: https://github.com/radareorg/radare2/issues/15533
Since we would want our native non-ascii arrows here anyway, after disabling `asm.lines`, this is not a Cutter problem anymore.
