### ISSUE TITLE
Change Icon

### ISSUE THREAD

**Issue by xarkes** [radareorg/cutter#134]
The current icon is white and does not render properly everywhere.
We must use the black and white one (cf the Telegram icon)

**Comment by thestr4ng3r** [comment]
Which one do you think looks better as the main application icon? Especially in the macOS dock.

![iconbg](https://user-images.githubusercontent.com/1460997/33555874-3c4e0e20-d902-11e7-902b-f0455013cf8e.png)

**Comment by radare** [comment]
probably the first will look better

**Comment by gingerbeardman** [comment]
This is closed but the new icon is not in the release.

I was just about to create my own icon.
