### ISSUE TITLE
RFE Better keybindings

### ISSUE THREAD

**Issue by radare** [radareorg/cutter#1343]
Take ideas from r2's visual mode:

* [ ] nN to select next/previous function
* [ ] use `^$` to go begining/end of the function/program/file
* [ ] X - show refs of the function, not the offset
* [ ] r - refresh all widgets
* [ ] cmd+[+/-] to change the font size in the disasm widget
...

**Comment by ITAYC0HEN** [comment]
The following were mplemented in #1589:
<kbd>^</kbd> - Seek to the begining of the current function
<kbd>$</kbd> -  Seek to the last instruction in the current function
Fixing <kbd>CTRL</kbd>+<kbd>+</kbd> to increase font size in disassembly widget

kbd>CTRL</kbd>+<kbd>-</kbd> was already there.

Others won't be implemented
