### ISSUE TITLE
The graph overview opens in wrong place (OSX)

### ISSUE THREAD

**Issue by dukebarman** [radareorg/cutter#1348]
**Environment information**
* Operating System: OSX 10.14
* Cutter version: 1.8
* File format: macho

**Describe the bug**
The graph overview window opens in wrong place and with wrong size.

**To Reproduce**

1. Go to 'Graph' panel

**Expected behavior**

It should be in this place as like in Linux

![image](https://user-images.githubusercontent.com/1186777/54759235-b7446500-4bfe-11e9-9154-9c3a60003847.png)

**Screenshots**

Preview for error

![image](https://user-images.githubusercontent.com/1186777/54758955-36856900-4bfe-11e9-99d0-442f047a39f1.png)

**Comment by Vane11ope** [comment]
does it always happen? could you "Reset Settings" and try again just in case if it'd not be too trouble? thanks you :)

**Comment by dukebarman** [comment]
After "Reset Settings" Cutter was crashed :) And yes, it always happen

**Comment by ITAYC0HEN** [comment]
happens to me as well but only until the Functions widget is propagated successfully. Means, that until Function widget finished loading the graph overview is on that place

**Comment by ITAYC0HEN** [comment]
This is already fixed. Closing :)
