### ISSUE TITLE
Export Current Graph View as Image

### ISSUE THREAD

**Issue by LogoiLab** [radareorg/cutter#1352]
**Is your feature request related to a problem? Please describe.** 

No just a feature request

**Describe the solution you'd like**

I would like a function to export the current view shown in Graph View as an image. This would allow sharing of flow diagrams without having to share the entire project. 

**Describe alternatives you've considered**

Currently taking a screenshot of the actual program importing it into a photo editing software and cropping out the UI is impractical and causes text to be unreadable for large flow diagrams. 

**Additional context**

It would be nice if cutter could generate a high definition image of the current state of graph view and allow you to save it to share later.

**Comment by RomeuG** [comment]
Current view or entire graph?

**Comment by ITAYC0HEN** [comment]
Or both?

**Comment by LogoiLab** [comment]
Honestly it could be both current view or entire graph depending on what the user selects. I know with some command line magic I can export r2 graphs as images. I haven't looked into cutter enough to see how you interface with the radare api but I'm assuming this is possible via either the api or the windowing system you're using.

**Comment by RomeuG** [comment]
What command line magic, if I may ask? :-)

**Comment by Maijin** [comment]
Is that different request than right click export graph which is already implemented?

<img width="272" alt="image" src="https://user-images.githubusercontent.com/1408600/54854335-e3411280-4cf2-11e9-8169-1677eaf14409.png">


<img width="842" alt="image" src="https://user-images.githubusercontent.com/1408600/54854326-d7ede700-4cf2-11e9-9db1-06d3d7ec9d1b.png">

**Comment by Maijin** [comment]
ping @LogoiLab  @RomeuG

**Comment by RomeuG** [comment]
I think that that right-click option is more than enough.
But I found a small bug there: if I save the graph as `.png` or `.jpg`, for instance, the file name will still be `graph.dot`.

**Comment by Adikso** [comment]
@RomeuG I can't reproduce it. It is saving with .png extension correctly (and without .dot)

**Comment by RomeuG** [comment]
@Adikso What version are you using? This happens me in 1.8.0.

**Comment by LogoiLab** [comment]
Ok im using the version currently available in the arch AUR. could be the issue probably an old version.

**Comment by LogoiLab** [comment]
I don't want to close this issue unless we've decided the previous errors mentioned by @Adikso have been figured out

**Comment by ITAYC0HEN** [comment]
seems fixed :)
Thanks! Export graph is enough
