### ISSUE TITLE
 Compilation error with radare2 master repo

### ISSUE THREAD

**Issue by RomeuG** [radareorg/cutter#1359]
**Environment information**
* Operating System: GNU/Linux
* Cutter version: 1.8.0
* File format: ???

**Describe the bug**

When compiling, this error appears:

```
../src/core/Cutter.cpp: In member function ‘bool CutterCore::loadFile(QString, long long unsigned int, long long unsigned int, int, int, bool, const QString&)’:
../src/core/Cutter.cpp:396:69: error: too few arguments to function ‘bool r_bin_file_hash(RBin*, long long unsigned int, const char*, RList**)’
     r_bin_file_hash(core_->bin, hashLimit, path.toUtf8().constData());
                                                                     ^
In file included from /usr/local/include/libr/r_asm.h:7,
                 from /usr/local/include/libr/r_egg.h:4,
                 from /usr/local/include/libr/r_core.h:13,
                 from ../src/core/CutterCommon.h:8,
                 from ../src/core/Cutter.h:4,
                 from ../src/common/Configuration.h:6,
                 from ../src/core/Cutter.cpp:8:
/usr/local/include/libr/r_bin.h:712:12: note: declared here
 R_API bool r_bin_file_hash(RBin *bin, ut64 limit, const char *file, RList/*<RBinFileHash>*/ **old_file_hashes);
            ^~~~~~~~~~~~~~~
make: *** [Makefile:2764: Cutter.o] Error 1
```

Most likely because in this [Radare2 issue](https://github.com/radare/radare2/pull/13441) a new argument was added to the `r_bin_file_hash` function.

**To Reproduce**

1. Compile Cutter with the `master` version of Radare2.

**Expected behavior**

Compile normally.

**Screenshots**

None

**Additional context**

I don't really know what is the purpose of `old_file_hashes`, the new argument. Probably use `nullptr` ?

**Comment by a1ext** [comment]
You can safely pass nullptr there. That’s a new argument to return old file hashes in case the binary was changed/patched

**Comment by a1ext** [comment]
The better is to wait until we update r2 and adjust everything in Cutter-side

**Comment by RomeuG** [comment]
Okay, I passed nullptr there in my working copy and everything went fine.
Thanks!
