### ISSUE TITLE
X-Refs Widget Improvements: wider `Code` column

### ISSUE THREAD

**Issue by a1ext** [radareorg/cutter#1362]
`Code` column has to be wider
---
![image](https://user-images.githubusercontent.com/14978853/54693879-65d1a280-4b38-11e9-955b-595e1baf92f6.png)

Because usually flags are long, the are not displayed fully. It has to have comments as well

**Comment by ITAYC0HEN** [comment]
Agree. I think that we should remove asm.lines and asm.bytes in the preview, which will make more space for the code column
