### ISSUE TITLE
Support 1 level refs/xrefs graphs

### ISSUE THREAD

**Issue by Maijin** [radareorg/cutter#1375]
**Is your feature request related to a problem? Please describe.**

Support 1 level refs/xrefs graphs from @trufae 

**Describe the solution you'd like**

Support 1 level refs/xrefs graphs from @trufae

**Comment by a1ext** [comment]
Could you explain that?

**Comment by Maijin** [comment]
@radare  please.

**Comment by trufae** [comment]
I saw that in a youtube video of someone using ghidra

![https://pbs.twimg.com/media/D08E9WsXQAAObbe.jpg](https://pbs.twimg.com/media/D08E9WsXQAAObbe.jpg)

and this is exactly the same i implemented in visuall callgraph navigation in r2 many years ago, and its similar to the new vbg graph mode.

**Comment by Maijin** [comment]
Then that's a duplicate of #406
