### ISSUE TITLE
Add compiler information in the dashboard

### ISSUE THREAD

**Issue by Maijin** [radareorg/cutter#1379]
**Is your feature request related to a problem? Please describe.**

Compiler information is now available in `iIj`

**Describe the solution you'd like**

Add compiler information when available in the dashboard

**Comment by RomeuG** [comment]
@Maijin I am working on it, almost finishing the issue. But I am a bit confused:

1. In which of the three columns of the dashboard do you want it added?
2. What if there is no compiler information? Do we still display it without any information or hide it?

Thanks

**Comment by Maijin** [comment]
Looks like you figured it out ;)
