### ISSUE TITLE
Graph view is blurry

### ISSUE THREAD

**Issue by scrapbird** [radareorg/cutter#1395]
**Environment information**
* Operating System: Ubuntu 18.04
* Cutter version: 1.8.0
* File format: Core dump

**Describe the bug**
The graph view is blurry in this version but not in the last version I used (1.7.4).

**To Reproduce**
Open any file, the graph will be blurry.

**Expected behavior**

The graph to not be blurry

**Screenshots**
![image](https://user-images.githubusercontent.com/2077061/54908202-3c57b300-4f4c-11e9-8012-bcf25733ece7.png)

**Additional context**

**Comment by xarkes** [comment]
I never experienced this.
Can you tell what happens if you zoom in/zoom out the graph view?
As of now I don't really know what could cause such an issue, can you provide the output of `env` here, maybe some QT environment variable is set?
Also what is your screen resolution?
Thanks :-)

**Comment by scrapbird** [comment]
If I recall correctly zooming in and out didn't help but I'll double check when I get home tonight and update with the other details. It's running on a 4k screen so I'm assuming it has something to do with DPI scaling but it's weird the rest of the app (especially the diass view) looks fine.

**Comment by karliss** [comment]
It isn't too that getting manual painting right takes more work than using builtin widgets where QT developers already handle all scaling.
I was able to achieve the blurry look by messing with QT_SCREEN_SCALE_FACTORS and manually setting different scaling factors for each monitor (1 and 2).

Looks like the problem is related to how image is cached using QPixmap. I tried removing it and painting to viewPort directly, that prevented blurry look.

**Comment by karliss** [comment]
[This](https://stackoverflow.com/questions/42011410/qt-drawing-high-dpi-qpixmaps) looks promising.

**Comment by ITAYC0HEN** [comment]
CC @Vane11ope, seems like this is related to the pixmap thing that was added

**Comment by karliss** [comment]
Similar fix is required for recent file icons.

**Comment by scrapbird** [comment]
Sorry @xarkes, this slipped my mind, will grab the details you asked for this weekend.

**Comment by xarkes** [comment]
No worries, it looks like @karliss might have a fix :-)

**Comment by scrapbird** [comment]
Awesome :)

QT env variables:
```
QT_AUTO_SCREEN_SCALE_FACTOR=1
QT_ACCESSIBILITY=1
```

**Comment by scrapbird** [comment]
Tested #1405 and can confirm it's working. Thanks guys!
