### ISSUE TITLE
Do not show duplicate switch->case edges

### ISSUE THREAD

**Issue by karliss** [radareorg/cutter#1416]
**Is your feature request related to a problem? Please describe.**

Switch statements can result in large amount of edges between two blocks. Drawing all of them increases the chance of hitting edge case in graph layout algorithm.

**Describe the solution you'd like**

If there are multiple edges between pair of basic blocks draw single but maybe thicker line.

**Additional context**
![Ekrānattēls no 2019-03-31 18-36-24](https://user-images.githubusercontent.com/7101031/55291207-b670b780-53e4-11e9-84b9-6d3ec2e745b8.png)

**Comment by karliss** [comment]
Made a prototype to better demonstrate what I meant.

Before on the left, after on the right.

![Ekrānattēls no 2019-04-06 14-14-32](https://user-images.githubusercontent.com/7101031/55668730-6ecfad00-5876-11e9-95be-ea9dbb3e4713.png)

**Comment by xarkes** [comment]
Not so bad, I'm unsure about the need of thickness but it looks much better anyway :)

**Comment by karliss** [comment]
I am fine with not having thickness, that would simplify the code. I don't have that much reverse engineering experience so I'll trust you if you say that it doesn't add any valuable information.

I have a feeling that there might be a bug causing more edge duplication than there should be which exaggerates the problem. Having multiple edges going to blocks that match multiple cases makes sense but that shouldn't apply to blocks with single case.
