### ISSUE TITLE
dir.projects doesn't change

### ISSUE THREAD

**Issue by Coualafool** [radareorg/cutter#1425]
**Environment information**
* Operating System: windows 10
* Cutter version: 1.8.0

**Describe the bug**

It is not possible to change the default path of projects with the select button. Cutter leaves the path by default ... Can you, please, help me?

**Comment by ITAYC0HEN** [comment]
Can't reproduce anymore, as the directory changes when I use the Select button. Might be fixed along the way.

If you are still facing this issue, please comment here and we will be happy to re-open the issues. In case you are facing with a new problem, please open a new issue.

Thanks!
