### ISSUE TITLE
Can't open file by typing the path

### ISSUE THREAD

**Issue by radare** [radareorg/cutter#143]
If I type the path in the input field of the open dialog and press enter or select or open it just opens a dialog to select a file but doesn't allows me to load any file by path

<img width="462" alt="screen shot 2017-12-05 at 10 22 07" src="https://user-images.githubusercontent.com/917142/33599382-4c493c9c-d9a6-11e7-8082-e970837938ab.png">

**Comment by radare** [comment]
Also, that positioning of the Open/Close buttons is a bit inconsistent, both buttons should be in the same vertical position

**Comment by gingerbeardman** [comment]
Would also be good to be able to drag project onto window/app.
