### ISSUE TITLE
Encoding warnings on Windows

### ISSUE THREAD

**Issue by pelijah** [radareorg/cutter#1435]
- [ ] https://ci.appveyor.com/project/radare/cutter/builds/23657068/job/co28srs8glxdrvsk?fullLog=true#L151

- [ ] https://ci.appveyor.com/project/radare/cutter/builds/23657068/job/co28srs8glxdrvsk?fullLog=true#L227

- [ ] https://ci.appveyor.com/project/radare/cutter/builds/23657068/job/co28srs8glxdrvsk?fullLog=true#L228

- [ ] https://ci.appveyor.com/project/radare/cutter/builds/23657068/job/co28srs8glxdrvsk?fullLog=true#L260

- [ ] https://ci.appveyor.com/project/radare/cutter/builds/23657068/job/co28srs8glxdrvsk?fullLog=true#L422

**Comment by ITAYC0HEN** [comment]
CC @a1ext

**Comment by a1ext** [comment]
These warnings are because of non fully-implemented this feature in r2-side https://github.com/radare/radare2/commit/3fba693b91173a65d5abc66aebdb45f93449ce08

@GustavoLCR could you take a look?
