### ISSUE TITLE
Import/Export projects

### ISSUE THREAD

**Issue by radare** [radareorg/cutter#144]
In the open dialog it will be good to have options to open projects from zip files, git repositories or random paths. The procedure to import/export would be just to get the source and put it in/out ~/.config/radare2/projects

this path can be taken from `dir.projects` and processed with r_str_home apis

`r2 -qcedir.projects --`

**Comment by radare** [comment]
Note that r2 supports GPG, GIT and ZIP projects, so maybe Cutter should have an UI for that

**Comment by xarkes** [comment]
Projects, you mean r2 projects? Like a r2 project in a zip file or git repo?
Imho this is not useful for 1.2

**Comment by Maijin** [comment]
@xarkes it's the further milestone we have otherwise we can just remove the milestone tag ?

**Comment by xarkes** [comment]
Keep it for now

**Comment by ITAYC0HEN** [comment]
this is a nice suggestion but not gonna happen. Users would be satisfied without this. Also, never receive other requests for this feature. closing

**Comment by bqv** [comment]
requesting this feature
