### ISSUE TITLE
Support for "pre-arguments" on the debug configuration

### ISSUE THREAD

**Issue by joaoescribano** [radareorg/cutter#1445]
**Is your feature request related to a problem? Please describe.**
I'm trying to debug a QT program that I cannot load "normally" at any debugger (I've tried a lot).

So this program actually has 2 binaries, one is a launcher and the other is the actual program client.

/program/bin/client
/program/launcher

So if you open directly the client binary directly at cutter (or at terminal normally), it will crash due to a segmentation fault cuz it cannot find the correct libraries from QT that has been packed inside the /bin folder (many .so files).

When you open the launcher, the program checks a few things (as well as version updates) and then "start a new program" (the client binary) but this time it does it by prepending a ```LD_LIBRARY_PATH=/program/bin /program/bin/client```

So this actually tricks the libc (i guess) to forget about loading QT libraries that already is on my system and use the ones on the /bin/ path.

This does 2 things:

1) Ensure program will never open if not from the launcher and will try to update every time
2) Ensure that when attaching the debugger to the "client" it will crash due to a segmentation fault and if attach to launcher it crashes due to the launch of the new PID (client).

Its frustrating cuz at the terminal, I can simply add the LD_LIBRARY_PATH prepended as an argument and open the client directly. 

**Describe the solution you'd like**
The solution I found out is to add a configuration like "prepended debugger argument" to the debugger preferences:
![image](https://user-images.githubusercontent.com/1336613/55845235-7792de00-5b17-11e9-8e98-a8752844becf.png)

**Describe alternatives you've considered**
I've tried to add the path directly through my OS but, since Cutter uses QT too, cutter crashes.

**Additional context**
Nothing to add, thanks so much for this awesome software.

**Comment by karliss** [comment]
"pre-arguments" is called environment variables.

**Comment by xarkes** [comment]
Hello,

I know that the menu item is called "Debug' and that we have a "Green arrow" that looks like a start debug button, and that is very misleading, but actually Cutter does not support debugging for now.
It is planned and a work in progress.

**Comment by joaoescribano** [comment]
@karliss thanks for the explanation, that's good to know.

@xarkes really? that's a plot twist! lol
So... what does the emulation actually do? cuz if it emulates the software and I could go stepping into the opcodes, it will be fine for my propose. I would just need to add the LD_LIBRARY_PATH into it as an environment variable.

Thanks

**Comment by xarkes** [comment]
Emulation simulates the instructions one by one. For now, as far as I know, there is nothing that mimicks syscalls and library calls, so what you are willing to do would not be possible.

**Comment by joaoescribano** [comment]
:/ now I understand.
Thanks anyway
