### ISSUE TITLE
Analysis levels issue

### ISSUE THREAD

**Issue by radare** [radareorg/cutter#145]
Current analysis levels are:

* 0 : no analysis
* 1 : auto-analysis (aaa) <----------- this is wrong, should be `aa`
* 2: experimental (aaaa)
* 3: advanced

so my proposal is to make 1: aa and then 2:aaa, 3:aaaa, ....

**Comment by Maijin** [comment]
`aa` is in advanced, `aaa` is the one that answer the most of the dummy question so it should remain like that

**Comment by radare** [comment]
aaa runs aav and that creates problems in many bins still. Imho aaa is experimental. I never use that. And aa is simple and works fine always. I dont see the point in hiding one a level

**Comment by Maijin** [comment]
Well may create problems in arm/mips but without it the assembly doesn't have sense at all and people are going to complain of that and the missing XREFS.

**Comment by radare** [comment]
People will always complain. And xrefs will always be missed

**Comment by Maijin** [comment]
if you want aa it's under advanced analysis done :p

**Comment by radare** [comment]
:___
