### ISSUE TITLE
Contradicting recent file behaviour in NewFileDialog

### ISSUE THREAD

**Issue by karliss** [radareorg/cutter#1452]
**Is your feature request related to a problem? Please describe.**

NewFileDialog currently contains code for two contradicting behaviors:
* have most recent file at the top - by doing removeAll+prepend in NewFileDialog::loadFIle
* sort recent files alphabetical order - flag in .ui file

**Describe the solution you'd like**
Choose which behavior is preferable and removed code for other.

Having most recent file at the top seems more useful to me than sorting list of 5 items (sorting would be more helpful for longer list).  This might be down to personal preference.

**Describe alternatives you've considered**
It wouldn't be difficult allow user choosing but doing, but that seems like overkill for something that gets used only few times per session.

**Comment by karliss** [comment]
React to this comment if you prefer **current behavior**.

**Comment by karliss** [comment]
React to this comment if you prefer **most recent at top**.

**Comment by ITAYC0HEN** [comment]
Most recent order. No doubt :)
Good catch!
