### ISSUE TITLE
RFE: Add widget for alias commands

### ISSUE THREAD

**Issue by radare** [radareorg/cutter#1457]
A frontend for the '$' command.

**Comment by ITAYC0HEN** [comment]
What would you want to see there? A list of aliases?

**Comment by radare** [comment]
yes, being able to click at them to execute (or assign a keybinding to it)

many r2pm packages use alias commands to expose their functionality

**Comment by ITAYC0HEN** [comment]
why do GUI users care about CLI aliases? I mean, Cutter users probably won't use their keyboard except renaming, searching, commenting and jumping between widgets. Not for typing commands

**Comment by thestr4ng3r** [comment]
I would rather integrate the regular r2 autocompletion in the console widget

**Comment by xarkes** [comment]
So should we rename this issue to "Implement r2 autocompletion in the consol widget?

**Comment by ITAYC0HEN** [comment]
It's there already
