### ISSUE TITLE
Crash on opening with no file

### ISSUE THREAD

**Issue by optizone** [radareorg/cutter#1463]
**Environment information**
* Operating System: arch 
* Cutter version: 1.8.1
* File format: N/A
 * Arch: N/A
 * Type: N/A

**Describe the bug**
When I try to open Cutter with no file to analysis, it crashes.
![segfault](https://user-images.githubusercontent.com/42874998/56234977-1aef7000-608f-11e9-9d9e-e348e80d342b.gif)

and from provided binaries:
![segfault 2](https://user-images.githubusercontent.com/42874998/56235328-e4662500-608f-11e9-9dfa-10201a8d0293.gif)

Crashdump:
[Cutter_crash_dump_16.04.19_21.37.10.zip](https://github.com/radareorg/cutter/files/3086428/Cutter_crash_dump_16.04.19_21.37.10.zip)

**To Reproduce**

1. Launch Cutter
2. Check "Do not open any file" checkbox
3. Press "Open" button
4. ....
5. Profit

**Expected behavior**
Launch Cutter with no binary.

**Comment by ITAYC0HEN** [comment]
Nooo I can't believe my eyes! You are the one who implemented the Crash
Dump feature so when users experience crashes they will share it with us
and attach the crash dump - and you didn't attach it yourself XD

Please do

**Comment by optizone** [comment]
Yeah, there is another issue, it seems like it is impossible to attach binary file to issue

**Comment by ITAYC0HEN** [comment]
Zip it

**Comment by optizone** [comment]
[Cutter_crash_dump_16.04.19_21.37.10.zip](https://github.com/radareorg/cutter/files/3086428/Cutter_crash_dump_16.04.19_21.37.10.zip)

**Comment by CarveKenneth** [comment]
I'm seeing this as well on ubuntu, will attach my crash dump as well in case it helps

**Comment by karliss** [comment]
Can be repeated using radare without cutter.
```
radare2 --
aaa
```

**Comment by Maijin** [comment]
Can't reproduce this on radare2

**Comment by Maijin** [comment]
Can you confirm this is still happening on latest Cutter with latest r2?

**Comment by optizone** [comment]
Fixed
