### ISSUE TITLE
Headers of the bytes column to fit the columns of the bytes

### ISSUE THREAD

**Issue by Maijin** [radareorg/cutter#1469]
**Is your feature request related to a problem? Please describe.**

Headers of the bytes column must be fit the columns of the bytes to avoid:

![](https://i.imgur.com/moXoDA8.png)

**Describe the solution you'd like**

Headers of the bytes column must be fit the columns of the bytes.

**Comment by karliss** [comment]
Fixed by #1485, this issue can be closed.

**Comment by Maijin** [comment]
Next time you can use Fix #1485 in your commit body/title and it will automatically close the issue when merged for info ;)

**Comment by karliss** [comment]
@Maijin doing that in PR also works but I messed the syntax for closing multiple issues.
