### ISSUE TITLE
Open dialog with advanced level is too tall

### ISSUE THREAD

**Issue by radare** [radareorg/cutter#147]
This dialog will probably be unusable on smaller screens. And i have a pretty big one.

Proposed solution: Show experimental and advanced options at right of the default dialog instead of at the bottom, making this dialog look more landscap-ish. Also, this 2nd panel can be put inside a scrolledview so it will fit even in a phone screen

<img width="543" alt="screen shot 2017-12-05 at 10 34 08" src="https://user-images.githubusercontent.com/917142/33599895-e9569984-d9a7-11e7-828f-f82dd62e5189.png">

**Comment by Maijin** [comment]
ping @xorb0ss
