### ISSUE TITLE
Mark available flags and available comments in hexdump

### ISSUE THREAD

**Issue by Maijin** [radareorg/cutter#1471]
**Is your feature request related to a problem? Please describe.**

To ease navigation and provide user with all the information available in the hexdump

**Describe the solution you'd like**

Mark available flags and available comments in hexdump, this should be optional.

**Comment by dhaval0894** [comment]
Hi, I would like to take this up. Can you please elaborate a bit on what is expected in terms of the design? How it should look like?

**Comment by karliss** [comment]
I can think of two approaches this could be done.

One is to use the mechanism suggested in https://github.com/radareorg/cutter/issues/1945#issuecomment-598440589 . Indicate the position of comment or flag using little marker in the hex section and display the flag name or comment text as tooltip when hovering the marker.

Other is to add a column and display text there.

**Comment by dhaval0894** [comment]
Is someone already working on creating the Highlighting infrastructure or can I get started with that?

**Comment by karliss** [comment]
Here is an example for how the additional column approach could look.
![photo_2020-03-23_15-53-15](https://user-images.githubusercontent.com/7101031/77324055-e19f9580-6d1e-11ea-96e0-1c55ee44dbd4.jpg)

**Comment by dhaval0894** [comment]
Thanks, got it. I'll change the design implementation.
