### ISSUE TITLE
Add decimal, 1-byte, half words, words and dwords format in the hexdump

### ISSUE THREAD

**Issue by Maijin** [radareorg/cutter#1472]
**Is your feature request related to a problem? Please describe.**

To show the hexdump in decimal, 1-byte, half words, words and dwords format

**Describe the solution you'd like**

Add right click format -> decimal, 1-byte, half words, words and dwords format (there is already hex and octal)

**Comment by TheLorax** [comment]
I'm working on this, but unsure when I will have time to finish. It might be worth pinging me to avoid duplicate work if somebody else wants to do this potentially faster than me.
