### ISSUE TITLE
Add right click Endianness -> Little Endian, Big Endian in hexdump

### ISSUE THREAD

**Issue by Maijin** [radareorg/cutter#1473]
**Is your feature request related to a problem? Please describe.**

To be able to visualize hexdump data depending onthe endianess

**Describe the solution you'd like**

Add right click Endianness -> Little Endian, Big Endian in hexdump

**Comment by TheLorax** [comment]
The hexdump view always displays 1 byte per column, what would an endian change look like here?

`68 65 6c 6c 6f 0a ff ff ff ff ff ff ff ff ff ff`   "hello" in ASCII

**Comment by karliss** [comment]
@TheLorax That's why there is #1472 for ability to display bytes in formats that benefit from endian change.

**Comment by Maijin** [comment]
Yep exactly @karliss  :)
