### ISSUE TITLE
Add Copy Address shortcut in hexdump

### ISSUE THREAD

**Issue by Maijin** [radareorg/cutter#1474]
**Is your feature request related to a problem? Please describe.**

To be able to quickly copy the current address

**Describe the solution you'd like**

(<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>C</kbd>) - will copy the address where the cursor is

**Comment by Maijin** [comment]
Actually this is fixed incorrectly, the copy paste must copy the starting address, not the end address of the selection/cursor for both ASCII and hexadecimal.

**Comment by karliss** [comment]
Copying address when something is selected fixed in #1516. Copies address for start of selection range regardless of selection direction or hex/ascii part. Right clicking outside selection range removes selection thus preventing confusion if address of selection or moue position will be copied.
