### ISSUE TITLE
Analysis in progress

### ISSUE THREAD

**Issue by radare** [radareorg/cutter#148]
* Show a spinning wheel or something in movement

**Comment by pelijah** [comment]
What about label with elapsed time?

**Comment by nezza** [comment]
On OSX the progress bar is animated, is that different on Windows/Linux?

**Comment by xarkes** [comment]
No same behaviour. I don't understand the issue actually.

**Comment by Maijin** [comment]
Yeah there is an animated progress bar already adding elapsed time could be cool for closing this
