### ISSUE TITLE
can't open r_core.h , what happen?

### ISSUE THREAD

**Issue by craigtao** [radareorg/cutter#1484]
thanks for shared. 

i have some question

environment:  qt5.8 vs2015

can't open r_core.h ,

**Comment by xarkes** [comment]
Hello, could you please follow the template and give more details on what actions you did? There are so few details in your question that all I can do is guess what's happening.

**Comment by craigtao** [comment]
i clone cutter-1.8.1.
open cutter-1.8.1\src\Cutter.pro
IDE: qt creator, compiler: Qt_5_8_0_MSVC2015_32bit
Build all project,

Error infomation: 
can't open r_core.h

**Comment by xarkes** [comment]
Hmm it looks like an issue with QtCreator on Windows, cc @pelijah.

**Comment by pelijah** [comment]
I guess you forgot to execute `prepare_r2.bat`

**Comment by craigtao** [comment]
@pelijah  i had execyte prepare_r2.bat

execute result: Unknown platform


@ECHO OFF
SETLOCAL ENABLEDELAYEDEXPANSION

IF "%VisualStudioVersion%" == "14.0" ( IF NOT DEFINED Platform SET "Platform=X86" )
FOR /F %%i IN ('powershell -c "\"%Platform%\".toLower()"') DO SET PLATFORM=%%i
powershell -c "if ('%PLATFORM%' -notin ('x86', 'x64')) {Exit 1}"
IF !ERRORLEVEL! NEQ 0 (
    ECHO Unknown platform: %PLATFORM%
    EXIT /B 1
)

SET "PATH=%CD%;%PATH%"
SET "R2DIST=r2_dist_%PLATFORM%"

ECHO Building radare2 (%PLATFORM%)
CD radare2
git clean -xfd
RMDIR /S /Q ..\%R2DIST%
python sys\meson.py --release --shared --install=..\%R2DIST% --options "r2_datdir=radare2/share" "r2_libdir=radare2/lib" "c_args=-D_UNICODE -DUNICODE"
IF !ERRORLEVEL! NEQ 0 EXIT /B 1
COPY /Y build\shlr\libr2sdb.a ..\%R2DIST%\radare2\lib\r_sdb.lib

**Comment by Maijin** [comment]
The bug report has specific fields you need to provide such as what is the operating system you're running on.

**Comment by craigtao** [comment]
> The bug report has specific fields you need to provide such as what is the operating system you're running on.

i had say ,compiler is " Qt_5_8_0_MSVC2015_32bit "

do you think in linux ?

**Comment by pelijah** [comment]
Then I guess you forgot to call `vcvarsall.bat` before running `prepare_r2.bat`

**Comment by craigtao** [comment]
> vcvarsall.bat

there are this file "vcvarsall.bat"

**Comment by pelijah** [comment]
It depends on your Visual Studio installation directory. By default it's "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat".
