### ISSUE TITLE
Show Qt version in AboutDialog

### ISSUE THREAD

**Issue by pelijah** [radareorg/cutter#1488]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

![изображение](https://user-images.githubusercontent.com/16493991/56752227-7953d700-6790-11e9-96b3-aaed29bbb09a.png)

**Comment by ITAYC0HEN** [comment]
What is the idea behind this? How would the user be benefit from it?

**Comment by pelijah** [comment]
At least knowledge of Qt version is required for installing PySide2
