### ISSUE TITLE
crash with radare script

### ISSUE THREAD

**Issue by spirobel** [radareorg/cutter#1495]
**Environment information**
* Operating System:Ubuntu x86_64 x86_64 x86_64 GNU/Linux

* Cutter version: 1.8.1
* File format: arm binary

**Describe the bug**

**To Reproduce**

run radare script
[crashreport.zip](https://github.com/radareorg/cutter/files/3125544/crashreport.zip)

**Expected behavior**

 do not crash

**Screenshots**

**Additional context**

![no update for arch](https://user-images.githubusercontent.com/43391631/56870706-99df9380-6a13-11e9-8a14-874101394609.png)

also when i update the arch in the console it does not update in the dashboard(i pressed refresh view)
It would also be nice to change this directly in the dashboard with a drop down menu.
![nocrash](https://user-images.githubusercontent.com/43391631/56870925-19229680-6a17-11e9-9ec3-a97fe7338b1e.png)
after unpicking options to use virtual addresses and import demangled symbols it does not crash anymore.
some other issue is that tab completion in the console does not work.

**Comment by spirobel** [comment]
ok it also does not crash if i just uncheck virtual addresses which makes sense. But even then I dont see the symbols in the symbols tab and this command: 
[0x00000000]> pd @ sym.irq_uart0_handler_0x00018000
produces no output which it does when running the script in radare without cutter

**Comment by thestr4ng3r** [comment]
You load the script using the "Load Script" Text field in the Initial Options dialog, right? What are the exact settings that you use there? Also which of the files do you load exactly? full100k.bin + radare_script_nrf51.r2?

**Comment by spirobel** [comment]
I didnt change any of the options and used the "Load Script" Text field. I loaded 100k.bin and the radare_script. It crashed on me multiple times. Thats where the crash dump came from. I retried it today but it seems like its not crashing anymore. Maybe this is some kind of heisenbug i am sorry. 
Anyhow, the issue with the missing symbols still persists.

**Comment by ITAYC0HEN** [comment]
Can you open separate issue for the bug you experience? :)

**Comment by Maijin** [comment]
Greetings,

Please reopen for the missing symbols in a different issue as requested.
