### ISSUE TITLE
Overview movement doesn't work when overview widget is small

### ISSUE THREAD

**Issue by karliss** [radareorg/cutter#1503]
**Environment information**
* Operating System: Linux
* Cutter version: 19be6df20c7034823c148d8de6d905bffa36658d
* File format: Not applicable

**Describe the bug**

When graph overview widget is small moving view by clicking and dragging doesn't work properly. View position gets only updated during initial click but not while dragging mouse. Problem disappears after increasing size of overview widget. It is more likely to happen with big functions (few hundred basic blocks).

Not sure if it's the same bug or different one but clicking outside the bounding box of graph produces similar result.

**To Reproduce**

1. Open large function (at least 200-300 basic blocks)
2. Open graph view and graph overview
3. reduce the size of overview widget
4. Try click + drag in overview widget and observe that position changes only during click
5. Increase size of overview widget and repeat step 4. Observe that dragging works.
6. If the problem doesn't appear try with different function. Large functions are more likely to trigger this, but not all large functions.

**Expected behavior**
* Clicking and dragging mouse in overview widget changes view position.
* When clicking and dragging outside the graph bounding box it works the same way as when initial click is inside bounding box. It should move the view clipping the position to bounding box.

**Comment by ITAYC0HEN** [comment]
CC @Vane11ope
