### ISSUE TITLE
Clicking on graph overview causes crash

### ISSUE THREAD

**Issue by karliss** [radareorg/cutter#1508]
**Environment information**
* Operating System: Linux 
* Cutter version: d6bb0c0446c30e5661b96c86fd532bbd46e99e9c
* File format: elf

**Describe the bug**

Clicking on empty graph overview causes crash.

**To Reproduce**

1.  Open executable in cutter, make sure graph isn't visible  but overview is. If graph was visible restart cutter after switching to Dashboard or Disassembly
2. Double click on a function, overview window should be still empty at this point
3. click on overview, it should crash

**Expected behavior**
Clicking on overview doesn't cause crash.

**Additional context**

Opening graph view before clicking on overview causes overview to be filled preventing crash. Overview is probably missing a check that it isn't initialized.

**Comment by ITAYC0HEN** [comment]
@Vane11ope can you look at it?
