### ISSUE TITLE
bashisms in build.sh

### ISSUE THREAD

**Issue by keesj** [radareorg/cutter#1509]
**Environment information**
* Operating System: Ubuntu cosmic
* Cutter version: git checkout

**Describe the bug**

The build script contains bashisms that cause problems on systems that do not have bash installed

*The use of "[["*

"[[" is bash specific and causes the following error on my system
./build.sh: 67: ./build.sh: [[: not found

I suggest using
if [ -n "$VAR" && "$VAR" = "bla" ]

*The use of source* 
the use of source a line bellow also is also a bashism. the portable replacement is using a "."

1.remove bash from your system / install a clean ubuntu 
2. git checjout'
2. run ./build.sh

**Screenshots**

```
Generated 961 translation(s) (551 finished and 410 unfinished)
Updating '/home/expo/projects/cutter/src/translations/cutter_nl.qm'...
    Generated 961 translation(s) (932 finished and 29 unfinished)
Updating '/home/expo/projects/cutter/src/translations/cutter_pt.qm'...
    Generated 961 translation(s) (391 finished and 570 unfinished)
Updating '/home/expo/projects/cutter/src/translations/cutter_ro.qm'...
    Generated 961 translation(s) (932 finished and 29 unfinished)
Updating '/home/expo/projects/cutter/src/translations/cutter_ru.qm'...
Removed plural forms as the target language has less forms.
If this sounds wrong, possibly the target language is not set or recognized.
    Generated 961 translation(s) (932 finished and 29 unfinished)
Updating '/home/expo/projects/cutter/src/translations/cutter_tr.qm'...
Removed plural forms as the target language has less forms.
If this sounds wrong, possibly the target language is not set or recognized.
    Generated 961 translation(s) (286 finished and 675 unfinished)
./build.sh: 67: ./build.sh: [[: not found
./build.sh: 70: ./build.sh: [[: not found
```

also 
scripts/prepare_breakpad_linux.sh hash #!/bin/bash as interpreter set

**Additional context**

I started fixing the issue here

```
diff --git a/build.sh b/build.sh
index 893f284..3eb11ac 100755
--- a/build.sh
+++ b/build.sh
@@ -50,7 +50,7 @@ find_lrelease() {
 
 find_gmake() {
        gmakepath=$(which gmake)
-       if [ -z "$gmakepath" ]; then
+       if [ -z "$gmakepath" ] ; then
                gmakepath=$(which make)
        fi
 
@@ -64,11 +64,11 @@ find_gmake() {
 }
 
 prepare_breakpad() {
-       if [ "$OSTYPE" = "linux-gnu" ]; then
-               source $ROOT_DIR/scripts/prepare_breakpad_linux.sh
+       if [ -n "$OSTYPE" && "$OSTYPE" = "linux-gnu" ] ; then
+               . $ROOT_DIR/scripts/prepare_breakpad_linux.sh
                export PKG_CONFIG_PATH="$CUSTOM_BREAKPAD_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH"
-       elif [ "$OSTYPE" = "darwin" ]; then
-               source $ROOT_DIR/scripts/prepare_breakpad_macos.sh
+       elif [ -n "$OSTYPE" && "$OSTYPE" = "darwin" ] ; then
+               . $ROOT_DIR/scripts/prepare_breakpad_macos.sh
        fi
        return 1
 }
```

**Comment by Maijin** [comment]
Can you send a Pull-request so it can be reviewed directly there?

**Comment by keesj** [comment]
It looks like the patch does address the problems I mentioned. somebodt on irc mentioned that is might be a good idea to run https://github.com/koalaman/shellcheck

**Comment by xarkes** [comment]
I think you can try again with master and let us know if anything's wrong.

**Comment by keesj** [comment]
Hello, 

I still have a build problem:
./build.sh: 103: ./build.sh: Bad substitution

I think the code tries to see if . QMAKE_CONF contains CUTTER_ENABLE_CRASH_REPORT=true by performing a substitution.

**Comment by optizone** [comment]
Yep, that's right, lgtm can not build either. Is it because sh doesn't know about substitution or what?

**Comment by xarkes** [comment]
Probably, I think the best is to just pass shellcheck on every `.sh` script as mentioned above, and address the warnings. It will surely fix the issues.

**Comment by xarkes** [comment]
Should be good now!
