### ISSUE TITLE
Add more display options to the hexdump

### ISSUE THREAD

**Issue by radare** [radareorg/cutter#151]
* hex.compact
* hex.comments (pxc command)
* show flags (pxa command) (not compatible-yet with hex.compact https://github.com/radare/radare2/issues/8957)
* pack bytes in words, dwords, qwords, ..(pxh, pxw, pxq)
* hex.pairs (it's set to false by default in cutter, but we should make it configurable for the user)

**Comment by Maijin** [comment]
Dup of #64
