### ISSUE TITLE
When idle, Hexdump Sidebar must not perform operations

### ISSUE THREAD

**Issue by Maijin** [radareorg/cutter#1528]
**Is your feature request related to a problem? Please describe.**

To optimize speed.

**Describe the solution you'd like**

When idle, Hexdump Sidebar must not perform operations

**Comment by karliss** [comment]
Did you meant when it is collapsed? Unless I missed something it only reacts to selection changes.

**Comment by Maijin** [comment]
Yes when collapsed (when clicking on the [x] )

<img width="419" alt="image" src="https://user-images.githubusercontent.com/1408600/57587852-36be2880-750c-11e9-83ab-d8ad589b54bb.png">
