### ISSUE TITLE
Companion r2 script

### ISSUE THREAD

**Issue by radare** [radareorg/cutter#153]
R2 when loading a file it will check if there's a file with the same filename but appending .r2 at the end.

Cutter should do the same, the UI for that should be like this:

- [x] Ask the user to load or not the companion script (displaying it in the same yes-no dialog)
- [x] Add a menu entry to edit/create that .r2 file

I use this workflow a lot, instead of depending on projects

**Comment by xarkes** [comment]
Did the first point in https://github.com/radareorg/cutter/commit/33732291e714fef319b1f0999a9f38cee379a065
Will wait for Jupyter/Note editor for the second one.

**Comment by xarkes** [comment]
Second point can be done via Jupyter Notebook.
