### ISSUE TITLE
Add some basic documentation

### ISSUE THREAD

**Issue by gingerbeardman** [radareorg/cutter#154]

**Comment by Maijin** [comment]
Actually there is a "website" http://rada.re/cutter/ but it needs to be completed see https://github.com/radare/radare.org/tree/master/cutter

**Comment by xarkes** [comment]
What kind of documentation are you expecting? The default shortcuts for every action, the description of each panel, etc.?

**Comment by gingerbeardman** [comment]
Well I have no idea how to use the app so a simple step-by-step tutorial or how-to would be very welcome.

**Comment by xarkes** [comment]
Well Cutter is very similar to any disassembling framework so if you ever used one of those it should be in no way hard to use.
If you never used any similar software, then I understand the issue, but I personally don't have the time to make such documentation, it will have to wait for other issues to be fixed first.

**Comment by gingerbeardman** [comment]
Of course, I'm slowly figuring it out.

**Comment by gingerbeardman** [comment]
Readme has this:

> Documentation
> 
> Proper documentation and website will be created before the first release.

**Comment by xarkes** [comment]
Ah.

**Comment by gingerbeardman** [comment]
Woah! I just realised the graph is interactive. 

So I guess a brief summary of features (including that) would be useful.

**Comment by xarkes** [comment]
Ok ok, I'm considering this.

**Comment by Maijin** [comment]
https://github.com/radareorg/cutter#keyboard-shortcuts
