### ISSUE TITLE
Support Intel Hex as input file format

### ISSUE THREAD

**Issue by TrueXakeP** [radareorg/cutter#1540]
**Is your feature request related to a problem? Please describe.**

I can't open file in Intel Hex format with Cutter. The `file://` prefix in IO at startup window can't be changed. The file format must be specified for Radar2 as `ihex://`, so that it opens it as Intel Hex.

![изображение](https://user-images.githubusercontent.com/5345528/57819361-cd9b1700-7790-11e9-8590-81973193aebb.png)

**Describe the solution you'd like**

The IO prefix can be editable. Or it finally can be extended with all supported options.

**Describe alternatives you've considered**

Trying to use r2 in cli mode.

**Additional context**

Sorry for my English.

**Comment by xarkes** [comment]
Hello,
Interesting issue as hex input file format is already supported! The funny thing is that the dropdown menu seems hidden, there are actually many more IO available, including `ihex://`.
Thanks for reporting this, can you give more details on what your OS is, what version of Cutter are you using, etc.?

**Comment by TrueXakeP** [comment]
Oh, I’m sorry. I forgot for system info.
I use Windows 10 1809 x86 64bit and Cutter Version 1.8.1 Using r2-3.4.1 from the github releases page.
Terminal is empty. Also the `RIO` tab under the `radare2 plugin information` window is empty if it is matter.

Offtopic: when I start `cutter -h` a help in window is badly formatted:
![изображение](https://user-images.githubusercontent.com/5345528/57849436-f8628b00-77e3-11e9-81c8-3f9759fb75d8.png)

**Comment by karliss** [comment]
I am getting the same on Linux with Cutter I compiled from master and r2 which gets included as submodule built using ./sys/user.sh.

**Comment by karliss** [comment]
Looks like json field names in CutterCore::getRIOPluginDescriptions are slighltly different from ones I see when running oLj. Changing them to match helped.

**Comment by karliss** [comment]
Json field names got changed in https://github.com/radare/radare2/commit/3f918a927c8aea0a0a79bd9548d5caac1acd787f

**Comment by karliss** [comment]
There is also now an uris field which we should probably use instead of name  as  they don't necessarily match. A plugin can also have multiple uris with different behavior.

**Comment by xarkes** [comment]
Yep indeed, I remember asking for that in radare2.

**Comment by ITAYC0HEN** [comment]
good catch @karliss
