### ISSUE TITLE
Take into account position in bb when focusing on address in graph view

### ISSUE THREAD

**Issue by karliss** [radareorg/cutter#1542]
**Describe the bug**

When focusing on address in GraphView by changing seek or using j/k keys view gets moved to the top of basic block. If the basic block is taller than screen selected line might be invisible. This makes j/k keys in tall basic blocks unusable.

**To Reproduce**

1. Find a function with tall basic block which doesn't fit in screen. Can be produced by inserting multi line comment in the middle of basic block and zooming in.
2. Click on the last instruction
3. Press 'k'
4. Observe that view was moved to the top of basic block and selected line is outside screen

**Expected behavior**

Take in to account position in basic block when focusing on address in graph view. If the whole BB fits in screen show that otherwise show the selected line.

**Additional context**

Split from comment in #1536 

@idandre

**Comment by thestr4ng3r** [comment]
+1, this is really annoying
