### ISSUE TITLE
Qt 5.9 can not compile any more

### ISSUE THREAD

**Issue by pangqingyuan1991** [radareorg/cutter#1552]
**Environment information**
* Operating System: Ubuntu 1804
* Cutter version: master
* File format:

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

When I try to compile it myself, I found the code uses newer API which isn't included in Qt 5.9 yet. But your document says that Qt 5.9 and above should be supported. I think your document needs updating?  ubuntu 1804 uses Qt 5.9 and there is no official way to upgrade Qt. The reason I compile the source instead of AppImage, is that I can get a better widget style.

**Comment by karliss** [comment]
Yeah, this was noticed few days ago. Supporting 5.9 would be nice due to Ubuntu 18.04.

I'll take a look if it can be done without too much workarounds and functionality degradation.

**Comment by karliss** [comment]
Got it compiling with 5.9 on Ubuntu 18.04. Doing it cleanly will take a bit more time, but nothing too bad.
2 most common problems were index operator for QJsonDocument, trivial to fix by calling .object().
Second was displayAt.

**Comment by pangqingyuan1991** [comment]
Great work! Thanks a lot. This is a very useful tool
