### ISSUE TITLE
Keybindings

### ISSUE THREAD

**Issue by radare** [radareorg/cutter#156]
I'm not a big fan of configurable keybindings because it can create a very fuckedup experience to different users when switching to a different computer and therefor confuse and complicate the use of the tool.

Having good default keybindings should be enough if we define the most important actions:

* CMD+L -> select console entry (and focus the console dialog)
* CMD+K -> select the navigation entry
* CMD+A -> assemble dialog (Todo)
* CMD+I -> insert(write hex)

* more to come (please propose yours)

**Comment by xarkes** [comment]
If you don't want to change the keybindings, don't do it? I mean we can have good default keybindings, and allow the user to change it too.

**Comment by Maijin** [comment]
Agree with Xarkes on this, if you don't want to change the keybindings don't do it.
If you don't want to use a GUI, don't use it :p
