### ISSUE TITLE
Show aai output in Dashboard

### ISSUE THREAD

**Issue by radare** [radareorg/cutter#1571]
probably fits well under hashes

<img width="806" alt="Screenshot 2019-05-21 at 13 38 20" src="https://user-images.githubusercontent.com/917142/58092969-b3689b00-7bcd-11e9-9eb6-0429a954b384.png">

**Comment by ITAYC0HEN** [comment]
This is the output of `aai`:
```
[0x00031120]> aai
fcns    2209
xrefs   42358
calls   55249
strings 3000
symbols 660
imports 660
covrage 856084
codesz  1508789
```
