### ISSUE TITLE
Functions widget i snever updated

### ISSUE THREAD

**Issue by radare** [radareorg/cutter#1573]
If i load a bin without analyzing them and then i run the analysis, the widget is still empty

<img width="402" alt="Screenshot 2019-05-21 at 13 53 29" src="https://user-images.githubusercontent.com/917142/58093921-d3995980-7bcf-11e9-9260-ac545465f507.png">

**Comment by karliss** [comment]
Somewhat overlaps with #447

**Comment by karliss** [comment]
One more related #834

**Comment by ITAYC0HEN** [comment]
Duplicate. closing
