### ISSUE TITLE
Evaluate Hexwidget behavior when right-clicking outside selection

### ISSUE THREAD

**Issue by karliss** [radareorg/cutter#1587]
**Is your feature request related to a problem? Please describe.**

When right clicking outside selection and showing context menu there are two major options - remove selection or keep the selection. Both behaviors have their advantages and disadvantages and are used by large widely used programs.

**Keeping selection when clicking outside selection**
![click_outside_selection_no_seek](https://user-images.githubusercontent.com/20182642/58367443-fd13f700-7ee7-11e9-8370-424bf2034890.gif)

Advantages:
* Less problems with accidentally removing selection 

Disadvantages:
* Its unclear if action will act on selection or position of mouse click. Can be extra confusing if selection is outside screen.

**Removing selection when clicking outside selection**
![click_outside_selection_seek](https://user-images.githubusercontent.com/20182642/58367446-01d8ab00-7ee8-11e9-90c4-e8c43916b145.gif)

Advantages:
* There is no confusion what action like copy address  or paste will do
* Allows easy copy and paste in position (not so useful for hexeditor where non overwriting paste is rarely used)

Disadvantages:
* miss-click, or opening context menu to change view settings remove selection

**Other considerations and solutions**
*  keep the selection but disable or hide actions that might be confusing
* what happens when right clicking completely outside the area with hex data or text
* context menu can also be opened using keyboard,  that should probably behave the same as right clicking on selection
* Selection is kept but action affects mouse click position. In my opinion worse than acting on selected range. I haven't seen any software doing that.

**Examples of software and UI library behavior**

Does behaviour for some software change based on OS default behavior? Note if you observe different behavior on your system.

| Software  | Removes selection | The same as clicking on selection | Other  |
| ------------- | ------------- |  ------------- |  ------------- | 
| QtCreator | :heavy_check_mark:  | | |
| vscode | :heavy_check_mark:  | | |
| gedit |   | :heavy_check_mark:  |  |
| gtk line edit| |  :heavy_check_mark:  |   |
| Firefox |   | :heavy_check_mark: |    |
| Chromium | :heavy_check_mark: |  |  |
| Chromium line edit | :interrobang: |  |  selects word |
|  Sublime | |  :heavy_check_mark:  |   |
| LibreOffice writer | :heavy_check_mark:  | | |
| GHex |  | | No context menu |
| Binary Ninja |  | :heavy_check_mark: |  Copied address value depends on selection direction. Click position also ignored with empty selection. |
| IDA Pro |  |  :heavy_check_mark: |  |
| 010 Editor |  |  :heavy_check_mark: |  |
| Add more examples | | |

**Comment by ITAYC0HEN** [comment]
Very thorough, thank you :) 
As we discussed earlier, my experience showed me that I lost my selected bytes over an over again. I am all for **not-removing** the selection upon right-clicking outside the selection.
Need to remember that a click outside the selection can be even 2px outside, so for example if you select bytes using left button, raising it, and then immediately right clicking, you will probably lose your selection.

So I prefer to keep the selection, and support the suggestion to hide confusing options from the selection-context menu which is something popular to do. For example, having a Selection-Context-Menu with Copy Bytes (RAW, HEX), Copy Start Address, Copy End Address and obviously all the non confusing layout options

And obviously **do-not** change seek if selection is kept.

**Comment by xarkes** [comment]
I prefer the first option: keeping the selection, because I hate when I lose my selection and have to select it all over again :-)
