### ISSUE TITLE
+ and - keys in graph overview should zoom the graph view

### ISSUE THREAD

**Issue by radare** [radareorg/cutter#1592]
^

**Comment by ITAYC0HEN** [comment]
This is the current behavior. Made sure several times wiht both numpad and number-bar.
What do you experience?

**Comment by radare** [comment]
Nope its not. It works if the graph is selected. But not if the graph overview

**Comment by ITAYC0HEN** [comment]
Ahhhh graph overview... You have such a niche requests hahah

**Comment by Petross404** [comment]
Let me know if another issue is best suited, but can this work with mouse wheel too?

I am not big on programming but this gives an idea : 
```cpp
bool nameOfGraphWidget::eventFilter(QObject *obj, QEvent *event)
{
        if (event->type() == QEvent::Wheel) 
        {
                QWheelEvent *wheelEvent = static_cast<QWheelEvent *>(event);
                wheelEvent(QWheelEvent* wheelEvent);
                return true
        } 
        else 
        {
                return QObject::eventFilter(obj, event);
        }
}

//....

void nameOfGraphicsWidget::wheelEvent(QWheelEvent* wheelEvent)
{
        if ( wheelEvent->angleData / 8 ) 
        {
                //Zoom in
        }
        else
        {
                //Zoom out
        }
        event->accept();
}
```

Copied from [here](https://doc.qt.io/qt-5/qobject.html#installEventFilter) and [here](https://doc.qt.io/qt-5/qwheelevent.html#angleDelta)
