### ISSUE TITLE
Alternative/improved macOS build instructions/script

### ISSUE THREAD

**Issue by radare** [radareorg/cutter#1593]
Random notes I found while building cutter on mac:

* brew qt5/qmake packages doesnt seems to work
* the build.sh aims to install a new system wide r2 wtf?
* build.sh seems to fail even by skipping this step

Working instructions:

* Install r2 from git
* Download the qt installer https://www.qt.io/download-qt-installer

```
export PATH=~/Qt/*/clang_64/bin:$PATH
cd ~/git/cutter
mkdir build ; cd build
qmake ../src/Cutter.pro
make -j 4
open ./Cutter.app
```

**Comment by radare** [comment]
See https://cutter.re/docs/building.html#compiling-on-linux-macos

**Comment by xarkes** [comment]
I agree with the fact that `build.sh` should not install a system wide radare2.

**Comment by ITAYC0HEN** [comment]
Compilation instructions improved and we moved to CMake as make bulding platform.
Thanks! <3
