### ISSUE TITLE
Search asm code should be case insensitive

### ISSUE THREAD

**Issue by Maijin** [radareorg/cutter#1594]
**Environment information**
* Operating System: OSX
* Cutter version: Git 1.8.2
* File format: Any

**Describe the bug**

Search asm code is case sensitive, thus for example searching `0xffffffed` will return and `r12d, 0xffffffed` but searching `0xFFFFFFED` will return nothing.

**To Reproduce**

1. Open ioili crackme0x00 w32
2. Search asm code containing 0xFFFFFFF0
3. No result
4. Search asm code containing 0xfffffff0
5 results

**Expected behavior**

Searching opcode is case insensitive

**Comment by ITAYC0HEN** [comment]
implemented /cc in radare2
https://github.com/radare/radare2/pull/14370

will fix in cutter now
