### ISSUE TITLE
Error launching Cutter.

### ISSUE THREAD

**Issue by GasparVardanyan** [radareorg/cutter#1603]
**Environment information**
* Operating System: Arch Linux x86_64 5.1.9-arch1-1-ARCH
* Cutter version: 1.8.2-1
* File format: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=7c2a054b496cf8f5edd5fce4a04411693fc837d0, for GNU/Linux 3.2.0, not stripped

**Describe the bug**

[gaspar@GasparVardanyan][~]
╼ $ Cutter
Plugins are loaded from "/home/gaspar/.local/share/RadareOrg/Cutter/plugins"
Loaded 0 plugin(s).
Warning: r_bin_file_hash: file exceeds bin.hashlimit
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] find and analyze function preludes (aap)
[x] Analyze len bytes of instructions for references (aar)
[x] Check for objc references
[x] Check for vtables
[x] Type matching analysis for all functions (aaft)
[x] Use -AA or aaaa to perform additional experimental analysis.
Cutter: ../src/widgets/GraphGridLayout.cpp:237: virtual void GraphGridLayout::CalculateLayout(std::unordered_map<long long unsigned int, GraphLayout::GraphBlock>&, long long unsigned int, int&, int&) const: Assertion `block.edges.size() == layoutState.edge[block.entry].size()' failed.
Aborted (core dumped)

**Comment by xarkes** [comment]
Hello, thanks for your report.
Is it possible that you share the binary you tried to open with Cutter so I can check how to reproduce from here?

Thanks!

**Comment by GasparVardanyan** [comment]
@xarkes I have recompiled my program and now Cutter works. Thank you.

**Comment by karliss** [comment]
@GasparVardanyan Note that you if your new build was in release mode the problem might still be there as asserts aren't checked in release builds.
