### ISSUE TITLE
Console dialog detachable or full-screenable

### ISSUE THREAD

**Issue by radare** [radareorg/cutter#161]
sometimes is too small :{

**Comment by Maijin** [comment]
Screenshot please

**Comment by radare** [comment]
Screenshot of wat. The console dialog is always visible in the ui. Theresno way to drop it or make it standalone

**Comment by xarkes** [comment]
Yeah I had the same issue in the other way -- sometimes it is too big and I can't remove it.

**Comment by Maijin** [comment]
ping @xorb0ss

**Comment by thestr4ng3r** [comment]
It's because the console is the MainWindow's centralWidget. This can be fixed by making it a QDockWidget and `centralWidget()->setVisible(false);` on the MainWindow.

**Comment by thestr4ng3r** [comment]
Default layout should stay the same after fixing this.
