### ISSUE TITLE
Unexpected switching to graph

### ISSUE THREAD

**Issue by karliss** [radareorg/cutter#1616]
**Environment information**
* Operating System: Arch Linux
* Cutter version: 8138a439239569a69afce1dbf992f80f929365ef
* File format: not applicable

**Describe the bug**

Bring to front logic cause unexpected switching to graph from disassembly when there are two graph widgets.

**To Reproduce**

1. Reset layout
2. switch to disassembly widget
3. add second graph
4. click on disassembly
5. observe that disassembly switched to graph view

This seems to happen first time after switching to second graph view. Can be also triggered if right half has graph view+something else after switching from something else to graph view.

**Expected behavior**

Interacting with disassembly never causes switching to different memory widget.

**Comment by karliss** [comment]
Looks like raising currently works by memory widget kind. I propose changing it to raising last active memory widget and falling back to disassembly if last active widget is not available.

Raising a certain widget kind might still be useful for certain actions like switch to graph shortcut.

**Comment by xarkes** [comment]
Yeah I think it would be better.

**Comment by karliss** [comment]
To be more precise priorities could be:
* last active
* any synchronized disassembly widget
* any synchronized widget
* create new synchronized disassembly widget

An alternative behavior would be forcing change of offset for non synchronized widget but I don't that's a good idea. It has potential of ruining the layout and would probably require updating more code.
Switching to non synchronized widget without changing it's position is probably wrong thing to do in most cases.

**Comment by karliss** [comment]
I am working on this. My plan for reworking raise behavior is

- [x] seperate seek from seek and show
- [ ] uniquely remember last raised widget
- [ ] rework fallback logic when last widget
