### ISSUE TITLE
Browser like back, forward buttons

### ISSUE THREAD

**Issue by karliss** [radareorg/cutter#1617]
**Is your feature request related to a problem? Please describe.**

Logic for choosing which offset changes to include in history isn't great. Sometimes it's necessary to click the back button multiple times to get to the place you want.

**Describe the solution you'd like**

Right clicking on back or forward buttons opens a menu listing history entries with addresses and nearest symbol name other human readable string. Chrome and Firefox has this, maybe other browsers.

**Describe alternatives you've considered**

* Improve logic for choosing what goes in to history. That should still be done.
* Alternative back forward actions, which always jumps to previous function

**Additional context**

![Screenshot from 2019-06-23 08-59-45](https://user-images.githubusercontent.com/7101031/59972374-6c880f80-9596-11e9-9188-4be0602338d4.png)

![Screenshot from 2019-06-23 09-08-49](https://user-images.githubusercontent.com/7101031/59972383-93dedc80-9596-11e9-8fd2-ec2e131bc5d9.png)

**Comment by ITAYC0HEN** [comment]
Good idea!
related issue: https://github.com/radareorg/cutter/issues/515

**Comment by ITAYC0HEN** [comment]
Example from Hopper.
![image](https://user-images.githubusercontent.com/20182642/60150142-127a8a80-97e0-11e9-9c77-09db230485ae.png)

thanks @shakreiner

**Comment by ITAYC0HEN** [comment]
This is available in radare2 under `sj`:
```
[0x00005b10]> sj~{}
[
  {
    "offset": 23257,
    "symbol": "main+6777"
  },
  {
    "offset": 23329,
    "symbol": "fcn.00005b10+17"
  },
  {
    "offset": 23338,
    "symbol": "fcn.00005b10+26"
  },
  {
    "offset": 23319,
    "symbol": "fcn.00005b10+7"
  },
  {
    "offset": 0,
    "symbol": "section."
  }
]
```

**Comment by karliss** [comment]
sj currently looks unusable. It includes undo and redo history  without any indicator of current location inside history.
```
[0x0002bad0]> s*
f undo_5 @ 0xb120
f undo_4 @ 0xb080
f undo_3 @ 0x2bad0
f undo_2 @ 0x27db0
f undo_1 @ 0x2bad0
f undo_0 @ 0x27db0
# Current undo/redo position.
f redo_0 @ 0x27db0
f redo_1 @ 0x27d10
f redo_2 @ 0x2bad0 
```

```
[0x0002bad0]> sj~{}
[
  {
    "offset": 45344,
    "symbol": "entry.fini0"
  },
  {
    "offset": 45184,
    "symbol": "entry0"
  },
  {
    "offset": 178896,
    "symbol": "sym.start_remote_job"
  },
  {
    "offset": 163248,
    "symbol": "sym.strcache_add"
  },
  {
    "offset": 178896,
    "symbol": "sym.start_remote_job"
  },
  {
    "offset": 163248,
    "symbol": "sym.strcache_add"
  },
  {
    "offset": 178896,
    "symbol": "sym.start_remote_job"
  },
  {
    "offset": 163248,
    "symbol": "sym.strcache_add"
  },
  {
    "offset": 163088,
    "symbol": "sym.strcache_iscached"
  },
  {
    "offset": 178896,
    "symbol": "sym.start_remote_job"
  }
] 
```

**Comment by Maijin** [comment]
`sj` should probably enhance then
