### ISSUE TITLE
Using arrow keys in functions list doesnt update disasm widget

### ISSUE THREAD

**Issue by trufae** [radareorg/cutter#1619]
will be good to have a way to do that without having to use the mouse, like the nN keys in r2

**Comment by xarkes** [comment]
You mean auto update on single select the function name? Like if single click is supposed to update the disasm view?

**Comment by trufae** [comment]
yes

**Comment by ITAYC0HEN** [comment]
I disagree. I dont think this should be the behavior. However, I think that hitting <kbd>Enter</kbd> should trigger a seek, just like double clicking the item

**Comment by ITAYC0HEN** [comment]
Thus, I recommend to close or to modify the requirement to apply Enter

**Comment by ITAYC0HEN** [comment]
Opened a better issue - https://github.com/radareorg/cutter/issues/1887
Closing this.
