### ISSUE TITLE
Add Quick Filter in the remaining List Widgets

### ISSUE THREAD

**Issue by radare** [radareorg/cutter#162]
Implemented in:
- [x] Imports
- [ ] Symbols
- [x] Exports
- [ ] Relocs
- [x] Functions
- [x] Flags
- [x] Strings
- [x] Comments

Read https://github.com/radareorg/cutter/issues/162#issuecomment-349777573 before starting to implement!

Original text by @radare:
This filter field is already implemented in functions, so i guess we can reuse some code here

**Comment by radare** [comment]
same goes for imports, symbols,. ..

**Comment by thestr4ng3r** [comment]
Should only be implemented after #183 is done for the respective widget. Then, `QSortFilterProxyModel::filterAcceptsRow()` can be implemented very clean and easy to do the filtering.

**Comment by thestr4ng3r** [comment]
QuickFilterView is now an independent class since https://github.com/radareorg/cutter/commit/f694daac8892454d044639f176eef18c9862aaf6 and can be integrated in other list widgets.

**Comment by hackertron** [comment]
is this issue still relevant / open for work ? . Can i take on this one !!

**Comment by thestr4ng3r** [comment]
Yes, definitely! But please keep the above comment in mind: https://github.com/radareorg/cutter/issues/162#issuecomment-349777573
