### ISSUE TITLE
Add key shortcuts for Set as -> dword/byte/word/string/...

### ISSUE THREAD

**Issue by trufae** [radareorg/cutter#1622]
The actions are already there. just need to decide the right key bindings

![image](https://user-images.githubusercontent.com/20182642/60149810-a51a2a00-97de-11e9-9a3f-6b6f1c7b43e7.png)

**Comment by trufae** [comment]
uhm its there, but didnt saw it at first try 
<img width="575" alt="Screenshot 2019-06-25 at 17 56 31" src="https://user-images.githubusercontent.com/6431515/60113676-985fec80-9772-11e9-9afb-993caf10b672.png">

**Comment by xarkes** [comment]
So basically, just add a shortcut for it?

**Comment by ITAYC0HEN** [comment]
> So basically, just add a shortcut for it?

changing the title

**Comment by smhaziq** [comment]
Currently dword/byte/word/string can be switched across with D key and ... shortcut is asterisk

**Comment by ITAYC0HEN** [comment]
True, thank you! :)
