### ISSUE TITLE
Disasm context menu misses many actions

### ISSUE THREAD

**Issue by radare** [radareorg/cutter#163]
* [x] Change asm.bits for current offset (ahb)
* [x] Remove flag (f-)
* [x] Undefine function (af-)
* [x] Change immediate base (ahi)

**Comment by Maijin** [comment]
ahi is done already

**Comment by xarkes** [comment]
ahb: https://github.com/radareorg/cutter/commit/b229513620b3a27c986fa5f972a1ad0820801595
