### ISSUE TITLE
Make cutter plugins more accessible

### ISSUE THREAD

**Issue by optizone** [radareorg/cutter#1632]
**Is your feature request related to a problem? Please describe.**
Currently there are no info about such repository as [cutter-plugins](https://github.com/radareorg/cutter-plugins) on the front page of Cutter repo. 
Plus there is no way to go there from Cutter either.

**Describe the solution you'd like**
Add link to plugins repo to readme and add some button like "get plugins" to "plugins" submenu.

**Comment by xarkes** [comment]
Also to documentation if not already there.

**Comment by ITAYC0HEN** [comment]
Current put it in cutter.re

**Comment by ITAYC0HEN** [comment]
Need to put it in README and Cutter binary

**Comment by xarkes** [comment]
I think the meaning is the same as https://github.com/radareorg/cutter/issues/1763 so I will close that issue.

**Comment by ITAYC0HEN** [comment]
Not exactly. It is for the documentation and a meantime solution to add a link to the plugins page

**Comment by xarkes** [comment]
Yes I understood but imo it's not worth it to do a temporary solution as we will focus on the new one asap.
