### ISSUE TITLE
build.sh to include r2dec

### ISSUE THREAD

**Issue by Maijin** [radareorg/cutter#1636]
**Is your feature request related to a problem? Please describe.**

While shipping r2dec in release is import #1341, we should also have it in done in build.sh.

**Describe the solution you'd like**

Automatically install r2dec in build.sh

**Comment by Bakwunye75** [comment]
Nice dear

**Comment by xarkes** [comment]
Hmm I'm not sure that is relevant anymore since r2ghidra is out and since r2pm is doing good progress.

**Comment by Maijin** [comment]
The issue is still relevant:
1 - Either we keep r2dec in both platform or we kill it both platform for release
2 - Either we keep r2ghidra in both platform or we kill it both platform for release
3 - Either we keep r2dec and r2ghidra in both platform or we kill it both platform for release

Otherwise we will keep getting the current questions on discrepency and support for those release in the chats.

**Comment by ITAYC0HEN** [comment]
As build.sh facing its upcoming abandon in favor of cmake, I suggest closing this issue and abandon the work on this script. What do you think?

**Comment by xarkes** [comment]
I agree!
