### ISSUE TITLE
A lot of errors in installation

### ISSUE THREAD

**Issue by Itra7** [radareorg/cutter#1638]
While building the cutter i get this error 
```
CC ht_up.c
AR libsdb.a
ar: creating libsdb.a
make[1]: *** wait: No child processes.  Stop.
Makefile:57: recipe for target 'all' failed
make: *** [all] Error 2
lrelease: could not find a Qt installation of ''
qmake: could not find a Qt installation of ''
make: *** No targets specified and no makefile found.  Stop.
Something went wrong!

```

I have alreardy installed new version on radare in my machine

**Comment by ITAYC0HEN** [comment]
how do you install Cutter?
Please use the `./build.sh` script

**Comment by Itra7** [comment]
@ITAYC0HEN I do that and the same occur

**Comment by ITAYC0HEN** [comment]
Do you really want to build Cutter from source? If you want to use cutter and not developing to it, I recommend using the pre-compiled builds from our release page.

Sadly, currently we don't have enough information about your machine to help
