### ISSUE TITLE
Clippy support

### ISSUE THREAD

**Issue by XVilka** [radareorg/cutter#164]

**Comment by xarkes** [comment]
If you want it, do it.

**Comment by gingerbeardman** [comment]
What's Clippy?

**Comment by xarkes** [comment]
That's clippy
![Clippy](https://i.amz.mshcdn.com/dhW9TRRrZHuFub1D4xii-TN3TuA=/1200x630/2017%2F03%2F01%2Fdc%2Fa2d4dbea27ea4f26adb79fa107754b50.b7579.jpg)

**Comment by xarkes** [comment]
I'm closing this unless anyone here wants to do it.
