### ISSUE TITLE
[Graph] Add label in graph blocks

### ISSUE THREAD

**Issue by dmknght** [radareorg/cutter#1646]
**Is your feature request related to a problem? Please describe.**

Currently, graph blocks doesn't have `label` (or anything it should be called which should has address that block starts) . It means graph is harder to track

![Screenshot at 2019-07-12 01-16-05](https://user-images.githubusercontent.com/29118926/61074768-aa17e400-a442-11e9-84d0-6710926bdeae.png)

**Describe the solution you'd like**

Radare2 has address of first instruction in each block (Visual graph mode). I think Cutter should have it as well (and enable it by default)
![Screenshot at 2019-07-12 01-19-06](https://user-images.githubusercontent.com/29118926/61075099-7a1d1080-a443-11e9-87de-0d5919f69219.png)

**Describe alternatives you've considered**

There is no other idea.

**Additional context**

I am testing with Parrot 4.6 (amd 64), radare2 and cutter pulled 11 Jul 2019 and

**Comment by FalcoGer** [comment]
I agree. On top of having the address in the blocks it would be nice if you could add some custom string to describe the whole block.
Coming from IDA this is one feature I miss (along with moving the blocks around)

This should be added to the `Graph improvements` project.

**Comment by ITAYC0HEN** [comment]
@FalcoGer , what did you mean by adding a custom string?

Although not that good in terms of UX, it is possible to rename a block by adding a flag to its address.

Before:
![image](https://user-images.githubusercontent.com/20182642/87807781-5ca63200-c861-11ea-973b-b2d441d45f32.png)

After:
![image](https://user-images.githubusercontent.com/20182642/87807871-6cbe1180-c861-11ea-8ff3-92a591794cd3.png)

**Comment by FalcoGer** [comment]
Yes something like that.
How'd you do that?

**Comment by ITAYC0HEN** [comment]
two ways:

1. Say you have "je ox1234" you can click on 0x1234 and press N. Then choose a name and press enter

2. go to the start of the block and right click to add a new flag. Give it a name and press enter
