### ISSUE TITLE
Analysis after opening a file

### ISSUE THREAD

**Issue by thestr4ng3r** [radareorg/cutter#165]
Currently, the only way to run analysis is in the OptionsDialog. If the file is already opened, it is more or less impossible.

I think a good way to do this would be to take the Analysis parts of OptionsDialog and encapsulate them in one or more QWidget subclasses that can then be embedded in both the OptionsDialog and some other dialog accessible from the MainWindow.

**Comment by Maijin** [comment]
yep that can be linked to https://github.com/radareorg/cutter/issues/82

**Comment by deeso** [comment]
+1 on this.  Also, is there a way to rebase the binary after it is loaded?

**Comment by Maijin** [comment]
Now you can force analysis of a blob of disassembly
