### ISSUE TITLE
Non-native looking horizontal scrollbar in disassembly widget.

### ISSUE THREAD

**Issue by karliss** [radareorg/cutter#1655]
**Environment information**
* Operating System: Arch linux
* Cutter version: 4b9a4ff2e2f5e5ddd468415eae06810bd9e37389

**Describe the bug**

Non-native looking horizontal scrollbar in disassembly widget.
Problems like this usually happen when modifying css in native qt theme.

**To Reproduce**

0. Choose native qt theme
1. Create long comment in disassembly view so that horizontal scrollbar appears
2. put hex widget next to it with  fixed byte width
3. observe that horizontal scrollbar in hex widget looks as expected

**Expected behavior**

When using native qt theme horizontal scrollbar in disassembly widget looks the same as everywhere else.

**Screenshots**

![Screenshot from 2019-07-14 14-08-34](https://user-images.githubusercontent.com/7101031/61182787-f9c3fe80-a640-11e9-97a1-2a8f56b004be.png)

**Comment by optizone** [comment]
It is regression from 77a7710dafb7aed5f22f43834d5d260b9912bf90.
When stylesheet is applied, it overrides native scrollbar. Check out [this](https://github.com/radareorg/cutter/commit/77a7710dafb7aed5f22f43834d5d260b9912bf90#diff-b616cfc0789080efa1ef513b16be6649R88) line.

**Comment by karliss** [comment]
Too vague css selectors getting applied to internal subwidgets like scrollbars?
