### ISSUE TITLE
Update the screenshot in README

### ISSUE THREAD

**Issue by XVilka** [radareorg/cutter#1658]
With a new DisasmWidget look ;)

**Comment by karliss** [comment]
There might be a few more tweaks to the new widget. Better wait for release to come closer before doing this.

**Comment by xarkes** [comment]
Agreed.

**Comment by jeaye** [comment]
This is superseded by #995, right?

**Comment by XVilka** [comment]
@xarkes ping?

**Comment by xarkes** [comment]
Hey @XVilka, sure we will take care of that soon :)

**Comment by XVilka** [comment]
How soon?

**Comment by XVilka** [comment]
See also https://github.com/radareorg/cutter-jupyter/issues/9
