### ISSUE TITLE
r2dec to work in task and refresh button removal

### ISSUE THREAD

**Issue by Maijin** [radareorg/cutter#1660]
**Is your feature request related to a problem? Please describe.**
 
To ensure that the pseudocode is always synchronised with the rest, we need to remove the refresh button.

**Describe the solution you'd like**

r2dec to work in task and remove refresh button in pseudocode panel.

**Comment by ITAYC0HEN** [comment]
fixed in https://github.com/radareorg/cutter/pull/1724
