### ISSUE TITLE
Labeling change required

### ISSUE THREAD

**Issue by ntoskrnl-exe** [radareorg/cutter#1661]
I want to draw your attention to the attached imaged. I selected a number of options on reversing one of my own executables. The attachment shows the labelling anal.xyz

The issue is not what xyz is, but the anal part. In the UK, and anywhere english speaking, that has a certain meaning. That real should be changed, to stop cutter and R2 becoming a joke. Just needs to be something a little less 'offensive'. Sorry I know this is a cosmetic, but I should bring it to peoples attention.

Fantastic and brilliant open source contribution by the way.

![Annotation 2019-07-15 202812](https://user-images.githubusercontent.com/43867884/61243219-632a3700-a73f-11e9-885b-4ffede9761b9.png)

**Comment by ITAYC0HEN** [comment]
Hey @xOrMalware, thank you for opening this issue and bringing this to our attention.
While we all clearly know the meaning of Anal in the public, it has a different meaning in radare2 as an abbreviation for "Analysis". We clearly have no will to offend anyone nor to make a joke of Cutter.

We take your concerns seriously, and while we don't have any intention of changing the `anal.*` eval variables in our core, we do agree that it can be changed in UI strings.

I invite you to take some time and modify the occurrences of `anal` in Cutter wherever you think it can be changed. A simple Pull Request will do.

If you don't want to give it a chance, lack the time or the skills, please let us know and we will solve this. :)
Finally, we appreciate your time and your kind words for Cutter and hope to see you around.
