### ISSUE TITLE
Lighter Docker image

### ISSUE THREAD

**Issue by XVilka** [radareorg/cutter#1667]
There are two things to make it smaller:
- [ ] Switch from Ubuntu to Alpine
- [ ] Switch to multistage build

```Dockerfile
FROM alpine:edge AS builder
RUN apk add --no-cache qt

RUN cmake
....

FROM alpine:edge AS runner
RUN apk add qt
COPY --from=builder /home/user/cutter /home/user
ENTRYPOINT [...]
```

https://docs.docker.com/develop/develop-images/multistage-build/

**Comment by ITAYC0HEN** [comment]
@ps1337 , what do you think?

**Comment by ps1337** [comment]
Good suggestion, a multistage build is definitely a nice thing to have. As long as we don't have any issues with building cutter on alpine: Looks good to me for both things. I might also look into this once I have time, but feel free to submit PRs
