### ISSUE TITLE
No scroll bar or cursor/page keys on disassembly panel

### ISSUE THREAD

**Issue by gingerbeardman** [radareorg/cutter#167]
At leats on macOS it's not possible to scroll the disassembly panel vertically using the scroll bar (there isn't one) or cursor/page keys.

**Comment by xarkes** [comment]
Do people really use the scroll bar nowadays? I mean we invented the scrollwheel.

**Comment by gingerbeardman** [comment]
My main use for a scrollbar is as a visual indicator of how far I am through something. 

But to answer your question yes I use a combination of keys, scroll bar and mouse depending on context.

**Comment by xarkes** [comment]
Yep good point, but this requires a refactoring of the Disassembly Widget, so I don't think this will be done for next release.

**Comment by radare** [comment]
How far from what? The current section? Map? File? Address space?

**Comment by gingerbeardman** [comment]
Far from the beginning/end or top/bottom of the disassembly.

**Comment by xarkes** [comment]
"disassembly" does not really mean anything to me. I mean that it's only bytes, and maybe you are talking about the .text section? Which might be interesting but I've seen some binaries executing stuff outside the .text section so it's not very profitable I believe.

**Comment by gingerbeardman** [comment]
"disassembly" as displayed  in the user interface

<img width="504" alt="screen shot 2017-12-06 at 10 42 38" src="https://user-images.githubusercontent.com/49612/33657885-99a1b966-da72-11e7-844e-f6e7904ecbed.png">

**Comment by xarkes** [comment]
So a scroll bar for about 2**64 lines? Or am I missing something here?

**Comment by gingerbeardman** [comment]
Yes, please enable the vertical scroll bar. 

Horizontal scroll bar is already enabled.

**Comment by xarkes** [comment]
cc @thestr4ng3r

**Comment by thestr4ng3r** [comment]
Cursor and page keys are straight-forward and absolutely useful. I will probably implement those soon.

About the scrollbar, I see the same problem as @xarkes. We could say the range of the scrollbar is the complete memory range mapped to the file or the current section.
Take a look at Hopper for example. It has a scrollbar that goes through all mapped memory. But as soon as you have a file of a certain size, moving the scrollbar by a single pixel makes disassembly jump all over the place, so the scrollbar is no more useful except as a visual indicator for where you roughly are.
However, if the desired use of the scrollbar is a only as a visual position indicator, I would rather add that to the GraphicsBar that is currently displayed below the toolbar to show the position of the current seek, like Hopper does with this small red arrow for example:
![posindicator](https://user-images.githubusercontent.com/1460997/33659352-2f8b079a-da80-11e7-8482-d646eccf3647.png)

I will maybe experiment with a scrollbar at some point, but I totally agree with @xarkes and @radare. It is less useful than you might initially think.

**Comment by gingerbeardman** [comment]
That works for me. Thanks for your understanding.

**Comment by gingerbeardman** [comment]
Also reminds me of Sublime minimal

![https://i.stack.imgur.com/FNfcn.jpg](https://i.stack.imgur.com/FNfcn.jpg)

**Comment by Maijin** [comment]
That's fixed thanks @nezza
