### ISSUE TITLE
Define essentials Debugger requirements and create issues

### ISSUE THREAD

**Issue by Maijin** [radareorg/cutter#1678]
**Is your feature request related to a problem? Please describe.**

The Debugger be pushed in production. 

**Describe the solution you'd like**

Essentials features as well as requirements must be defined and tasks created accordingly. The project must be completed with those and the tasks ordered accordingly

**Comment by xarkes** [comment]
Ping @Maijn :)

**Comment by ITAYC0HEN** [comment]
@Maijin can you sure the hack.md here?
Probably @yossizap would want to have a look at it

**Comment by Maijin** [comment]
I provided to @yossizap the start i had but didn't really had time to work on it at all after that :/ Hackmd is in maintenance mode, will provide link when it's back up

**Comment by yossizap** [comment]
Didn't get to updating it either, I'll get to it once we're in a stable state with the basic features.

**Comment by ITAYC0HEN** [comment]
ahm? (how) should we proceed with this?

**Comment by yossizap** [comment]
We still have to finish it, we are currently at basic functionality.

**Comment by ITAYC0HEN** [comment]
we're quite advanced in the progress of this one. Tracking it in the hack.md and need to finish soon.

**Comment by ITAYC0HEN** [comment]
Closing as this issue doesn't help with keeping track really.
