### ISSUE TITLE
Duplicate widgets

### ISSUE THREAD

**Issue by karliss** [radareorg/cutter#1680]
**Environment information**
* Operating System: ArchLinux
* Cutter version: 116e72755587a8e3c0772c26cd8489a564761e93
* File format:

**Describe the bug**

Sometimes cutter opens all the widgets twice. Including ones that should really have only one copy like search bar or forward, back arrows.

**To Reproduce**

No Idea. I have seen it only ~3 times over a couple of months.

Happens immediately after opening Cutter. Resetting layout doesn't help.  Gets normal after restarting Cutter.

*update* see comment bellow

**Screenshots**

![dup](https://user-images.githubusercontent.com/7101031/61583072-b59e9580-ab3b-11e9-99cd-a4e91d117582.png)

**Additional context**

This is a very rare bug, if you have seen it or have any information about it write comment.

**Comment by ITAYC0HEN** [comment]
Super weird. Never experienced this

**Comment by karliss** [comment]
Happened again today while testing 1679

**Comment by karliss** [comment]
Found the trick for repeating it, it is necessary to trigger error before opening a file. 

* select io type that require specific file, for example gzip
* select an elf file (anything that isn't gzip)
* open an elf file with io type set to file://
* observe duplicate widgets

**Comment by ITAYC0HEN** [comment]
reproduced :)
