### ISSUE TITLE
Preferences not saving

### ISSUE THREAD

**Issue by gingerbeardman** [radareorg/cutter#169]
at least the following:

- [x] active tab in File Open
- [x] Projects path (dir.projects)
- [x] Unlock Panels
- [x] Show Tabs at Top

are not saved with project or app preferences.

**Comment by thestr4ng3r** [comment]
Tab at startup in NewFileDialog is selected dynamically depending on whether there are any projects saved or not. But I would have nothing against just saving it.

`dir.projects` comes from r2. Is the default in r2 loaded from somewhere, so we could modify that maybe?

**Comment by Maijin** [comment]
Yep

**Comment by xarkes** [comment]
Last item done in https://github.com/radareorg/cutter/commit/b222aaa09431e58d05277d94613073a14cd9a4f6
