### ISSUE TITLE
A problem while debugging a code!

### ISSUE THREAD

**Issue by q8ing** [radareorg/cutter#1692]
**Environment information**
* Operating System: windows 10
* Cutter version: 1.8.3
* File format: pe
 * Arch: x86
 * Type: EXEC (Executable file)

**Describe the bug**
Why does the debugger show me invalid instead of allowing me to continue debugging the code?

**To Reproduce**
F7 and F8 to step or to step over the code while debugging.

**Expected behavior**
Continuing debugging process.

**Screenshots**
![1](https://user-images.githubusercontent.com/52950756/61918909-ee83a380-af5b-11e9-83e3-16057585db9d.png)

**Additional context**
I am trying to debug crackme0x05.exe with cutter and I faced this problem.

**Comment by Maijin** [comment]
There is currently no debugger available in Cutter. 

What you're currently using/seeing only attempt to emulate the code. 

Since this functionality is not able to emulate Dynamic Library you're end up in this invalid sea.
