### ISSUE TITLE
r2dec decompiler

### ISSUE THREAD

**Issue by idandre** [radareorg/cutter#1699]
**Environment information**
* Operating System: arch 
* Cutter version: 1.8.3
* File format: elf64
 * Arch: x86
 * Type: DYN (Shared object file)

**Describe the bug**
If I type the command pdd In the Console the currently selected function is decompiled as it will be in radare2.

**To Reproduce**
1. Go to 'Window Pseudocode'
2. Click on 'Down Arrow to the right of Decompiler'
3. r2dec is not available

**Expected behavior**
toogle to r2dec and show decompiled code after left clicking the Refresh button.

**Screenshots**
![issue_Cutter](https://user-images.githubusercontent.com/41512496/62321251-80326a00-b4a2-11e9-9e4a-ee0ca4678e0c.png)

**Additional context**

**Comment by xarkes** [comment]
Hello, are you using the AppImage or did you compile Cutter yourself?
If you did compile yourself, could you provide the actual git commit?

Also can you print the output of `e cmd.pdc=?` (type in the console).
Thanks.

**Comment by idandre** [comment]
Dear Xarkes,

I am not sure what you mean by providing the actuall git commit. Yesterday I did not build the newest version 1.8.4 Sorry my mistake. Today I did

$ git clone https://github.com/radareorg/cutter.git

switched to cutter with

$ cd cutter

and did

$ ./build.sh

which did not work so i build it with cmake.

For your second task "e cmd.pdc=?" I just used the provided version in pacman for arch linux and got this output:

pdc
!r2snow
pdd

Now (1.8.4) there is r2dec available in the cutter window Pseudocode as Decompiler. But pdc and r2snow are not (as far as I remember in the last version (1.8.2 with r2 3.5.8 you one was able to choose between pdc and r2dec).

Thank you so far,
André


________________________________
Von: xarkes <notifications@github.com>
Gesendet: Freitag, 2. August 2019 14:25
An: radareorg/cutter <cutter@noreply.github.com>
Cc: ReverseiT <idandre@hotmail.de>; Author <author@noreply.github.com>
Betreff: Re: [radareorg/cutter] r2dec decompiler (#1699)


Hello, are you using the AppImage or did you compile Cutter yourself?
If you did compile yourself, could you provide the actual git commit?

Also can you print the output of e cmd.pdc=? (type in the console).
Thanks.

**Comment by thestr4ng3r** [comment]
pdc is deprecated and was removed from Cutter and snowman is not supported in Cutter.
So r2dec works for you now?

**Comment by idandre** [comment]
Sure with 1.8.4 all is going well.

Ty

________________________________
Von: Florian Märkl <notifications@github.com>
Gesendet: Freitag, 2. August 2019 16:33
An: radareorg/cutter <cutter@noreply.github.com>
Cc: ReverseiT <idandre@hotmail.de>; Author <author@noreply.github.com>
Betreff: Re: [radareorg/cutter] r2dec decompiler (#1699)


pdc is deprecated and was removed from Cutter and snowman is not supported in Cutter.
So r2dec works for you now?
