### ISSUE TITLE
Support for double byte text

### ISSUE THREAD

**Issue by gingerbeardman** [radareorg/cutter#170]
I'm working with Japanese at the moment.

**Comment by Maijin** [comment]
![image](https://user-images.githubusercontent.com/1408600/33652723-ba51311c-da6a-11e7-8689-bf531a8d49aa.png)

Already supported, be more specific

**Comment by XVilka** [comment]
Related to https://github.com/radare/radare2/issues/2032

**Comment by Maijin** [comment]
@gingerbeardman ping

**Comment by gingerbeardman** [comment]
Maybe this is an r2 issue? Here's a screenshot. 

I've highlighted some lines because strings are not legible in yellow on white.

![screen shot 2017-12-06 at 11 33 46](https://user-images.githubusercontent.com/49612/33659839-a1207f90-da79-11e7-92de-a09f9fb90316.png)

**Comment by Maijin** [comment]
yes this is r2 issue, see @xvilka pointer.

Closing here

**Comment by gingerbeardman** [comment]
On further consideration, I'm not 100% convinced this is double byte text?
