### ISSUE TITLE
Support radare2 Table API

### ISSUE THREAD

**Issue by XVilka** [radareorg/cutter#1716]
See [#7519 - Generic "table" command/api](https://github.com/radare/radare2/issues/7519) radare2 issue by @radare and @deepakchethan

Also relevant:
- [#14352 - Support Table API and `scr.utf8=true` in `p-h` command](https://github.com/radare/radare2/issues/14352)
- [#12745 - Generic "tree" command/API](https://github.com/radare/radare2/issues/12745)
- [#13763 - Support CSV](https://github.com/radare/radare2/issues/13763)
- [#3222 - Structured Document Helpers](https://github.com/radare/radare2/issues/3222)

**Comment by karliss** [comment]
@XVilka Please clarify a few things. Looking at the issues I didn't see anything implemented yet, is that correct?
Is Table API meant to provide a way of describing a visual look of table or just grid of values with different output formatters? I assume that support from cutter would mean parsing one of those formats. Will there be some meta information about column content (is it a string, number, address)?

**Comment by XVilka** [comment]
Yes, for now no need to care about that, unless you want provide suggestions for the implementation. It is work-in-progress feature in radare2, I will ping once it is ready to use.

**Comment by ITAYC0HEN** [comment]
Can you explain how Cutter would benefit from supporting ASCII table or this data structure? 
Today we use JSON to parse data and put it in visual GUI table

**Comment by xarkes** [comment]
> Yes, for now no need to care about that

I would rather not have an opened issue then.

**Comment by xarkes** [comment]
The idea is interesting, but I think it's too soon to take care of it. We should reopen that issue once it is integrated into radare2.
