### ISSUE TITLE
"Live" disassembly and pseudo code address selection

### ISSUE THREAD

**Issue by dmknght** [radareorg/cutter#1719]
**Is your feature request related to a problem? Please describe.**

I am thinking it would be awesome if cutter can have a feature like this (i don't know how to say it in English so i'll do it in the hard way): If I am having both pseudo code widget and disassembly / graph widget, when i click on a line in pseudo code, diasm / graph widget jumps to the offset in ASM code as well. (it is as same as ghidra). For a noob like me, it would be much more easier to read and track and understand the code.

**Describe the solution you'd like**
From what i understand, r2dec get output of radare2 and generates pseudo code and cutter gets output of r2dec (damn, so many steps). So i think there is no solution by now if cutter wants to access data directly (?)

**Describe alternatives you've considered**

This is `decompile current function with side assembly` from r2dec. Maybe we can map address from r2dec and set offset to radare2 and make a `movement event`?
Is it terrible for performance if we open large binary file?
![Screenshot at 2019-08-28 01-51-41](https://user-images.githubusercontent.com/29118926/63799486-69165900-c936-11e9-85d7-b07186cb0406.png)

**Additional context**

**Comment by ITAYC0HEN** [comment]
This is already implemented in Cutter. On which version you checked it?

**Comment by ITAYC0HEN** [comment]
Implemented here https://github.com/radareorg/cutter/commit/7017c8a323a8a68e7cbeda56e3085e95276efee7

**Comment by dmknght** [comment]
Ah sorry i think it is version of 2 weeks ago. Didn't catch the news.
