### ISSUE TITLE
Using backslash in variable name prevents it from further renaming

### ISSUE THREAD

**Issue by karliss** [radareorg/cutter#1729]
**Environment information**
* Operating System: ArchLinux
* Cutter version: 81f71693795ff97ae32c15635796e26335376349 compiled from git
* File format: elf

**Describe the bug**

It is possible to rename local variable using 'y' to something like "arg1\\" which prevents it from being further renamed and possible other actions.

**To Reproduce**

* find a function with stack variable or register argument
* open edit variable dialog using 'y'
* append backslash '\\' to the name
* confirm
* try renaming variable again back to original name
* observe that second rename fails and `Missing " in (afvn arg1 arg1\").` gets printed in terminal

**Expected behavior**

Either renaming variable to bad name gets rejected or such names are properly escaped when interacting with r2.

**Screenshots**

**Additional context**

There might be other problematic symbols beside backslash.

**Comment by xarkes** [comment]
What should we do? A quick fix on Cutter to replace `\` with empty string, or fix r2?
