### ISSUE TITLE
cutter-small.png doesn't exist; no icon installed

### ISSUE THREAD

**Issue by dtzWill** [radareorg/cutter#174]
Mentioned here:

https://github.com/radareorg/cutter/blob/b331dfd083edbbcbd33de83ce7bba17f4d142fe6/src/cutter.pro#L179

As a result, icon is not installed (Linux, non-appimage).

Using `cutter.svg` instead gets an icon installed, but recent commit history suggests what is desired is to install `cutter_appicon.svg` as `cutter.svg` (as is manually done for APPIMAGE builds).

The workaround I'm using for now is to use `cutter_appicon.svg` instead of `cutter-small.png` and modify the `cutter.desktop` to look for icon named `cutter_appicon` instead of `cutter`.

**Comment by dtzWill** [comment]
FWIW, I encountered this while packaging this up for nixpkgs: https://github.com/NixOS/nixpkgs/pull/32345

The changes I describe above are included in the Nix expression: https://github.com/NixOS/nixpkgs/pull/32345/commits/56a05d96db410444d679e71f22df58d7ffe844a2#diff-c66daaafccdc763a7c89bb67ae23e98bR17
(which should be fairly understandable even if you've not used Nix before)

**Comment by Maijin** [comment]
Can you send a Pull-Request
