### ISSUE TITLE
Rename (used-here) dialog is top-most

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/cutter#1742]
**Environment information**
* Operating System: Any
* Cutter version: most recent from Master 
* File format: Any

**Describe the bug**

The "Rename "xyz" (used here)" dialog is set to top-most and follows me around to different applications.

**To Reproduce**

1. Open a function
2. Click on some instruction with a used flag, and press Shift+N, or Right Click -> rename...
3. Now switch to different application such as your browser and see that the dialog is still there, top-most.

**Expected behavior**

The dialog should show only in the context of the program

**Screenshots**

![image](https://user-images.githubusercontent.com/20182642/64270219-7d141900-cf3b-11e9-8d2c-ccdf9666373b.png)

**Comment by karliss** [comment]
Properly fixing #1735 will probably fix this as well.

**Comment by ITAYC0HEN** [comment]
Fixed via #1743
