### ISSUE TITLE
Variable renaming broken when using asm.ucase

### ISSUE THREAD

**Issue by pandasauce** [radareorg/cutter#1749]
**Environment information**
* Operating System: Ubuntu 18.04 LTS
* Cutter version: 1.9
* File format: ELF

Pressing Y to rename the currently selected variable gives an empty dropdown.

**To Reproduce**

1. Open `vermu_elf` from R2Con CTF 2019 vermu1
2. Go to `main`
3. Click on `VAR_14H`
4. Press `Y`

Expected behavior: dropdown to have the currently selected variable, cursor to be in the name field.

It would be cooler to have different hotkeys for cursor to go into type or name field (IDA's Y and N hotkeys), but that is probably a feature request. Same for the Ghidra widget, but that is probably also a feature request.

**Comment by pandasauce** [comment]
Was caused by `asm.ucase` being set. The string matching algorithm for renaming should probably take that setting into account.

**Comment by xarkes** [comment]
Need to update the submodule.
