### ISSUE TITLE
Build errors on Ubuntu 16.04 (missing header files from path)

### ISSUE THREAD

**Issue by deeso** [radareorg/cutter#175]
Had to perform the additional step when building cutter:

```
cd src
mkdir build
cd build
cmake ..
cp -r ../../radare2/libr/include/* . <===| Need the r_*.h includes in the build directory or include path
make
```

**Comment by thestr4ng3r** [comment]
What exactly is your error and how did you install r2?
Please post the CMakeCache.txt cmake generates.

**Comment by deeso** [comment]
I followed all of the instructions stated on the main page.  
'''
<snip>
Scanning dependencies of target cutter
[  3%] Building CXX object CMakeFiles/cutter.dir/main.cpp.o
In file included from /research_data/code/git/cutter/src/MainWindow.h:6:0,
                 from /research_data/code/git/cutter/src/main.cpp:6:
/research_data/code/git/cutter/src/cutter.h:9:20: fatal error: r_core.h: No such file or directory
compilation terminated.
CMakeFiles/cutter.dir/build.make:62: recipe for target 'CMakeFiles/cutter.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/cutter.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/cutter.dir/all' failed
make[1]: *** [CMakeFiles/cutter.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
'''

Here's how I figured out the issue:
'''
cutter/src/build$ grep -Rn r_core.h .
./CMakeFiles/cutter.dir/CXX.includecache:36:r_core.h
./CMakeFiles/cutter.dir/CXX.includecache:37:../r_core.h
./CMakeFiles/cutter.dir/CXX.includecache:224:r_core.h
./CMakeFiles/cutter.dir/CXX.includecache:225:../r_core.h
./CMakeFiles/cutter.dir/CXX.includecache:6152:r_core.h
./CMakeFiles/cutter.dir/CXX.includecache:6153:/research_data/code/git/cutter/src/r_core.h
</snip>
'''

**Comment by thestr4ng3r** [comment]
So you did install r2 with `sys/install.sh`, right?
Please post the CMakeCache.txt. This is a single file in the build folder.

**Comment by thestr4ng3r** [comment]
Also, please try `pkg-config --cflags r_core`.

**Comment by deeso** [comment]
Ok.  I had to remove all installations of r2  in /usr/local/ and /usr/, and then do the installation in a clean console because of stale environment variables.
