### ISSUE TITLE
Enable Copy action in Decompiler Widget

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/cutter#1753]
**Is your feature request related to a problem? Please describe.**

Currently, the Decompiler Widget is set to Read-Only which probably disables the option to copy the selected text.

**Describe the solution you'd like**

Enable the option to Copy the selected text using Right-click and also using Ctrl+C.

**Comment by karliss** [comment]
If it can be selected it should be copyable even when read only.

**Comment by ITAYC0HEN** [comment]
Well, ctrl c didnt work for me. Does it work for you?

**Comment by ITAYC0HEN** [comment]
Seems like Qt::CustomContextMenu removes the default context menu and thus removes the support for copying text. 
Should I manually add a Copy action to copy selected text or there is a way to use custom context menu while preserving the regular context menu (with "Copy")

**Comment by a1ext** [comment]
@ITAYC0HEN then don't use custom menu, just add your actions to the widget's actions list

**Comment by karliss** [comment]
I don't think the theories above are correct. Ctrl+C sometimes works but inconsistently.  As has been observed by many people `ctrl+c` often triggers decompilation which causes text to be updated thus interfering with selection and copying.  There might be some conflicting or incorrectly set up shortcuts. Needs to be investigated how exactly it gets triggered. First thing to check is inserting breakpoint in decompilation function and looking at the stacktrace to see what event exactly triggers it.

**Comment by Anubis88** [comment]
The best approach would be to add an option in the right-click contextual menu to:

```
Copy > Address
     > Copy text
```

This way you are still open to add further options in the future. Thanks.

**Comment by NirmalManoj** [comment]
Closed by PR #2391
