### ISSUE TITLE
Disable seeking when selecting text in Decompiler Widget

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/cutter#1756]
**Is your feature request related to a problem? Please describe.**

Currently, when text is selected in the Decompiler widget, the seek is changed as you go with the selection. Example in the attached gif animation.

![2019-09-07_12-23-06](https://user-images.githubusercontent.com/20182642/64473699-440dbb80-d16a-11e9-8576-88680513da48.gif)

**Describe the solution you'd like**
Selecting text should not trigger seeks. Seek should be triggered only on the release of the mouse button in a single click, and not as part of text selection.

**Comment by xweskingx** [comment]
What is the expected location of the seek for a selection, should it be the end position of the selection or the start (anchor)?

If the seek should always be at the anchor of a selection, then would it be sufficient to only seek when the anchor (start) of the selection has changed, rather than detecting mouse release event?

**Comment by ITAYC0HEN** [comment]
This is a good question - as mentioned in the original post -
> Selecting text should not trigger seeks. Seek should be triggered only on the release of the mouse button in a single click, and not as part of text selection.

It means that only a single click should trigger a seek in Cutter. While performing text selection, seek should not be triggered. Not in the beginning (button pressed) nor in the end (button released). The idea is that when the user clicks in the widget, they are trying to seek. And when they selection text, they want to select and not to seek.
