### ISSUE TITLE
Cutter 1.9.0 Ghidra Decompiler (r2ghidra) not detected / used on some Windows10/Win7 PC

### ISSUE THREAD

**Issue by bvernoux** [radareorg/cutter#1759]
**Environment information**
* Operating System: windows 7sp1 + 16GB RAM
* Cutter version: 1.9.0
* File format: pe
 * Arch: x86
 * Type: EXEC (Executable file)

**Describe the bug**
Cutter 1.9.0 Ghidra Decompiler (r2ghidra) not detected / used on some Windows10/Win7 PC (In this bug report I provide mainly screenshot on Win7Sp1 64bits (up to date) but I have reproduced exactly same issue on an other PC with Win10 Pro 64bits (with 32GB RAM)

**To Reproduce**
1. Download https://github.com/radareorg/cutter/releases/download/v1.9.0/Cutter-v1.9.0-x64.Windows.zip
2. Extract the archive with 7Zip (I used 19.00 x64) to **D:\Tools\Cutter-v1.9.0-x64.Windows**
3. Start it (Double click from Windows) from D:\Tools\Cutter-v1.9.0-x64.Windows\cutter.exe
4. No error but Ghidra Decompiler (r2ghidra) is not detected and not used (r2dec is used instead)

**Expected behavior**
Ghidra Decompiler (r2ghidra) shall be used by default and also present in plugins (like it is on Linux for example tested with XUbuntu 18.4 LTS all work fine)

**Screenshots**
See screenshots:
![Screenshot1_no_r2ghidra_Win7Sp1](https://user-images.githubusercontent.com/432709/64474834-b38ba700-d17a-11e9-82c9-f560a0d9b206.jpg)

![Screenshot2_r2ghidra_plugin_not_found_Win7Sp1](https://user-images.githubusercontent.com/432709/64474839-bd150f00-d17a-11e9-8e5f-28f4462b823d.jpg)

**Comment by pelijah** [comment]
Ghidra plugin is static so it is not present in plugin tab. Try to run `pdg` command from console widget. If it return disassembly then plugin is really broken.

**Comment by pelijah** [comment]
So there is no `ghidra` entry in the `Decompiler` drop-down list in the bottom right corner?

**Comment by bvernoux** [comment]
I confirm that in console `pdg` works and code is decompiled using r2ghidra
```
[0x0044f125]> pdg
// WARNING: Unable to track spacebase fully for stack
// WARNING: Variable defined which should be unmapped: var_7ch
// WARNING: Globals starting with '_' overlap smaller symbols at the same address
// WARNING: [r2ghidra] Failed to match type LPSTARTUPINFOA for variable lpStartupInfo to Decompiler type: Unknown type
// identifier LPSTARTUPINFOA
// WARNING: [r2ghidra] Failed to get address for var arg_10h
// WARNING: [r2ghidra] Failed to get address for var arg_8h
// WARNING: [r2ghidra] Failed to get address for var arg_4h
// WARNING: [r2ghidra] Failed to match type UINT for variable uExitCode to Decompiler type: Unknown type identifier UINT
// WARNING: [r2ghidra] Failed to get address for var arg_34h
// WARNING: [r2ghidra] Failed to get address for var arg_24h
// WARNING: [r2ghidra] Failed to get address for var arg_ch

void entry0(uint32_t uParm1, int32_t iParm2)
{
    code *pcVar1;
    int16_t *piVar2;
    int32_t iVar3;
    undefined4 uVar4;
    uint32_t uVar5;
...

```
Question is why it is not used by default by Decompiler window ? (like it is under Linux)
  - I have not found any way to force use of r2ghidra for Decompiler window as it default to r2dec in my case

**Comment by bvernoux** [comment]
Oups finally I have found the option in Decompiler window Decompiler is r2dec and can be changed to Ghidra and all work fine
So it is just it was by default on r2dec and it shall be changed manually to Ghidra
After that when I exit and relaunch Cutter it use Ghidra again

So this issue is minor and it will be good to set Ghidra decompiler by default on first launch for future release

**Comment by xarkes** [comment]
Thanks for the feedback, moved in https://github.com/radareorg/cutter/issues/1761.

**Comment by eagleoflqj** [comment]
> Oups finally I have found the option in Decompiler window Decompiler is r2dec and can be changed to Ghidra and all work fine
> So it is just it was by default on r2dec and it shall be changed manually to Ghidra
> After that when I exit and relaunch Cutter it use Ghidra again
> 
> So this issue is minor and it will be good to set Ghidra decompiler by default on first launch for future release

Thank you a lot.
