### ISSUE TITLE
jump to symbol broken when using version of r2 in git submodule

### ISSUE THREAD

**Issue by dtzWill** [radareorg/cutter#176]
## Overview

It appears cutter has problems jumping to symbols when using either the r2 version in the git submodule
or the latest release (2.1.0); using 2.0.1 works properly.

The example below provides a particular binary and symbol to show the problem,
but it seems to happen when "jumping" to references in general and not just the lookup bar.
(double-clicking symbol from symbols table/tab, or following reference from disassembly graph)

Testing was done on Linux in various environments but mostly on NixOS.

## Steps

* Open a binary such as [this `nix-env`](http://dtz.so/docs/numiq)
* Type "main" in lookup bar at top, hit 'enter'
* Observe behavior

### Expected Output

Jumps to 'main' (`sym.main`).

### What happens instead

Console complains about:

```
Invalid address (method.boost::io::detail.(anonymousnamespace)::do_pad(std::__cxx11::basic_string<char,std::char_traits<char)
|ERROR| Invalid command 'afcc @ method.boost::io::detail.(anonymousnamespace)::do_pad(std::__cxx11::basic_string<char,std::char_traits<char>,std::allocator<char>>&,long,char,std::_Ios_Fmtflags,bool)' (0x61)
Oops at 0x0021fb9a (ff ff ff ...)
Unknown opcode
```

And seemingly jumps to that boost symbol instead?

## Versions and Results

* Built to use r2 2.0.1: works as expected
* Built to use r2 2.1.0: prints error and jumps to seemingly unrelated symbol
* AppImage build (using r2 pinned as submodule): prints error and jumps to seemingly unrelated symbol

Please let me know if additional information or testing would be useful, thanks!

**Comment by Maijin** [comment]
Does main exists in your binary? Because this works here

**Comment by dtzWill** [comment]
Yes, main exists-- notice that cutter is able to "jump" to it successfully when built to use radare2 2.0.1.

Can you try the binary I provided to see if you can reproduce?

I suspect this has something to do with long (demangled) symbols; perhaps some printing/formatting differences cause problems with recent r2?

Poking at this some more it seems cutter actually manages to create an empty text file containing a portion of some symbol name (!):

```
',std::allocator<char>>&,long,char,std::_Ios_Fmtflags,bool)'
```

Which is a bit alarming.

**Comment by Maijin** [comment]
That's not a cutter issue. That's a radare2 analysis issue
That's the same issue as https://github.com/radare/radare2/issues/8824

**Comment by Maijin** [comment]
Can you open an issue on radare2 tracker, I'm closing here.

**Comment by radare** [comment]
Its because aaa. So enable aa in analysis dialog

Ill fix this when i have some time. One solution would be to run af@main after aaa?

**Comment by Maijin** [comment]
FFS no, it's happenning with aa too I already said that
