### ISSUE TITLE
Use custom context menu in Decompiler instead of DisassemblyContextMenu

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/cutter#1764]
**Is your feature request related to a problem? Please describe.**

Currently the DisassemblyContextMenu is the one used in graph, disassembly and Decompiler widgets. This context menu wasn't written with the Decompiler in mind and may contain irrelevant entries and lack of relevant ones. 

**Describe the solution you'd like**
I suggest using a custom context menu for Decompiler.

**Comment by karliss** [comment]
Currently work in progress as GSoC project done by @NirmalManoj
