### ISSUE TITLE
Cutter hangs on a 1.5MB so file

### ISSUE THREAD

**Issue by ikey4u** [radareorg/cutter#1765]
**Environment information**
* Operating System: MacOS Mojave 10.14.6
* Cutter version: Cutter 1.9.0 - Codename "Trojan Dragon"
* File format: ELF32

**Describe the bug**

Launch cutter and open the attached so file, and cutter will hang there.

**To Reproduce**

1.  Launch cutter
2. Select the attached so file with default option
3.  Let cutter analyze the file

**Expected behavior**

Cutter will cost less one minute to complete the anaylsis.

**Screenshots**

![image](https://user-images.githubusercontent.com/12681575/64500423-af34ca80-d2ef-11e9-9da8-8f7423ee0c95.png)

[libcrackme.so.zip](https://github.com/radareorg/cutter/files/3588480/libcrackme.so.zip)

**Comment by ITAYC0HEN** [comment]
for me it stuck more than 15 minutes on radare2.

```
$ r2 libcrackme.so

[0x0005e240]> aaa
[x] Analyze all flags starting with sym. and entry0 (aa)
[ ] Analyze function calls (aac)


```

**Comment by xarkes** [comment]
If it's stuck on analysis, it's more likely a bug from r2. Investigation is needed.

**Comment by pelijah** [comment]
Profiler says that r2 spends too much cpu time on this https://github.com/radareorg/radare2/blob/3b8b754cdf394f7b849922958cb5d42c5c4884e6/libr/anal/op.c#L152

**Comment by thenger** [comment]
Huh I tested it with a game installer (namely Valorant) of 64MB (x and I was wondering why it took time

Tested on windows 10 Cutter-v1.10.2-x64.Windows

**Comment by pelijah** [comment]
Actually that hang was fixed a long time ago so the issue can be closed.
