### ISSUE TITLE
Better Disassembly Fetching

### ISSUE THREAD

**Issue by thestr4ng3r** [radareorg/cutter#177]
Current State:
- DisassemblyWidget uses `pd` and displays the output. If the offset for a displayed line is needed, it parses the begin of the line. This works currently, but obviously is a horrible solution and breaks with `asm.offset=false`
- DisassemblerGraphView uses `agj` which does not output nicely formatted disassembly, but only plain opcodes.

My idea:
Add a command to r2 (called `pdJ` or whatever) that is basically something between `pd` and `pdj` and uses the whole formatting logic from `r_core_print_disasm()`. It should output the fully formatted lines with additional information, like this for example:
```
[
  {
    offset: 4213152,
    text: "0x004049a0    test2:",
    flag: "test2"
  },
  {
    offset: 4213152,
    text: "0x004049a0 xor ebp, ebp"
  },
  {
    offset: 4213154,
    text: "0x004049a2 mov r9, rdx"
  },
  {
    offset: 4213157,
    text: "0x004049a5 pop rsi"
  }
]
```
At the very least it should be text+offset.
The same output could be integrated in a similar command like `agj`.

**Comment by radare** [comment]
I would do this as an option. Keeping the current one can be useful because it honors r2 format but its slow. R2 will be improved over time. But a gui should cache and be faster

**Comment by thestr4ng3r** [comment]
I don't get what you mean. What I want is not much different from what we are doing already. The difference is that formatted disassembly should be retrieved with offsets "annotated" to each line.

**Comment by thestr4ng3r** [comment]
Currently experimenting a bit in https://github.com/thestr4ng3r/radare2/tree/cutter-disas

**Comment by radare** [comment]
What i mean is that r2 disasm output is configurable via eval vars and its already used by many ppl and it works. Redoing that loop can result in missing info like the emulation etc. Which will require to work on enhancing the pdj. So i think this can be good to have but not as a replacement. At least for now.

**Comment by thestr4ng3r** [comment]
Ah yes, I agree. The way I am currently implementing it, is by directly adding the functionality to `r_core_print_fcn_disasm()` and all the `ds_*` functions it uses.

The idea is that every time a new line starts, `ds_begin_json_line()` is called which prints `{"offset":<whatever>,text:"` and when the line has been finished, instead of directly printing a newline, `ds_newline()` is called, which prints `"}`.

Whether this should be done or regular text disassembly should be printed is controlled by `use_json` in `RDisasmState`

See the current diff here: https://github.com/radare/radare2/compare/master...thestr4ng3r:cutter-disas

This does what I want, works fine and includes all eval vars and features available already without duplicating code.

One danger I see here is that in the future when someone wants to modify the disassembly code in radare2, he has to follow the rules of `ds_begin_json_line()` and `ds_newline()`, otherwise it will break Cutter.
We might catch some cases with tests though.

However, this is the best solution I can currently think of. We really need to get rid of relying on `asm.offset` to always give us the offset at the start of the line, but reimplementing disassembly printing is stupid as well.

What do you think?

**Comment by thestr4ng3r** [comment]
@radare Also, do you think it would be a good idea to add a parameter to `r_core_print_disasm()`? (since it is a public api function)

**Comment by radare** [comment]
In r2land we break abis without too much concern. In fact i plan to do some big api breaks at some point. Commands are more stables than apis
