### ISSUE TITLE
Define string of length N in address

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/cutter#1771]
**Is your feature request related to a problem? Please describe.**

Currently, we can define a string in a given address. Sadly, we can't define its length and radare2 tries to understand it by itself

![image](https://user-images.githubusercontent.com/20182642/64545600-53873300-d329-11e9-8224-7c63fa06a7e0.png)
 
**Describe the solution you'd like**

We currently use `Cs @ <addr>`, we can add the option to use `Cs <len> @ <addr>` in addition, to give the user more power

**Comment by ITAYC0HEN** [comment]
CC @pandasauce

**Comment by pandasauce** [comment]
Ideally should work with current selection in hexdump/disasm without having to supply a size. I started working on the hexdump version, but got stuck building the AppImage to test my changes. Might get another chunk of free time towards the end of this week, no promises though.

**Comment by karliss** [comment]
There is no need to build AppImage for development purpose unless you are testing the Appimage packaging itself.

**Comment by Properrr** [comment]
Hello, I implemented the sub-menu for strings.
I will create PR with this feature after cleanup

![image](https://user-images.githubusercontent.com/5008234/70696105-e52f7500-1c77-11ea-9e6e-4a9ecc485763.png)

![image](https://user-images.githubusercontent.com/5008234/70695735-312dea00-1c77-11ea-8c20-8c53fb6b31bb.png)

**Comment by ITAYC0HEN** [comment]
Nice! notice the typo in "Advanced". Also, if possible, a heuristic to guess the Size will be great

**Comment by ITAYC0HEN** [comment]
Thanks to @Properrr , this feature is now implemented :)
A bit late to close it because we forgot haha

Good work!  Waiting to see your next ones :)
