### ISSUE TITLE
Create a global plugin path

### ISSUE THREAD

**Issue by dmknght** [radareorg/cutter#1783]
**Is your feature request related to a problem? Please describe.**

I am packaging cutter for Parrot OS with pre-installed ghidra decompiler. However the current appdir path is in `$HOME` folder which isn't supported by debhelper (from the docs i read online). I think i can change the `appdir` flag of cutter but it looks like cutter won't use $HOME path to read plugins in the future so users can't install plugin with user permission. I think this way will very friendly for Debian packaging.

**Describe the solution you'd like**
Create a global path for plugin and an other path in `$HOME`. It should be like vim:
- `/etc/vimrc` is the global path
- `$HOME/.vimrc` is the local path of user

**Describe alternatives you've considered**

**Additional context**

**Comment by karliss** [comment]
I suggest using https://doc.qt.io/qt-5/qstandardpaths.html if possible.

**Comment by dmknght** [comment]
I think `/usr/share/` or `/usr/local/share` should be good so Debian packaging should be as easy as normal. It can be add as PREFIX in make file so maintainer just need to add a flag.
And i see r2ghidra decompiler writes its data to radare2 plugin path (and it is in home folder) so maybe radare2 must have this kind of path as well (i didn't check Makefile flags of radare2).

**Comment by dmknght** [comment]
@karliss do you know how can I set cutter plugin path in this version? I is like hard coded to me. It is always in `/home/dmknght/.local/share/RadareOrg/Cutter/plugins`. I tried ROOT_INSTALL flag and CMAKE_INSTALL_PREFIX but the path doesn't change.

**Comment by karliss** [comment]
I haven't touched the plugins but looking at the code it seems like it is using first item from  `QStandardPaths::AppDataLocation`. Would it work for you it used all of them ("~/.local/share/<APPNAME>", "/usr/local/share/<APPNAME>", "/usr/share/<APPNAME>") instead of just first one?

**Comment by dmknght** [comment]
From output of terminal i saw the first one only. I also add ghidra plugin for cutter into `/usr/share/` but it doesn't work (it worked for $HOME path).
![Screenshot at 2019-09-23 23-57-15](https://user-images.githubusercontent.com/29118926/65446113-e1047000-de5d-11e9-804a-a88112b2871a.png)

**Comment by karliss** [comment]
Maybe I wasn't clear. Yes it is currently using the first one https://github.com/radareorg/cutter/blob/b9be49b8846feaa004d4541aa08daf7fc36b9eff/src/plugins/PluginManager.cpp#L39 . I was asking if changing the Cutter to use all of them would solve your packaging problem?

**Comment by dmknght** [comment]
ahhh yeah. It will solve my all packaging problem easily without adding new flag in cmake or something like this from cutter side.

**Comment by dmknght** [comment]
1 more question: does radare2 use only 1 plugin path as same as cutter? becuase if radare2 has 2 paths like this, i can make ghidra decompiler be installed with radare2 and radare2-cutter

**Comment by dmknght** [comment]
@karliss i saw on google debian package can be installed for user only so please give me a few day before you change the code about this issue. I'll package r2ghidra-dec, try install it with user permission and give the feed back.

**Comment by karliss** [comment]
@dmknght You can start testing the branch in in PR. I still need to test if special case for AppImage can be removed but that shouldn't affect your setup.

**Comment by dmknght** [comment]
Thanks. I am goin to test and report as soon as possible (please give me 24 hours).
P/s: previous result was failed sadly

**Comment by dmknght** [comment]
P/s2: it would be easier if you can contact me in telegram, @dmknght so i can ask you everything about new flags and others so i think we can work easier about it :D
