### ISSUE TITLE
Strings not visible as yellow on white

### ISSUE THREAD

**Issue by gingerbeardman** [radareorg/cutter#179]
I've highlighted some lines because strings are not legible in yellow on white.

![screen shot 2017-12-06 at 11 33 46](https://user-images.githubusercontent.com/49612/33659854-b523ae2c-da79-11e7-9657-3caa9ee395ae.png)

**Comment by Maijin** [comment]
See https://github.com/radareorg/cutter/blob/master/src/utils/Configuration.cpp you can even use the github pencil to contribute.

**Comment by xarkes** [comment]
Will be fixed in https://github.com/radare/radare2/pull/8995

**Comment by Maijin** [comment]
Fixed
