### ISSUE TITLE
r_core.dll\rcons.dll

### ISSUE THREAD

**Issue by MaheshMahi19** [radareorg/cutter#1791]
I want to use Cutter in my windows Machine. But When I am trying to use Cutter.exe it's not opening and those[Titled] Errors are popping up! :(

![Capture](https://user-images.githubusercontent.com/30853110/65630225-9cf6a400-dff2-11e9-9398-b981c7f3ad8f.PNG)
and the window is up!
any solution

**Comment by xarkes** [comment]
Did you manage to solve your issue?
It looks like there is packaging issue like missing dll :)
