### ISSUE TITLE
Newly created graph dock have empty title

### ISSUE THREAD

**Issue by karliss** [radareorg/cutter#1802]
**Environment information**
* Operating System: Arch Linux
* Cutter version: fee8db6ad862cb570691778dc868ed60c256fe0f
* File format: any

**Describe the bug**

**To Reproduce**

* Open any file in cutter
* Click Windows/Add Graph
* Observe that the dock has empty title
* After changing current function title 

**Expected behavior**

* Title gets set immediately when opening

**Screenshots**

**Additional context**

**Comment by dwarvish** [comment]
Add Graph First On Windows Menu then add Graph Overview

**Comment by karliss** [comment]
@dwarvish What did you meant by that? Are those instructions for producing different bug?
