### ISSUE TITLE
After installing r2ghidra-dec, r2dec disappears from Decompiler's menu bar

### ISSUE THREAD

**Issue by doublegrey** [radareorg/cutter#1808]
**Environment information**
* Operating System: Arch Linux
* Cutter version: Version 1.9.0 (using r2-3.8.0)
* File format: All file formats

**Describe the bug**
After installing r2ghidra-dec, you can't choose r2dec - tooltip is inactive

**To Reproduce**

1. Install r2dec and r2ghidra-dec
2. Open Cutter
3. Ghidra's decompiler open by default, but you can't change it

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/25150523/66062470-2a357d80-e54a-11e9-8360-6564db4e73c5.png)

**Comment by ITAYC0HEN** [comment]
CC @thestr4ng3r

**Comment by ITAYC0HEN** [comment]
@thestr4ng3r can you reproduce?

**Comment by thestr4ng3r** [comment]
No. @doublegrey can you still reproduce this with current master of Cutter, r2 and r2ghidra-dec?

**Comment by doublegrey** [comment]
Sorry for late response. I can' reproduce this issue with current Cutter's version.
Have a nice day!
