### ISSUE TITLE
Breakpoint in emulation mode

### ISSUE THREAD

**Issue by dukebarman** [radareorg/cutter#1809]
**Environment information**
* Operating System: macOS Mojave
* Cutter version: 1.9
* File format: PE

**Describe the bug**

Couldn't set breakpoint in emulation mode

**To Reproduce**

1. Open `crackme0x02.exe` from [IOLI-crackme](https://dustri.org/b/files/IOLI-crackme.tar.gz)
2. Go to 0x00401365
3. Start emulation
4. Set breakpoint at 0x00401382 with F2 key or through context menu with RMB click (`Continue until line` works)

**Expected behavior**

Successfully set breakpoint.

**Comment by karliss** [comment]
Tried the breakpoints during emulation. Here are my observations.
* setting breakpoint using contextmenu or F2 works - entering db in console shows that breakpoint was set and continue stops at it
* setting breakpoint using breakpoint widget works at the same amount as described above
* breakpoint widget doesn't show any of the breakpoints
* disassembly and graph widget doesn't show any visual indicator of breakpoints
