### ISSUE TITLE
Add shortcut label to Redo and Undo seek on Edit menu

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/cutter#1836]
**Is your feature request related to a problem? Please describe.**

Add labels to show the keyboard shortcuts of Redo Seek and Undo Seek in the “Edit” menu.
![image](https://user-images.githubusercontent.com/20182642/66716694-63d37780-edd9-11e9-9d0b-88793b7aa76a.png)

I want this menu to display the shortcuts to trigger these actions. Similar to what you can find in any context menu. E.g -
![image](https://user-images.githubusercontent.com/20182642/66716743-0986e680-edda-11e9-8aac-d75a7573d5aa.png)

Currently the shortcut for "Seek backward" is <kbd>Esc</kbd>
we don't have a shortcut for "Seek next" (Seek forward) and **we need to decide on one**

**Describe the solution you'd like**

My feature request has three parts:
1. Decide for a keyboard shortcut for Seek forward
2. Show the labels of the shortcuts in the Edit menu
3. Show tooltip with the keyboard shortcuts when hovering the back\forward arrows
![image](https://user-images.githubusercontent.com/20182642/66716758-35a26780-edda-11e9-9933-5e77f02d642c.png)

**Additional context**

IDA uses <kbd>Ctrl</kbd>+<kbd>Enter</kbd> for Seek Froward

**Comment by karliss** [comment]
There should already be shortcuts in cutter for seeking back and forward based on standard key back and forward. Alt+left and alt+right on non macos and alt+[ on macos.

The task itself should be fixed by having the same instance of qaction in menu and toolbar.

**Comment by karliss** [comment]
See #1299
