### ISSUE TITLE
Move "Show bytes (asm.bytes)" setting to a more visisble place

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/cutter#1838]
**Is your feature request related to a problem? Please describe.**

The "Show bytes" setting is one of the most useful and popular settings we have, but currently, it is not as visible because it is in the bottom of the Metadata tab on Preferences dialog.

![image](https://user-images.githubusercontent.com/20182642/66717028-34bf0500-eddd-11e9-94c2-c9e86108e15d.png)

**Describe the solution you'd like**
1. Put it in a more visible place as the top of the list or in `Style` tab which is more suitable there
2. Change the label from "Shwo bytes" to "Display the bytes of each instruction"

**Comment by z3v5** [comment]
I will handle it
