### ISSUE TITLE
Debug : return to a wrong address

### ISSUE THREAD

**Issue by Meng-YC** [radareorg/cutter#1875]
<img width="802" alt="截屏2019-11-12上午8 51 19" src="https://user-images.githubusercontent.com/56018598/68632466-99c76100-0529-11ea-98d0-c2493dd3f44d.png">
In this picture, the return of 0x100000f1c should be returned to main, but returned to 0x00000000
<img width="1351" alt="截屏2019-11-12上午8 54 14" src="https://user-images.githubusercontent.com/56018598/68632588-05113300-052a-11ea-83f4-3d1b341f7518.png">
How can I fix this?

**Comment by ITAYC0HEN** [comment]
Your issue is lacking of crucial information. Please fill all the required
information from the template.
Specifically, what binary did you use, what steps did you take, where did
you begin the emulation, etc

Also, please notice that the feature you test isn't Debugging, but
Emulation

**Comment by Meng-YC** [comment]
I tried to write the following code in c language.
<img width="465" alt="截屏2019-11-12上午9 42 42" src="https://user-images.githubusercontent.com/56018598/68634543-cdf25000-0530-11ea-88fc-6285785a1762.png">
The above picture is the result of decompilation.
then I simulated the instruction to 0x100000f47 to jump to the f1 function, which is 0x100000ef0, step by step simulation, reached the ‘return’ of 0x100000f1c, and then should it return the instruction of 0x100000f4c?

**Comment by ITAYC0HEN** [comment]
Sadly, without the relevant information, we can't respond and support this issue. Moreover, as it seems - even if there is an issue, it is related to our parent-project, radare2.

We appreciate the time you invested in opening a new issue report this. At this time, I will close this issue. Please don't hesitate to re-open it with more information and open new ones, following our template for issues. 


Thanks!
