### ISSUE TITLE
define length of a string in cutter

### ISSUE THREAD

**Issue by andrewclarkii** [radareorg/cutter#1876]
It would be great if you add this feature:

I have got this, when I marked code as a string:
.string "END OF MW_SHELL\xff\xff\xff\xff\xff\xff
And I want this:
.string "END OF MW_SHELL
and whole \xff define as dup X (ff)?

https://twitter.com/thestr4ng3r/status/1159042131962617856

**Comment by karliss** [comment]
Duplicate of #1771
