### ISSUE TITLE
Strings widget show unreadable character

### ISSUE THREAD

**Issue by dmknght** [radareorg/cutter#1884]
**Environment information**
* Operating System: Parrot OS 4.7 amd64
* Cutter version: 1.9.0 pulled 23/11/2019
* File format: ELF

**Describe the bug**
Strings widget shows invalid characters (nothing can be read)
![Screenshot at 2019-11-23 17-26-51](https://user-images.githubusercontent.com/29118926/69477266-ad6ea380-0e16-11ea-9e44-fe3e313c8970.png)

**To Reproduce**

1. Open Cutter with auto analysis
2. See the bug in Strings widget

**Expected behavior**
Regular strings like normal

**Additional context**
- R2 output still shows characters / strings correctly
- R2 updated to 23/11/2019
![Screenshot at 2019-11-23 17-28-11](https://user-images.githubusercontent.com/29118926/69477273-bc555600-0e16-11ea-9609-ee3adf9e728f.png)
- Dissasm widget shows text correctly
![Screenshot at 2019-11-23 17-28-11](https://user-images.githubusercontent.com/29118926/69477274-c4ad9100-0e16-11ea-97e7-8e285511eb2b.png)
- Seems like the bug happens after 9/11/2019 (It happened to me from patch 16/11/2019 and 23/11/2019 (latest) )
Build flags `-DCUTTER_ENABLE_QTWEBENGINE=true -DCUTTER_ENABLE_GRAPHVIZ=true -DCUTTER_ENABLE_KSYNTAXHIGHLIGHTING=on`

**Comment by thestr4ng3r** [comment]
Caused by https://github.com/radareorg/radare2/commit/54d503f7c618ad0edddf1ac69e6769b266299531
