### ISSUE TITLE
Appimage fails to run on Ubuntu 16.04

### ISSUE THREAD

**Issue by vikasgola** [radareorg/cutter#1897]
**Environment information**
* Operating System: Ubuntu 16.04
* Cutter version: 1.9.0
* File format: appimage

**Describe the bug**

Running appimage downloaded from https://cutter.re/ in Ubuntu 16.04 gives

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

**To Reproduce**

1. wget https://github.com/radareorg/cutter/releases/download/v1.9.0/Cutter-v1.9.0-x64.Linux.appimage
2. chmod +x Cutter-v1.9.0-x64.Linux.appimage
3. ./Cutter-v1.9.0-x64.Linux.appimage
4. Error: 

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
Available platform plugins are: xcb.

**Expected behavior**
I expected it to run.

**Screenshots**
None

**Additional context**
`uname -a`
Linux identity 4.15.0-70-generic #79~16.04.1-Ubuntu SMP Tue Nov 12 14:01:10 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by cshanahan** [comment]
I experienced the same error on openSUSE Leap 15.1.

**Environment information**
Operating System: openSUSE Leap 15.1
Cutter version: 1.9.0, 1.10, 1.10.1
File format: AppImage

**Error / Output**
```
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.
```

**Steps to Reproduce**
1)  Download AppImage from GitHub
2)  chmod +x Cutter-v1.10.1-x64.Linux.AppImage
3)  ./Cutter-v1.10.1-x64.Linux.AppImage

**Comment by vikasgola** [comment]
@cshanahan Try installing by r2pm that worked for me.
