### ISSUE TITLE
Code Emulation Does Nothing

### ISSUE THREAD

**Issue by iceblu3710** [radareorg/cutter#1901]
**Environment information**
* Operating System: Ubuntu
* Cutter version: v1.8.3 and v1.9.0
* File format: z80 Binary Dump

**Describe the bug**
None of the emulation features do anything. I have tried all the type of emulators and they do not run in the background. The code steps through like its running but no registers or stack changes happen. The console prints out this message every set, the same message regardless of the emulator selected.

```
Failed to parse JSON for command "drrj": illegal value
[,{"reg":"f","value":"0x0","ref":""},{"reg":"a","value":"0x0","ref":""},{"reg":"c","value":"0x0","ref":""},{"reg":"b","value":"0x0","ref":""},{"reg":"e","value":"0x0","ref":""},{"reg":"d","value":"0x0","ref":""},{"reg":"l","value":"0x0","ref":""},{"reg":"h","value":"0x0","ref":""}]
```

**To Reproduce**

1. Select a function
2. Click on the green play "emulator" button
3. Press "Step"
4. The next line of assembly is selected but nothing changes

**Expected behavior**

I was hoping to be able to set the HL register, step into the function and see how the function manipulates the SP. 

**Additional context**

You can select Bochs as the external emulator but there are no setup or configurations, how is this suppose to work?

**Comment by karliss** [comment]
`adA_  8          z80         GPL     Zilog Z80 (by condret)`
R2 does not support emulating z80 code.

**Comment by karliss** [comment]
Isn't Bochs a x86 emulator? How is that relevant in this issue?

**Comment by ITAYC0HEN** [comment]
Since no response to our questions was given by you, we will sadly close this issue for now. 
While this issue can still be relevant, we simply do not have enough information to work with and investigate the problem.

Please feel free to re-open this issue if needed.
Thank you!
