### ISSUE TITLE
Install headers to global includes folder

### ISSUE THREAD

**Issue by dmknght** [radareorg/cutter#1914]
**Is your feature request related to a problem? Please describe.**

By now, all header files won't be installed into system path (like `/usr/include` for example) so if any plugin has to compile the source code, it needs Cutter source code (the whole project code)

**Describe the solution you'd like**

Install headers in `/usr/include` or whatever system has so plugins can use the headers to compile the source (as same as current radare2 i believe)
**Describe alternatives you've considered**

Debian packaging should set the `libradare2-cutter-dev` or something like that for the header

**Additional context**

**Comment by ret2libc** [comment]
I also need this to package r2ghidra cutter plugin in Fedora. I may try to fix this issue in the next days.

**Comment by karliss** [comment]
@ret2libc Note that currently there is no proper install target for cmake. So it's a bit more work than adding headers to the list of file that need to be installed.

**Comment by dmknght** [comment]
> I also need this to package r2ghidra cutter plugin in Fedora. I may try to fix this issue in the next days.

Hi ret2libc.By now you can package r2ghidra by copying 5 folders in Cutter source code into r2ghidra and generate building rules. 
Source code folders
![Screenshot at 2020-02-08 15-15-09](https://user-images.githubusercontent.com/29118926/74081838-d1d93400-4a85-11ea-9d70-05bdd8b669c3.png)
My compile flags (i am building for Parrot OS - debian base)
![Screenshot at 2020-02-08 15-16-15](https://user-images.githubusercontent.com/29118926/74081857-fdf4b500-4a85-11ea-99a6-ff2fd26af6bd.png)

**Comment by karliss** [comment]
Might be fixed during #2084
