### ISSUE TITLE
Set breakpoint F2 shortcut doesn't work

### ISSUE THREAD

**Issue by karliss** [radareorg/cutter#1924]
**Environment information**
* Operating System: Linux
* Cutter version: 59af77f
* File format: ELF

**Describe the bug**

**To Reproduce**

1. Start debuging
2. Right click a line and toggle breakpoint using context menu
3. Use arrows or j/k to confirm that disassembly window has keyboard focus
4. Try adding breakpoint using F2 - observe that it doesn't get added

**Expected behavior**

Shortcut for toggling breakpoint indicated in context menu works.

**Comment by karliss** [comment]
The same problem affects graph window.

**Comment by yossizap** [comment]
Can't reproduce. Works for me in graph and disassembly view, Ubuntu 18.04.

**Comment by ITAYC0HEN** [comment]
Same here. F2 was a problem a long ago but now I can't reproduce on Arch64

**Comment by karliss** [comment]
I will recheck this later this evening, maybe it requires opening certain set of widgets.

**Comment by karliss** [comment]
Everything is fine. I had pressed f-lock.
