### ISSUE TITLE
Crash when refreshing after debuging

### ISSUE THREAD

**Issue by karliss** [radareorg/cutter#1925]
**Environment information**
* Operating System: Linux
* Cutter version: 59af77f
* File format: ELF

**Describe the bug**

Doing "View/Refresh contents" after executable has finished running causes crash

**To Reproduce**

1. Start debuging `ls`
2. Click continue until process exits
3. Click "View/Refresh contents" and observe crash

**Expected behavior**

No crash.

**Screenshots**

**Additional context**

**Comment by karliss** [comment]
Refreshing while the executable is still running also causes crash.

**Comment by yossizap** [comment]
Apart from the solution I submitted to solve the crash, we should also add r_event to debug.c so we could know that debug actually ended and notify the user/automatically exit.
