### ISSUE TITLE
Cutter crash after build 59af77fb7272765b3d50e0af6067e036e4d4e93b

### ISSUE THREAD

**Issue by meowmeowxw** [radareorg/cutter#1927]
**Environment information**
* Operating System: Arch Linux
* Cutter version: 59af77fb7272765b3d50e0af6067e036e4d4e93b
* File format: ELF

I compiled cutter using the [instruction](https://cutter.re/docs/building.html) with cmake.

I tried to analyze [ret2win 64 bit binary](https://ropemporium.com/challenge/ret2win.html) but it crashes after I try to seek to a function.

error:

qt.qpa.xcb: QXcbConnection: XCB error: 8 (BadMatch), sequence: 4633, resource id: 83886280, major code: 130 (Unknown), minor code: 3

![cutter-crash](https://user-images.githubusercontent.com/43200867/70854533-0a5cf700-1eb5-11ea-836c-5cb56da60f3f.gif)

**Comment by meowmeowxw** [comment]
I tried to recompile cutter with the last build (using cmake) (64371bb07a250101c829ca590005194db3756449) and now it doesn't crash

**Comment by ITAYC0HEN** [comment]
Great! I am closing the issue then. Please let us know as soon as you find any other problem. :)
Thank you!
