### ISSUE TITLE
Should we merge Windows -> Debug with Debug menu?

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/cutter#1937]
Currently, we have two menus for debug. Should they be merged?

- Debug windows, under Windows -> Debug... 
![image](https://user-images.githubusercontent.com/20182642/70970752-e44b7880-20a7-11ea-9ea2-1ea7144da238.png)

- Debug operations, under Debug
![image](https://user-images.githubusercontent.com/20182642/70970781-f3cac180-20a7-11ea-8e16-ab18f29c6667.png)

On one hand, debug windows are related to the Windows menu since they decide which widgets are visible. On the other hand, there's a dedicated main menu for Debug. Intuitively, where will the user search for their desired widget?

**Comment by yossizap** [comment]
>Intuitively, where will the user search for their desired widget?

I am used to searching the windows menu for toggleable windows and the debug menu for debug actions that aren't shown in the toolbar. I would prefer having the same menu in both, if that's possible.

**Comment by ITAYC0HEN** [comment]
@karliss @thestr4ng3r @xarkes what do you think? :)

**Comment by thestr4ng3r** [comment]
I don't mind having window toggles in "Debug", but I do want to keep every window toggleable from "Windows".

**Comment by karliss** [comment]
No objections against having it in both assuming it is as simple as I think it is.

**Comment by xarkes** [comment]
I like the way it is currently. Debugging windows are under windows, debugging actions are under debug. It makes sense to me.

**Comment by ITAYC0HEN** [comment]
@xarkes Are you against having it in both places?

"Windows -> Debug -> ,,," as well as "Debug -> Windows -> ..."

**Comment by xarkes** [comment]
If it implies code duplication, yes I am against it.

**Comment by karliss** [comment]
It takes 3 lines that I already wrote no code duplication. Should I make PR?
