### ISSUE TITLE
Fail to patch with multiple instructions

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/cutter#1939]
**Describe the bug**

In Cutter this is impossible to patch with multiple instructions even though the preview shows the multiple instructions.

Here I am trying to patch an address with multiple instructions. This should override the following instructions as well (see `"wa nop;nop;nop"`). As you can see, the preview shows the values of multiple instructions

![image](https://user-images.githubusercontent.com/20182642/70979962-29c57100-20bb-11ea-9d98-d15571ccaedd.png)

But in the results, it probably truncates the ";" from the input and ignores everything after it

![image](https://user-images.githubusercontent.com/20182642/70979976-2f22bb80-20bb-11ea-8013-0d533a5e78b2.png)

**To Reproduce**

1. Open a binary in write-mode
2. Right click an address and choose Edit -> Instruction
3. Concatenate multiple instructions using `;`
4. See that everything after the first `;` is ignored

**Expected behavior**

All the instructions should be applied and override if needed

**Additional context**

Whoever implements this, please pay attention to prevent code injection using `;`

**Comment by nk521** [comment]
Removing `;` will work but I can't say anything about code injection. Can I just convert instructions to opcode first and then use `wx` ?

**Comment by ITAYC0HEN** [comment]
First, try to verify whether command injection is even possible there (usually I add `; ?E hello world` to test if something is printed to the console and means that command injected. If it is not a problem, then everything works :)
