### ISSUE TITLE
Prevent debug widgets from opening when not in debug mode

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/cutter#1941]
**Describe the bug**

Do to the new changes in Debug and the creation of new widgets, some Debug widgets such as processes and threads are opened when not in debug mode. 
This especially happening when using Cutter's version with debug for the first time due to changes in settings. 

All debug widgets should be disabled and prevented from showing when not in debug mode. 

**To Reproduce**

1. Revert to a version without debugging support
2. Open cutter, reset settings, move widgets around and close cutter
3. Build the newest version of cutter
4. Open a binary in Cutter and you might see that some debug widgets are shown. 

**Expected behavior**
All debug widgets should be disabled and prevented from showing when not in debug mode. 

**Screenshots**

**Additional context**

**Comment by karliss** [comment]
The new docks fall into this category.

https://github.com/radareorg/cutter/blob/78c6e651c825f6625037708299ec9a9aa48fbec4/src/core/MainWindow.cpp#L674-L675
