### ISSUE TITLE
New breakpoint deletes an existing one

### ISSUE THREAD

**Issue by c8kie** [radareorg/cutter#1952]
If you try to add a new breakpoint with the same address as one of the existing breakpoints, the old one would be deleted and replaced by the new one. I suggest that nothing should happen in that case, or\and a warning message should pop-up.

**Comment by karliss** [comment]
I just tried it using breakpoint widget and behaviour was even worse. Old one was deleted and new one wasn't added.

**Comment by karliss** [comment]
R2 `db 0xadde5` command behaves as c8kie suggested. So it's the question of using appropriate r2 command.

@c8kie Which method of adding breakpoint did you use?

**Comment by c8kie** [comment]
@karliss yep, my bad. It actually just deletes existing and do not add a new one.
