### ISSUE TITLE
Mac OS Preference dialog doesn't fit screen.

### ISSUE THREAD

**Issue by Maijin** [radareorg/cutter#1958]
**Environment information**
* Operating System: Mac OS 
* Cutter version: 1.10

**Describe the bug**

Mac OS Preference dialog is misplaced (OK button is hidden)

**To Reproduce**

Open preferences

**Expected behavior**

Preference Dialog properly positionned

**Screenshots**

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1408600/71306665-a02be100-23e3-11ea-9cef-e2d874a71ac0.png">

via  @Th4nat0s

**Comment by karliss** [comment]
I guess it's more of preferences window not fitting the screen problem than OK button placement.

**Comment by Th4nat0s** [comment]
I do confirm, the screen is too small, but it is the screen of my macbook air ...   the issue is that you can't reach the OK...  Is is possible to tighten space between line  to be usable on 1366x768

**Comment by Maijin** [comment]
Feel free to edit @karliss ;) - I'm adding the issues live.

**Comment by karliss** [comment]
Height is probably limited by Disassembly/Style page and metadata page is just spacing things evenly using available space.

**Comment by Th4nat0s** [comment]
If it's possible to put it in a scrolling frame like this, it's more than nice.

![image](https://user-images.githubusercontent.com/1728186/71307394-1f261700-23ee-11ea-841d-e5baff16bab5.png)

**Comment by Th4nat0s** [comment]
the resize do the job for finding the ok button.
![image](https://user-images.githubusercontent.com/1728186/71307421-657b7600-23ee-11ea-8109-9771a9cf7fa3.png)
