### ISSUE TITLE
Windows - Right click options aren't applied

### ISSUE THREAD

**Issue by Maijin** [radareorg/cutter#1960]
**Environment information**
* Operating System: Windows10 [Version 10.0.18362.535]
* Cutter version: 1.10
* File format: PE/DLL x64

**Describe the bug**

Right click options don't produce any results

**To Reproduce**

1. Right click Add comment or / set immediate base

**Expected behavior**

Right click options works

**Screenshots**

![image](https://user-images.githubusercontent.com/1408600/71306798-5cd27200-23e5-11ea-9cdd-66a49908b104.png)

![image](https://user-images.githubusercontent.com/1408600/71306799-5f34cc00-23e5-11ea-8ffd-6cc853e0fc15.png)

and

![image](https://user-images.githubusercontent.com/1408600/71306802-63f98000-23e5-11ea-8502-101a3cda44d6.png)

![image](https://user-images.githubusercontent.com/1408600/71306804-66f47080-23e5-11ea-8713-91e0d4cf0239.png)

![image](https://user-images.githubusercontent.com/1408600/71306811-7c699a80-23e5-11ea-86f3-b05e6e6d39ac.png)

via @Th4nat0s

**Comment by ITAYC0HEN** [comment]
Does the console widget (or the running terminal) says something?

**Comment by Th4nat0s** [comment]
Damn... reopened, cannot reproduce, ill try

**Comment by pelijah** [comment]
Can't reproduce

**Comment by ITAYC0HEN** [comment]
@Th4nat0s did you experience this issue again? I couldn't reproduce

**Comment by ITAYC0HEN** [comment]
Hey @Th4nat0s , I still can't reproduce it. I will close this issue for now, please let us know if it happen again - thank you! :)
