### ISSUE TITLE
The debugger don't like the spaces

### ISSUE THREAD

**Issue by Th4nat0s** [radareorg/cutter#1961]
**Environment information**
* Operating System: Win 10
* Cutter version: 1.10.0
* File format: PE 32

I got the following issue when trying to debug a exe with a space in the folder path 

![image](https://user-images.githubusercontent.com/1728186/71309216-a6cb5000-2405-11ea-8acd-bf21fefbe66e.png)

**To Reproduce**

1. open a file on your desktop having a space in your folder
2. Click on debug

**Comment by Th4nat0s** [comment]
Well even without spaces... an exe the root of the drive c: it give the same issue ( without the space naming issue )..

It's only a display issue. it's occurs when trying a debug on a pe DLL

**Comment by yossizap** [comment]
That would be appropriate since dlls can't be executed in Cutter atm

**Comment by ITAYC0HEN** [comment]
But it's totally planned :) We are working on implementing a loader for shared libraries, similarly to what OllyDbg had in the old days
