### ISSUE TITLE
Multi-thread Initial Analysis support?

### ISSUE THREAD

**Issue by pangqingyuan1991** [radareorg/cutter#1970]
Open large elf file (>1M) can take quite some time. I have observed that only one cpu is 100% during initial analysis. So I guess it is a single thread processing.
Is there any limitation that prevents multi-thread processing?

**Comment by ITAYC0HEN** [comment]
CC @thestr4ng3r

**Comment by thestr4ng3r** [comment]
Well, if multi-threading is done only for the sake of multi-threading, you won't gain anything. The kind of analysis that r2 does needs random access to many different kinds of data which would need to be synchronized and will most likely cause more synchronization overhead than potential speedup when trying to multi-thread it.

Our current goal is to make the analysis asynchronous in a coroutine-like way so you can already browse around the code while the analysis is running, as well as precisely identify and eliminate bottlenecks in the analysis, which eventually can often lead to much more speedup than multi-threading could even provide in its best case.

This does not mean we will never have any multi-threaded analysis, but it really only makes sense if the kind of algorithm has the right properties.

**Comment by pangqingyuan1991** [comment]
Got it
