### ISSUE TITLE
Cutter ignores font size on new sessions

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/cutter#1976]
**Environment Info**
**System :** Windows 7 Ultimate x64 SPI 
**Cutter version :** Cutter—v1.10. 0-x64 . Windows 
**Obtained From:** Downloaded From Release 

**Issue** 
Weired Font Issue Of Decompiler 

**Step To Reproduce .** 
1. Choose Any File To Analysis ( I used Default aaa)
2. After Analysis Complete Try To Change Font >:-
Edit > Preferences > Appearance > select font (I used Arial Font With Bold and Size was 14) 
Effect To Be Seen: All Font Become Larger In Disassembly and Decompiler 
3. Restart Cutter and Analyze Same File with Same Configuration and See The GUI 

**Expected Font Size** 
Disassembly: 14
Decompiler: 14 

**What We get .** 
Disassembly:  14
Decompiler: SMALLER THAN WE APPLIED LAST TIME  // ISSUE

**Comment by karliss** [comment]
Probably font propagation again. It would nice to figure out cleaner way of dealing with than making sure we reload fonts after widget gets added to parent or parent font is changed.

Only slightly related but we should probably use `QFontDatabase::systemFont(QFontDatabase::FixedFont)` as default fixed size font when Cutter settings are empty.
