### ISSUE TITLE
Building steps: location of build directory

### ISSUE THREAD

**Issue by eagleoflqj** [radareorg/cutter#2010]
I'm trying to make `r2pm install cutter` work on Linux, so I reference building steps on this website.
I notice in the "Building steps" section the build dir is in src dir, and in "Compiling on Linux / macOS" section the build dir is in root dir.
I don't know why they are different. My own opinion is that placing build dir in root dir is better. Having build dir in src dir is more like in-source build (although different) and confusing. After all the stuff in build dir are not source code.
However, if you decide to remain that way, I will modify my r2pm script accordingly, so please let me know your opinion.

**Comment by karliss** [comment]
Note that you are probably comparing build instructions for two different build systems.  Location of build folder doesn't matter. Both cmake and qmake allow specifiying it as can be seen in build instructions. As long as you test that it works choose whatever suits the rest of build procedure.

**Comment by xarkes** [comment]
Also note that there is a new version of r2pm that is being worked on. See https://github.com/radareorg/r2pm

**Comment by eagleoflqj** [comment]
Got it, thank you!
