### ISSUE TITLE
Fail to run on Ubuntu 20.04

### ISSUE THREAD

**Issue by eagleoflqj** [radareorg/cutter#2018]
**Environment information**
* Operating System:
Ubuntu 20.04 GNOME
* Cutter version:
80c21280391dd01a897513b6d2255020884c650e
* Obtained from:
  - [x] Built from source
  - [ ] Downloaded from release
  - [ ] Distribution repository
* File format:
executable

**Describe the bug**
When executing `./build/Cutter`, an error occurs: ./build/Cutter: error while loading shared libraries: libr_socket.so.4.2.0-git: cannot open shared object file: No such file or directory.

**To Reproduce**

Follow all building instructions.

**Expected behavior**

Successfully open cutter window.

**Screenshots**

**Additional context**

```
$ ldd build/Cutter
	linux-vdso.so.1 (0x00007ffe0b0e3000)
	libQt5Svg.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Svg.so.5 (0x00007fb05afbe000)
	libQt5Network.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Network.so.5 (0x00007fb05adfd000)
	libQt5Widgets.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 (0x00007fb05a764000)
	libQt5Gui.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5 (0x00007fb05a17e000)
	libQt5Core.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 (0x00007fb059c37000)
	libr_core.so.4.2.0-git => /mnt/wdb/github/cutter/src/build/Radare2-prefix/lib/libr_core.so.4.2.0-git (0x00007fb05997b000)
	libr_config.so.4.2.0-git => /mnt/wdb/github/cutter/src/build/Radare2-prefix/lib/libr_config.so.4.2.0-git (0x00007fb059970000)
	libr_cons.so.4.2.0-git => /mnt/wdb/github/cutter/src/build/Radare2-prefix/lib/libr_cons.so.4.2.0-git (0x00007fb059940000)
	libr_io.so.4.2.0-git => /mnt/wdb/github/cutter/src/build/Radare2-prefix/lib/libr_io.so.4.2.0-git (0x00007fb0598b7000)
	libr_util.so.4.2.0-git => /mnt/wdb/github/cutter/src/build/Radare2-prefix/lib/libr_util.so.4.2.0-git (0x00007fb0597a0000)
	libr_flag.so.4.2.0-git => /mnt/wdb/github/cutter/src/build/Radare2-prefix/lib/libr_flag.so.4.2.0-git (0x00007fb059794000)
	libr_asm.so.4.2.0-git => /mnt/wdb/github/cutter/src/build/Radare2-prefix/lib/libr_asm.so.4.2.0-git (0x00007fb058bc1000)
	libr_debug.so.4.2.0-git => /mnt/wdb/github/cutter/src/build/Radare2-prefix/lib/libr_debug.so.4.2.0-git (0x00007fb058b67000)
	libr_hash.so.4.2.0-git => /mnt/wdb/github/cutter/src/build/Radare2-prefix/lib/libr_hash.so.4.2.0-git (0x00007fb058b58000)
	libr_bin.so.4.2.0-git => /mnt/wdb/github/cutter/src/build/Radare2-prefix/lib/libr_bin.so.4.2.0-git (0x00007fb058998000)
	libr_anal.so.4.2.0-git => /mnt/wdb/github/cutter/src/build/Radare2-prefix/lib/libr_anal.so.4.2.0-git (0x00007fb058696000)
	libr_parse.so.4.2.0-git => /mnt/wdb/github/cutter/src/build/Radare2-prefix/lib/libr_parse.so.4.2.0-git (0x00007fb058627000)
	libr_bp.so.4.2.0-git => /mnt/wdb/github/cutter/src/build/Radare2-prefix/lib/libr_bp.so.4.2.0-git (0x00007fb05861f000)
	libr_egg.so.4.2.0-git => /mnt/wdb/github/cutter/src/build/Radare2-prefix/lib/libr_egg.so.4.2.0-git (0x00007fb058607000)
	libr_reg.so.4.2.0-git => /mnt/wdb/github/cutter/src/build/Radare2-prefix/lib/libr_reg.so.4.2.0-git (0x00007fb0585f9000)
	libr_search.so.4.2.0-git => /mnt/wdb/github/cutter/src/build/Radare2-prefix/lib/libr_search.so.4.2.0-git (0x00007fb0585f0000)
	libr_syscall.so.4.2.0-git => /mnt/wdb/github/cutter/src/build/Radare2-prefix/lib/libr_syscall.so.4.2.0-git (0x00007fb0585e7000)
	libr_fs.so.4.2.0-git => /mnt/wdb/github/cutter/src/build/Radare2-prefix/lib/libr_fs.so.4.2.0-git (0x00007fb0585a1000)
	libr_magic.so.4.2.0-git => /mnt/wdb/github/cutter/src/build/Radare2-prefix/lib/libr_magic.so.4.2.0-git (0x00007fb05858b000)
	libr_crypto.so.4.2.0-git => /mnt/wdb/github/cutter/src/build/Radare2-prefix/lib/libr_crypto.so.4.2.0-git (0x00007fb05855b000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fb05836d000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb05821e000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fb058204000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb058013000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fb057ff7000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb057fd2000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fb057fcc000)
	libGL.so.1 => /usr/lib/x86_64-linux-gnu/libGL.so.1 (0x00007fb057f38000)
	libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007fb057f00000)
	libharfbuzz.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007fb057e09000)
	libicui18n.so.63 => /usr/lib/x86_64-linux-gnu/libicui18n.so.63 (0x00007fb057b2e000)
	libicuuc.so.63 => /usr/lib/x86_64-linux-gnu/libicuuc.so.63 (0x00007fb05795c000)
	libpcre2-16.so.0 => /usr/lib/x86_64-linux-gnu/libpcre2-16.so.0 (0x00007fb0578e1000)
	libdouble-conversion.so.3 => /usr/lib/x86_64-linux-gnu/libdouble-conversion.so.3 (0x00007fb0578cb000)
	libglib-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007fb0577a3000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb05b5d4000)
	libr_socket.so.4.2.0-git => not found
	libr_lang.so.4.2.0-git => not found
	libr_socket.so.4.2.0-git => not found
	libr_socket.so.4.2.0-git => not found
	libGLX.so.0 => /usr/lib/x86_64-linux-gnu/libGLX.so.0 (0x00007fb05776d000)
	libGLdispatch.so.0 => /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0 (0x00007fb0576b0000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007fb0575f3000)
	libgraphite2.so.3 => /usr/lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007fb0575c6000)
	libicudata.so.63 => /usr/lib/x86_64-linux-gnu/libicudata.so.63 (0x00007fb055bd5000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fb055b61000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007fb055a23000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fb0559f8000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007fb0559f2000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fb0559ea000)
	libbsd.so.0 => /usr/lib/x86_64-linux-gnu/libbsd.so.0 (0x00007fb0559d0000)
```
I see libr_socket.so.4.2.0-git and libr_lang.so.4.2.0-git pointing to nothing, however there exist those 2 libs in build/Radare2-prefix/lib. So I excute `../radare2/env.sh build/Radare2-prefix`, or simply `export LD_LIBRARY_PATH=build/Radare2-prefix/lib`, then Cutter can be successfully opened.

**Comment by karliss** [comment]
This is a known issue caused by combination of the way r2 build scripts works and default linker flags on latest Ubuntu versions. See the second part under troubleshooting section https://cutter.re/docs/building.html#troubleshooting .

**Comment by ITAYC0HEN** [comment]
@eagleoflqj were you able to solve the issue?

**Comment by eagleoflqj** [comment]
I'm quite new to cmake (and cutter, too), otherwise I'd open a pr ASAP.

**Comment by mr-m0nst3r** [comment]
@eagleoflqj 
Hi mate, I'm running the latest ubuntu 1910, but can't build from source.

Sometimes it's shiboken version not met, require 5.12, but I don't know where to install 5.12. apt only support 5.11, and pip.

How did you managed to build it?

Would you like to write your history here?

**Comment by eagleoflqj** [comment]
@mr-m0nst3r 
I used a fresh ubuntu 1910 VM, apt update and upgrade, then exactly followed the instruction. I don't have shiboken installed at all.

**Comment by hexagr** [comment]
I've been looking into this and have been able to successfully build Cutter on Ubuntu 20.04 by adding a few additional packages in apt: `sudo apt install build-essential make meson liibzip-dev zlib1g-dev qt5-default libqt5svg5-dev qttools5-dev qttools5-dev qttools5-dev-tools libgvc6 graphviz-dev libkf5syntaxhighlighting-dev python3-setuptools liblz4-dev libcapstone-dev openssl xxhash libuv1-dev` 

Then as radare2/cutter developers have documented, cd into the cutter directory and: `cmake -S src -B build -DCUTTER_USE_BUNDLED_RADARE2="ON" -DCMAKE_EXE_LINKER_FLAGS="-Wl,--disable-new-dtags"`, and finally, `cmake --build build`

Then you can run cutter with: `./build/Cutter`

**Comment by ITAYC0HEN** [comment]
Thanks for the detailed answer @hexagr ! :+1:
We highly appreciate it, and it confirms our initial assumptions.

If so, it seems like our docs are covered :) If you guys feel that there is anything we can add, we'd love to have your PR and add it to the docs.

Thank you very much

**Comment by flobotics** [comment]
hi,
the packages are missing in the docs, https://cutter.re/docs/building.html, in the one-liner-statement. Thats what all are using, adding this would delete some pain i think

sudo apt install build-essential cmake meson libzip-dev zlib1g-dev qt5-default libqt5svg5-dev qttools5-dev qttools5-dev qttools5-dev-tools libmagic-dev libgvc6 libgraphviz-dev libkf5syntaxhighlighting-dev python3-setuptools liblz4-dev libcapstone-dev libssl-dev libxxhash-dev libuv1-dev

**Comment by jubnzv** [comment]
Got a similar problem after building Cutter on Debian 11.

The `libr_socket` library already was built, so I just specified the path to it: `LD_LIBRARY_PATH=$(realpath build/Radare2-prefix/lib) build/Cutter`.
