### ISSUE TITLE
Increase Graph Maximum Line Length  (more than 99 characters)

### ISSUE THREAD

**Issue by lillypad** [radareorg/cutter#2025]
**Is your feature request related to a problem? Please describe.**

We used to be able to set the maximum line length to a desired size which could be greater than 99 however in the most recent version this does not function as expected. We can only set a maximum of 99 and the GUI does not allow for anymore.

The solution would be to allow a larger line length the user specifies, I'm not sure of a threshold however I'm finding a lot of the time 99 to be too short.

Being able to set this number high is what made things easier than using Ghidra as keeping track of long API calls and strings was easier.

![image](https://user-images.githubusercontent.com/9785864/72920851-89e5ad80-3d20-11ea-975c-fd240b1c58ec.png)

**Comment by ITAYC0HEN** [comment]
Thank you for letting us know!
This was probably a regression that introduced from Qt, since their default maximum-size is 99.
Fix will be sent very soon :)
