### ISSUE TITLE
AppImage doesn't embed proper version information

### ISSUE THREAD

**Issue by TheAssassin** [radareorg/cutter#2037]
The AppImage ships a git hash as "version number". Git hashes however don't make for very good version information; they're only really useful for machines, but I as a human can at most tell apart two versions but not tell which one is newer and, even worse, not tell which one correlates to the `v1.10` or `v1.10-BETA` AppImages I downloaded.

![Bildschirmfoto_2020-01-28_13-43-41](https://user-images.githubusercontent.com/4503202/73265004-54cfd400-41d4-11ea-842a-de7798adf701.png)

Please `export VERSION=v1.10` in your build system. You can also let Git generate that information, e.g., by calling `export VERSION=$(git describe --tags)`. That way, a proper version number is automatically embedded by appimagetool, and integration tools like AppImageLauncher can pick that up.

**Comment by karliss** [comment]
This refers to version X-AppImage-Version key inside .desktop file. All other places I looked at showed "1.10.0" as version.

**Comment by TheAssassin** [comment]
Exactly. This key in the desktop file is set automatically by appimagetool to the content of `$VERSION`.
