### ISSUE TITLE
Cmake failed to detect version number of shiboken2

### ISSUE THREAD

**Issue by dmknght** [radareorg/cutter#2046]
**Environment information**
* Operating System: Parrot OS 4.7
* Cutter version: 1.10.1 (pull from git 02022020)
* Obtained from:
  - [x] Built from source

* File format:

**Describe the bug**

Cmake failed to detect valid version of shiboken2 to compile the project. 
```
CMake Error at /usr/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Shiboken2 (missing: SHIBOKEN_LIBRARY SHIBOKEN_INCLUDE_DIR
  SHIBOKEN_BINARY) (found suitable version "5.13.2", minimum required is
  "5.12")
```

**To Reproduce**

1. clone cutter
2. compile with
```
cd cutter/src
mkdir build
cmake -B build -DPYTHON_CONFIG_SUFFIX=".cpython-38
m-x86_64-linux-gnu" -DCUTTER_ENABLE_PYTHON=on -DCUTTER_ENABLE_PYTHON_BINDINGS=on
cmake --build build
```

**Expected behavior**

Cmake should  accept version > 5.12

**Screenshots**

![Screenshot at 2020-02-02 15-14-53](https://user-images.githubusercontent.com/29118926/73605267-c80b8880-45ce-11ea-99d0-f6abb5fb00ec.png)

**Additional context**

**Comment by dmknght** [comment]
Turned out it was incompatible python version. After changing to python3.7, i'm having this error
```
CMake Error in CMakeLists.txt:
  Imported target "PySide2::pyside2" includes non-existent path

    "/usr/lib/include/PySide2"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

```

**Comment by ghodgeon** [comment]
I had this issue

My way to get past this was matching builds of qmake and shiboken2

I'm on osx 10.15.2. I tried to compile Cutter with Qt 5.14.1 and needed to compile PySide2 on my system first. Then Cutter would build with `python3 setup.py install --qmake=/Users/USER/Qt/5.14.1/clang_64/bin/qmake`

**Comment by karliss** [comment]
Full log from the last problem.
https://pastebin.com/QPm6bEQ2

**Comment by karliss** [comment]
Debian testing has broken pyside2-dev package https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=949846 . This is not a Cutter bug.
