### ISSUE TITLE
Cutter 1.10.1 crashes on theme edition

### ISSUE THREAD

**Issue by sagittarius-a** [radareorg/cutter#2048]
**Environment information**
* Operating System: Windows 10
* Cutter version: 1.10.1
* Obtained from:
  - [ ] Built from source
  - [x] Downloaded from release
  - [ ] Distribution repository
* File format: None

**Describe the bug**

Cutter 1.10.1 crashes when editing a theme. See crash dump attached.
[Cutter_crash_dump_03.02.20_23.33.51.dmp.zip](https://github.com/radareorg/cutter/files/4150572/Cutter_crash_dump_03.02.20_23.33.51.dmp.zip)

**To Reproduce**

0. Open Cutter (no file required)
1. Go to Edit->Preferences
2. Click on Appearance
3. Select any theme
4. Create a  copy of the theme
5. Edit it

**Expected behavior**

Theme edition menu should appear. Works on 1.10.0 from release,

**Comment by ITAYC0HEN** [comment]
Reproduced! Thank you very much for the report. Highly important to us.

**Comment by ITAYC0HEN** [comment]
Crashes on `MainWindow::getContextMenuExtensions`
