### ISSUE TITLE
Document the support of .cutterrc initialization file

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/cutter#2063]
**Is your feature request related to a problem? Please describe.**

We currently have support for an initialization file under the name `.cutterrc`. Users can use this file to execute radare2 commands on the start of every session.

https://github.com/radareorg/cutter/blob/dd7e01be3a4d21d4e788ec534f6ffd125372bdb4/src/core/Cutter.cpp#L228-L242

**Describe the solution you'd like**

Add a section dedicated to `.cutterrc` in the documentation.

**Comment by NirmalManoj** [comment]
I will do this after finishing issue #1837 (Add text editor for .cutterrc)
