### ISSUE TITLE
Dcoument how to update the radare2 submodule

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/cutter#2066]
**Is your feature request related to a problem? Please describe.**

From now and then, people are struggling with updating the radare2 submodule. 

**Describe the solution you'd like**
I suggest adding this to our dev documentation :)

**Comment by dhaval0894** [comment]
Hi @ITAYC0HEN, I would like to work on this issue. I just had one question. To update the radare2 submodule, would it be alright if we use:
`git submodule foreach git pull origin master`
which would also update the other submodule(**translations**) in the repo or are there any other set of commands that you would like to suggest?

**Comment by ITAYC0HEN** [comment]
Great! Since it is documentation, you can demonstrate several ways to do so.
You can show how to update ALL submodules, add them and commit the changes. And in addition, you can demonstrate how to specifically update the radare2 submodule which is the more common task.

**Comment by dhaval0894** [comment]
Thanks @ITAYC0HEN for your suggestions. I have raised the PR for this. Please review it whenever you get a chance.
