### ISSUE TITLE
The program freezes too much

### ISSUE THREAD

**Issue by maskelihileci** [radareorg/cutter#2073]
Windows Version : Windows 10 1603
Cpu : İ7 6700k
Gpu : Gtx 1070
Cutter Version : 1.10.1

The Program is very good, but the performance is very bad when it freezes the loading screen would be better if we saw

**Comment by ITAYC0HEN** [comment]
Hi :) Thank you for the feedback. 
Please fill our issue template so we can fully understand the detailed feedback. As of now, this issues doesn't help us sol e the problems :)
