### ISSUE TITLE
Helo my name luthf100-web 

### ISSUE THREAD

**Issue by luthf100-web** [radareorg/cutter#2085]
**Environment information**
* Operating System:
* Cutter version:
* Obtained from:
  - [x] Built from source
  - [ ] Downloaded from release
  - [x] Distribution repository
* File format:

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by luthf100-web** [comment]
Thank yoh

**Comment by luthf100-web** [comment]
Terima kasih

**Comment by ITAYC0HEN** [comment]
Closing, spam.
