### ISSUE TITLE
qmake: bindings_target race condition leads to compile error (cutterbindings_python.h)

### ISSUE THREAD

**Issue by anthraxx** [radareorg/cutter#2103]
**Environment information**
* Operating System: Arch Linux
* Cutter version: 1.10.2
* Obtained from:
  - [x] Built from source

**Describe the bug**

QMake build system doesn't seem to properly specify target dependencies. When i build on a very beefy machine like a ryzen with 64 concurrency, the compilation aborts (in like ~3 out of 4 cases) with:
```
...
g++ -c -pipe -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DCUTTER_ENABLE_PYTHON -DCUTTER_ENABLE_PYTHON_BINDINGS -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I../src -I. -I../src -I../src/core -I../src/widgets -I../src/dialogs -I../src/common -I../src/plugins -I../src/menus -I/build/radare2-cutter/src/radare2-cutter/build/bindings/CutterBindings -isystem /usr/include/PySide2 -isystem /usr/include/PySide2/QtCore -isystem /usr/include/PySide2/QtWidgets -isystem /usr/include/PySide2/QtGui -isystem /usr/include/libr -isystem /usr/include/python3.8 -isystem /usr/include/shiboken2 -isystem /usr/include/qt -isystem /usr/include/qt/QtSvg -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtNetwork -isystem /usr/include/qt/QtCore -I. -I. -I/usr/lib/qt/mkspecs/linux-g++ -o BasicBlockHighlighter.o ../src/common/BasicBlockHighlighter.cpp
../src/plugins/PluginManager.cpp:6:10: fatal error: cutterbindings_python.h: No such file or directory
    6 | #include <cutterbindings_python.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:5239: PluginManager.o] Error 1
make: *** Waiting for unfinished jobs....
```

I can work around this issue by either limiting the parallel jobs (hence making it more unlikely to out-race the binding generator) or by simply invoking `make bindings_target` myself before the full `make` call.

**To Reproduce**

```
  qmake ../src/Cutter.pro \
    CUTTER_ENABLE_PYTHON=true \
    CUTTER_ENABLE_PYTHON_BINDINGS=true \
    CUTTER_USE_BUNDLED_RADARE2=false
  make
```

**Expected behavior**

Can compile using qmake on a beefy machine without race conditions.

**Comment by karliss** [comment]
Was able to repeat using `make -j16` and ccache.

**Comment by karliss** [comment]
@anthraxx I see that you are one of the Arch Linux package maintainers for Cutter. Note that we are planning of switching from qmake to CMake. There are already few features like ksyntaxhighligthing and graphviz which are only implemented in the cmake build. Previously it didn't have the install target but it was recently added. If it does something badly making you difficult to package let me know.

**Comment by anthraxx** [comment]
I will be testing this patch during the weekend and also take a dive into replacing qmake with cmake and give feedback on that as well. Thanks for the quick handling and the headsup related to the Arch package.

**Comment by anthraxx** [comment]
cmake build seems fine, so will switch the Arch package to it with the next update.
The PR also looks good :)
