### ISSUE TITLE
Numpad input on UI input fields not working

### ISSUE THREAD

**Issue by arnaugamez** [radareorg/cutter#2118]
**Environment information**
* Operating System: Ubuntu 19.10
* Cutter version: 1.10.3 Pre Release
* Obtained from:
  - [X] Downloaded from release

**Describe the bug**

Numpad input does not work on any input field of the UI

**To Reproduce**

1. Go to any input field of the UI, for example "Quick filter" of functions windows, r2 console input. Or open dialogue for putting a comment or renaming a local var. Any input field I tried has the problem.
2. Try to input numbers (or floating point) from numpad and observe they are not being written.

**Expected behavior**

When Num lock is enabled on a keyboard with numpad, input fields of the UI should be able to get input from it.

**Comment by karliss** [comment]
Seems to be specific to Appimage builds, doesn't happen when I build locally using my system's Qt.

My initial guess that the Qt version or it's build on Ci servers is bad but the Appimage from qt 5.14 branch is also bad.

It might be useful to do a build locally using qt from cutter-deps.

**Comment by ITAYC0HEN** [comment]
@karliss, Is this a known issue in Qt? I can't reproduce on non-appimage builds so I can verify that what you're describing is true.
Also. is there a way we can force Qt to handle this?

**Comment by karliss** [comment]
Was able to repeat using local build and Qt from cutter-deps without appimage.

Next test building cutter-deps locally using the same scripts as in CI. That should tell if the problem is in build scripts or the CI environment where cutter-deps are compiled.

**Comment by karliss** [comment]
Using locally built QT using the same scripts  (but qt 5.14.2) worked. That leaves 3 theories:
* something in the system headers on CI machines - I really hope that this isn't the case
* difference in qt build configuration variables that were chosen automatically
* something that got fixed between 5.14.1 and 5.14.2 - seems unlikely

For the second theory I will compare the build config print by Qt in my local build and CI builds.  I need to update cutter-deps from qt 5.14.1 to 5.14.2 anyway.

**Comment by karliss** [comment]
```diff
--- <unnamed>
+++ <unnamed>
@@ -1,12 +1,12 @@
-Compiler: gcc 9.3.0
-Configuration: use_gold_linker sse2 aesni sse3 ssse3 sse4_1 sse4_2 avx avx2 avx512f avx512bw avx512cd avx512dq avx512er avx512ifma avx512pf avx512vbmi avx512vl ccache compile_examples enable_new_dtags f16c largefile precompile_header rdrnd shani x86SimdAlways shared shared rpath release c++11 c++14 c++1z concurrent dbus reduce_exports reduce_relocations stl
+Compiler: gcc 5.4.0
+Configuration: use_gold_linker sse2 aesni sse3 ssse3 sse4_1 sse4_2 avx avx2 avx512f avx512bw avx512cd avx512dq avx512er avx512ifma avx512pf avx512vbmi avx512vl ccache compile_examples enable_new_dtags f16c largefile precompile_header rdrnd shani x86SimdAlways shared shared rpath release c++11 c++14 concurrent dbus reduce_exports reduce_relocations stl
@@ -32,12 +32,12 @@
   Qt Xml ................................. yes
 Support enabled for:
   Using pkg-config ....................... yes
-  udev ................................... yes
+  udev ................................... no
   Using system zlib ...................... yes
-  Zstandard support ...................... yes
+  Zstandard support ...................... no
@@ -95,10 +95,10 @@
   Session Management ..................... yes
 Features used by QPA backends:
   evdev .................................. yes
-  libinput ............................... yes
+  libinput ............................... no
   INTEGRITY HID .......................... no
-  mtdev .................................. yes
-  tslib .................................. yes
+  mtdev .................................. no
+  tslib .................................. no
   xkbcommon .............................. yes
   X11 specific:
     XLib ................................. yes
@@ -113,7 +113,7 @@
     EGLFS i.Mx6 Wayland .................. no
     EGLFS RCAR ........................... no
     EGLFS EGLDevice ...................... yes
-    EGLFS GBM ............................ yes
+    EGLFS GBM ............................ no
     EGLFS VSP2 ........................... no
     EGLFS Mali ........................... no
     EGLFS Raspberry Pi ................... no
@@ -121,8 +121,8 @@
   LinuxFB ................................ yes
   VNC .................................... yes
   XCB:
-    Using system-provided XCB libraries .. yes
-    XCB XKB .............................. yes
+    Using system-provided XCB libraries .. no
+    XCB XKB .............................. no
     XCB XInput ........................... yes
     Native painting (experimental) ....... no
     GL integrations:
```

There were more differences than ones listed above, but those were unlikely to affect keyboard input. Next step is trying to repeat the problem using local qt build by changing the features that differ. And if that works doing the opposite in CI build.

**Comment by karliss** [comment]
As I expected using cutter-deps and qt wayland backend numpad works. Most likely the problem is in "XCB XKB" or "Using system-provided XCB libraries".

**Comment by karliss** [comment]
I was able to make numpad not work by setting "-no-xkb" for local qt build. Will try to enable it in cutter-deps.

**Comment by karliss** [comment]
Qt 5.14 test release has been rebuilt with xkb. Numpad seems to be working. If anyone wants to confirm - it is available [here](https://github.com/radareorg/cutter/releases/tag/deploy-test-qt514),

**Comment by arnaugamez** [comment]
> Qt 5.14 test release has been rebuilt with xkb. Numpad seems to be working. If anyone wants to confirm - it is available [here](https://github.com/radareorg/cutter/releases/tag/deploy-test-qt514),

Working fine for me with same config as when described issue.

Thanks for taking a look at it.
