### ISSUE TITLE
Cannot debug an elf 64bit file with 1.10.2 version

### ISSUE THREAD

**Issue by int3rsys** [radareorg/cutter#2120]
**Environment information**
* Operating System: Ubuntu 18.04.1, 64bit
* Cutter version: 1.10.2
* Obtained from:
  - [] Built from source
  - [x] Downloaded from release
  - [ ] Distribution repository
* File format: ELF 64bit

1. After inserting a breakpoint, I click on the debug button. 
2. I don't add any command line args
3. The program stops in a different address 
4. I push<F5> and it stops at a different address, but not the breakpoint yet
5. I push <F5> again and the program exits with "Debugged process exited (34827)"

1. open x5 binary 
2. put a breakpoint, doesn't matter where
3. start debugging
4. see error

**Expected behavior**

The program will exit without stopping in the breakpoint.

**Additional context**
the file:
[x5.zip](https://github.com/radareorg/cutter/files/4411239/x5.zip)

**Comment by karliss** [comment]
Please read the release notes. https://github.com/radareorg/cutter/releases/tag/v1.10.2
