### ISSUE TITLE
Tooltips in light theme are unreadable

### ISSUE THREAD

**Issue by karliss** [radareorg/cutter#2124]
**Environment information**
* Operating System: Arch Linux, Qt 5.14.1 Gnome desktop
* Cutter version:  4f649808344b5e6ffa70d4280997147a5ae880bb  ~ 1.10.2-1.10.3
* Obtained from: Built from source
* File format: Not applicable

**Describe the bug**

Font and background settings in light theme make tooltips almost unreadable.

**To Reproduce**

1. Open a file in Cutter.
2. Set the interface theme to "Light".
3. Hover over "Execute command" button in console widget or navbar to trigger the tooltip

**Expected behavior**

Tooltip background has contrasting color with the text color.

**Screenshots**

![tooltip](https://user-images.githubusercontent.com/7101031/78245818-cc7df000-74f0-11ea-847d-c3f2a4cce7aa.png)

**Additional context**

**Comment by ITAYC0HEN** [comment]
Looks good on my Arch with dark themed OS:
![image](https://user-images.githubusercontent.com/20182642/78249234-b115e380-74f6-11ea-8953-526eed1f051d.png)

**Comment by ITAYC0HEN** [comment]
So we can force background color for tooltips in light theme maybe...

**Comment by karliss** [comment]
Yes, it probably doesn't have it specified and uses the value from system theme which has varying results.
