### ISSUE TITLE
Debug stepping does not refreshing the disassembly

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/cutter#2163]
**Environment information**
* Operating System:
* Cutter version:
* Obtained from:
  - [x] Built from source: commit 8957e5eb64eccae1ee4dfa55cab0f217c7d0c667
  - [ ] Downloaded from release
  - [ ] Distribution repository
* File format:

**Describe the bug**
A regression in the debug cause the disassembly not to refresh, unltil a refresh is triggered (e.g clicking on the widget == seeking).

The gif shows the faulty behavior:
![cutter_bug_seek](https://user-images.githubusercontent.com/20182642/79688602-f4db4d80-8257-11ea-91e1-80ff7c156f37.gif)

**To Reproduce**

1. Open a binary in Cutter
2. start debug\emulation mode
3. Step using keyboard or buttons
4. See that the IP highlight isn't changed
5. Click on the disas and see that refresh was triggered

**Expected behavior**

IP highlight should be shown for every step

**Comment by karliss** [comment]
Caused by `cmd` refactoring. `CutterCore::seek(QString)` uses `cmdRaw`  which doesn't check if seek changed.

**Comment by karliss** [comment]
I can't reproduce this. Step gets called as `asyncCmd("ds")` which has the seek change check.

**Comment by karliss** [comment]
By the way are you missing step out button?

**Comment by ITAYC0HEN** [comment]
weird, tried to pull from master again and everything is fixed. Alright then :) Closing

**Comment by karliss** [comment]
Can be reproduced in emulation mode using appimage build.
