### ISSUE TITLE
Cann't set breakpoint in 1.10.2

### ISSUE THREAD

**Issue by datnt53** [radareorg/cutter#2167]
**Environment information**
* Operating System: Linux kali 5.2.0-kali2-amd64
* Cutter version: 1.10.2
* Obtained from:
  - [ ] Built from source
  - [x] Downloaded from release
  - [ ] Distribution repository
* File format: Cutter-v1.10.2-x64.Linux.AppImage

**Describe the bug**

I tried to reverse ELF ARM aarch64 but cannot set breakpoint.
`base addr should not be larger than the breakpoint address.`
I don't get this error in v1.10.1.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ITAYC0HEN** [comment]
Hey, thanks for opening the issue :)
Before we're looking at it, would you mind trying with 1.10.3-pre? 
https://github.com/radareorg/cutter/releases/tag/v1.10.3-pre

**Comment by datnt53** [comment]
OK, this error is resolved. Thanks!

**Comment by ITAYC0HEN** [comment]
Sure! Thank you for reporting :))
