### ISSUE TITLE
Unexpected color theme switching

### ISSUE THREAD

**Issue by karliss** [radareorg/cutter#2174]
**Environment information**
* Operating System: ArchLinux (also observed on macOS)
* Cutter version: 1.10.3-pre2  a3661fa2595004bf255726a02a99e5141415bc9b
* Obtained from:
  - [x] Built from source
* File format: N/A

**Describe the bug**

When lightness/darkness of native theme doesn't match disassembly color theme and settings get opened color theme gets switched.

**To Reproduce**

1. Make system(not Cutter) theme light. Can be done using qt5ct on Linux or Light/Dark switch on macOS. 
2. Open Cutter, select native theme, make sure disassembly color theme is light.
3. Close Cutter
4. Switch system theme to dark
5. Open Cutter observe that disassembly widget is using light color theme
6. Open settings, observe that color theme switches to dark one

**Expected behavior**

Changes in native theme lightness is detected when opening Cutter.

Different approach would be not doing automatic color theme change at all.

**Screenshots**
**Additional context**

**Comment by ITAYC0HEN** [comment]
This happen to me when re-opening after reset settings, without changing OS theme mode (kept dark the entire time)

**Comment by karliss** [comment]
I am not surprised. Explicitly selecting seemed like a more reliable way ensuring that light color theme is selected.
