### ISSUE TITLE
Navigation bar is all green

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/cutter#2195]
**Environment information**
* Operating System: Any
* Cutter version: 1.10.3
* Obtained from:
  - [x] Downloaded from release
* File format: Any

**Describe the bug**

The quick navigation map\bar looks all green, instead of showing sections, analyzed code, and more - as it used to.

![image](https://user-images.githubusercontent.com/20182642/81672088-51461d00-9452-11ea-9ea9-538025eec7dc.png)

**To Reproduce**

Open any binary in Cutter and look at the navigation bar

**Expected behavior**

It should show the different sections, the code, the data, the library functions, and more, as it used to do. This can be seen in these screenshots.

![image](https://user-images.githubusercontent.com/20182642/81672234-85b9d900-9452-11ea-8720-cab2e92ae80c.png)

![image](https://user-images.githubusercontent.com/20182642/81672225-82265200-9452-11ea-9fc1-36e647788255.png)

![image](https://user-images.githubusercontent.com/20182642/81672243-894d6000-9452-11ea-8819-df9f6db50bf8.png)

**Comment by karliss** [comment]
Just noticed that content of bar depends on "Search in" value in search widget.
