### ISSUE TITLE
missing dependency on website (https://cutter.re/docs/building.html)

### ISSUE THREAD

**Issue by luonii** [radareorg/cutter#2200]
Debian-based Linux: libkf5syntaxhighlighting-dev pkg-config libgraphviz-dev python3-setuptools

**Comment by karliss** [comment]
Not sure about pkg-config and python3-setuptools, but libkf5syntaxhighlighting libgraphviz are optional dependencies.

**Comment by luonii** [comment]
if only one of its packages is missing, Cutter does not build

**Comment by karliss** [comment]
pkg-config is probably always required but it should not fail without libgraphviz and libkf5syntaxhighlighting unless you have manually forced use of the specific features. I will retest this.

**Comment by luonii** [comment]
test for yourself (preferably with bootstrap to check in new environment)
I have not checked everything, I just warn that your doc is incomplete and needs to be revised

**Comment by luonii** [comment]
pkg-config and python3-setuptools are still not on https://cutter.re/docs/building.html

**Comment by karliss** [comment]
Just tried to do a build with clean, minimal Ubuntu 18.04 install and packages listed in Debian-based Linux.
libkf5syntaxhighlighting-dev pkg-config libgraphviz-dev python3-setuptools were not strictly required and I was able to compile Cutter without them using cmake building steps directly bellow requirements. CMake prints the messages that 

R2 required meson >= 0.50.1. Which comes with Ubuntu >= 19.10. Suitable meson version can be installed using pip. Installation of pip also installed a bunch of python dev stuff and  python3-setuptools but after meson was installed for the testing purpose I removed them.

My current plan for changes is:
* create list of optional dependencies
* instructions related to meson
* add the second command for distro specific install commands which includes optional dependencies.
* pkg config should probably be included in the primary dependency list even though it isn't strictly required. R2 meson uses it for detecting some extra libraries which serve more functional purpose than syntax highlighter and graphviz in Cutter.

**Comment by luonii** [comment]
I have not tested on Ubuntu so what you say is possible, but is need for Debian

**Comment by karliss** [comment]
@luonii What debian version are you using? What build command are you using and what errors (please include full output log) do you see?

**Comment by karliss** [comment]
Repeated the test using Debian 9 and had the same observations.

**Comment by luonii** [comment]
OS: Debian GNU/Linux bullseye x86_64
Kernel: 5.6.0-2-amd64
Build command:  -DCUTTER_USE_BUNDLED_RADARE2=ON


python3-setuptools --- BUILD NO / RUN NO:
Program python3 found: YES (/usr/bin/python3)
../../../../repositories/radare2/meson.build:3:0: ERROR: <ExternalProgram 'python3' -> ['/usr/bin/python3']> is not a valid python or it is missing setuptools


pkg-config --- BUILD YES / RUN YES:
but "Found Pkg-config: NO"


libgraphviz-dev --- BUILD YES / RUN NO:
/development/bin/Cutter: error while loading shared libraries: libgvc.so.6: cannot open shared object file: No such file or directory


libkf5syntaxhighlighting-dev --- BUILD YES / RUN NO:
error while loading shared libraries: libKF5SyntaxHighlighting.so.5: cannot open shared object file: No such file or directory

**Comment by luonii** [comment]
OS: Debian GNU/Linux bullseye x86_64
Kernel: 5.6.0-2-amd64
Build command:  -DCUTTER_USE_BUNDLED_RADARE2=ON


python3-setuptools --- BUILD NO / RUN NO:
Program python3 found: YES (/usr/bin/python3)
../../../../repositories/radare2/meson.build:3:0: ERROR: <ExternalProgram 'python3' -> ['/usr/bin/python3']> is not a valid python or it is missing setuptools


pkg-config --- BUILD YES / RUN YES:
but "Found Pkg-config: NO"


libgraphviz-dev --- BUILD YES / RUN NO:
error while loading shared libraries: libgvc.so.6: cannot open shared object file: No such file or directory


libkf5syntaxhighlighting-dev --- BUILD YES / RUN NO:
error while loading shared libraries: libKF5SyntaxHighlighting.so.5: cannot open shared object file: No such file or directory

**Comment by karliss** [comment]
I assume that by "BUILD YES/RUN NO" you mean that you were able to compile but not run without the corresponding system component.

1. python3-setuptools  - seems plausible. I wonder why I didn't hit that during my test. What meson version did you use and how did you install it?

2. pkgconfig -  So you were able to confirm my results about pkgconfig not being strictly required. Showing a message that optional component was not found in case of it not being present seems reasonable to me.

3, 4 I can't imagine how it's possible to compile and link against those libraries without them being present and getting the error only when executing final result. If they are not present Cutter make files should have detected it and automatically disabled the corresponding feature. If it didn't catch it there should have been a linker error  due to undefined symbols. Are you didn't do the build with graphviz installed and then remove it before running? Maybe by accidentally reusing the old build.  Please send the full build log where you were able to build Cutter without grpahviz in a way that requires it at runtime.

**Comment by luonii** [comment]
# meson --version
0.49.2

no juste clasique cmake why -DCUTTER_USE_BUNDLED_RADARE2 = ON
after apt remove grpahviz and kf5syntaxhighlighting && apt autoremove

**Comment by karliss** [comment]
I'll ask you the third time, please provide full log with commands you run and their outputs.  It has hard for me to help you if you don't provide the information you are asked.

**Comment by luonii** [comment]
I'm just informing you, I solved the problem on my side and just wanted to tell you what's missing. all the other projects correct what I tell them, I have no time to waste excuse me

for help you:
minimal runtime required for debian: libqt5svg5 libkf5syntaxhighlighting5 libgvc6 libuv1
minimal build required for debian: juste add python3-setuptools on your building.html
