### ISSUE TITLE
Add a command line option to open a file in write-mode

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/cutter#2202]
**Is your feature request related to a problem? Please describe.**
Currently, if someone wants to open a file in write mode they have to go through the inital options dialog, or manually enable it via the interface. 

**Describe the solution you'd like**
I would like to suggest a `-w` command line flag to enable write mode. This will allow users to open Cutter like this:
```
$ Cutter -w -A 0 /tmp/test.txt 
```

**Comment by tobigrimm** [comment]
Oh, great idea!
I would like to give this a try, currently looking into the InitialOptions handling to understand how to hand the writemode flag over from the Commandline parsing. I'll create a pull request once thats done :)
