### ISSUE TITLE
cannot find -lcapstone

### ISSUE THREAD

**Issue by Daniele-B** [radareorg/cutter#222]
I have an issue building cutter. When i do 'make' it gives me this error:
`/usr/bin/ld: cannot find -lcapstone
Makefile:513: recipe for target 'cutter' failed
collect2: error: ld returned 1 exit status
make: *** [cutter] Error 1
22:40:37: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project cutter (kit: Desktop Qt 5.7.0 GCC 64bit)
When executing step "Make"
22:40:37: Elapsed time: 00:00.`

It seems my g++ doesn't have '-lcapstone' flag.
I'm currently using Kali Linux and my g++ version is `7.2.1`

**Comment by Maijin** [comment]
If you can't follow the building steps, use the releases https://github.com/radareorg/cutter/releases
