### ISSUE TITLE
lib folder location

### ISSUE THREAD

**Issue by luonii** [radareorg/cutter#2225]
cutter search lib on /lib/ instead of ../lib/

which means that if Cutter uses a different prefix by (-DCMAKE_INSTALL_PREFIX=), it cannot find the libs

**Comment by karliss** [comment]
I assume you are talking about Linux.

Could you describe your use case in more details? By default searching for libs in /lib and a few other folders is the default behavior of Linux dynamic linker. Most Linux executables behave that way unless they are purpose built for being portable like Appimage or something like that which gets shipped together with libraries. If Cutter project also built some dynamic libraries not only single executable it would be a slightly different story. I would expect CMake to handle that, but I can't be sure without actually testing it.

You can probably achieve what you want using CMAKE_INSTALL_RPATH option. Regardless of it helping you or not I would like to hear more about your use case.

**Comment by luonii** [comment]
I build Cutter and other program in a directory /myprog/ so that it is not mixed with the rest of the system
