### ISSUE TITLE
Document the shortcuts to toggle Console Widget

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/cutter#2245]
**Is your feature request related to a problem? Please describe.**

Currently, the menu-items part in the user documentation does not mention the shortcuts for toggling the Console widget 
https://cutter.re/docs/user-docs/menus/menu-bar/windows-menu.html?highlight=console#show-console

That said, it does mentioned in the shortcuts page

https://cutter.re/docs/user-docs/shortcuts.html

**Describe the solution you'd like**

Document the shortcuts to toggling the console widget in the windows-menu page 

**Additional context**

Please notice that there are two shortcuts for this. Document both

**Comment by Surendrajat** [comment]
The same goes for widgets like Search, Imports, Exports, etc. Guess the issue can be updated for a more generalized update.
