### ISSUE TITLE
failed when compile cutter

### ISSUE THREAD

**Issue by HaxorGaruda** [radareorg/cutter#226]
i has follow instruction, build radare2 from submodule , but when compiling Cutter got this error : 
```
/usr/bin/ld: cutter.o: undefined reference to symbol 'r_magic_version'
//usr/lib/x86_64-linux-gnu/libr_magic.so.2.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:444: recipe for target 'cutter' failed

```
thanks ..

**Comment by xarkes** [comment]
If you need to use Cutter please refer to the following release: https://github.com/radareorg/cutter/releases/tag/v1.0
We need more information to help you, like the exact commands you typed.
