### ISSUE TITLE
r_util/r_annotated_code.h: No such file or directory

### ISSUE THREAD

**Issue by nauliajati** [radareorg/cutter#2262]
Hi, i trying to install Cutter in Ubuntu 16.04.6 LTS, i have the latest version of Cutter, but when i try to compile from the sources:
1. mkdir build && cd build
2. cmake -DCUTTER_USE_BUNDLED_RADARE2=ON ../src
3. cmake --build .

then i got this error: **r_util/r_annotated_code.h: No such file or directory**

i didn't solve this problem until now.. :disappointed:

**Comment by karliss** [comment]
Please double check that you have properly checked out git submodules.

**Comment by Surendrajat** [comment]
@nauliajati your **radare2** submodule is out of sync. Either you do `git submodule sync --recursive` or just go to **radare2** dir and do `git pull & git checkout e968c94` as a temporary solution.

**Comment by nauliajati** [comment]
i have already doing that, $ git clone --recurse-submodules https://github.com/radareorg/cutter
fatal: destination path 'cutter' already exists and is not an empty directory.

**Comment by Surendrajat** [comment]
@nauliajati it's telling that you have already the cutter dir cloned. No need to clone again. Just do `cd cutter` and run the above-mentioned command.

**Comment by NirmalManoj** [comment]
@nauliajati Hey, you have opened a similar issue 3 weeks ago here: https://github.com/radareorg/r2ghidra-dec/issues/113#issuecomment-638641362. Itay and I had explained the reason for why this is happening there. If you hadn't understood it then, you could have reopened that issue for more queries. I thought it worked for you. If you are still facing issues, I would suggest you make a new clone (deleting the old one) and try it now so that it will work for sure.

**Comment by nauliajati** [comment]
okay, i successfully install Cutter, but when i trying to open ELF 32-bit file, Cutter got force close..
(locked: no new keys can be created (asm.bytespace))
Plugins are loaded from "~/.local/share/RadareOrg/Cutter/plugins"
Loaded 1 plugin(s).
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Check for objc references
[x] Check for vtables
[x] Type matching analysis for all functions (aaft)
[x] Propagate noreturn information
[x] Use -AA or aaaa to perform additional experimental analysis.

**Comment by NirmalManoj** [comment]
Did you update your submodule?

**Comment by NirmalManoj** [comment]
Is it possible to share that binary?

**Comment by nauliajati** [comment]
Of course, i have already update submodule: $ git clone --recurse-submodules https://github.com/radareorg/cutter

**Comment by nauliajati** [comment]
where can i share binary file?

**Comment by NirmalManoj** [comment]
You can share it here. Also, can you try `cd radare2 && git checkout e968c9442 `. Then build cutter.

**Comment by NirmalManoj** [comment]
> i have already update submodule: $ git clone --recurse-submodules https://github.com/radareorg/cutter

Just making sure. So you removed the previous clone and made a new clone, right?

**Comment by nauliajati** [comment]
> > i have already update submodule: $ git clone --recurse-submodules https://github.com/radareorg/cutter
> 
> Just making sure. So you removed the previous clone and made a new clone, right?

yes, i remove it first, and clone again with --recurse-submodules options..

**Comment by nauliajati** [comment]
> You can share it here. Also, can you try `cd radare2 && git checkout e968c9442 `. Then build cutter.

i'll tried it first..

**Comment by NirmalManoj** [comment]
> i'll tried it first..

This is actually a different commit than what surendrajat mentioned. If you made a new clone with `git clone --recurse-submodules https://github.com/radareorg/cutter`, you don't have to try this.

**Comment by nauliajati** [comment]
> > i'll tried it first..
> 
> This is actually a different commit than what surendrajat mentioned. If you made a new clone with `git clone --recurse-submodules https://github.com/radareorg/cutter`, you don't have to try this.

okay, now i tried installing cutter again..

**Comment by nauliajati** [comment]
didn't solve, i have already reinstall Cutter, but when i'm tried to open binary file, Cutter got force close..

**Comment by nauliajati** [comment]
> Is it possible to share that binary?

**Comment by Surendrajat** [comment]
@nauliajati You should probably open another issue for the crash. This issue should be closed now.

**Comment by nauliajati** [comment]
Okay, i already open another issue, Thanks.
