### ISSUE TITLE
Cutter Get Force Close

### ISSUE THREAD

**Issue by nauliajati** [radareorg/cutter#2264]
**Environment information**
* Operating System: Ubuntu 16.04.6 LTS
* Cutter version: 1.10.3
* Obtained from:
  - [x] Built from source
  - [ ] Downloaded from release
  - [ ] Distribution repository
* File format: ELF 32-bit LSB executable

**Describe the bug**

i have already install Cutter, but when i'm tried to open binary(ELF 32bit) file, Cutter got force close.

**To Reproduce**

1. Go to 'Open File'
2. Click on 'Select'
3. Scroll down to 'Binary File ELF 32 bit'
4. Click OK
5. Cutter Force Close
6. Example Binary File: [examplebin1file.zip](https://github.com/radareorg/cutter/files/4825047/examplebin1file.zip)

**Comment by xarkes** [comment]
Hello, could you please fill the issue template accordingly?
We would need a copy of the binary file and a stack trace in order for us to try to reproduce the bug here.
If you could provide us with such things, it would help us for investigating the issue.
Thank you :)

**Comment by karliss** [comment]
The fragment of output log from your previous issue mentioned loading of plugin. If you have any old plugins compiled against different cutter version those may cause problems. Please try running without any plugins, you can remove the plugin manually or start the Cutter with `--no-plugins` flag.

**Comment by nauliajati** [comment]
> The fragment of output log from your previous issue mentioned loading of plugin. If you have any old plugins compiled against different cutter version those may cause problems. Please try running without any plugins. You can remove the plugin manually or start the Cutter with `--no-plugins` flag.

Thanks, it's work now..
