### ISSUE TITLE
Sort by Resource "Size" is incorrect

### ISSUE THREAD

**Issue by threatlead** [radareorg/cutter#2272]
**Environment information**
* Operating System: Debian
* Cutter version: v1.10.3
* Obtained from:
  - [ ] Built from source
  - [x] Downloaded from release
  - [ ] Distribution repository
* File format: PE32

When sorting by "size" in resource page, it sorts by string-order and not numerical order.

**To Reproduce**

1. Go to 'resources' tab
2. Click on 'size' column
3. See error

**Expected behavior**

Sort by numerical order and not string.

**Screenshots**

![cutter-sort-by-resource-size](https://user-images.githubusercontent.com/6679170/86203101-f5764700-bb18-11ea-9e33-3a295da01395.png)

**Comment by karliss** [comment]
Related #2152
