### ISSUE TITLE
How to save *.so binary after edit function name?

### ISSUE THREAD

**Issue by unknow-dev** [radareorg/cutter#2274]
Hello Cutter Team,
After change function name in *.so file, how to save it to separate binary?

Thansk.

**Comment by karliss** [comment]
The renaming functionality is for the purpose of making annotations during reverse-engineering. It can't rename the functions inside the binary itself. If you really want to rename function in a way that that *.so can be loaded and function with new name can be called you need a different tool.

**Comment by xarkes** [comment]
I think the question was answered, feel free to reopen if not.
