### ISSUE TITLE
command line usage guide

### ISSUE THREAD

**Issue by mkfcoffee** [radareorg/cutter#2279]
Sorry, I am a newbie, I have carefully browsed the documentation and Issues, but I don’t know how to use `Cutter [options] [<filename>]`  in the terminal.
I use .dmg file to install, do I need to configure environment variables?

Please guide me what steps I need to do before I can use Cutter in the terminal,thanks!

**Comment by karliss** [comment]
How to pass a command line argument to a GUI .app on macOS is more of a macOS question not a Cutter one and you should ask it in an appropriate macOS forum.

Next time for questions how to use Cutter (assuming they are not about how to use your operating system) better ask in the Cutter  Telegram group or IRC. The issue tracker isn't the best place for such questions.

I don't use macOS but quick search indicates that you can probably do it using the `open` program. Don't try to mix the macOS specif open file GUI app  mechanism with the arguments for customizing how the file specified in command line gets opened. Those are two different things.
