### ISSUE TITLE
Strings offset not assignd by -m

### ISSUE THREAD

**Issue by jjm2473** [radareorg/cutter#2282]
**Environment information**
* Operating System: osx 10.15.5
* Cutter version: 1.10.3
* File format: any
 * Arch: N/A
 * Type: N/A

**Describe the bug**
Strings offset was wrong when set -m OFFSET

**To Reproduce**
1. Open a binary
2. Set Arch as 'arm'
3. Set Map offset (-m) as '0x20000'
4. Press OK to start analysis
5. Double click any string in Strings window
6. String offset not matches Disassembly or Hexdump window

**Expected behavior**
String offset matches Disassembly and Hexdump window as -m did.

**Screenshots**
<img width="600" alt="WechatIMG23" src="https://user-images.githubusercontent.com/3896703/87000053-b7e37f00-c1e6-11ea-9ddc-f6b013af895d.png">
<img width="1007" alt="WechatIMG24" src="https://user-images.githubusercontent.com/3896703/87000060-bca83300-c1e6-11ea-95b8-2da1d8f060fb.png">

**Additional context**

**Comment by xarkes** [comment]
Check https://github.com/radareorg/cutter/issues/516 and https://github.com/radareorg/radare2/issues/10722 for references. I think this issue is known and must be fixed in radare2.

**Comment by jjm2473** [comment]
OK,  thanks
