### ISSUE TITLE
Unable to open functions in decompiler after closing decompiler window

### ISSUE THREAD

**Issue by TheProgramableTurtle** [radareorg/cutter#2300]
**Environment information**
* Operating System: Windows 10 version 2004
* Cutter version: 1.10.3
* Obtained from:
  - [ ] Built from source
  - [x] Downloaded from release
  - [ ] Distribution repository
* File format: aarch64

**Describe the bug**

When right-clicking a function in the function window it is possible to click "Show in" and "Decompiler". This opens the Decompiler window if it isn't open already, and while the window is open other functions can be shown in the decompiler in the same way, but after closing the decompiler window "Decompiler" is no longer an option in the "Show in" menu, even if the decompiler window is re-opened from the "Windows" tab at the top. Opening functions in the decompiler again requires closing and reloading the project.
**To Reproduce**

1. Open a file in Cutter.
2. Right-click a function in the function window.
3. Click "Show in" and "Decompiler".
4. Close decompiler window.
5. Functions cannot be opened in the decompiler.

**Expected behavior**

Right-clicking a function and selecting "Open in" would show a "Decompiler" option. 

**Screenshots**

![image](https://user-images.githubusercontent.com/44685118/87881289-3b278080-c9f0-11ea-97b2-674a3feb0b75.png)
![image](https://user-images.githubusercontent.com/44685118/87881326-6ad68880-c9f0-11ea-93ba-8fcce29d7356.png)

**Additional context**

Does radare2 properly support arm64? The README only says arm, not explicitly arm64, but Cutter seems to work with it, giving arm64 as the call type for all the functions.

**Comment by karliss** [comment]
Was able to repeat with 1.10.3 works correctly in master. I initially thought that it was fixed by e5d7bd660af558330b98249857e8ea109208cddc which slightly reworked show-in menu due to callgraphs but it also works in previous commit so it was probably fixed by layout managment changes 3545f059f10dc30886b8403b48b51812f65726d5
