### ISSUE TITLE
Opening files

### ISSUE THREAD

**Issue by TheProgramableTurtle** [radareorg/cutter#2304]
**Environment information**
* Operating System: Windows 10 version 2004
* Cutter version: 1.10.3
* Obtained from:
  - [ ] Built from source
  - [x] Downloaded from release
  - [ ] Distribution repository
* File format: aarch64

**Describe the bug**
When opening files Cutter only analyses correctly about 5% of the time. I'll select a file to open, choose Auto-Analysis, and keep all options at default except Architecture and CPU which I set to arm and v8. Sometimes it works and a long list of functions is displayed. But the vast majority of the time I just see the screenshot below.

**To Reproduce**

1. Open a file choosing arm as the architecture and v8 as the processor. I managed to replicate this with a bunch of different files, like [this](https://github.com/radareorg/cutter/files/4947834/SecureROM-s5l8960xsi-1704.10-RELEASE.txt) file.
2. Cutter analyses correctly or it doesn't.

**Expected behavior**

Cutter would open and analyse the file correctly, as it does sometimes.

**Screenshots**

![image](https://user-images.githubusercontent.com/44685118/87940630-d3c20d00-ca91-11ea-9fac-cf387d8225df.png)

**Additional context**

While trying to take a screenshot of the failed opening, the file actually opened the first time. But then the next time it failed. And then it worked again. And then failed several times. I can't find any consistent behavior, it seems entirely random.

**Comment by TheProgramableTurtle** [comment]
Ok, I think I've figured it out, it depends on how the options are selected. If I click the dropdown, then click the option from the list, and then click open, the file is analysed successfully. But if I scroll over the option box to select the option, it doesn't open properly. Clicking elsewhere in the window before opening doesn't help either, the option must be selected with left mouse button. I suppose this would be considered a UI bug?

**Comment by karliss** [comment]
Thank you for your time investigating the problem.  Indeed sounds like there might be a UI bug not handling certain kind of ways for changing input fields. Can you clarify exactly which dropdowns are you referring to?

I am also a bit curios about what you meant by "Distribution repository" for Windows 10. I am not quite sure what that means for anything that isn't Linux. Do you mean Windows Store or Winget?

**Comment by TheProgramableTurtle** [comment]
Sorry, I was thinking of the radare2 repository, I got Cutter from the release page. These are the dropdowns I was referring to under "Advanced Options".
![image](https://user-images.githubusercontent.com/44685118/87950126-cc553080-ca9e-11ea-8e8e-0c3c613f0d98.png)

**Comment by karliss** [comment]
Can you show the output of running `e asm.cpu` in console widgets in the bad and good case?

**Comment by TheProgramableTurtle** [comment]
`e asm.cpu` gives "v8" in both cases, and `e asm.arch` gives "arm" in both cases as well.
