### ISSUE TITLE
Explain how to build the docs

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/cutter#2309]
**Is your feature request related to a problem? Please describe.**

There is no documentation explaining how to build the docs for Cutter

**Describe the solution you'd like**

A dedicated page under `docs/contributing/docs/` that will instruct how to build Cutter's docs. Explain the requirements and the different `make` commands such as `make html` and `make quick`.

**Describe alternatives you've considered**

To add it to the `getting-started` document under `docs/contributing/docs`.

**Comment by karliss** [comment]
It should also mention what software is required for doing that.

**Comment by ITAYC0HEN** [comment]
This goes under "explain the requirements"
