### ISSUE TITLE
Use or remove fonts in src/fonts

### ISSUE THREAD

**Issue by thestr4ng3r** [radareorg/cutter#231]
Currently not used afaik: https://github.com/radareorg/cutter/tree/master/src/fonts

**Comment by xarkes** [comment]
Yes cf https://github.com/radareorg/cutter/issues/129

**Comment by xarkes** [comment]
I don't know how default fonts are on other Operating systems, but on linux at least it is quite convenient. If it's also good on Windows and OsX too maybe we can just throw it? Unless someone really likes it and then we make it default for every OS. I would tend to use the last one so it looks the same on every platform (by default obviously)

**Comment by xarkes** [comment]
https://github.com/radareorg/cutter/commit/4cc51a6a51c77591a8392eb7abe08e583a9c034d
