### ISSUE TITLE
Buggy line highlighting during debugging

### ISSUE THREAD

**Issue by karliss** [radareorg/cutter#2317]
**Environment information**
* Operating System: Windows 10
* Cutter version: Cutter 1.11.0-rc1
* Obtained from:
  - [ ] Built from source
  - [x] Downloaded from release
  - [ ] Distribution repository
* File format: PE

**Describe the bug**

During debuging it seems that condition for highlighting line with current PC is incorrectly uses current seek offset instead of PC for some of the checks.

**To Reproduce**

1. Start debugging and wait for program to stop, it should be one of builtin stopping on entry or something like that. Not tested with breakpoints which would introduce third line highlighting rule.
2. Select line that is few lines bellow the one with current PC
3. scroll up until selected line reaches end, observe that the last line is now highlighted using current PC color instead of selected line color and line with current PC isn't highlighted at all. Since scrolling happens multiple lines at a time the selected line might need some adjustment to allow positioning it at the bottom of screen.
4. scroll further up and observe that no line is highlighted even though line with current PC is still in screen.

**Expected behavior**

Line with current PC is correctly highlighted regardless of scroll position.

**Screenshots**

Step 1 - 2. The green line indicates current PC and gray/blue is selected line.

![f2](https://user-images.githubusercontent.com/7101031/88202586-c6ec1780-cc51-11ea-9e8c-06f1605d99b1.PNG)
Step 3, wrong highlighting
![f3](https://user-images.githubusercontent.com/7101031/88202861-21857380-cc52-11ea-8da1-4c8c667a2cd7.PNG)
Step 4, highlighting disappears completely.
![f4](https://user-images.githubusercontent.com/7101031/88202914-3530da00-cc52-11ea-91ba-0f3d71d6e6b4.png)

**Additional context**

**Comment by cctechwiz** [comment]
I'd like to take this one.

**Comment by ITAYC0HEN** [comment]
Hey @cctechwiz , sure!
You can start by quickly going over our guidelines for contributors: https://cutter.re/docs/contributing/code/getting-started.html
You might find it, and the links inside, useful :)

Let us know if you have any question and we would love to guide you

**Comment by cctechwiz** [comment]
A PR (#2444) has been created that addresses this issue. It is ready for review at your convenience. Thanks!
