### ISSUE TITLE
analysis big dll will cause cutter make no response to any others

### ISSUE THREAD

**Issue by frustreated** [radareorg/cutter#2334]
**Environment information**
* Operating System:
Windows
* Cutter version:
lateses
* Obtained from:
  - [x] Built from source
download from official website
  - [ ] Downloaded from release
  - [ ] Distribution repository
* File format:
dll(PE)
**Describe the bug**
open a big dll file will cause cutter like died
![image](https://user-images.githubusercontent.com/5463104/88479655-5449a780-cf83-11ea-93ed-d088819600dd.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ITAYC0HEN** [comment]
Hey! Thanks for reporting this issue.
Cutter has a known issue with analyzing big files as it takes time and freeze the interface. We plan to make analysis in the background so one can start working while the analysis is performed. Currently, we can suggest to try different analysis options which might be faster. There is an Analysis Scroll you can move in the Initial Analysis dialog.

See this feature request https://github.com/radareorg/cutter/issues/1856

(cc @Surendrajat maybe worth adding to known issues or FAQ)

**Comment by frustreated** [comment]
ida pro also take a long time for more than 50M may be .
a good aspect of ida is not die-ing response .
really hope cutter can be more better

**Comment by ITAYC0HEN** [comment]
It will! Thank you for giving us your trust :)
Indeed, large binaries are problematic, and believe me when I say it's not so easy to make the analysis in the background.
Hopefully you will find it more useful with smaller binaries

**Comment by frustreated** [comment]
> It will! Thank you for giving us your trust :)
> Indeed, large binaries are problematic, and believe me when I say it's not so easy to make the analysis in the background.
> Hopefully you will find it more useful with smaller binaries

binary ninja cannot deal with big files smoolthly when process files like chrome_child.dll
now only ida can deal with it and also take a long time may be as long as 20 minutes.
if cutter can deal with it , i think despite any other respect , its realy better than commecial ones.
