### ISSUE TITLE
Suggestion: Option to compile with custom Qt5 library

### ISSUE THREAD

**Issue by lars18th** [radareorg/cutter#2339]
Hi,

First of all, I need to describe my _use case_:

- I need to fix a closed source binary in a Linux embedded system. The AppImage doesn't work as the system libraries are quite old. Then I'm triying to compile Cutter in a _similar_ Linux environment (mainly using the same kernel version) and generate a _solid_ package with all the dependencies (using the good tool Exodus (https://github.com/intoli/exodus). However, the problem is to compile Cutter on ancient environments (and because it can't work in a Client-Server mode as explained in #2311 ).

For example, after fixing the radare2 troubles (#2316), I discovered that only with Qt5 v5.5 or up it's possible to compile Cutter. So I need to recompile a full Qt5 library from scratch. And the problem is that versions 5.9 and 5.8 doesn't compile, and 5.5, 5.6 and 5.7 seems to be incompatible with Cutter _when compiling with them_.

So here my suggestion: Provide the option to enable the full compilation of the Qt5 with only the required modules/libraries. Then link (optionally) Cutter with it for a new version without the Qt5 dependecy.

What you think about this idea? It has sense?
Regards.

**Comment by karliss** [comment]
No, so far the the text you are writing doesn't make sense I am not capable to understand what you want.

> Option to compile with custom Qt5 library

You can already configure build system to use Qt of your choice assuming it compatible with Cutter. If you lack the experience working with build systems Kitware provides training courses where you can improve your skills.

>  5.5, 5.6 and 5.7 seems to be incompatible with Cutter when compiling with them.

All Cutter commits tested using Qt 5.5. IIf Cutter compiles using Qt 5.14 and 5.5 it is unlikely that the versions between (5.6, 5.7) will not work but if you find problems with them you are welcome to send pull requests fixing that.

> Provide the option to enable the full compilation of the Qt5 with only the required modules/libraries.

"full compilation of Qt5" and  "only the required modules" seems contradicting. Either way compilation of Qt is handled by build scripts that are part of Qt. I don't see how it is related to Cutter. If you don't understand how Qt compilation process works you can discuss that with Qt developers.

>  Then link (optionally) Cutter with it for a new version without the Qt5 dependecy.

This sentence doesn't make sense. Cutter is GUI for radare2 made using Qt. 90% of Cutter code interacts with Qt.  Cutter without dependency on Qt5 would be just radare2.

**Comment by lars18th** [comment]
Hi @karliss ,

I understand well what you say. Futhermore, I now how to configure/compile Qt; so that's not the question. However:

- In some non-recent Linux environments is quite complex to compile recent Qt versions.
- Some old GCC versions (4.7 for example) has some "bugs" or "pseudo-bugs" that make very complex to compile _current_ Cutter code.
- The Qt library is _VERY_ modular. And not all modules/plugins/libraries are necessary to compile Cutter.

So, I try to reformulate my request:

- Can you provide a script for a custom compilation of Qt with _only_ the minimal requirements?

This will simplifies the generation of a _local_ qt5 library to support the compilation of the Cutter (using the corresponding `QTDIR` and `PATH` & `LD_LIBRARY_PATH`).

I hope it's more clear now, right?
Regards.

**Comment by lars18th** [comment]
Hi @karliss ,

As example (current Cutter repo with Qt5.7.0):
```
[ 18%] Building CXX object CMakeFiles/Cutter.dir/dialogs/AboutDialog.cpp.o
/home/user/cutter/src/dialogs/AboutDialog.cpp: In lambda function:
/home/user/cutter/src/dialogs/AboutDialog.cpp:102:55: error: ‘this’ was not captured for this lambda function
/home/user/cutter/src/dialogs/AboutDialog.cpp:105:71: error: ‘this’ was not captured for this lambda function
/home/user/cutter/src/dialogs/AboutDialog.cpp:105:100: error: ‘this’ was not captured for this lambda function
make[2]: *** [CMakeFiles/Cutter.dir/dialogs/AboutDialog.cpp.o] Error 1
make[1]: *** [CMakeFiles/Cutter.dir/all] Error 2
make: *** [all] Error 2
```
And this error can be fixed with a simple:
```
    connect(&updateWorker, &UpdateWorker::checkComplete,
-    [&updateWorker](const QVersionNumber & version, const QString & error) {
+    [&updateWorker,this](const QVersionNumber & version, const QString & error) {
        if (!error.isEmpty()) {
            QMessageBox::critical(nullptr, tr("Error!"), error);
```
However, other more complex errors still appears:
```
/home/usercutter/src/widgets/DisassemblyWidget.cpp: In member function ‘virtual void DisassemblyLeftPanel::paintEvent(QPaintEvent*)’:
/home/usercutter/src/widgets/DisassemblyWidget.cpp:857:31: error: ‘INT32_MAX’ was not declared in this scope
In file included from /home/usercutter/src/widgets/CutterDockWidget.h:5:0,
                 from /home/usercutter/src/plugins/CutterPlugin.h:8,
                 from /home/usercutter/src/core/Cutter.h:26,
                 from /home/usercutter/src/widgets/DisassemblyWidget.h:4,
                 from /home/usercutter/src/widgets/DisassemblyWidget.cpp:1:
/home/usercutter/src/common/RefreshDeferrer.h: In instantiation of ‘class ReplacingRefreshDeferrerAccumulator<long long unsigned int>’:
/home/usercutter/src/widgets/CutterDockWidget.h:53:119:   required from ‘RefreshDeferrer* CutterDockWidget::createReplacingRefreshDeferrer(bool, Func) [with ParamResult = long long unsigned int; Func = DisassemblyWidget::DisassemblyWidget(MainWindow*)::<lambda(const RVA*)>]’
/home/usercutter/src/widgets/DisassemblyWidget.cpp:113:6:   required from here
/home/usercutter/src/common/RefreshDeferrer.h:66:5: error: looser throw specifier for ‘ReplacingRefreshDeferrerAccumulator<T>::~ReplacingRefreshDeferrerAccumulator() [with T = long long unsigned int]’
/home/usercutter/src/common/RefreshDeferrer.h:21:13: error:   overriding ‘virtual RefreshDeferrerAccumulator::~RefreshDeferrerAccumulator() noexcept (true)’
In file included from /usr/local/qt-5.7.0/include/QtWidgets/qwidget.h:44:0,
                 from /usr/local/qt-5.7.0/include/QtWidgets/qmenu.h:43,
                 from /usr/local/qt-5.7.0/include/QtWidgets/QMenu:1,
                 from /home/usercutter/src/core/Cutter.h:9,
                 from /home/usercutter/src/widgets/DisassemblyWidget.h:4,
                 from /home/usercutter/src/widgets/DisassemblyWidget.cpp:1:
/usr/local/qt-5.7.0/include/QtCore/qobject.h: At global scope:
/usr/local/qt-5.7.0/include/QtCore/qobject.h:299:13: error: ‘static typename QtPrivate::QEnableIf<(QtPrivate::FunctionPointer<Func2>::ArgumentCount == (-1)), QMetaObject::Connection>::Type QObject::connect(const typename QtPrivate::FunctionPointer<Func1>::Object*, Func1, const QObject*, Func2, Qt::ConnectionType) [with Func1 = void (RefreshDeferrer::*)(void*); Func2 = CutterDockWidget::createReplacingRefreshDeferrer(bool, Func) [with ParamResult = long long unsigned int; Func = DisassemblyWidget::DisassemblyWidget(MainWindow*)::<lambda(const RVA*)>]::<lambda(RefreshDeferrerParamsResult)>; typename QtPrivate::QEnableIf<(QtPrivate::FunctionPointer<Func2>::ArgumentCount == (-1)), QMetaObject::Connection>::Type = QMetaObject::Connection; typename QtPrivate::FunctionPointer<Func1>::Object = RefreshDeferrer; QObject = QObject]’, declared using local type ‘CutterDockWidget::createReplacingRefreshDeferrer(bool, Func) [with ParamResult = long long unsigned int; Func = DisassemblyWidget::DisassemblyWidget(MainWindow*)::<lambda(const RVA*)>]::<lambda(RefreshDeferrerParamsResult)>’, is used but never defined [-fpermissive]
make[2]: *** [CMakeFiles/Cutter.dir/widgets/DisassemblyWidget.cpp.o] Error 1
make[1]: *** [CMakeFiles/Cutter.dir/all] Error 2
make: *** [all] Error 2
```
So, if you can, try to compile Cutter using the GCC 4.7 version.

Regards.

**Comment by karliss** [comment]
First one isn't even a qt error that's a C++ error. Providing a script for compiling Qt wouldn't help you with that.

GCC 4.7 doesn't have proper c++11 support. Trying to compile Cutter using it or maintaining patches to do so is waste of time.

If you are not happy with Qt build using build scripts provided by Qt developers that's up to you.

**Comment by XVilka** [comment]
If you really need Cutter on that system - you can compile it statically
within Alpine Linux container and just copy the binaries. I don't know
though if Qt or Cutter support completely static builds though.

**Comment by XVilka** [comment]
But I recommend to try to do whatever you want with plain radare2 since you
succeeded with building it.

**Comment by lars18th** [comment]
Hi @karliss and @XVilka ,

Thank you for your responses. I feel this willl be useful for other users, so for this reason I post some more comments (sorry to continue writing in a closed issue):

- At time the compilation of the radare2 on ancient platforms is solved.
- A manual compilation of the Qt library is not a problem. The problem is to know the minimal requirements of the configuration of this library when compiling Cutter with it. I really think that it will useful to know the best configuration to achieve that.
- Not all C++ compilers support C11. So in order to support environments _without_ recent GCC versions, I feel it will be useful to provide minimal support.
- As Cutter is a GUI for radare2, and a GUI improves a lot the usability, it will be interesting to run it in the same platforms.

I understand the effort to support ancient environments. Perhaps much effort for less, but almost it will be profitable to help to users that try to do it.

For example: here my current configuration of the Qt5.7 for Debian 7 when compiling it for Cutter:
```
../qt5/configure -prefix /usr/local/qt-5.7.0 \
-skip serialbus -skip virtualkeyboard \
-skip qtmultimedia -skip qtquick1 -skip qtquickcontrols -skip qtsensors \
-qt-zlib -qt-libjpeg -qt-libpng -qt-xcb -qt-freetype -qt-pcre \
-no-opengl -no-egl -no-dbus -no-eglfs -no-directfb -no-linuxfb \
-no-accessibility -no-cups -no-feature-accessibility \
-opensource -nomake examples -nomake tests
```
This compiles fine with the stock compiler environment. Now I'm trying to fix the C++ erros when compiling Cutter.

I hope it helps. 😄

**Comment by ITAYC0HEN** [comment]
Hey Lars! :) Thank you for the detailed explanations and for taking the time to properly describe your requests. 

Your request is legit but isn't a priority of ours and isn't a popular request we get frequently. Moreover, maintaining such list of minimal requirements isn't something we would like to put efforts in. 

That said, I invite you to send us a pull request to the docs or to the building scripts with the information you would want to see (so others can use it). I can't guarantee we will accept such PR but we will discuss and consider it. Alternatively, you can maintain such list in a separated personal repository.

Thank you again! <3
