### ISSUE TITLE
Add a link to the Documentation from Cutter's "Help" menu

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/cutter#2343]
**Is your feature request related to a problem? Please describe.**

Currently there is no link to [Cutter' docs](https://cutter.re/docs/) from the interface.

**Describe the solution you'd like**

Add a menu Item under `Help` that will be called "Documentation" and will open the docs in the browser: https://cutter.re/docs

![image](https://user-images.githubusercontent.com/20182642/88788349-e3320c00-d19d-11ea-8955-35adf7bf3c0b.png)

**Additional information**

You can see how it was implemented in `Help -> Report an issue` which also opens the browser with a URL

**Comment by 7h3qu1rkyb1t** [comment]
on it
