### ISSUE TITLE
Add xref dialog option for showing only references to

### ISSUE THREAD

**Issue by karliss** [radareorg/cutter#2353]
**Is your feature request related to a problem? Please describe.**

Currently xrefs dialog has two sections on the left side xrefs to and xrefs from given address. In some situations it is known that xrefs from section will be empty or not contain any useful information. 

Some examples of such situations are when opening xrefs from function list widget or string list. Strings are unlikely to have xrefs from unless they are instructions misinterpreted as strings. If they are user can still open the address of "string" in disassembly view and open xrefs dialog from there. Doing so will also give user information how the "string" looks when interpreted as instruction.

Situation is slightly different when viewing xrefs for function. For function xref dialog will show xrefs from the first instruction in the function (usually function header not referencing any memory adress unles appropriate optimizations are used). Viewing xrefs form first instruction can be  useful if user is actually inspecting the first instruction of function in disassembly view. But it is probably less useful when user clicks a function in function list.

In the following image, you can see an example to the X-Ref dialog as it was opened from the Strings widget:

![image](https://user-images.githubusercontent.com/20182642/89121112-b2ffab80-d4c4-11ea-959d-52039597aa48.png)

As strings are not supposed to reference to another addresses or objects, the "X-Refs from" section is redundant.

**Describe the solution you'd like**

Add an option which can be passed when creating xrefs dialog. If it is set to true "xrefs from" section in the dialog should be hidden and "xrefs from" expanded to use full window height.

**Describe alternatives you've considered**

Make a choice of hiding from or to section when it's empty. I don't think this is a good idea. Empty list also serves as confirmation that r2 didn't find any xrefs. In situation where both xrefs types are expected but they are missing due to bad analysis done by r2 hiding one of xref sections might be confusing.

**Additional context**

**Comment by ITAYC0HEN** [comment]
Nice idea! I think that I'd be happier to see a list of **all** references **from** a function (`afx`) when opening the x-ref dialog from the Functions widget (_and from the function name at function declaration in disas/graph , although it is now mixed with the first instruction. This can be done later on._)

**Comment by karliss** [comment]
Showing `axf` in case of function widget wouldn't be bad that can be second part. But as first issue i would recommend to start with just hiding.

**Comment by RadwanSelo** [comment]
should we add two new options to the context menu?
Show X-Refs (default with shortcut X)
Show X-Refs To (no shortcut)
Show X-Refs From (no shortcut)
or just hide if the found results is 0 (we will still show that nothing found for the Xrefs from)

**Comment by ITAYC0HEN** [comment]
Hi Radwan.
No, only one option:

Show All Xrefs (shortcut X) with optional `bool showXrefFrom` argument which defaults to true.

When this dialog will be executed from the following widgets, the `showXrefFrom` argument will be passed as `false` and you will hide the "Xrefs from" view in the dialog:

- Strings widget
- Functions widget

You don't hide the view when 0 results are found for X-Refs in any other place. It is important to see that no x-refs were found.
