### ISSUE TITLE
Compiling error with GCC 4.7

### ISSUE THREAD

**Issue by lars18th** [radareorg/cutter#2354]
Hi,

I know that the GCC 4.7 is quite old, but it's the default compiler with Debian 7 and I'm trying to compile Cutter inside this platform (the radare2 compiles, and I'm using a recent Qt5.7 and all other dependencies). So far, I fixed some of the compiling errors generated by the not fully C+11 conformance of GCC 4.7; but I don't know how to fix this:

```
[ 13%] Building CXX object CMakeFiles/Cutter.dir/widgets/GraphGridLayout.cpp.o
In file included from /home/user/cutter/src/widgets/GraphGridLayout.cpp:10:0:
/home/user/cutter/src/common/BinaryTrees.h:115:21: error: ‘using PointSetSegmentTree<NodeType, FinalType>::BaseType::BaseType’ conflicts with a previous declaration
/home/user/cutter/src/common/BinaryTrees.h:113:58: note: previous declaration ‘using BaseType = class SegmentTreeBase<NodeType, FinalType>’
/home/user/cutter/src/widgets/GraphGridLayout.cpp: In member function ‘void GraphGridLayout::calculateEdgeMainColumn(GraphGridLayout::LayoutState&) const’:
/home/user/cutter/src/widgets/GraphGridLayout.cpp:563:57: error: no matching function for call to ‘PointSetMinTree::PointSetMinTree(size_t, int)’
/home/user/cutter/src/widgets/GraphGridLayout.cpp:563:57: note: candidates are:
In file included from /home/user/cutter/src/widgets/GraphGridLayout.cpp:10:0:
/home/user/cutter/src/common/BinaryTrees.h:141:7: note: PointSetMinTree::PointSetMinTree(const PointSetMinTree&)
/home/user/cutter/src/common/BinaryTrees.h:141:7: note:   candidate expects 1 argument, 2 provided
/home/user/cutter/src/common/BinaryTrees.h:141:7: note: PointSetMinTree::PointSetMinTree(PointSetMinTree&&)
/home/user/cutter/src/common/BinaryTrees.h:141:7: note:   candidate expects 1 argument, 2 provided
/home/user/cutter/src/widgets/GraphGridLayout.cpp: In function ‘void optimizeLinearProgramPass(size_t, std::vector<int>, std::vector<std::pair<std::pair<int, int>, int> >, std::vector<std::pair<std::pair<int, int>, int> >, std::vector<int>&, bool)’:
/home/user/cutter/src/widgets/GraphGridLayout.cpp:1339:32: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
make[2]: *** [CMakeFiles/Cutter.dir/widgets/GraphGridLayout.cpp.o] Error 1
make[1]: *** [CMakeFiles/Cutter.dir/all] Error 2
make: *** [all] Error 2
```

The problem is caused by this code inside `cutter/src/common/BinaryTrees.h`:
```
template<class NodeType, class FinalType>
class PointSetSegmentTree : public SegmentTreeBase<NodeType, FinalType>
{
    using BaseType = SegmentTreeBase<NodeType, FinalType>;
public:
    using BaseType::BaseType;
```
The problem is the second forward alias declaration, as the comiler interprets without using the previous `BaseType` alias.
Any idea to fix this error?

Thank you!

**Comment by XVilka** [comment]
Why not to install gcc-5 which should be available in Wheezy? https://wiki.debian.org/GCC5

**Comment by karliss** [comment]
Please don't waste your an everyone else time trying to make Cutter work with GCC 4.7.  Being limited to broken 8 year old compiler increase the burden of development process making Cutter worse for 90% of people.

It would be much more useful if you spent your energy improving or at least investigating the remote debugging problems in radare2.

**Comment by lars18th** [comment]
Hi @XVilka ,

> Why not to install gcc-5 which should be available in Wheezy? https://wiki.debian.org/GCC5

I'll try, but I'm not sure if this will work, as I need to recompile *all* with the new GCC5 (including Qt5.7).

> It would be much more useful if you spent your energy improving or at least investigating the remote debugging problems in radare2.

Perhaps it isn't a waste of time... when using cross-compiling for embedded systems it's very common that _ancient_ compilers are used. And if we need to execute Cutter on such platforms, then we need to compile with such compilers. That's will be true until _full_ remote debugging will be supported. In any case, I'll try to not consume the time of the great developers of this project. Thank you all for your comments! :wink: 

Regards.

**Comment by ITAYC0HEN** [comment]
Thank you @lars18th :)
As you understand, the Cutter project aims to focus on modern technologies and as such we don't intend to support old technologies. 

I am sure that if you took the time to open these issues it means that you want to help improve Cutter and these requests are important requests to you personally. Thus, it is not at all a waste of time.

Sadly, we would not be able to provide the help in the way you wish, as we would not support these technologies. That said, we will try our best to improve the remote debugging so you can have a great remote debugging experience when time comes. Until then, keep let us know of issues you encounter on other aspects of Cutter which are not related to support old technologies.

Thank you again, and for your kind words <3
