### ISSUE TITLE
Enable drag and drop on OSX Dock icon

### ISSUE THREAD

**Issue by Maijin** [radareorg/cutter#236]
Enable drag and drop on OSX Dock icon

**Comment by xarkes** [comment]
Drag and drop works on Windows, not sure why it wouldn't work on OsX?

**Comment by xarkes** [comment]
Can you confirm the bug is still present?

**Comment by Maijin** [comment]
Still present

**Comment by Maijin** [comment]
This is still not working @marcograss

**Comment by hezi** [comment]
I've just tried this with 1.3 (from here: https://github.com/radareorg/cutter/releases/tag/v1.3) and seems to work.

**Comment by Maijin** [comment]
Yep now it works !
