### ISSUE TITLE
J/K shortcuts to work like arrows and vice-versa

### ISSUE THREAD

**Issue by Maijin** [radareorg/cutter#237]
Arrows to have same behavior as JK in the graph
https://github.com/radareorg/cutter/blob/master/src/widgets/DisassemblerGraphView.cpp#L68
JK to have same behavior as arrows in the disassembly
https://github.com/radareorg/cutter/blob/master/src/widgets/DisassemblyWidget.cpp#L449

**Comment by BigKahuna1957** [comment]
Do you want arrow up and down?  Or left and right?  Just asking as arrow up and down already work for me.

**Comment by Maijin** [comment]
It doesn't work in the graph
