### ISSUE TITLE
Add export graph as dot, SVG

### ISSUE THREAD

**Issue by Maijin** [radareorg/cutter#242]
Add export graph:
* [x] .dot with `aggd` command
* [ ] .svg (require https://github.com/radare/radare2/issues/9199)

Radare2 can already output as Graphviz dot with `aggd`, and dot can be converted to SVG (not from radare2 though).

Suggestion from @rootbsd

**Comment by Maijin** [comment]
https://github.com/radareorg/cutter/blob/master/src/Cutter.cpp#L709

**Comment by pelijah** [comment]
About *.svg:
It requires changes on r2 side because `ag` command can't export graph to specified file.
Alternative: export graph to temp *.dot file and then convert it to svg.

Both ways require presence of installed `graphviz`.

**Comment by Maijin** [comment]
The first solution is better as we should be able to define a location for those commands.

**Comment by Maijin** [comment]
I'm seeing your PR https://github.com/radare/radare2/pull/10841/files

**Comment by Maijin** [comment]
@pelijah the PR have been merged in r2 for this
