### ISSUE TITLE
How to sideload libraries?

### ISSUE THREAD

**Issue by lars18th** [radareorg/cutter#2426]
Hi,

As the cross-debug functionality with remote GDB is still in development, I'm searching for the best method to decompile a binary that uses shared objects (external libraries).

As example assume this use case:

- You're running Cutter in Windows.
- Your target binary is a Linux ELF64 with some shared object dependency (in example with "libc.so.6").
- In this environment then you want to load the binary in Cutter with Windows, and you can see in the Dashboard the Libraries used by it. Futhermore you have the Relocs page with all the functions imported too. However, the question is how you can "map" (aka "load") the libraries binaries? For sure, you have the binary file of the library in the local filesystem, so the question is how to load it.

Please, can you describe how to achieve this?
And if this isn't implemented, then you can consider to add support for it, please?
And I'm sorry if this is a newbie question.
Thank you!

**Comment by karliss** [comment]
This isn't a bad question and I don't want to discourage you from learning more about Cutter, but please do not use issue tracker for asking questions.
Does Github has a link for creating issues which skips this page?
![question](https://user-images.githubusercontent.com/7101031/92367404-0639cf00-f0ff-11ea-93a1-f9bee329c04d.png)

**Comment by lars18th** [comment]
Hi @karliss ,

Sorry! I close then this "issue" (not a real issue).

In any case, I'm reading a lot about Cutter & Radare2 but I don't know how to map "shared objects", specifically when loading Linux ELF binaries inside the Windows version of Cutter. Any idea about where to found info, please?

Regards.

**Comment by ITAYC0HEN** [comment]
Hey @lars18th , come join us on Telegram (https://t.me/r2cutter) or IRC :) We would love to assist in there
