### ISSUE TITLE
Got Build Error

### ISSUE THREAD

**Issue by codedJaguar12** [radareorg/cutter#243]
Followed every step including building radare2 from subdirectory but got following:
**The output of make**
[  1%] Automatic moc, uic and rcc for target cutter
Generating moc compilation cutter_automoc.cpp
Generating qrc source cutter_automoc.dir/qrc_resources_HAS2BXGMQQBHVI.cpp
[  1%] Built target cutter_automoc
Scanning dependencies of target cutter
[  3%] Building CXX object CMakeFiles/cutter.dir/main.cpp.o
[  5%] Building CXX object CMakeFiles/cutter.dir/cutter.cpp.o
[  6%] Building CXX object CMakeFiles/cutter.dir/widgets/DisassemblerGraphView.cpp.o
[  8%] Building CXX object CMakeFiles/cutter.dir/utils/RichTextPainter.cpp.o
[ 10%] Building CXX object CMakeFiles/cutter.dir/dialogs/OptionsDialog.cpp.o
[ 11%] Building CXX object CMakeFiles/cutter.dir/dialogs/AboutDialog.cpp.o
[ 13%] Building CXX object CMakeFiles/cutter.dir/dialogs/CommentsDialog.cpp.o
[ 15%] Building CXX object CMakeFiles/cutter.dir/dialogs/FlagDialog.cpp.o
[ 16%] Building CXX object CMakeFiles/cutter.dir/dialogs/RenameDialog.cpp.o
[ 18%] Building CXX object CMakeFiles/cutter.dir/dialogs/XrefsDialog.cpp.o
[ 20%] Building CXX object CMakeFiles/cutter.dir/MainWindow.cpp.o
[ 22%] Building CXX object CMakeFiles/cutter.dir/utils/Helpers.cpp.o
[ 23%] Building CXX object CMakeFiles/cutter.dir/utils/HexAsciiHighlighter.cpp.o
[ 25%] Building CXX object CMakeFiles/cutter.dir/utils/HexHighlighter.cpp.o
[ 27%] Building CXX object CMakeFiles/cutter.dir/utils/Highlighter.cpp.o
[ 28%] Building CXX object CMakeFiles/cutter.dir/utils/MdHighlighter.cpp.o
[ 30%] Building CXX object CMakeFiles/cutter.dir/dialogs/preferences/AsmOptionsWidget.cpp.o
[ 32%] Building CXX object CMakeFiles/cutter.dir/dialogs/NewFileDialog.cpp.o
[ 33%] Building CXX object CMakeFiles/cutter.dir/AnalThread.cpp.o
[ 35%] Building CXX object CMakeFiles/cutter.dir/widgets/CommentsWidget.cpp.o
[ 37%] Building CXX object CMakeFiles/cutter.dir/widgets/ConsoleWidget.cpp.o
[ 38%] Building CXX object CMakeFiles/cutter.dir/widgets/Dashboard.cpp.o
[ 40%] Building CXX object CMakeFiles/cutter.dir/widgets/EntrypointWidget.cpp.o
[ 42%] Building CXX object CMakeFiles/cutter.dir/widgets/ExportsWidget.cpp.o
[ 44%] Building CXX object CMakeFiles/cutter.dir/widgets/FlagsWidget.cpp.o
[ 45%] Building CXX object CMakeFiles/cutter.dir/widgets/FunctionsWidget.cpp.o
[ 47%] Building CXX object CMakeFiles/cutter.dir/widgets/ImportsWidget.cpp.o
[ 49%] Building CXX object CMakeFiles/cutter.dir/widgets/Notepad.cpp.o
[ 50%] Building CXX object CMakeFiles/cutter.dir/widgets/Omnibar.cpp.o
[ 52%] Building CXX object CMakeFiles/cutter.dir/widgets/PieView.cpp.o
[ 54%] Building CXX object CMakeFiles/cutter.dir/widgets/RelocsWidget.cpp.o
[ 55%] Building CXX object CMakeFiles/cutter.dir/widgets/SdbDock.cpp.o
[ 57%] Building CXX object CMakeFiles/cutter.dir/widgets/SectionsDock.cpp.o
[ 59%] Building CXX object CMakeFiles/cutter.dir/widgets/SectionsWidget.cpp.o
[ 61%] Building CXX object CMakeFiles/cutter.dir/widgets/Sidebar.cpp.o
[ 62%] Building CXX object CMakeFiles/cutter.dir/widgets/StringsWidget.cpp.o
[ 64%] Building CXX object CMakeFiles/cutter.dir/widgets/SymbolsWidget.cpp.o
[ 66%] Building CXX object CMakeFiles/cutter.dir/menus/DisassemblyContextMenu.cpp.o
[ 67%] Building CXX object CMakeFiles/cutter.dir/widgets/DisassemblyWidget.cpp.o
[ 69%] Building CXX object CMakeFiles/cutter.dir/widgets/SidebarWidget.cpp.o
[ 71%] Building CXX object CMakeFiles/cutter.dir/widgets/HexdumpWidget.cpp.o
[ 72%] Building CXX object CMakeFiles/cutter.dir/utils/Configuration.cpp.o
[ 74%] Building CXX object CMakeFiles/cutter.dir/utils/Colors.cpp.o
[ 76%] Building CXX object CMakeFiles/cutter.dir/dialogs/SaveProjectDialog.cpp.o
[ 77%] Building CXX object CMakeFiles/cutter.dir/utils/TempConfig.cpp.o
[ 79%] Building CXX object CMakeFiles/cutter.dir/utils/SvgIconEngine.cpp.o
[ 81%] Building CXX object CMakeFiles/cutter.dir/utils/SyntaxHighlighter.cpp.o
[ 83%] Building CXX object CMakeFiles/cutter.dir/widgets/PseudocodeWidget.cpp.o
[ 84%] Building CXX object CMakeFiles/cutter.dir/widgets/VisualNavbar.cpp.o
[ 86%] Building CXX object CMakeFiles/cutter.dir/widgets/GraphView.cpp.o
[ 88%] Building CXX object CMakeFiles/cutter.dir/dialogs/preferences/PreferencesDialog.cpp.o
[ 89%] Building CXX object CMakeFiles/cutter.dir/dialogs/preferences/GeneralOptionsWidget.cpp.o
[ 91%] Building CXX object CMakeFiles/cutter.dir/dialogs/preferences/GraphOptionsWidget.cpp.o
[ 93%] Building CXX object CMakeFiles/cutter.dir/widgets/QuickFilterView.cpp.o
[ 94%] Building CXX object CMakeFiles/cutter.dir/widgets/ClassesWidget.cpp.o
[ 96%] Building CXX object CMakeFiles/cutter.dir/cutter_automoc.cpp.o
[ 98%] Building CXX object CMakeFiles/cutter.dir/cutter_automoc.dir/qrc_resources_HAS2BXGMQQBHVI.cpp.o
[100%] Linking CXX executable cutter
CMakeFiles/cutter.dir/cutter.cpp.o: In function `CutterCore::sdbList(QString)':
cutter.cpp:(.text+0x4e7): undefined reference to `sdb_ns_path'
CMakeFiles/cutter.dir/cutter.cpp.o: In function `CutterCore::sdbListKeys(QString)':
cutter.cpp:(.text+0x679): undefined reference to `sdb_ns_path'
cutter.cpp:(.text+0x6a5): undefined reference to `sdb_foreach_list'
CMakeFiles/cutter.dir/cutter.cpp.o: In function `CutterCore::sdbGet(QString, QString)':
cutter.cpp:(.text+0x807): undefined reference to `sdb_ns_path'
cutter.cpp:(.text+0x854): undefined reference to `sdb_const_get'
CMakeFiles/cutter.dir/cutter.cpp.o: In function `CutterCore::sdbSet(QString, QString, QString)':
cutter.cpp:(.text+0x965): undefined reference to `sdb_ns_path'
CMakeFiles/cutter.dir/cutter.cpp.o: In function `CutterCore::cmd(QString const&)':
cutter.cpp:(.text+0xd30): undefined reference to `r_mem_free'
CMakeFiles/cutter.dir/cutter.cpp.o: In function `CutterCore::cmdj(QString const&)':
cutter.cpp:(.text+0x10f4): undefined reference to `r_mem_free'
cutter.cpp:(.text+0x1269): undefined reference to `r_mem_free'
CMakeFiles/cutter.dir/cutter.cpp.o: In function `CutterCore::loadFile(QString, unsigned long, unsigned long, bool, int, int, bool, QString const&)':
cutter.cpp:(.text+0x14f3): undefined reference to `r_bin_force_plugin'
CMakeFiles/cutter.dir/cutter.cpp.o: In function `CutterCore::tryFile(QString, bool)':
cutter.cpp:(.text+0x2908): undefined reference to `sdb_bool_set'
CMakeFiles/cutter.dir/cutter.cpp.o: In function `CutterCore::functionAt(unsigned long long)':
cutter.cpp:(.text+0x40a1): undefined reference to `r_anal_get_fcn_in'
CMakeFiles/cutter.dir/cutter.cpp.o:(.data+0x88): undefined reference to `r_crypto_version'
CMakeFiles/cutter.dir/cutter.cpp.o:(.data+0xe8): undefined reference to `r_magic_version'
collect2: error: ld returned 1 exit status
make[2]: *** [cutter] Error 1
make[1]: *** [CMakeFiles/cutter.dir/all] Error 2
make: *** [all] Error 2

**Seems like a linking error to me, so tried various methods
I've already purged radare2(one which is available from Ubuntu repositories)
C/C++ Compiler: gcc-7.1 
OS : Ubuntu 14.04
Kernel: 4.4.0-104-generic**

**Comment by ishitatsuyuki** [comment]
Please code-format your comment.

**Comment by codedJaguar12** [comment]
<div style="background: #ffffff; overflow:auto;width:auto;border:solid gray;border-width:.1em .1em .1em .8em;padding:.2em .6em;"><pre style="margin: 0; line-height: 125%">CMakeFiles/cutter.dir/cutter.cpp.o: In <span style="color: #008800; font-weight: bold">function </span>CutterCore::sdbList<span style="color: #333333">(</span>QString<span style="color: #333333">)</span><span style="background-color: #fff0f0">&#39;: cutter.cpp:(.text+0x4e7): undefined reference tosdb_ns_path&#39;</span>
CMakeFiles/cutter.dir/cutter.cpp.o: In <span style="color: #008800; font-weight: bold">function </span>CutterCore::sdbListKeys<span style="color: #333333">(</span>QString<span style="color: #333333">)</span><span style="background-color: #fff0f0">&#39;: cutter.cpp:(.text+0x679): undefined reference tosdb_ns_path&#39;</span>
cutter.cpp:<span style="color: #333333">(</span>.text+0x6a5<span style="color: #333333">)</span>: undefined reference to sdb_foreach_list<span style="background-color: #fff0f0">&#39; CMakeFiles/cutter.dir/cutter.cpp.o: In functionCutterCore::sdbGet(QString, QString)&#39;</span>:
cutter.cpp:<span style="color: #333333">(</span>.text+0x807<span style="color: #333333">)</span>: undefined reference to sdb_ns_path<span style="background-color: #fff0f0">&#39; cutter.cpp:(.text+0x854): undefined reference tosdb_const_get&#39;</span>
CMakeFiles/cutter.dir/cutter.cpp.o: In <span style="color: #008800; font-weight: bold">function </span>CutterCore::sdbSet<span style="color: #333333">(</span>QString, QString, QString<span style="color: #333333">)</span><span style="background-color: #fff0f0">&#39;: cutter.cpp:(.text+0x965): undefined reference tosdb_ns_path&#39;</span>
CMakeFiles/cutter.dir/cutter.cpp.o: In <span style="color: #008800; font-weight: bold">function </span>CutterCore::cmd<span style="color: #333333">(</span>QString const&amp;<span style="color: #333333">)</span><span style="background-color: #fff0f0">&#39;: cutter.cpp:(.text+0xd30): undefined reference tor_mem_free&#39;</span>
CMakeFiles/cutter.dir/cutter.cpp.o: In <span style="color: #008800; font-weight: bold">function </span>CutterCore::cmdj<span style="color: #333333">(</span>QString const&amp;<span style="color: #333333">)</span><span style="background-color: #fff0f0">&#39;: cutter.cpp:(.text+0x10f4): undefined reference tor_mem_free&#39;</span>
cutter.cpp:<span style="color: #333333">(</span>.text+0x1269<span style="color: #333333">)</span>: undefined reference to r_mem_free<span style="background-color: #fff0f0">&#39; CMakeFiles/cutter.dir/cutter.cpp.o: In functionCutterCore::loadFile(QString, unsigned long, unsigned long, bool, int, int, bool, QString const&amp;)&#39;</span>:
cutter.cpp:<span style="color: #333333">(</span>.text+0x14f3<span style="color: #333333">)</span>: undefined reference to r_bin_force_plugin<span style="background-color: #fff0f0">&#39; CMakeFiles/cutter.dir/cutter.cpp.o: In functionCutterCore::tryFile(QString, bool)&#39;</span>:
cutter.cpp:<span style="color: #333333">(</span>.text+0x2908<span style="color: #333333">)</span>: undefined reference to sdb_bool_set<span style="background-color: #fff0f0">&#39; CMakeFiles/cutter.dir/cutter.cpp.o: In functionCutterCore::functionAt(unsigned long long)&#39;</span>:
cutter.cpp:<span style="color: #333333">(</span>.text+0x40a1<span style="color: #333333">)</span>: undefined reference to r_anal_get_fcn_in<span style="background-color: #fff0f0">&#39; CMakeFiles/cutter.dir/cutter.cpp.o:(.data+0x88): undefined reference tor_crypto_version&#39;</span>
CMakeFiles/cutter.dir/cutter.cpp.o:<span style="color: #333333">(</span>.data+0xe8<span style="color: #333333">)</span>: undefined reference to <span style="background-color: #fff0f0">`</span>r_magic_version<span style="color: #FF0000; background-color: #FFAAAA">&#39;</span>
collect2: error: ld returned 1 <span style="color: #007020">exit </span>status
make<span style="color: #333333">[</span>2<span style="color: #333333">]</span>: *** <span style="color: #333333">[</span>cutter<span style="color: #333333">]</span> Error 1
make<span style="color: #333333">[</span>1<span style="color: #333333">]</span>: *** <span style="color: #333333">[</span>CMakeFiles/cutter.dir/all<span style="color: #333333">]</span> Error 2
make: *** <span style="color: #333333">[</span>all<span style="color: #333333">]</span> Error 2
</pre></div>

**Comment by codedJaguar12** [comment]
This is after last stage  [**100%] Linking CXX executable cutter**

**Seems like a linking error to me, so tried various methods
I've already purged radare2(one which is available from Ubuntu repositories)
C/C++ Compiler: gcc-7.1
OS : Ubuntu 14.04
Kernel: 4.4.0-104-generic**

**Comment by Maijin** [comment]
What is output of r2 -v and r2 -V

**Comment by codedJaguar12** [comment]
r2 -V Output
<div style="background: #ffffff; overflow:auto;width:auto;border:solid gray;border-width:.1em .1em .1em .8em;padding:.2em .6em;"><pre style="margin: 0; line-height: 125%">2.1.0-197-gd6e0b60  r2
2.1.0-197-gd6e0b60  r_anal
2.1.0-197-gd6e0b60  r_lib
2.1.0-197-gd6e0b60  r_egg
2.1.0-197-gd6e0b60  r_asm
2.1.0-197-gd6e0b60  r_bin
2.1.0-197-gd6e0b60  r_cons
2.1.0-197-gd6e0b60  r_flag
2.1.0-197-gd6e0b60  r_core
2.1.0-197-gd6e0b60  r_crypto
2.1.0-197-gd6e0b60  r_bp
2.1.0-197-gd6e0b60  r_debug
2.1.0-197-gd6e0b60  r_hash
2.1.0-197-gd6e0b60  r_fs
2.1.0-197-gd6e0b60  r_io
2.1.0-197-gd6e0b60  r_magic
2.1.0-197-gd6e0b60  r_parse
2.1.0-197-gd6e0b60  r_reg
2.1.0-197-gd6e0b60  r_sign
2.1.0-197-gd6e0b60  r_search
2.1.0-197-gd6e0b60  r_syscall
2.1.0-197-gd6e0b60  r_util
</pre></div>

**Comment by codedJaguar12** [comment]
r2 -v Output

<div style="background: #ffffff; overflow:auto;width:auto;border:solid gray;border-width:.1em .1em .1em .8em;padding:.2em .6em;"><pre style="margin: 0; line-height: 125%">radare2 2.2.0-git 16809 @ linux-x86-64 git.2.1.0-197-gd6e0b60
commit: d6e0b606c79e777f7f28e015c4e85e68282df7f8 build: 2017-12-25__20:29:21
</pre></div>

**Comment by Maijin** [comment]
That doesn't look like the version of the submodule.

**Comment by codedJaguar12** [comment]
but I've built it twice with
<div style="background: #ffffff; overflow:auto;width:auto;border:solid gray;border-width:.1em .1em .1em .8em;padding:.2em .6em;"><pre style="margin: 0; line-height: 125%">git submodule init radare2 <span style="color: #333333">&amp;&amp;</span> git submodule update radare2
<span style="color: #007020">cd </span>radare2 <span style="color: #333333">&amp;&amp;</span> ./sys/install.sh
</pre></div>

**Comment by codedJaguar12** [comment]
You were right here is the new output for r2 -V
<div style="background: #ffffff; overflow:auto;width:auto;border:solid gray;border-width:.1em .1em .1em .8em;padding:.2em .6em;"><pre style="margin: 0; line-height: 125%">2.2.0  r2
2.2.0  r_anal
2.2.0  r_lib
2.2.0  r_egg
2.2.0  r_asm
2.2.0  r_bin
2.2.0  r_cons
2.2.0  r_flag
2.2.0  r_core
2.2.0  r_crypto
2.2.0  r_bp
2.2.0  r_debug
2.2.0  r_hash
2.2.0  r_fs
2.2.0  r_io
2.2.0  r_magic
2.2.0  r_parse
2.2.0  r_reg
2.2.0  r_sign
2.2.0  r_search
2.2.0  r_syscall
2.2.0  r_util
</pre></div>

**Comment by codedJaguar12** [comment]
and Output for r2 -v

<div style="background: #ffffff; overflow:auto;width:auto;border:solid gray;border-width:.1em .1em .1em .8em;padding:.2em .6em;"><pre style="margin: 0; line-height: 125%">radare2 2.2.0 16809 @ linux-x86-64 git.2.2.0
commit: 27f4c38292f7e8e51a1049362d4f01ac7bb0ee73 build: 2017-12-25__21:32:38
</pre></div>

**Comment by codedJaguar12** [comment]
But error message is same, but the version is correct now

**Comment by xarkes** [comment]
What platform and arch?

**Comment by codedJaguar12** [comment]
Ubuntu 14.04 x86-64

**Comment by xarkes** [comment]
Hard to debug, try the troubleshooting section in the README and check that the shared libs contains the symbol it is looking for (e.g. with nm)

**Comment by codedJaguar12** [comment]
Ok...I will try

**Comment by codedJaguar12** [comment]
@xarkes ok I will try

**Comment by codedJaguar12** [comment]
@xarkes yes I checked each of the undefined symbol , they are all present in respective shared object file.

**Comment by xarkes** [comment]
Did you try cleaning everything and rebuilding?

**Comment by codedJaguar12** [comment]
@xarkes yes I already did git clone at least 3 times , each try with clean configuration, but no success

**Comment by Maijin** [comment]
Did you autoclean, autoremove via apt-get etc., checked the pkg-config that are on your system etc. ?

**Comment by Maijin** [comment]
Why don't you use the linux AppImage we provide in the release section of this github repository btw?

**Comment by codedJaguar12** [comment]
@Maijin I will try

**Comment by codedJaguar12** [comment]
Just deleted libs of radare from /usr , and did a fresh install now everything is working fine.

**Comment by xarkes** [comment]
Ok thanks.
