### ISSUE TITLE
The content of the Parsing tab in Hexdump should be Read-Only

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/cutter#2431]
**Environment information**
* Operating System: Any
* Cutter version: 1.12.0 master ad66718f375b013a3021e531891c71082ee48867
* Obtained from:
  - [x] Built from source
* File format: Any

**Describe the bug**

The "Parsing" tab in the hexdump view should be read-only as it only parses the selected bytes into different formats. Currently, the text box is editable and this can be confusing as people might think it can be used to patch bytes.

**To Reproduce**

The following gif demonstrates how to reproduce this issue.

1. Open a binary in Cutter
2. Open the Hexdump widget
3. Make sure that the sidebar is opened and "Parsing" tab is selected
4. Select few bytes in the Hex view
5. Choose the text box in the sidebar and start modifying the content shown

![Peek 2020-09-26 11-27](https://user-images.githubusercontent.com/20182642/94336345-2fa59680-ffeb-11ea-854f-1491a82dc602.gif)

**Expected behavior**

The text box should be read-only

**Comment by hexagr** [comment]
Looking into this. QT supports read-only features including comboboxes. Will submit a PR when I get a successful build.

**Comment by hexagr** [comment]
I've just submitted a PR to make the parsing tab in the hexdump widget read-only.

**Comment by cctechwiz** [comment]
This issue appears to have been resolved in PR #2434, looks like it can be closed.

**Comment by ITAYC0HEN** [comment]
Good catch, thank you!
