### ISSUE TITLE
Ghidra Decompiler Error: Deleting integrated varnode

### ISSUE THREAD

**Issue by TheProgramableTurtle** [radareorg/cutter#2445]
**Environment information**
* Operating System: Windows 10 19041
* Cutter version: 1.10.3
* Obtained from:
  - [ ] Built from source
  - [x] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format:
mach064
**Describe the bug**
When trying to decompile some functions, the ghidra decompiler gives the error
`// Ghidra Decompiler Error: Deleting integrated varnode`

**To Reproduce**

1. Go to the decompiler window.
2. Select ghidra decompiler.
3. Click refresh.
4. See error.

**Expected behavior**
The decompiler would decompile the function as it does with some other functions.

**Screenshots**

![image](https://user-images.githubusercontent.com/44685118/95686155-1fe59f00-0bf4-11eb-9dd6-711013f6d5c3.png)

**Additional context**
The file I am using is a UnityFramework binary from an iOS app.

**Comment by karliss** [comment]
1.10.3 is an old version. Please try with latest Cutter version first.

**Comment by TheProgramableTurtle** [comment]
Works with 1.12.0 (gives a load of other errors but they don't seem important). The callgraphs are very useful, I'll try to stay up to date from now on.
