### ISSUE TITLE
No theme for the following widgets:

### ISSUE THREAD

**Issue by radare** [radareorg/cutter#245]
* [ ] console
* [ ] notepad
* [ ] sections
* [ ] symbols
* [ ] functions
* [ ] ...

**Comment by xarkes** [comment]
Do you mean that kind of theme? https://github.com/radareorg/cutter/issues/130
We did not take a decision about it.

**Comment by xarkes** [comment]
Fixed in https://github.com/radareorg/cutter/commit/d878e5055e45991466337e592229394e7ba808f8
