### ISSUE TITLE
MacOS "LSOpenURLsWithRole() failed with error -10810"

### ISSUE THREAD

**Issue by wangtsiao** [radareorg/cutter#2456]
**Environment information**
* Operating System:
MacOS Catalina 10.15.7
* Cutter version:
v1.12.0
* Obtained from:
https://cutter.re/
  - [ ] Built from source
  - [x] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format:

**Describe the bug**

Cutter can't be opend, when "open /Applications/Cutter.app" , it gives error with " LSOpenURLsWithRole() failed with error -10810."

**Screenshots**

![image](https://user-images.githubusercontent.com/70847926/97153706-e3966f00-17ad-11eb-98a0-246616cda869.png)

**Comment by wangtsiao** [comment]
brew install gettext

**Comment by karliss** [comment]
Duplicate of https://github.com/radareorg/cutter/issues/2428
