### ISSUE TITLE
Versions 1.1 still says 1.0 in "About" menu

### ISSUE THREAD

**Issue by mehdideveloper** [radareorg/cutter#256]
I just downloaded Cutter 1.1 for Mac OS X.
It still says "1.0" on the About dialog.
Here's a screenshot:

<img width="477" alt="screen shot 2017-12-26 at 8 18 35 pm" src="https://user-images.githubusercontent.com/12119776/34363182-fdcc48f4-ea79-11e7-9537-b2f45f801a0e.png">

**Comment by Maijin** [comment]
Already fixed in the dev.
CC @xarkes may want to release again idk.

**Comment by xarkes** [comment]
Yes I should do it to avoid further misunderstanding but I do not have the
time right now.
