### ISSUE TITLE
Import functions are not correctly detected

### ISSUE THREAD

**Issue by xarkes** [radareorg/cutter#258]
![image](https://user-images.githubusercontent.com/10772605/34385410-18683d90-eb3c-11e7-8f9f-56e0f8b8a940.png)

**Comment by radare** [comment]
maybe this is because of the autonaming because ppl uses aaaaaaa :P

e anal.autoname=false

**Comment by xarkes** [comment]
No the current detection is not based on the function name.

**Comment by Maijin** [comment]
That has nothing to do with autoname...

**Comment by xarkes** [comment]
Also I am wondering if imports should appear in the function panel. It seems this is not the case currently, just check the imports list versus functions list

**Comment by Maijin** [comment]
? Wat

**Comment by xarkes** [comment]
Fixed while updating radare2.
