### ISSUE TITLE
Loading a PDB replace the current bin by the pdb 

### ISSUE THREAD

**Issue by Maijin** [radareorg/cutter#26]
Loading a PDB replace the current bin by the pdb 

![image](https://user-images.githubusercontent.com/1408600/31056696-490c7f6a-a6d6-11e7-82a3-8615de294020.png)

**Comment by thestr4ng3r** [comment]
I'm confused right now. It's somehow related to `idp pdb-filename` calling `idpi* pdb-filename` which loads the file with `r_core_bin_load()` at https://github.com/radare/radare2/blob/dd12780f265596e08b7af05d8496d49fee26482f/libr/core/cmd_info.c#L578

**Comment by thestr4ng3r** [comment]
Also I've noticed calling `idp` or `idpi*` with a filename in r2 works normally, but calling `idpi*` without specifying a filename breaks the bin information too.

**Comment by thestr4ng3r** [comment]
Related to https://github.com/radareorg/cutter/blob/05982b1304ac131dbf3057ff54d8d1eddd40599c/src/cutter.cpp#L462 being commented out.
Otherwise, the RCoreFile will be loaded twice and that somehow causes `idpi* filename` to overwrite the info.
