### ISSUE TITLE
Makefile:458: recipe for target 'cutter' failed

### ISSUE THREAD

**Issue by cegi** [radareorg/cutter#261]
I had managed to make Cutter work, but after a recent update on Debian Linux, i can't build it anymore. Tried with Qmake here's the error when using "make" (the last lines ) : 

**lr_fs -lr_crypto -lmagic -lcapstone -lQt5Svg -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
/usr/bin/ld: cutter.o: undefined reference to symbol 'r_magic_version'
//usr/lib/x86_64-linux-gnu/libr_magic.so.2.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:458: recipe for target 'cutter' failed
make: *** [cutter] Error 1**

And when using Cmake i get this when using "make" ;

**[ 98%] Building CXX object CMakeFiles/cutter.dir/cutter_autogen/EWIEGA46WW/qrc_resources.cpp.o
[100%] Linking CXX executable cutter
/usr/bin/ld: CMakeFiles/cutter.dir/cutter.cpp.o: undefined reference to symbol 'r_magic_version'
//usr/lib/x86_64-linux-gnu/libr_magic.so.2.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/cutter.dir/build.make:1554: recipe for target 'cutter' failed
make[2]: *** [cutter] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/cutter.dir/all' failed
make[1]: *** [CMakeFiles/cutter.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2**

I installed the same dependencies i needed and that i used to make it work last time, so i don't know what the problem is, any help appreciated.

**Comment by rohan-0100010110010100** [comment]
Check Troubleshooting in README.md

**Comment by cegi** [comment]
Thanks, but i'm on Linux Debian, the troubleshooting is only for MacOS. I think the issue comes from dependencies, i'm missing libraries, but i don't know which.

**Comment by Maijin** [comment]
That:

If you encounter the Project ERROR: r_core development package not found try this command instead PKG_CONFIG_PATH=$HOME/bin/prefix/radare2/lib/pkgconfig qmake

is not mac OS only.

**Comment by cegi** [comment]
Yes i misread, that line is not for MacOS, however it did not fix the problem i have.

**Comment by xarkes** [comment]
Paste the commands you typed (with the environment variable)

**Comment by cegi** [comment]
It's written on my first post, i just followed the steps on README.
If you talk about the Project ERROR, i don't have that error, and i have used : **sudo PKG_CONFIG_PATH=$HOME/bin/prefix/radare2/lib/pkgconfig qmake ../src** inside "cutter/build"
and **sudo make**    i used sudo because otherwise i get permission issue and it can't finish the process.

**Comment by xarkes** [comment]
I'm unsure about that environment variable, could you try with
```
export PKG_CONFIG_PATH=...
qmake ../src
```

On Dec 29, 2017 7:08 PM, "cegi" <notifications@github.com> wrote:

It's written on my first post, i just followed the steps on README.
If you talk about the Project ERROR, i don't have that error, and i have
used : *sudo PKG_CONFIG_PATH=$HOME/bin/prefix/radare2/lib/pkgconfig qmake
../src* inside "cutter/build"
and *sudo make* i used sudo because otherwise i get permission issue and it
can't finish the process.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/radareorg/cutter/issues/261#issuecomment-354480307>,
or mute
the thread

**Comment by cegi** [comment]
With your command i get : **Unable to generate makefile for: ../src/cutter.pro
make: *** No targets specified and no makefile found.  Stop.**

I need sudo almost everywhere, it's a tight computer.

**Comment by Maijin** [comment]
Isn't the AppImage working ?

**Comment by Maijin** [comment]
https://github.com/radareorg/cutter/releases

**Comment by cegi** [comment]
It does, and flawlessly, just wanted to build it myself but couldn't, so i will use the AppImage instead. Thanks for the help.
