### ISSUE TITLE
inconsistent version numbers

### ISSUE THREAD

**Issue by jnbr** [radareorg/cutter#262]
version numbers here: https://github.com/radareorg/cutter/blob/0ebd34370bcaed00000168147572bb78106eeab1/src/cutter.pro#L6
and here:
https://github.com/radareorg/cutter/blob/0ebd34370bcaed00000168147572bb78106eeab1/src/CMakeLists.txt#L7
do not match the current release.

**Comment by xarkes** [comment]
Yes I'm sorry I forgot it while releasing and I didn't take the time to modifiy it.

**Comment by xarkes** [comment]
https://github.com/radareorg/cutter/commit/8b52c66f4f0091cd9d97389b32aa519c2c602e2b
