### ISSUE TITLE
Cutter is not saving flags to project file

### ISSUE THREAD

**Issue by OhioDuckFarmer** [radareorg/cutter#263]
I am seeing an issue where when a project is saved to a project file (either from the file save command or from the issuing of Ps at the cli window) any flag I have defined (either from within the disassembly window or the cli window) is not being saved to the project file.  If I exit out of cutter and repeat the same test using just r2 then the flags are being saved to the rc file.

The steps that I used to reproduce this issue are:
```
$> dd if=/dev/zero of=./testfile.bin bs=1 count=1024
$> cutter ./testfile.bin
...
Disable Analysis

either:
  Switch to disassembly window
  Right click on address 0x00000000
  Select Add Flag
  Create Flag with flagname: testflag and size of 1
  Save file (using Ctrl+s) to testprj

or:
  Switch to the cli window
  Seek to address 0x0
  f testflag
  Save project file using Ps testprj

Exit cutter (using Ctrl+q) and select save
Edit the testprj/rc file and search for the string 'testflag' (which will not show up)
```
NOTE:  It does not make a difference if you specify the flag length of 1 or the actual number of characters in the flag string

Now if I use the r2 which I installed/updated during my installation/update of cutter and perform the same task my newly created flag (testflag) will be in the rc file.

The version information is as follows:
```
$>cutter -v
cutter 1.0-dev

$>r2 -v
radare2 2.2.0-git 16809 @ linux-x86-64 git.2.1.0-197-gd6e0b60
commit: d6e0b606c79e777f7f28e015c4e85e68282df7f8 build: 2017-12-28__07:06:47
```

**Comment by thestr4ng3r** [comment]
Did you test in r2 with `prj.simple` enabled? Cutter uses that by default.

**Comment by OhioDuckFarmer** [comment]
No, I have not tested with the prj.simple enabled.  I will give that a try and post my results

**Comment by xarkes** [comment]
We are still waiting for your results :)

**Comment by Maijin** [comment]
I think we can close until further notice

**Comment by OhioDuckFarmer** [comment]
Ah man.......Life got the best of me and this slipped past me.  I will get this done this weekend as I am at work now.  Sorry!

**Comment by OhioDuckFarmer** [comment]
I just went back through the reproduction instructions and with prj.simple enabled the issue is still there; however, if I de-select the prj.simple option the problem goes away (as shown by the below clippings of the testprj2.rc file).
   ```
   # r2 rdb project file
   # flags
   fs *
   f testflag2 1 0x00000000
   ```

**Comment by xarkes** [comment]
Ok so this is not an issue an can be closed. Thanks for confirming. We will make prj.simple disabled by default eventually.

**Comment by nonchip** [comment]
so 2 years later this "non-issue" is still an issue and the "recommended" `prj.simple` setting just ate 80% of my work...
