### ISSUE TITLE
Refresh graph after changing immediate base

### ISSUE THREAD

**Issue by pelijah** [radareorg/cutter#265]

**Comment by xarkes** [comment]
I think this is more complex than just refreshing the graph. I believe `agj` command does not expose the immediate base, which is why this remains always the same.

**Comment by Maijin** [comment]
I think @thestr4ng3r is working on `agJ`

**Comment by xarkes** [comment]
Fixed since we use agJ https://github.com/radareorg/cutter/commit/c99fff72fc8140cfcc749629c1186f19f37abe55
