### ISSUE TITLE
"Quick Filter" option for strings?

### ISSUE THREAD

**Issue by xsubliminalx** [radareorg/cutter#267]
I'm sorry if this isn't a real issue, but I'm wondering if such a feature exists within Cutter. I know you can use quick filter for functions but can't seem to figure out how to do this for strings. If this isn't a feature already can I request that it be added? Scrolling through thousands of lines of assembly is quite tiring especially if you're trying to search for a single line of code.

**Comment by Maijin** [comment]
It's already there in the dev version here was the fix https://github.com/radareorg/cutter/commit/0ebd34370bcaed00000168147572bb78106eeab1 (2 lines)

**Comment by xsubliminalx** [comment]
Where can I download the dev version? I don't see it in the releases tab.

**Comment by Maijin** [comment]
You have to build it yourself, or just wait for the next release.
