### ISSUE TITLE
Official Cutter v1.1 release for Win32/Win64 does not include all radare2 arch

### ISSUE THREAD

**Issue by bvernoux** [radareorg/cutter#276]
Official Cutter v1.1 release for Win32/Win64 does not include all radare2 arch
Link: https://github.com/radareorg/cutter/releases/tag/v1.1
Especially the arch avr is not included I have not checked other arch but maybe other are missing to

**Comment by xarkes** [comment]
Yes many are missing too, I'll check later for this specific one.

**Comment by xarkes** [comment]
Since this is a known issue I'm closing it. Please refer to this issue: https://github.com/radare/radare2/issues/8950
