### ISSUE TITLE
Add endianness option

### ISSUE THREAD

**Issue by Maijin** [radareorg/cutter#277]
Add endianness option in advanced options next to bits.
Also to be added in Preferences-> Disassembly

**Comment by thestr4ng3r** [comment]
Endianness option is now available in OptionsDialog.

**Comment by Maijin** [comment]
The endianess is also used for display only (see even the eval is under scr. and not anal.) , we need to ensure that this doesn't make people analysis twice if it's just for changing endianess otherwise it could have bad feedbacks

**Comment by Maijin** [comment]
I say for now this should be enough.

**Comment by thestr4ng3r** [comment]
> The endianess is also used for display only

Is it? It's under cfg., not scr. Also, @radare wrote this on Telegram:

> What will analyze if the endian is wrong :D

**Comment by Maijin** [comment]
sorry cfg* you're right my bad
