### ISSUE TITLE
[QUESTION] How can I tell Cutter to use the SnowMan decompiler?

### ISSUE THREAD

**Issue by joxeankoret** [radareorg/cutter#279]
Just what the title says: how can I tell Cutter to use SnowMan for the "Pseudocode" tab?

**Comment by xarkes** [comment]
You can't for now.

**Comment by Maijin** [comment]
You can use it with the console though.

**Comment by joxeankoret** [comment]
Is it already possible?

**Comment by Maijin** [comment]
You can use it with the console

**Comment by Maijin** [comment]
so yes

**Comment by joxeankoret** [comment]
Being able to use it in the console is not what people want, but anyway.

**Comment by Maijin** [comment]
For the plugin it's already tracked the same way as the retdec is done

**Comment by xarkes** [comment]
Cutter does not have a decent plugin management system for now so it cannot be shown in a widget for now. It will come some day, but there are many things to do before that.

**Comment by joxeankoret** [comment]
I will check Cutter again when there is support for this. Thanks!

**Comment by joxeankoret** [comment]
With due respect: why would I implement something when I have a tool with it implemented already and fully working?

**Comment by Maijin** [comment]
Let's stop at "I will check Cutter again when there is support for this. Thanks!"
