### ISSUE TITLE
hex panel disappears when resizing panel

### ISSUE THREAD

**Issue by gingerbeardman** [radareorg/cutter#281]
![screen shot 2018-01-24 at 10 57 56](https://user-images.githubusercontent.com/49612/35328838-95428cca-00f5-11e8-8718-f9326e65e0aa.png)

See video: https://transfer.sh/qbcYP/cutter-hex-vanish.mov

**Comment by xarkes** [comment]
I cannot reproduce this bug, maybe was it fixed while I reworked a bit the Hexdump widget?

**Comment by gingerbeardman** [comment]
Yes, it no longer happens (tested 1.2 release)

**Comment by xarkes** [comment]
Ok great, thanks for confirming.
