### ISSUE TITLE
zero-byte binary saved in project directory

### ISSUE THREAD

**Issue by gingerbeardman** [radareorg/cutter#282]
1. load binary
2. analyse
3. wait for it to open
4. save
5. check "save the target binary inside the project directory (prj.files)"
6. inspect size of binary in project directory

**Comment by xarkes** [comment]
This is more likely a radare2 bug.

**Comment by xarkes** [comment]
```
TODO: prj.files: support copying more than one file into the project directory
cp: cannot stat '': No such file or directory
Warning: Cannot copy '' into '/home/antide/.config/radare2/projects/projectL/bin/'
```
Output from r2 when using `e prj.files = true`

**Comment by ITAYC0HEN** [comment]
@gingerbeardman is this problem still occurs on latest Cutter from master?
I can't reproduce, maybe it was already fixed in radrare2

**Comment by gingerbeardman** [comment]
Yes, it's fixed! Not sure when that happened.

Closing

**Comment by ITAYC0HEN** [comment]
Thank you! :)
