### ISSUE TITLE
Double cutter window title and input too small

### ISSUE THREAD

**Issue by radare** [radareorg/cutter#290]
<img width="1059" alt="screen shot 2018-01-31 at 02 11 30" src="https://user-images.githubusercontent.com/917142/35600033-1f4617e4-062c-11e8-9991-7ef55ee3495e.png">

**Comment by radare** [comment]
Tab titles cant be read

**Comment by thestr4ng3r** [comment]
The double title bar is macOS's application tab bar. Did it appear by default for you? I could only see it after manually enabling it:
![showtabbar](https://user-images.githubusercontent.com/1460997/35770848-89d9a59a-0923-11e8-9608-da7f61086b7c.png)

Doesn't seem to be easy to disable in Qt though, without directly accessing Cocoa APIs: http://lists.qt-project.org/pipermail/interest/2016-September/024488.html

**Comment by thestr4ng3r** [comment]
Everything is fixed now except for the global tab bar, which seems impractical to fix.

**Comment by thestr4ng3r** [comment]
https://bugreports.qt.io/browse/QTBUG-61707
