### ISSUE TITLE
macOS open-with doesnt works

### ISSUE THREAD

**Issue by radare** [radareorg/cutter#292]
Finder -> click any file -> right click -> open with -> other application -> enable: all applications -> cutter -> Open

cutter is launched but the open dialog is displayed

**Comment by xarkes** [comment]
Cf https://github.com/radareorg/cutter/issues/236 which is similar.

**Comment by xarkes** [comment]
It'd be nice if anyway who as a Mac could debug and fix this issue as well as the one linked above.

**Comment by marcograss** [comment]
my initial version is here https://github.com/marcograss/cutter/commit/c9bffaa42d332b597e14df232d82ba23a63dfcc4

although I want to test it a little more, also I didn't try yet linux build

covers also #236

**Comment by xarkes** [comment]
Just open a PR, the CI will tell you if it builds on linux or not
