### ISSUE TITLE
Add command console in hexdump widget.

### ISSUE THREAD

**Issue by radare** [radareorg/cutter#295]
Add a 3rd tab in parsing, info... to allow the user to type a command in a small entry and get the output , this will be executed everytime the selection changes.

this can be handy to get base64 encoding , qword formatting, etc

**Comment by xarkes** [comment]
So like the console widget but only for the selected bytes?

**Comment by radare** [comment]
yes

**Comment by xarkes** [comment]
Can't we just imagine a dropdown menu with the different formats you want to show?

**Comment by radare** [comment]
We can name it "Struct" and just use pf as backend. with a combobox to select the structs defined and an entry line to type the pf expression

**Comment by radare** [comment]
See cmd.hexcursor=pf xx in latest r2

**Comment by ITAYC0HEN** [comment]
I think we would be able to give access to the selected bytes through the future API. Something like:
```
bytes = cutter.get_selected_bytes()
```
or
```
cutter.onSelectedBytesChanged(func)
```
So no need for an extra tab in HexWidget.
Moreover, I prefer that Cutter users would have to know zero (or as little as possible) things and commands of radare2 backend

**Comment by ITAYC0HEN** [comment]
I think this can be closed.
I don't want our users to type more r2 commands in another dedicated console.
And as mentioned before, we MUST supply this via API :)
