### ISSUE TITLE
In hexdump add statistical tab

### ISSUE THREAD

**Issue by radare** [radareorg/cutter#302]
Count how many times each byte appears and shows column bars for each byte value count in rows.

**Comment by ITAYC0HEN** [comment]
@trufae - Can you give an example for this? (from radare2 or any other hex editor)

**Comment by ITAYC0HEN** [comment]
Well, while it may be useful for some people, I believe this would not be useful for the majority of current and future Cutter users. This feature should be implemented as a Plugin and shouldn't be in core
