### ISSUE TITLE
Add a button "Version Information" in Dashboard (iVj)

### ISSUE THREAD

**Issue by Maijin** [radareorg/cutter#317]
Add a button "Version Information" in Dashboard that displays the version info (iVj) if version info is here.
Otherwise should show "no version info"

**Comment by Maijin** [comment]
iVj has been implemented by @giuscri, remains integration in cutter 👍

**Comment by xarkes** [comment]
![2018-03-08-090601_653x659_scrot](https://user-images.githubusercontent.com/10772605/37139892-ef13aa96-22af-11e8-966e-9cdfeac95549.png)
Already available here. No need to overload the Dashboard.

**Comment by Abogical** [comment]
@xarkes I think you've misunderstood the issue. `iVj` doesn't show version information of radare, instead it shows the version information of the binary to be reverse engineered itself. This shouldn't be closed.

**Comment by xarkes** [comment]
Yes indeed I read too fast.

**Comment by Abogical** [comment]
Why the need of an extra button? Can't we just show the information directly in the dashboard?

**Comment by Maijin** [comment]
There are way too much information in iVj this will clutter the dashboard thus I think another button is necessary

**Comment by xarkes** [comment]
Done in #468
