### ISSUE TITLE
NewFileDialog and About don't use white logo when dark theme is in use

### ISSUE THREAD

**Issue by ndaprela** [radareorg/cutter#319]
the color of the logo that is used depends on the return value of palette().window().color().value(), it seems that this property isn't set properly for NewFileDialog, at the contrary everything is fine for OptionsDialog.

<img width="451" alt="newfiledialog" src="https://user-images.githubusercontent.com/25092016/36049802-55559638-0de4-11e8-83b9-4156639ed001.png">

<img width="598" alt="optionsdialog" src="https://user-images.githubusercontent.com/25092016/36049805-5b46e3b2-0de4-11e8-9267-9dda4f319a6f.png">

**Comment by Maijin** [comment]
Well can you do a Pull request please.

**Comment by Maijin** [comment]
ping @ndaprela

**Comment by ndaprela** [comment]
`palette().window().color().value()` changes value after that `setWindowFlags(...)` is called, indeed if I comment out `setWindowFlags(...)` in `OptionsDialog::OptionsDialog` the logo doesn't change even in OptionsDialog.
However the values returned by `WindowFlags()` are the same both for NewFileDialog and OptionsDialog before calling setWindowFlags(...) and they change in the same way after calling `setWindowFlags(...)` but for some reason that I'm not aware of the palette().window().color().value() changes only for OptionsDialog.
Maybe something related to how a class or a function is defined that causes problem with inheritance? For example I noticed that there are some differences like the type of this function arguments`OptionsDialog::OptionsDialog(MainWindow *main)` and `NewFileDialog::NewFileDialog(QWidget *parent)`  but I don't know if this is how it is supposed to be or a mistake, I tried to play a bit with these but without succesfully solving the issue.

**Comment by xarkes** [comment]
Those are "mistakes" at first every widget needed MainWindow as a parameter but now not anymore, maybe OptionsDialog is the last one.
Anyway just do as it is done in the OptionsDialog:
```

**Comment by ndaprela** [comment]
That is already implemented also in `NewFileDialog::NewFileDialog` but it doesn't work because `palette().window().color().value()` doesn't change when `setWindowFlags(...)` is called so it returns the same value as in the normal theme.

**Comment by xarkes** [comment]
Hmm weird because the theme looks correctly loaded.

**Comment by ndaprela** [comment]
Yeah. I thought that maybe OptionsDialog is inheriting the palette from something while NewFileDialog doesn't, or that something is missing in the dark theme.
What I can say is that the moment where the behaviours of the two dialogs differ is when `palette().window().color().value()` changes after calling `setWindowFlags(windowFlags() & (~Qt::WindowContextHelpButtonHint))` for one and not the other, but I can't understand why.

**Comment by xarkes** [comment]
Using the Configuration rather than computing it makes more sense. Fixed.
