### ISSUE TITLE
Patch/Assemble instructions

### ISSUE THREAD

**Issue by shawnanastasio** [radareorg/cutter#331]
It would be nice to have the ability to directly assemble instructions and patch them into an existing binary.

I believe radare2 already includes an assembler, so I'm not sure how difficult this would be.

**Comment by xarkes** [comment]
Editing instructions has been recently added to Cutter. You can try it by cloning the repo and compiling it yourself.

**Comment by shawnanastasio** [comment]
Good to hear! Thanks.
