### ISSUE TITLE
"Cutter" capitalization in desktop vs installed binary name

### ISSUE THREAD

**Issue by dtzWill** [radareorg/cutter#333]
Capitalization was changed in https://github.com/radareorg/cutter/commit/bcba36a53d678a6c48c00c7e71f1c17de46383f1 but the ".desktop" still tries to execute using lower-case name:

https://github.com/radareorg/cutter/blob/master/src/cutter.desktop#L4

(https://github.com/radareorg/cutter/blob/v1.2/src/cutter.desktop in 1.2, for what it's worth)

As a result "Cutter" fails to launch on systems that are case-sensitive (Linux).

**Comment by Maijin** [comment]
@dtzWill Did you try editing with https://help.github.com/articles/editing-files-in-your-repository/ ?

**Comment by dtzWill** [comment]
I, erm, did not try that no.  But patching my local copy did fix the problem :).  Just reporting as something I thought you folks (upstream) would like to be aware of so the minor fix could be made and included in next release.

**Comment by xarkes** [comment]
He was just saying that manually editing would have created a PR and taken less time than opening your issue :p
Thanks for reporting!

**Comment by dtzWill** [comment]
Ha! Okay well duly noted, anyway feel free to make the change on my behalf--or let me know if a PR would be preferred :).

**Comment by xarkes** [comment]
Don't worry I'll fix tomorrow.

**Comment by xarkes** [comment]
(And yes PR are preferred :p)
