### ISSUE TITLE
Discrepancy between Cutter and Radare2 in terminal

### ISSUE THREAD

**Issue by cclassic** [radareorg/cutter#335]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch Linux / x86 / 64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| Cutter and r2 version, See About Cutter (mandatory)         | radare2 2.4.0 9c12c4fe2021fb035797e474c94a9a05c62522c7 / Version 1.2 (using 2.2.0-502-g9c12c4fe2) 0e9be6343b60b2725b3a07b171df55e10a22e933
| Show version information **full output** (See About Cutter) in a pastebin document (mandatory) | https://gist.github.com/cclassic/7cb9bfba8d52523dfbac9287553f2a77

### Expected behavior
By using "af <name> <addr>" a single function will be analyzed.

### Actual behavior
Many functions, including the supplied one, are analyzed.

### Steps to reproduce the behavior 
Open the supplied test binary (r2test) in radare2 (no other args) and cutter (disable Analyze checkbox). Enter the following commands:
```
af foo 0x000005fb
pd @ 0x000005fb
```
Notice how the cutter log has also detected functions after the supplied one.

### Additional Logs, screenshots, source-code,  configuration dump, ...
[test-binary.zip](https://github.com/radareorg/cutter/files/1738484/test-binary.zip)

Output from cutter:
```
[0x000005b0]> pd @ 0x000005fb

/           0x000005fb      (fcn) fcn.foo 23
|   fcn.foo ();
|           0x000005fb           ; var int local_4h @ rbp-0x4
|           0x000005fb           mov  rbp, rsp
|           0x000005fe           mov  dword [local_4h], edi
|           0x00000601           movzx eax, byte str.hello            ; [0x201028:1]=104 ; "hello"
|           0x00000608           movsx edx, al
|           0x0000060b           mov  eax, dword [local_4h]
|           0x0000060e           add  eax, edx
|           0x00000610           pop  rbp
\           0x00000611           ret
/           0x00000612      (fcn) fcn.00000612 24
|   fcn.00000612 ();
|           0x00000612           ; var int local_4h @ rbp-0x4
|           0x00000612           push rbp
|           0x00000613           mov  rbp, rsp
|           0x00000616           mov  dword [local_4h], edi
|           0x00000619           movzx eax, byte [0x00201029]         ; [0x201029:1]=101
|           0x00000620           movsx edx, al
|           0x00000623           mov  eax, dword [local_4h]
|           0x00000626           add  eax, edx
|           0x00000628           pop  rbp
\           0x00000629           ret
/           0x0000062a      (fcn) fcn.0000062a 24
```

Output from radare2:
```
[0x000004f0]> pd @ 0x000005fb
/ (fcn) fcn.foo 23
|   fcn.foo ();
|           ; var int local_4h @ rbp-0x4
|           0x000005fb      4889e5         mov rbp, rsp
|           0x000005fe      897dfc         mov dword [local_4h], edi
|           0x00000601      0fb605200a20.  movzx eax, byte str.hello   ; [0x201028:1]=104 ; "hello"
|           0x00000608      0fbed0         movsx edx, al
|           0x0000060b      8b45fc         mov eax, dword [local_4h]
|           0x0000060e      01d0           add eax, edx
|           0x00000610      5d             pop rbp
\           0x00000611      c3             ret
            0x00000612      55             push rbp
            0x00000613      4889e5         mov rbp, rsp
            0x00000616      897dfc         mov dword [rbp - 4], edi
            0x00000619      0fb605090a20.  movzx eax, byte [0x00201029] ; [0x201029:1]=101
            0x00000620      0fbed0         movsx edx, al
            0x00000623      8b45fc         mov eax, dword [rbp - 4]
            0x00000626      01d0           add eax, edx
            0x00000628      5d             pop rbp
            0x00000629      c3             ret
            0x0000062a      55             push rbp
```

**Comment by xarkes** [comment]
Might be somehow related to https://github.com/radareorg/cutter/issues/341

**Comment by xarkes** [comment]
So this had to do with `anal.hasnext` which was set to true by default, unlike radare2 which sets it to false.
I've set the value to false by default to reflect radare2 behaviour, if you want to change it there's an option in advanced analyses.

**Comment by xarkes** [comment]
Feel free to reopen if this doesn't fix the issue for you.
