### ISSUE TITLE
Simplify readme, oneliner instructions to build

### ISSUE THREAD

**Issue by radare** [radareorg/cutter#336]
Ideally we should provide a shellscript or makefile to do all those steps in just 1 line. To build it on mac with brew i followed these steps:

```
brew install qt5
export PATH="/usr/local/opt/qt/bin:$PATH"
mkdir -p build ; qmake ../src ; make -j12
cp -rf Cutter.app /Applications
```

**Comment by JulioSDDR** [comment]
Cutter has its own pacman package so arch users can just :
`pacman -S radare2-cutter`

If you want the git version, you have to go to the aur and use something like:
`yay -S radare2-cutter-git`

**Comment by xarkes** [comment]
Thanks for the information, I'm going to add a standalone script to build it though. I will add your information in the README.

**Comment by xarkes** [comment]
The script is not 100% reliable and needs improvements, but it should be better.
