### ISSUE TITLE
Edit function does not work 

### ISSUE THREAD

**Issue by JulioSDDR** [radareorg/cutter#341]
| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             |  4.15.3-2-ARCH
| File format of the file you reverse (mandatory)      | bin
| Architecture/bits of the file (mandatory)            | AMD64

### Expected behavior
When editing any instruction in the disassembly tab, via right click>Edit>Instructions, the instruction should change. 

### Actual behavior
The instruction does not change :(

**Comment by Maijin** [comment]
Did you open the file in write mode ?

**Comment by 0xcpy** [comment]
Can you try `e io.cache=true` ?

**Comment by JulioSDDR** [comment]
I have reinstalled the git version and used the "e io.cache=true". Is working now. Does not work with the "e io.cache=true". May be useful to do it automagically  when in write mode

**Comment by xarkes** [comment]
Confirmed, I started debugging and apparently the io map doesn't have the correct permissions. I couldn't figure out why yet.

**Comment by xarkes** [comment]
Hi,
Could you please try again with current master branch? It looks fixed on my side.

**Comment by xarkes** [comment]
Ping?
