### ISSUE TITLE
Dark desktop theme hides back and forward button

### ISSUE THREAD

**Issue by Abogical** [radareorg/cutter#356]
When using a dark desktop theme, the back and forward buttons' background are black as in the theme, and has black arrows.

![screenshot](https://user-images.githubusercontent.com/10688496/37000187-42954c74-20cb-11e8-920c-0f294b8e13b1.png)

Expected behaviour:
back and forward button must have a white background, or white arrows.

**Comment by xarkes** [comment]
Hmm it does not happen in my case.

**Comment by Abogical** [comment]
I'm using an OpenSUSE Tumbleweed with KDE Breeze Dark theme.

**Comment by Abogical** [comment]
@xarkes Does your theme make your button background dark?

The back and forward button only inherit the desktop theme's button style.

**Comment by Maijin** [comment]
Could you follow the template for issue creation please.

**Comment by Abogical** [comment]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | OpenSUSE Tumbleweed
| File format of the file you reverse (mandatory)      | ELF, PE _(Theoretically irrelevant)_
| Architecture/bits of the file (mandatory)            | x86_64 _(Theoretically irrelevant)_
| Cutter and r2 version, See About Cutter (mandatory)         | Version 1.2 / Using 2.2.0-595-g4bc314526
| Show version information **full output** (See About Cutter) in a pastebin document (mandatory) | https://gist.github.com/Abogical/96e95b516e095b0145d0983d5ea238b5

### Expected behaviour
back and forward button must have a colour that contrasts 

### Actual behaviour
back and forward button and arrow have the same colour

### Steps to reproduce the behaviour 
- Use a dark **desktop** theme which uses a black background for it's buttons (Example is Breeze Dark)
- Open a binary in cutter
- Observe the forward and back buttons.

### Additional Logs, screenshots, source-code,  configuration dump, ...
![screenshot](https://user-images.githubusercontent.com/10688496/37000187-42954c74-20cb-11e8-920c-0f294b8e13b1.png)
_Back and forward buttons_

**Comment by xarkes** [comment]
Here is what I have on my machine.
![2018-03-07-215310_365x156_scrot](https://user-images.githubusercontent.com/10772605/37117589-fa4756e6-2251-11e8-9f29-2a6c815d711f.png)

**Comment by xarkes** [comment]
The old theme was using `palette(light)`, but I've changed it to `white` so you should have the same as in my screenshot above. Can you confirm it is fixed?

**Comment by Abogical** [comment]
Confirmed, it's fixed now. Thanks!
