### ISSUE TITLE
Compilation failed in Fedora 27

### ISSUE THREAD

**Issue by oliveriandrea** [radareorg/cutter#359]
It is impossible to compile cutter (directly from the latest git version) in Fedora 27 because this fatal error:

./src/Cutter.cpp: In member function ‘void CutterCore::setSettings()’:
../src/Cutter.cpp:829:28: error: ‘COLOR_MODE_DISABLED’ was not declared in this scope setConfig("scr.color", COLOR_MODE_DISABLED);

**Comment by xarkes** [comment]
Hi, can you paste the output of
```
r2 -V
```
I suspect you have some old libraries on your system.

**Comment by oliveriandrea** [comment]
2.2.0-602-g70bd99da2  r2
2.2.0-602-g70bd99da2  r_anal
2.2.0-602-g70bd99da2  r_lib
2.2.0-602-g70bd99da2  r_egg
2.2.0-602-g70bd99da2  r_asm
2.2.0-602-g70bd99da2  r_bin
2.2.0-602-g70bd99da2  r_cons
2.2.0-602-g70bd99da2  r_flag
2.2.0-602-g70bd99da2  r_core
2.2.0-602-g70bd99da2  r_crypto
2.2.0-602-g70bd99da2  r_bp
2.2.0-602-g70bd99da2  r_debug
2.2.0-602-g70bd99da2  r_hash
2.2.0-602-g70bd99da2  r_fs
2.2.0-602-g70bd99da2  r_io
2.2.0-602-g70bd99da2  r_magic
2.2.0-602-g70bd99da2  r_parse
2.2.0-602-g70bd99da2  r_reg
2.2.0-602-g70bd99da2  r_sign
2.2.0-602-g70bd99da2  r_search
2.2.0-602-g70bd99da2  r_syscall
2.2.0-602-g70bd99da2  r_util

**Comment by xarkes** [comment]
So yes your version of radare2 is obviously too old. Please use at least the one given with the submodule.

**Comment by oliveriandrea** [comment]
I'm using build.sh in order to compile cutter...

**Comment by xarkes** [comment]
The script is quite new and doesn't handle every cases. You surely have some old libraries installed with another installer that was not removed. Locate those files on your system and delete them manually, or run `sudo make purge` in radare2 folder.

**Comment by dukebarman** [comment]
On Fedora 27 (KDE) `build.sh` works:
```
...
Build complete. Binary available at: build/Cutter
$ 
```

You need only add qmake to PATH and `export PKG_CONFIG_PATH=/usr/lib/pkgconfig/` after install r2

**Comment by xarkes** [comment]
In the absence of answer I'm closing this issue. Feel free to reopen if it still doesn't work for you.
