### ISSUE TITLE
Drawing large graphs optimization

### ISSUE THREAD

**Issue by XVilka** [radareorg/cutter#366]
Can be very useful to quickly draw/redraw huge callgraphs/control flow graphs. Found this paper 
[meyerhenke2017.pdf](https://github.com/radareorg/cutter/files/1792056/meyerhenke2017.pdf)
Hopefully will be useful.

**Comment by ITAYC0HEN** [comment]
thanks to @Adikso, now hugggggge graphs are created very fast and it is super easy to navigate :)
