### ISSUE TITLE
Add more information in Function Panel

### ISSUE THREAD

**Issue by Maijin** [radareorg/cutter#382]
Add more function information in Function Panel with `aflj`

- nbbs
- nargs
- nlocals
- cc (cyclomatic-cost)
- calltype

**Comment by straceX** [comment]
@Maijin 
![screenshot from 2018-03-24 22-01-41](https://user-images.githubusercontent.com/17849283/37868942-4021bb40-2fc0-11e8-9fc9-8763a6382739.png)
Adding more information right side (sidebar)? And where is actual area?

**Comment by Maijin** [comment]
To be added here 
![image](https://user-images.githubusercontent.com/1408600/37874721-b66ec38c-3034-11e8-906e-60b5845c3d8c.png)

All the values are in aflj already as said in the initial issue
