### ISSUE TITLE
Replace notepad plugin by jupyter notebook

### ISSUE THREAD

**Issue by XVilka** [radareorg/cutter#39]
Idea is to integrate jupyter notebook in two-way interaction with r2 core inside the r2 GUI.
There are widgets support in Jupyter Notebook - see http://jupyter.org/widgets.html

See about low-level widgets interaction here http://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Low%20Level.html

Creating widget on the fly inside the Jupyter Notebook https://blog.dominodatalab.com/interactive-dashboards-in-jupyter/

Angr + IPython https://apps.sandstorm.io/app/cxp85aey2qrdqvxja1zgrs0tyzq7s55qwqdwqgz12k036s3rc1yh

Check the IDA + IPython plugins:

https://github.com/james91b/ida_ipython
https://github.com/eset/ipyida
https://github.com/tmr232/Sark

## Use cases

1. Writing text in the markdown format

2. Including images

3. Attaching files (images, pdfs, textfiles)

4. Simple embedded r2pipe command line (ipython + r2pipe.py imported)

5. Some widgets from r2 GUI available embedded in jupyter nodebook - e.g. graph, so you'll be able to run "afg [funcname]" to get the graph of the function, embedded in the notebook - see example of http://nbviewer.jupyter.org/github/james91b/ida_ipython/blob/master/notebook/examples/Sark%20Snapshots.ipynb
But keep in mind, that this example is poor - because it's just a snapshot. Embedding full-feature graph is nicer.

6. Functions entropy (or similar characteristics) - see http://nbviewer.jupyter.org/github/james91b/ida_ipython/blob/master/notebook/examples/Function%20Entropy.ipynb

7. Machine learning and data analysis:
   - http://www.kdnuggets.com/2016/04/top-10-ipython-nb-tutorials.html
   - https://dev.socrata.com/blog/2016/02/01/pandas-and-jupyter-notebook.html 
   - https://blog.treasuredata.com/blog/2015/06/23/data-science-101-interactive-analysis-with-jupyter-pandas-and-treasure-data/
   - 

## Widgets information

https://github.com/ipython/ipython/wiki/Widgets

Example of the plugin and custom widget for Jupyter - SparkMonitor https://krishnan-r.github.io/sparkmonitor/

**Comment by XVilka** [comment]
Since you were interested in, mentioning you @guedou

**Comment by xarkes** [comment]
Obviously this means removing the current "Notepad"

**Comment by XVilka** [comment]
Note, that next Jupyter generation is JupyterLab - version for real-time collaboration - https://channel9.msdn.com/Events/PyData/Seattle2017/BRK11 

See code here https://github.com/jupyterlab/jupyterlab

So may be there is a good idea to target it instead, since this issue wont be closed in one day obviously.

**Comment by Maijin** [comment]
@Properrr

**Comment by Properrr** [comment]
@Maijin ok, i will try

**Comment by Maijin** [comment]
https://qtconsole.readthedocs.io/en/stable/

**Comment by XVilka** [comment]
@Maijin everything required for embedding is already in my links. Qtconsole is just a wrapper.

**Comment by Maijin** [comment]
branch needs help https://github.com/radareorg/cutter/tree/jupyter 👍

**Comment by guedou** [comment]
FYI will release my jupyter-radare kernel next week

**Comment by Maijin** [comment]
kk, @guedou if you want to take a look at this issue too, that'd be great :)

**Comment by guedou** [comment]
Here is the radare2 kernel: https://github.com/guedou/jupyter-radare2

**Comment by XVilka** [comment]
@Properrr any progress on this?

**Comment by xarkes** [comment]
Check the Jupyter branch

**Comment by XVilka** [comment]
@xarkes I saw this one commit already. If I remember correctly @Properrr wanted to check it and improve.

**Comment by XVilka** [comment]
Added link to https://krishnan-r.github.io/sparkmonitor/ as a good example of extending both jupyter runtime/server and writing a custom widget.

**Comment by xarkes** [comment]
@thestr4ng3r @Properrr ping, how is it going?

**Comment by thestr4ng3r** [comment]
Too much other stuff to do lately unfortunately, but I haven't forgotten about it.

**Comment by thestr4ng3r** [comment]
Too much other stuff to do lately unfortunately, but I haven't forgotten about it.

**Comment by xarkes** [comment]
Check again the branch:
https://github.com/radareorg/cutter/tree/jupyter
I added a commit so now you can access the Cutter r2 instance by calling `r2pipe.open('tcp://localhost:1234')`
The radare2-r2pipe python module seems to be not very stable though (I get broken pipe errors).

**Comment by XVilka** [comment]
@Properrr by any chance?

**Comment by xarkes** [comment]
Old Notepad has been removed, Jupyter branch has been merged.
Remains only a correct bundling for all of that and we're good.
