### ISSUE TITLE
In the Console, pressing the TAB key does not "complete" the command (enhancement)

### ISSUE THREAD

**Issue by rdjondo** [radareorg/cutter#391]
# Expecting list of commands (completion) to be displayed when pressing TAB

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Windows 7, 64 bits
| File format of the file you reverse (mandatory)      | any 
| Architecture/bits of the file (mandatory)            | any
| Cutter and r2 version, See About Cutter (mandatory)  | Version 1.3 / Using r2 2.4.0-56-g4dffa5cd2

### Expected behavior
Expecting TAB keyboard press to behave like in the Console radare2. TAB should be used to suggest commands to complete.

### Actual behavior
Unfortunately TAB is used to switch focus between UI panes :-(

### Steps to reproduce the behavior 
Open a binary to analyse
In the Console input line start typing "e asm.b"
The Console input line loses focus and no suggestions are displayed

**Comment by Abogical** [comment]
I'm not sure if you know, but I don't think this feature is implemented, thus it isn't necessary to follow the bug issue format.

Radare2's commands themselves are very short and compressed. auto completing them impractical. However auto completing config variable names such as `asm.bytes` may be useful.

**Comment by xarkes** [comment]
So as said, do we want to add auto completion for the 4 characters length commands?
