### ISSUE TITLE
Cutter is not in archlinux

### ISSUE THREAD

**Issue by trufae** [radareorg/cutter#394]
Will be good to make cutter appear in all major distros.

right now archlinux have a package named `cutter` which is a TCP/IP connection cutting stuff

**Comment by xarkes** [comment]
Cutter is available in AUR though.

**Comment by XVilka** [comment]
Not in Gentoo, Fedora, Debian (maybe in 20 years), Ubuntu, OpenSUSE, RedHat, Mint, Mageia, Manjaro, Slackware, AltLinux, AstraLinux.

**Comment by stkw0** [comment]
cutter is in Gentoo from 2 months ago (https://github.com/gentoo/gentoo/tree/master/dev-util/cutter)
