### ISSUE TITLE
Support for more types of searches

### ISSUE THREAD

**Issue by trufae** [radareorg/cutter#396]
* [ ] /m - search magic
* [x] /v/V - search value/dword
* [x] /R - search rop

**Comment by Maijin** [comment]
This requires `/mj`, `/vj` and `/Vj` on radare2 side ^_^

**Comment by xarkes** [comment]
cf. https://github.com/radare/radare2/issues/9705

**Comment by Maijin** [comment]
Commands have been added, remain implementation ping @fcasal
