### ISSUE TITLE
Implement minigraph to scroll and get an overview

### ISSUE THREAD

**Issue by trufae** [radareorg/cutter#397]

**Comment by trufae** [comment]
And also support zooming in graph

**Comment by xarkes** [comment]
There's already zooming in graph.
The minigraph (overview) is already in the source code, just never used as far as I remember.

**Comment by xarkes** [comment]
I think @fcasal is working on it.

**Comment by ITAYC0HEN** [comment]
@fcasal, are you on it? please write if there's any update on this one :)

**Comment by Maijin** [comment]
@ITAYC0HEN @fcasal is currently focus on the GSOC (debugger) see the Pull requests and give your feedbacks.

**Comment by xarkes** [comment]
As said this is quite easy to do as the code is (or was) present (taken from x64dbg graphs).
I think it's just a matter of knowing what to copy paste and where.

**Comment by xarkes** [comment]
Btw @fcasal what was your status on this?

**Comment by Vane11ope** [comment]
im steal this.

**Comment by xarkes** [comment]
Fixed in https://github.com/radareorg/cutter/pull/1120
