### ISSUE TITLE
Add asm.describe as a view options

### ISSUE THREAD

**Issue by Maijin** [radareorg/cutter#4]
Add asm.describe as a view options

![image](https://user-images.githubusercontent.com/1408600/30883938-1886847e-a30e-11e7-83f6-2e34eb1a5836.png)

**Comment by Maijin** [comment]
This is already in the loading menu but should be moved there.

**Comment by Maijin** [comment]
All those disassembly options should be moved from this droplist and from the loading menu under one single place with the options to choose from.

**Comment by Maijin** [comment]
See also right click Show stack pointer and show hide bytes, this need to be moved also in this menu

**Comment by thestr4ng3r** [comment]
I like the idea of moving all these options to a separate dialog. Also to remove them from the loading menu since they clearly have nothing to do with loading. I will implement this next.

**Comment by Maijin** [comment]
Great to recap:
* Current menu
* Right click
* Loading Menu
-> separate dialog 👍
