### ISSUE TITLE
Typing a command that starts with a dash freezes cutter

### ISSUE THREAD

**Issue by Abogical** [radareorg/cutter#402]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | OpenSUSE Tumbleweed x86/64
| File format of the file you reverse (mandatory)      | PE, ELF *(Theoretically irrelevant)*
| Architecture/bits of the file (mandatory)            | x86/64 *(Theoretically irrelevant)*
| Cutter and r2 version, See About Cutter (mandatory)  | Version 1.3 / Using r2 2.2.0-751-g0cf304a4f
| Show version information **full output** (See About Cutter) in a pastebin document (mandatory) | https://gist.github.com/Abogical/847d919a4b1ff910b459a646541306e2

### Expected behavior
Any behaviour that should not include freezing.

### Actual behavior
Cutter freezes. In the terminal output, a default editor is shown opening a temporary file. Closing the editor unfreezes cutter.

### Steps to reproduce the behavior 
- Open any binary.
- Type a command that starts with the dash character (`-`) such as `-j`

**Comment by xarkes** [comment]
Probably a bug in radare2 which doesn't take care of `scr.interactive`

**Comment by xarkes** [comment]
Fixed in https://github.com/radare/radare2/commit/3bc955c7133f34b0c6efd41ae4eb888dce578587
