### ISSUE TITLE
Add Call-Graph

### ISSUE THREAD

**Issue by Maijin** [radareorg/cutter#406]
Add Call-Graph

**Comment by apasamar** [comment]
Consider to port agc call-graph and also agx. 
Depth levels are important. I coded this small example in python using r2pipe() for agx (2 levels)
https://github.com/apasamar/radare_stuff/blob/master/agx_depth.py

**Comment by Maijin** [comment]
From @radare 
![image](https://user-images.githubusercontent.com/1408600/54883781-c8dd7500-4e69-11e9-82f7-ed14a28f5124.png)
