### ISSUE TITLE
Hang on when open binary on Win10

### ISSUE THREAD

**Issue by XYlearn** [radareorg/cutter#408]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Windows10 64
| File format of the file      | PE
| Architecture/bits of the file (mandatory)            | 64
| Cutter and r2 version  | Version 1.3 / Using r2 2.4.0-56-g4dffa5cd2
| Show version information | https://gist.github.com/XYlearn/087fa245f1b4d3bc6645c35b1ba40383

### Expected behavior
show main panel after I press OK in Load Option panel

### Actual behavior
The Load Option Menu hang on for a long time with no responding

### Steps to reproduce the behavior 
- Can't open the binary I uploaded as well as other binaries I've tested(including ELF binary).
[bin.zip](https://github.com/radareorg/cutter/files/1821748/bin.zip)
compiled from
```C
int main() {
    return 0;
}
```
- open with default options

### Additional Logs, screenshots, source-code,  configuration dump, ...
![screen](https://user-images.githubusercontent.com/20752088/37556813-226eb5ce-2a36-11e8-9912-05d9b64ae9c4.png)

Drag and drop zip archives containing the Additional info here, don't use external services or link.

- After dubugging. I found the program hang on in cutter_jupyter.start_jupyter

**Comment by XYlearn** [comment]
The reason is that there is something wrong with my network loopback, I found it by ping localhost.
And I fix it by restarting firewall.

**Comment by xarkes** [comment]
Ok thank you, maybe we could add a timeout or something.
