### ISSUE TITLE
Vertical and horizontal split view

### ISSUE THREAD

**Issue by XVilka** [radareorg/cutter#41]
To be able to
 - [ ] Scroll different parts of same disasm 
 - [ ] To view disasm of another file (may be for diffing mode?)
 - [ ] Same for hex view
 - [ ] Or one panel is for disasm and another - for graph
 - [ ] Or disasm + notes (notepad)

**Comment by xarkes** [comment]
Reauires to do https://github.com/radareorg/cutter/issues/36 first

**Comment by xarkes** [comment]
Also it requires that each widget has a way to desynchronize from radare2. Save current seek, and handle properly radare2 seek change (window focused, whatever)

**Comment by xarkes** [comment]
Closing as I think it's done already.
