### ISSUE TITLE
Remove ascii arrows from disassembly widget

### ISSUE THREAD

**Issue by xarkes** [radareorg/cutter#413]
Needs to fix `pdJ` with `scr.html=true` some characters aren't parsed correctly.
Needs to fix some `fcnlines` in radare2 too, cf screenshot below.
![2018-03-21-104545_1019x288_scrot](https://user-images.githubusercontent.com/10772605/37703161-08cdf87a-2cf5-11e8-9451-7105b88698e3.png)

**Comment by Maijin** [comment]
@thestr4ng3r ^

**Comment by thestr4ng3r** [comment]
Do you have an example what exactly needs to be fixed in pdJ?

**Comment by xarkes** [comment]
I can't send a screenshot but the fcnlines character when utf8 is enabled is printed as \xe4\xXX\xXX something and it should be converted to a single character when using `scr.html=true`

**Comment by ITAYC0HEN** [comment]
Screenshots attached. 
Also, while scrolling with the wheel, it changes where and how the lines are.

![image](https://user-images.githubusercontent.com/20182642/39427528-b54f3b8e-4c8c-11e8-88dc-ab0f3909712b.png)


![image](https://user-images.githubusercontent.com/20182642/39427565-e18b2e6a-4c8c-11e8-8192-cafa7b877736.png)

**Comment by xarkes** [comment]
I tried with this dumb patch:

```diff
diff --git a/libr/core/disasm.c b/libr/core/disasm.c
index fd83d10f4..a2bd2e50f 100644
--- a/libr/core/disasm.c
+++ b/libr/core/disasm.c
@@ -1729,7 +1729,8 @@ static void ds_print_pre(RDisasmState *ds) {
 
        char *c_esc = NULL;
        if (ds->use_json) {
-               c = c_esc = r_str_escape (c);
+               //c = c_esc = r_str_escape (c);
+               c = c_esc = strdup (c);
        }
        r_cons_printf ("%s%s%s ",
                COLOR (ds, color_fline), c,
```
Now the utf-8 characters are properly shown, but it looks like the characters are not vertically aligned anymore.

**Comment by XVilka** [comment]
See also https://github.com/radare/radare2/pull/10555

**Comment by Maijin** [comment]
CC @cyanpencil

**Comment by XVilka** [comment]
Wasn't this fixed already?

**Comment by xarkes** [comment]
No, otherwise the issue would be closed :)

**Comment by ITAYC0HEN** [comment]
@xarkes your fix works fine - the problem with the vertical alignment is in the font being used. I assume 
Inconsolata doesn't support some characters such as ">" so the character is being printed with different font that has different char-width.

**Inconsolata (Default font):**
![inconsolata](https://user-images.githubusercontent.com/20182642/44273958-96bbc300-a249-11e8-9dcc-ae51af518aed.JPG)

**Free Mono:**
![freemono](https://user-images.githubusercontent.com/20182642/44273960-98858680-a249-11e8-97a8-b490f53d72a9.png)

**Comment by XVilka** [comment]
Open a bug in Inconsolata.

**Comment by xarkes** [comment]
Great, maybe we can change default font in Cutter and then merge the fix.

**Comment by radare** [comment]
agave is nice too. i put some nice console fonts in my Therm (iterm2 fork) if u want to check them too

**Comment by thestr4ng3r** [comment]
Yeah agave is great. Looks really nice in cutter.

**Comment by ITAYC0HEN** [comment]
It's too heavy imo. I prefer thiner fonts.
Also, yeah, no continuous lines :(

**Comment by ITAYC0HEN** [comment]
okay so we need to decide on the right font to use and finally get rid of the dashed lines in cutter
```
|
|
|
|
```

**Comment by xarkes** [comment]
I think we just need to stop relying on r2 output when it comes to our interface.
All we need from 2 is the disassembly, we should draw our own arrows.
I am renaming this issue.

**Comment by XVilka** [comment]
Exactly, it will help to solve also 1) selection problem (don't select opcode bytes and reflines) 2) folding 3) highlighting and colors.

**Comment by ITAYC0HEN** [comment]
the solution is a WIP and almost done. Tracked by @xarkes here: https://github.com/radareorg/cutter/tree/disassemblyWidget

**Comment by ITAYC0HEN** [comment]
Pullrequest is pending: https://github.com/radareorg/cutter/pull/1626
