### ISSUE TITLE
project ERROR: ERROR: Python 3 could not be found. Make sure it is available to pkg-config.

### ISSUE THREAD

**Issue by hklm-win** [radareorg/cutter#417]
| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Linux kali 4.14.0-kali3-amd64 #1 SMP Debian 4.14.12-2kali1 (2018-01-08) x86_64 GNU/Linux

Install is not working on kali.
git clone --recurse-submodules https://github.com/radareorg/cutter
cd cutter
./build.sh 

Cannot find file: .
/opt/cutter/src/Cutter.pro:14: defined(function, type): unexpected type [var].
/opt/cutter/src/Cutter.pro:17: defined(function, type): unexpected type [var].
Project MESSAGE: Jupyter support enabled.
Project MESSAGE: QtWebEngine support enabled.
/opt/cutter/src/Cutter.pro:68: defined(function, type): unexpected type [var].
Project ERROR: ERROR: Python 3 could not be found. Make sure it is available to pkg-config.
make: *** No targets specified and no makefile found.  Stop.
Something went wrong!

Python3 is installed and available.
root@kali:/opt/cutter# /usr/bin/python3 --version
Python 3.6.4

I'm not able to install cutter :-(

**Comment by xarkes** [comment]
Why don't you download the AppImage in the releases tab?

**Comment by hklm-win** [comment]
AppImage worked correctly, thanks.

**Comment by emmh** [comment]
Sorry for re-opening this issue. 
But using an image may not be the answer to those who want to compile from scratch. On my debian-based system installing 
 python3-pkgconfig
satisfied the projects needs.

**Comment by xarkes** [comment]
Thanks for the hint.

**Comment by Maijin** [comment]
Update - You need to install python3-pkgconfig and python3-dev.
