### ISSUE TITLE
Crash upon opening - _getentropy - symbol not found

### ISSUE THREAD

**Issue by silverdr** [radareorg/cutter#424]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | OS X 10.11.6 (15G20015)/x86_64/64
| File format of the file you reverse (mandatory)      | raw binary
| Architecture/bits of the file (mandatory)            | 6502 / 8
| Cutter and r2 version, See About Cutter (mandatory)  | Version 1.3 / Using r2 2.4.0-56-g4dffa5cd2
| Show version information **full output** (See About Cutter) in a pastebin document (mandatory) | 2.4.0-56-g4dffa5cd2 r2
2.4.0-56-g4dffa5cd2 r_anal
2.4.0-56-g4dffa5cd2 r_lib
2.4.0-56-g4dffa5cd2 r_egg
2.4.0-56-g4dffa5cd2 r_asm
2.4.0-56-g4dffa5cd2 r_bin
2.4.0-56-g4dffa5cd2 r_cons
2.4.0-56-g4dffa5cd2 r_flag
2.4.0-56-g4dffa5cd2 r_core
2.4.0-56-g4dffa5cd2 r_crypto
2.4.0-56-g4dffa5cd2 r_bp
2.4.0-56-g4dffa5cd2 r_debug
2.4.0-56-g4dffa5cd2 r_hash
2.4.0-56-g4dffa5cd2 r_fs
2.4.0-56-g4dffa5cd2 r_io
2.4.0-56-g4dffa5cd2 r_magic
2.4.0-56-g4dffa5cd2 r_parse
2.4.0-56-g4dffa5cd2 r_reg
2.4.0-56-g4dffa5cd2 r_sign
2.4.0-56-g4dffa5cd2 r_search
2.4.0-56-g4dffa5cd2 r_syscall
2.4.0-56-g4dffa5cd2 r_util

### Expected behavior

Works

### Actual behavior

Crash

### Steps to reproduce the behavior 

* Launch application
* Open binary file

### Additional Logs, screenshots, source-code,  configuration dump, ...

[Cutter_2018-04-01-152744_Leviathan.crash.zip](https://github.com/radareorg/cutter/files/1866614/Cutter_2018-04-01-152744_Leviathan.crash.zip)

**Comment by xarkes** [comment]
Hi, I cannot reproduce any crash with latest radare2 and latest Cutter. Can you please paste a stacktrace?

**Comment by silverdr** [comment]
The crash report with stacktrace is attached above.

**Comment by silverdr** [comment]
Please also note that previous release version does not exhibit the issue.

**Comment by xarkes** [comment]
Ah sorry my bad I went too fast, I thought that was the binary...
@thestr4ng3r can you check this, it looks like it's a bug with Jupyter.

**Comment by thestr4ng3r** [comment]
This seems to be an issue with El Capitan, which does not have `_getentropy`. Maybe we can use a workaround like this in travis: https://lsongnotes.wordpress.com/2016/09/27/first-blog-post/

**Comment by 404NetworkError** [comment]
I'm having the same issue as the original post (on El Capitan), just with the recently released version 1.5. Attached is my crash log.

[Cutter_2018-07-02-094925.crash.zip](https://github.com/radareorg/cutter/files/2155715/Cutter_2018-07-02-094925.crash.zip)
