### ISSUE TITLE
Takes much, much longer to open main window with Game Gear ROM (1.3 regression)

### ISSUE THREAD

**Issue by gingerbeardman** [radareorg/cutter#427]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | macOS 10.13.4, 64-bit
| File format of the file you reverse (mandatory)      | SEGA Game Gear ROM
| Architecture/bits of the file (mandatory)            | M68/16
| Cutter and r2 version, See About Cutter (mandatory)  | Version 1.3 / Using r2 2.4.0-56-g4dffa5cd2
| Show version information **full output** | https://gist.github.com/gingerbeardman/c06714c05d2080bed956bfe75ae7e83f

### Expected behavior
Should analyze file

OK in...
Version 1.2 / Using r2 2.2.0-333-gcc7b6e2c1  
Version 1.0 / Using r2 2.2.0 (v1.1)  
Version 1.0 / Using r2 2.1.0-62-g410ca0980

### Actual behavior
Will open with Analysis disabled, but crashes when Analyse is chosen

### Steps to reproduce the behavior 
- Open and analyze [popils.gg.zip](https://github.com/radareorg/cutter/files/1869155/popils.gg.zip) in 1.3

**Comment by xarkes** [comment]
I can't reproduce any crash, the only behaviour I have is that it takes a lot of time.

**Comment by xarkes** [comment]
Although GameGear seems to be very poorly supported in radare2, and the binary doesn't have any sections, which might be one of the reason why the analysis fails.

**Comment by xarkes** [comment]
Please can you upload a stacktrace?

**Comment by gingerbeardman** [comment]
I'll upload one soon

**Comment by gingerbeardman** [comment]
So if left long enough, it does open.

Here are some timings:

Cutter 1.2 = 4 seconds

Cutter 1.3 = 2 minutes 20 seconds

**Comment by xarkes** [comment]
Oh, okay. Maybe the top bar drawing too many things. I'll try to fix that :)
Thanks for reporting.

**Comment by gingerbeardman** [comment]
Thanks for following up
