### ISSUE TITLE
Input Hex String Format & GUI Response

### ISSUE THREAD

**Issue by lmstearn** [radareorg/cutter#431]
### Work environment: Windows 10
Arch: Windows Amd64
| File format: PE
| Architecture/bits of the file (mandatory) X64
|Cutter and r2 version: Version 1.3 / Using r2 2.4.0-56-g4dffa5cd2
| Ver Info: (https://pastebin.com/vQ3pgauyhttps://gist.github.com/

### Expected behavior
Feature Request: Hexstring search should show cancellable progress bar display. A search argument like 00000000 does work and the search pane is populated. Using an invalid argument like "PYX" should generate a beep. String arguments not of format subset of "HH HH HH HH ..." require reformat to populate the pane with results. Double click the offset column to show highlighted result in pane.
### Actual behavior
Choose a non zero argument that is in the obj file and the search will not populate the pane with the result. Paste in a non zero hex string not of format subset of "HH HH HH HH ..." and the GUI issues no response. Double click the offset column to locate the string argument, but the offset line with the string is about 5 or 6 rows above the visible pane.
### Steps to reproduce the behavior
Select a hex string like 00 00 01 00 00 00 and note results will populate for it and 000001000000
However, select a string like 0B 02 0E for no results- yet the Data column will show a result for 0B020E. 
Double click the offset column to locate the string, but the string is about 5 or 6 rows above the visible pane.
 
Binary isn't shareable but the dumpbin is [here](http://www.theassimilationlab.com/forums/files/file/1401-sksequasidebuglogtest/?do=download&r=27973&confirm=1&t=1&csrfKey=b3e25c660b71eb5951f1d6e497539500).

**Comment by xarkes** [comment]
Fixed in #435
