### ISSUE TITLE
Crash after binary analysis - malloc(): memory corruption: 0x0000000001a92ba0

### ISSUE THREAD

**Issue by zMathieu** [radareorg/cutter#437]
I can't get Cutter v1.3 to works on my computer, it crash with any binary file. Cutter v1.2 works perfectly.

Thank you for helping me.

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | amd64, Deepin 4.9.0
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| Cutter and r2 version, See About Cutter (mandatory)  | Version 1.3 / Using r2 2.4.0-56-g4dffa5cd2
| Show version information **full output** (See About Cutter) in a pastebin document (mandatory) | https://gist.github.com/zMathieu/e6cf4a0604d7c407db21f7315e143e39#file-version-info-cutter-md

### Expected behavior

Cutter should start normally after I press ok in order to begin the analysis.

### Actual behavior

Cutter crash after I click on ok.

### Steps to reproduce the behavior

1. Start Cutter.

```
./Cutter-v1.3-x86_64.AppImage
```
2. Select any binary file
3. Press ok

I tried with several ELF files and it seems to crash everytime. The only way i get Cutter to works is to use Cutter v1.2.

### Additional Logs, screenshots, source-code,  configuration dump, ...

[stderr.zip](https://github.com/radareorg/cutter/files/1896092/stderr.zip)

**Comment by xarkes** [comment]
Hi, indeed it seems to be an issue with Jupyter and the embeded Python. Maybe @thestr4ng3r can help when he'll have some time.

**Comment by thestr4ng3r** [comment]
I can reproduce it in a Deepin vm (what a funny distribution). I will investigate further...

**Comment by thestr4ng3r** [comment]
Phew, that one was quite tricky.
Next release should be fine again.

Until then, the 1.3 AppImage can be used like this:
```
$ ./Cutter-v1.3-x86_64.AppImage --appimage-mount
/tmp/.mount_CutterrCMVTE
```
Then, in a different terminal with the path it outputs:
```
LD_LIBRARY_PATH=/tmp/.mount_CutterrCMVTE/usr/lib /tmp/.mount_CutterrCMVTE/AppRun
```
