### ISSUE TITLE
Ability to open several window tabs

### ISSUE THREAD

**Issue by wavvs** [radareorg/cutter#448]
Hello, how can I open several tabs with, for example, graphs like in Ida? Either I didn't find this feature or cutter doesn't support it yet? Thanks.

**Comment by xarkes** [comment]
Hi, this feature is not yet supported but will be implemented soon. I think there's already an issue dealing with this but I can't check right now.

**Comment by xarkes** [comment]
@fcasal One of the first things you will have to do ;)

**Comment by xarkes** [comment]
Done earlier in June.
