### ISSUE TITLE
big icons are still not retina friendly

### ISSUE THREAD

**Issue by radare** [radareorg/cutter#458]
i can see the pixels there

<img width="510" alt="screen shot 2018-04-24 at 19 56 02" src="https://user-images.githubusercontent.com/917142/39204940-8f3aac04-47f9-11e8-8318-27df50154230.png">

**Comment by xarkes** [comment]
Ahh ok thx for screenshot

**Comment by thestr4ng3r** [comment]
That's strange. The icns file included in the .app contains images up to 1024x1024. I just had a collegue with a retina mac test the 1.4 dmg for me and it looks perfectly fine for him:
<img width="503" alt="bildschirmfoto 2018-05-03 um 13 35 24" src="https://user-images.githubusercontent.com/1460997/39574391-6441af86-4ed7-11e8-9950-d3beeb9be09f.png">

**Comment by thestr4ng3r** [comment]
I don't think that is the case here. If you click on the original screenshot to display it in full resolution, you can clearly see it is rendering a lower resolution image than 1024x1024. It is not just blurry like it would appear with non-integer scaling.

**Comment by ITAYC0HEN** [comment]
So bottom line, what should be done here? I can use Photoshop/Illustrator if need some improvements

**Comment by thestr4ng3r** [comment]
This is old, I've used Cutter on macOS many times since and the icon always looked perfect. Perhaps it was just a caching issue.
