### ISSUE TITLE
Coding style convention

### ISSUE THREAD

**Issue by pelijah** [radareorg/cutter#477]
1. `Q_NULLPTR` vs `nullptr` vs `0`

1. Connecting signal/slot 
`connect(sender, &QObject::destroyed, this, &MyObject::objectDestroyed);`
vs
`connect(sender, SIGNAL(destroyed()), this, SLOT(objectDestroyed()));`

**Comment by xarkes** [comment]
1/ For sure not 0. And I don't think we use `Q_NULLPTR` but maybe we should consider it.

2/ I would go for the second one with `SIGNAL()` and `SLOT()`

**Comment by pelijah** [comment]
`Q_NULLPTR` was used by me: https://github.com/radareorg/cutter/blob/d58e69d411fc954676901ac36356722ae341b03c/src/widgets/RelocsWidget.h#L45

You can find `0` in Cutter sources: 
https://github.com/radareorg/cutter/blob/master/src/widgets/FunctionsWidget.h#L84

**Comment by xarkes** [comment]
Ok, imho the `0` should be removed and replaced by `Q_NULLPTR` if it is a `QObject` instance, otherwise `nullptr` for any other object.

**Comment by xarkes** [comment]
I'm reading that `Q_NULLPTR` was used before `nullptr` was introduce in C++11, and so if C++11 is enabled `Q_NULLPTR` expands to `nullptr`.

**Comment by thestr4ng3r** [comment]
+1 for nullptr everywhere

Also, I would prefer `connect(sender, &QObject::destroyed, this, &MyObject::objectDestroyed)`. This is also the only syntax that supports lambda expressions.

Another aspect that is still inconsistent throughout the code: C++11 for each should be preferred over the qt foreach macro.

**Comment by xarkes** [comment]
Ah yes that's right I forgot about the lamda functions.

**Comment by xarkes** [comment]
Closed via https://github.com/radareorg/cutter/commit/d34dab392552f4a629551782a2db034a3b51b1df
