### ISSUE TITLE
Empty Graph and Disas widgets in a function

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/cutter#482]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Windows 10 64bit
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86/32
| Cutter and r2 version, See About Cutter (mandatory)  | Version 1.4 / Using r2 2.5.0-105-gc79874941

### Expected behavior
Double click on a function name would show its content

### Actual behavior
The disas view and Graph view are showing empty content.
File: [dropshot.zip](https://github.com/radareorg/cutter/files/1980353/dropshot.zip)

I'm analyzing a malware on Cutter 1.4 Windows.
It opened just fine
![1](https://user-images.githubusercontent.com/20182642/39700743-10483304-5207-11e8-8929-9b59da7cba84.PNG)

I'm searching for a specific function I want to analyze, it is showed correctly in the functions widget
![2](https://user-images.githubusercontent.com/20182642/39700746-12d18792-5207-11e8-9648-09f2dcd08d9d.PNG)

I'm double clicking on it and sees nothing. An empty content in the Graph widget
![3](https://user-images.githubusercontent.com/20182642/39700752-147243de-5207-11e8-9b48-eb078773ae7d.PNG)

Also empty in the disas widget
![4](https://user-images.githubusercontent.com/20182642/39700753-16583726-5207-11e8-8759-fc9fd41e9158.PNG)

But when I scroll up in this empty disas widget I'm seeing part of the function
scrolling down will end with empty screen
![5](https://user-images.githubusercontent.com/20182642/39700757-185bd000-5207-11e8-8d09-4586e9afa0d4.PNG)

**Comment by xarkes** [comment]
Need more parsing for extra `\` and `"` in ds_print_str

**Comment by Maijin** [comment]
@kazarmy ^ ?

**Comment by kazarmy** [comment]
I've narrowed it down to:

```
[0x00408adb]> pdJ 1 @ 0x004012eb
[{"offset":4199147,"text":"            0x004012eb      8a8a3cba4100   mov cl, byte [edx +
    str.AaCcdDeFfGhiKLlMmnNoOpPrRsSTtUuVvwWxyZz32.__EbgjHI__YQB:] ; [0x41ba3c:1]=65 ;
    \"AaCcdDeFfGhiKLlMmnNoOpPrRsSTtUuVvwWxyZz32.\EbgjHI _YQB:\\"/@\n\r\x1a\""}]
```

Apparently the code that JSONifies pd output (which isn't ds_print_str unfortunately, otherwise it would have been found) is escaping quotation marks but not backslashes.

**Comment by xarkes** [comment]
Thank you @kazarmy!

**Comment by xarkes** [comment]
(Updated r2 in https://github.com/radareorg/cutter/commit/4fa4460cd556b5871964a1eb0fb00a7b3f64b270)

**Comment by ITAYC0HEN** [comment]
did it fix this for you?
I'm getting
`Failed to parse JSON for command "pdJ 37 @ 4199072": unterminated object`
and
```
Failed to parse JSON for command "agJ": unterminated object
[{"name":"fcn.004012a0","offset":4199072
...
```

**Comment by kazarmy** [comment]
`e scr.color = 0; pdJ 37 @ 4199072` is valid JSON according to JSONLint:
https://jsonlint.com/?json=%5B%7B%22offset%22%3A4199072%2C%22text%22%3A%22%20%20%20%20%20%20%20%20%20%20%20%200x004012a0%20%20%20%20%20%2055%20%20%20%20%20%20%20%20%20%20%20%20%20push%20ebp%22%7D%2C%7B%22offset%22%3A4199073%2C%22text%22%3A%22%20%20%20%20%20%20%20%20%20%20%20%200x004012a1%20%20%20%20%20%208bec%20%20%20%20%20%20%20%20%20%20%20mov%20ebp%2C%20esp%22%7D%2C%7B%22offset%22%3A4199075%2C%22text%22%3A%22%20%20%20%20%20%20%20%20%20%20%20%200x004012a3%20%20%20%20%20%2083ec08%20%20%20%20%20%20%20%20%20sub%20esp%2C%208%22%7D%2C%7B%22offset%22%3A4199078%2C%22text%22%3A%22%20%20%20%20%20%20%20%20%20%20%20%200x004012a6%20%20%20%20%20%206a04%20%20%20%20%20%20%20%20%20%20%20push%204%20%3B%204%22%7D%2C%7B%22offset%22%3A4199080%2C%22text%22%3A%22%20%20%20%20%20%20%20%20%20%20%20%200x004012a8%20%20%20%20%20%206800100000%20%20%20%20%20push%200x1000%22%7D%2C%7B%22offset%22%3A4199085%2C%22text%22%3A%22%20%20%20%20%20%20%20%20%20%20%20%200x004012ad%20%20%20%20%20%200fbf450c%20%20%20%20%20%20%20movsx%20eax%2C%20word%20%5Bebp%20%2B%200xc%5D%20%3B%20%5B0xc%3A2%5D%3D0xffff%20%3B%2012%22%7D%2C%7B%22offset%22%3A4199089%2C%22text%22%3A%22%20%20%20%20%20%20%20%20%20%20%20%200x004012b1%20%20%20%20%20%2083c001%20%20%20%20%20%20%20%20%20add%20eax%2C%201%22%7D%2C%7B%22offset%22%3A4199092%2C%22text%22%3A%22%20%20%20%20%20%20%20%20%20%20%20%200x004012b4%20%20%20%20%20%2050%20%20%20%20%20%20%20%20%20%20%20%20%20push%20eax%22%7D%2C%7B%22offset%22%3A4199093%2C%22text%22%3A%22%20%20%20%20%20%20%20%20%20%20%20%200x004012b5%20%20%20%20%20%206a00%20%20%20%20%20%20%20%20%20%20%20push%200%22%7D%2C%7B%22offset%22%3A4199095%2C%22text%22%3A%22%20%20%20%20%20%20%20%20%20%20%20%200x004012b7%20%20%20%20%20%20ff15a8314100%20%20%20call%20dword%20%5Bsym.imp.KERNEL32.dll_VirtualAlloc%5D%20%3B%200x4131a8%20%3B%20%5C%22%40%5C%5Cx98%5C%5Cx01%5C%22%22%7D%2C%7B%22offset%22%3A4199101%2C%22text%22%3A%22%20%20%20%20%20%20%20%20%20%20%20%200x004012bd%20%20%20%20%20%208945f8%20%20%20%20%20%20%20%20%20mov%20dword%20%5Bebp%20-%208%5D%2C%20eax%22%7D%2C%7B%22offset%22%3A4199104%2C%22text%22%3A%22%20%20%20%20%20%20%20%20%20%20%20%200x004012c0%20%20%20%20%20%20c745fc000000.%20%20mov%20dword%20%5Bebp%20-%204%5D%2C%200%22%7D%2C%7B%22offset%22%3A4199111%2C%22text%22%3A%22%20%20%20%20%20%20%20%20%2C%3D%3C%200x004012c7%20%20%20%20%20%20eb09%20%20%20%20%20%20%20%20%20%20%20jmp%200x4012d2%22%7D%2C%7B%22offset%22%3A4199113%2C%22text%22%3A%22%20%20%20%20%20%20%20.--%3E%200x004012c9%20%20%20%20%20%208b4dfc%20%20%20%20%20%20%20%20%20mov%20ecx%2C%20dword%20%5Bebp%20-%204%5D%22%7D%2C%7B%22offset%22%3A4199116%2C%22text%22%3A%22%20%20%20%20%20%20%20%3A%7C%20%20%200x004012cc%20%20%20%20%20%2083c101%20%20%20%20%20%20%20%20%20add%20ecx%2C%201%22%7D%2C%7B%22offset%22%3A4199119%2C%22text%22%3A%22%20%20%20%20%20%20%20%3A%7C%20%20%200x004012cf%20%20%20%20%20%20894dfc%20%20%20%20%20%20%20%20%20mov%20dword%20%5Bebp%20-%204%5D%2C%20ecx%22%7D%2C%7B%22offset%22%3A4199122%2C%22text%22%3A%22%20%20%20%20%20%20%20%3A%60-%3E%200x004012d2%20%20%20%20%20%200fbf550c%20%20%20%20%20%20%20movsx%20edx%2C%20word%20%5Bebp%20%2B%200xc%5D%20%3B%20%5B0xc%3A2%5D%3D0xffff%20%3B%2012%22%7D%2C%7B%22offset%22%3A4199126%2C%22text%22%3A%22%20%20%20%20%20%20%20%3A%20%20%20%200x004012d6%20%20%20%20%20%203955fc%20%20%20%20%20%20%20%20%20cmp%20dword%20%5Bebp%20-%204%5D%2C%20edx%20%3B%20%5B0x18%3A4%5D%3D-1%20%3B%2024%22%7D%2C%7B%22offset%22%3A4199129%2C%22text%22%3A%22%20%20%20%20%20%20%20%3A%2C%3D%3C%200x004012d9%20%20%20%20%20%207d1a%20%20%20%20%20%20%20%20%20%20%20jge%200x4012f5%22%7D%2C%7B%22offset%22%3A4199131%2C%22text%22%3A%22%20%20%20%20%20%20%20%3A%7C%20%20%200x004012db%20%20%20%20%20%208b45fc%20%20%20%20%20%20%20%20%20mov%20eax%2C%20dword%20%5Bebp%20-%204%5D%22%7D%2C%7B%22offset%22%3A4199134%2C%22text%22%3A%22%20%20%20%20%20%20%20%3A%7C%20%20%200x004012de%20%20%20%20%20%208b4d08%20%20%20%20%20%20%20%20%20mov%20ecx%2C%20dword%20%5Bebp%20%2B%208%5D%20%3B%20%5B0x8%3A4%5D%3D-1%20%3B%208%22%7D%2C%7B%22offset%22%3A4199137%2C%22text%22%3A%22%20%20%20%20%20%20%20%3A%7C%20%20%200x004012e1%20%20%20%20%20%200fbf1441%20%20%20%20%20%20%20movsx%20edx%2C%20word%20%5Becx%20%2B%20eax%2A2%5D%22%7D%2C%7B%22offset%22%3A4199141%2C%22text%22%3A%22%20%20%20%20%20%20%20%3A%7C%20%20%200x004012e5%20%20%20%20%20%208b45f8%20%20%20%20%20%20%20%20%20mov%20eax%2C%20dword%20%5Bebp%20-%208%5D%22%7D%2C%7B%22offset%22%3A4199144%2C%22text%22%3A%22%20%20%20%20%20%20%20%3A%7C%20%20%200x004012e8%20%20%20%20%20%200345fc%20%20%20%20%20%20%20%20%20add%20eax%2C%20dword%20%5Bebp%20-%204%5D%22%7D%2C%7B%22offset%22%3A4199147%2C%22text%22%3A%22%20%20%20%20%20%20%20%3A%7C%20%20%200x004012eb%20%20%20%20%20%208a8a3cba4100%20%20%20mov%20cl%2C%20byte%20%5Bedx%20%2B%20str.AaCcdDeFfGhiKLlMmnNoOpPrRsSTtUuVvwWxyZz32.__EbgjHI__YQB%3A%5D%20%3B%20%5B0x41ba3c%3A1%5D%3D65%20%3B%20%5C%22AaCcdDeFfGhiKLlMmnNoOpPrRsSTtUuVvwWxyZz32.%5C%5CEbgjHI%20_YQB%3A%5C%5C%5C%22%2F%40%5C%5Cn%5C%5Cr%5C%5Cx1a%5C%22%22%7D%2C%7B%22offset%22%3A4199153%2C%22text%22%3A%22%20%20%20%20%20%20%20%3A%7C%20%20%200x004012f1%20%20%20%20%20%208808%20%20%20%20%20%20%20%20%20%20%20mov%20byte%20%5Beax%5D%2C%20cl%22%7D%2C%7B%22offset%22%3A4199155%2C%22text%22%3A%22%20%20%20%20%20%20%20%60%3D%3D%3C%200x004012f3%20%20%20%20%20%20ebd4%20%20%20%20%20%20%20%20%20%20%20jmp%200x4012c9%22%7D%2C%7B%22offset%22%3A4199157%2C%22text%22%3A%22%20%20%20%20%20%20%20%20%60-%3E%200x004012f5%20%20%20%20%20%200fbf550c%20%20%20%20%20%20%20movsx%20edx%2C%20word%20%5Bebp%20%2B%200xc%5D%20%3B%20%5B0xc%3A2%5D%3D0xffff%20%3B%2012%22%7D%2C%7B%22offset%22%3A4199161%2C%22text%22%3A%22%20%20%20%20%20%20%20%20%20%20%20%200x004012f9%20%20%20%20%20%208b45f8%20%20%20%20%20%20%20%20%20mov%20eax%2C%20dword%20%5Bebp%20-%208%5D%22%7D%2C%7B%22offset%22%3A4199164%2C%22text%22%3A%22%20%20%20%20%20%20%20%20%20%20%20%200x004012fc%20%20%20%20%20%20c6041000%20%20%20%20%20%20%20mov%20byte%20%5Beax%20%2B%20edx%5D%2C%200%22%7D%2C%7B%22offset%22%3A4199168%2C%22text%22%3A%22%20%20%20%20%20%20%20%20%20%20%20%200x00401300%20%20%20%20%20%208b45f8%20%20%20%20%20%20%20%20%20mov%20eax%2C%20dword%20%5Bebp%20-%208%5D%22%7D%2C%7B%22offset%22%3A4199171%2C%22text%22%3A%22%20%20%20%20%20%20%20%20%20%20%20%200x00401303%20%20%20%20%20%208be5%20%20%20%20%20%20%20%20%20%20%20mov%20esp%2C%20ebp%22%7D%2C%7B%22offset%22%3A4199173%2C%22text%22%3A%22%20%20%20%20%20%20%20%20%20%20%20%200x00401305%20%20%20%20%20%205d%20%20%20%20%20%20%20%20%20%20%20%20%20pop%20ebp%22%7D%2C%7B%22offset%22%3A4199174%2C%22text%22%3A%22%20%20%20%20%20%20%20%20%20%20%20%200x00401306%20%20%20%20%20%20c3%20%20%20%20%20%20%20%20%20%20%20%20%20ret%22%7D%2C%7B%22offset%22%3A4199175%2C%22text%22%3A%22%20%20%20%20%20%20%20%20%20%20%20%200x00401307%20%20%20%20%20%20cc%20%20%20%20%20%20%20%20%20%20%20%20%20int3%22%7D%2C%7B%22offset%22%3A4199176%2C%22text%22%3A%22%20%20%20%20%20%20%20%20%20%20%20%200x00401308%20%20%20%20%20%20cc%20%20%20%20%20%20%20%20%20%20%20%20%20int3%22%7D%2C%7B%22offset%22%3A4199177%2C%22text%22%3A%22%20%20%20%20%20%20%20%20%20%20%20%200x00401309%20%20%20%20%20%20cc%20%20%20%20%20%20%20%20%20%20%20%20%20int3%22%7D%5D

**Comment by kazarmy** [comment]
Cutter works fine here. Build from git?

![cutter-json-fix](https://user-images.githubusercontent.com/12002672/39846246-2fe78aa2-542d-11e8-8321-f9126fd94090.png)
