### ISSUE TITLE
Graph blocks are not symmetric and can't be relocated

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/cutter#485]
Here's an example of a non-symmetric graph. I used the blue arrows to emphasize the issues:

![image](https://user-images.githubusercontent.com/20182642/39857618-a15af624-543c-11e8-84ed-ab08fc461665.png)

I'd expect the red arrow at the top to be in the same line of the green one. 
I'd expect the bottom block to be centered as the top one.

Here's how IDA did it:
![image](https://user-images.githubusercontent.com/20182642/39857723-21fda56a-543d-11e8-8bd0-6ba9b7b23c85.png)

Another thing is to give the possibility to move and relocate the blocks in order to give the user more flexibility.

We can open a Meta issue with Graph related enhancements.

**Comment by xarkes** [comment]
Note that I'd like to move those widgets into an external library https://github.com/radareorg/cutter/issues/467
Which will bring more contributors to it I think.

**Comment by xarkes** [comment]
I think this issue should be splitted in two.
