### ISSUE TITLE
Fix travis cmake build

### ISSUE THREAD

**Issue by xarkes** [radareorg/cutter#49]
I thought https://github.com/radareorg/cutter/pull/33 was ok but it seems not.
It fails to find `make install`. CC @SiebelsTim

**Comment by SiebelsTim** [comment]
You already fixed it, it appears :)

**Comment by xarkes** [comment]
Well I think  there is still some error on the branch master, but it seems resolved after a tag is created while deploying...
Weird behaviour.

**Comment by SiebelsTim** [comment]
That's something about deploy. I don't know why, but 5b1337d063882 seems to be running fine.

**Comment by xarkes** [comment]
cc @Maijin

**Comment by Maijin** [comment]
Looks fixed now
