### ISSUE TITLE
Add theme editor preference tab

### ISSUE THREAD

**Issue by Maijin** [radareorg/cutter#494]
Add theme editor preference tab which includes:

- [x] colors selection for every colors settings (QColorDialog) -- (Implemented in #709)
- [ ] instant preview on the current disassembly/graph (like current disassembly/graph options)
- [ ] save/export/import theme

**Comment by optizone8** [comment]
@ITAYC0HEN 
Yeah, I thought about instant preview. But first, I think we should do some refactoring and add button 'apply' to settings dialog.

And about import/export. Do you talk about buttons that functions of copying files from/to radare2 custom schemes folder?

**Comment by ITAYC0HEN** [comment]
please split the left tasks to single issues on your free time :)

**Comment by Maijin** [comment]
Splitted.

**Comment by Maijin** [comment]
@optizone just a button that save as the theme and a button that import the theme in cutter so it can be used by the user.
