### ISSUE TITLE
Cutter is slow with big binaries

### ISSUE THREAD

**Issue by xarkes** [radareorg/cutter#498]
Currently working on a 17MB arm binary. It looks like everything is slow (seeking mainly).

**Comment by xarkes** [comment]
I suspect the navbar, maybe we should cap it to a maximum number of slices, or maybe rework the code for improvements.

**Comment by thestr4ng3r** [comment]
May be related: https://github.com/radare/radare2/issues/10162

**Comment by ulidtko** [comment]
I just loaded up a **45 MiB binary** (static link + debuginfo)... 5 minutes later, had to abort the `aaa` phase and retry without analysis. This time, it loaded up, and `aa`'d reasonably fast — however, the Cutter process now shows a crushing RSS of **6 GiB** o'ram.

Like, guys... if anyone would be willing to take on some heap profiling for this — it'd be shining cool to shave off some of this **13000%** on-disk-binary→cutter-ram amplification!

**Comment by xarkes** [comment]
Yes of course, that's why this issue is opened. Ideally it would be great if you could share the binary, because that much RAM usage might be due to the analysis of your binary.

**Comment by ulidtko** [comment]
Well it's really nothing particularly special, just a statically linked C++ service with dwarf3 debuginfo and some LLVM instrumentation (fuzz+asan). Afraid I can't simply share it, since that's uhh company property; however I guess, pretty much any similar big binary will do.

**Comment by ulidtko** [comment]
The bare `r2`, btw, eats 2.2 GiB just on loading the same binary, with additional 1.5 GiB consumed after `aa`. The total 3.7 gig is considerably smaller that cutter's; so it seems there're ways to go.

**Comment by xarkes** [comment]
Thanks for clarifying.

**Comment by thestr4ng3r** [comment]
VisualNavbar now uses p- and works much faster.

**Comment by xarkes** [comment]
So I tried with latest version on master, and although the loading is still slow and the interface freezes a bit during loading, I can navigate in the binary very fluently.
Notes:
* Clicking in the X-Refs widget still freezes which makes me think we need to do those [DisassemblyWidget improvements](https://github.com/radareorg/cutter/issues/972).

**Comment by ITAYC0HEN** [comment]
Closing. It is not a specific issue which is focused or limited
