### ISSUE TITLE
Handle multiple r2 version on system

### ISSUE THREAD

**Issue by xarkes** [radareorg/cutter#50]
The thing is, you might want to use radare2 from the command line for your daily tasks, so you would use master. However you might also want to use cutter sometimes but the version might mismatch from the one which is stable with cutter.
- [ ] Install/Copy/Whatever radare2 from cutter submodule in a separate folder (not with default ./sys/install.sh)
- [ ] On startup set PATH according to the previous installation

**Comment by blanham** [comment]
For the Install couldn't you just set `$PREFIX` before running `install.sh`?

**Comment by xarkes** [comment]
Yes the install should not be an issue. But Cutter has to find by itself the default installation PATH to this radare version.

**Comment by Maijin** [comment]
Can't you just add a detection + a possibility to add manual path

**Comment by xarkes** [comment]
Well I didn't look at all the code, but it seems it's calling `r_core_new` rather than doing a `exec("r2")`. But then I wonder why there is a warning about radare2 version, unless that's about the dynamic libraries.

**Comment by xarkes** [comment]
Actually I think we can close this because cutter calls the `r_core_new()` function from the library which is with the binary. It should never use radare2 from system environment unless the builtin libraries are deleted.

**Comment by xarkes** [comment]
Also fix share folder issues

**Comment by xarkes** [comment]
![2017-10-24-000649_602x141_scrot](https://user-images.githubusercontent.com/10772605/31915579-3ec1ba86-b84f-11e7-8941-44d0adc25e1d.png)
Seems fixed
