### ISSUE TITLE
cant load project in Cutter. "Pj": illegal value

### ISSUE THREAD

**Issue by s0i37** [radareorg/cutter#510]
I have some problems with loading r2-project in Cutter.
I dont see my projects in "projects tab" and have output:

```
(locked: no new keys can be created (asm.lines.fcn))
(locked: no new keys can be created (asm.var.subonly))
(locked: no new keys can be created (asm.var.summary))
(locked: no new keys can be created (asm.var.sub))
(locked: no new keys can be created (asm.flags.offset))
Failed to parse JSON for command "Pj": illegal value
```

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Linux kali 4.6.0-kali1-amd64 #1 SMP Debian 4.6.4-1kali1 (2016-07-21) x86_64 GNU/Linux
| File format of the file you reverse (mandatory)      | projects
| Architecture/bits of the file (mandatory)            | -
| Cutter and r2 version, See About Cutter (mandatory)  | Cutter 1.4
radare2 2.6.0-git 17895 @ linux-x86-64 git.2.5.0-24-g7b2752880
commit: 7b27528807b5d6ecfac6ef9d0498a8eefbabb31d build: 2018-04-13__23:29:57

### Expected behavior
I expected to load old projects

### Actual behavior
Failed to parse JSON for command "Pj": illegal value

### Steps to reproduce the behavior 
just open cutter

### Additional Logs, screenshots, source-code,  configuration dump, ...

My Pj output:
`["projname1","projname2"]`

**Comment by s0i37** [comment]
All good.
I removed all radare* packages (include dev,lib,etc)
Then I made:
```
export PKG_CONFIG_PATH=/opt/radare2/lib/pkgconfig/
make
```
And I have loaded my project successful!

**Comment by xarkes** [comment]
Cool, thanks for the feedback!
