### ISSUE TITLE
Add hotkey to change display type in disassembler

### ISSUE THREAD

**Issue by RobertBuhren** [radareorg/cutter#511]
Maybe something like:
"d" -> change to type "data"
"c" ->change to code
"e" -> toggle endianess
etc...

Right now I can't tell Cutter manually that a certain byte/word is actually data and not to be decoded as an opcode.
Regards,

Robert

**Comment by forGGe** [comment]
FYI: in r2 console, you can mark a block of data using visual mode:
hit `V`, then enter cursore mode by hitting `c`. After that, you can select bytes by `shift+j,k` shortcuts.
When required bytes are selected, hit `d` to change bytes meaning.

(This is just for reference, I love to see that feature in cutter)

**Comment by pelijah** [comment]
So now you can use:
* "d" to define data and switch between Byte/Word/Dword/Qword;
* "*" to define data arrays;
* "c" to delete any data meta.

**Comment by Maijin** [comment]
e cfg.bigendian

**Comment by pelijah** [comment]
I mean `swap endianess` for given offset. And `cfg.bigendian` is global setting. I think it is bad idea to add such feature to context menu and especially to add shortcut for it.

**Comment by Maijin** [comment]
yes ok understood, then that's a good feature to add to r2 tracker 👍

**Comment by pelijah** [comment]
So this issue might be closed.

**Comment by Maijin** [comment]
? Well no it needs to stay open until it's fixed on r2 side and cutter :p or we reopen an issue on cutter repo only with this swap endianess request

**Comment by Maijin** [comment]
https://github.com/radareorg/cutter/issues/608
