### ISSUE TITLE
Crash when loading Cutter executable with analysis enabled

### ISSUE THREAD

**Issue by MiroslavR** [radareorg/cutter#512]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian testing x86_64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| Cutter and r2 version, See About Cutter (mandatory)  | Cutter 14cfe743245946bd0d6808559d914f0e7d3c7c91  / Using r2 2.6.0-32-g3c8d7d53f
| Show version information **full output** (See About Cutter) in a pastebin document (mandatory) | https://gist.github.com/MiroslavR/5bbf5928d0830eef54c09e386cdfc2c4

### Expected behavior

I expected to load my build of Cutter... in my build of Cutter. :)

### Actual behavior

Cutter crashes with a segmentation fault during analysis.

### Steps to reproduce the behavior 
- Open the following binary in Cutter: [binary.zip](https://github.com/radareorg/cutter/files/2066230/binary.zip)

- Keep analysis settings at default (auto-analysis, aaa)
- Crash

### Additional Logs, screenshots, source-code,  configuration dump, ...

- Cutter output: [cutter_output.txt.zip](https://github.com/radareorg/cutter/files/2066243/cutter_output.txt.zip)
- GDB backtrace: [gdb_backtrace.txt.zip](https://github.com/radareorg/cutter/files/2066244/gdb_backtrace.txt.zip)

- `git bisect` points at 33955f95169b699df37f972102711d08f1518567 as the first bad commit, which seems to indicate this might be a R2 bug, however the R2 CLI does not exhibit this issue.
- With analysis disabled, Cutter does not crash, but manually entering `aaa` in the console *does* trigger the crash. Analysis via the R2 CLI (without Cutter) works fine.

**Comment by xarkes** [comment]
I cannot reproduce with `radare2 2.7.0-git 18579 @ linux-x86-64 git.2.6.0-101-ge6ff3aa11`
Maybe it's been fixed already?

**Comment by MiroslavR** [comment]
> I cannot reproduce with radare2 2.7.0-git 18579 @ linux-x86-64 git.2.6.0-101-ge6ff3aa11
> Maybe it's been fixed already?

Nope. I get the same crash with your Radare2 commit as well as the latest one (bc5627239).

**Comment by MiroslavR** [comment]
Something is horribly wrong. Even with a simple hello world program Cutter produces different results than Radare2 CLI. For example, outputs of the `afl` command do not match:

```
[0x00000530]> afl
0x00000000    2 60           sym.imp.__libc_start_main
0x000004e8   21 532  -> 592  sym._init
0x00000530   16 460  -> 520  entry0
```

(↑Cutter) vs (↓R2 CLI)

```
[0x00000530]> afl
0x00000000    2 60           sym.imp.__libc_start_main
0x0000021a    1 30           fcn.0000021a
0x000004e8    3 23           sym._init
0x00000510    1 6            sym.imp.puts
0x00000520    1 6            sub.__cxa_finalize_520
0x00000530    1 43           entry0
0x00000560    4 50   -> 40   sym.deregister_tm_clones
0x000005a0    4 66   -> 57   sym.register_tm_clones
0x000005f0    4 49           sym.__do_global_dtors_aux
0x00000630    1 10           entry1.init
0x0000063a    1 23           sym.main
0x00000660    4 101          sym.__libc_csu_init
0x000006d0    1 2            sym.__libc_csu_fini
0x000006d4    1 9            sym._fini
```

There is no main function in Cutter and the register use info ("aeaf") on `entry0` is completely off as well...

**Comment by xarkes** [comment]
With `aaa` in both cases?

**Comment by MiroslavR** [comment]
> With `aaa` in both cases?

Yes.

**Comment by xarkes** [comment]
Can you share that simple hello world program too?

**Comment by MiroslavR** [comment]
Sure, here it is: [helloworld.zip](https://github.com/radareorg/cutter/files/2068158/helloworld.zip)

**Comment by MiroslavR** [comment]
BTW, these are my build/run scripts:
- [Build Radare2](https://gist.github.com/MiroslavR/f85b1165979d60ebc8e6c29f4103161b)
- [Build Cutter](https://gist.github.com/MiroslavR/c3422cabd9c3d58616a917d9cf0dff9c)
- [Run Cutter](https://gist.github.com/MiroslavR/96151e5384e265a5f272d585cbef0b01)

Is there anything wrong with how I build Cutter or R2?

**Comment by MiroslavR** [comment]
Ok, I think I figured it out. For some reason, Radare2's pkgconfig (_r_core.pc_) is adding a dependency on my system capstone via `-lcapstone`, even though these libraries actually use built-in capstone. I guess the two capstones were somehow conflicting. Removing capstone from _r_core.pc_ solved all the issues mentioned in this report.

**Comment by xarkes** [comment]
Cool, thanks for investigating!
