### ISSUE TITLE
Analysis presets?

### ISSUE THREAD

**Issue by xarkes** [radareorg/cutter#514]
radare2 analysis is not meant to be fully automatic and painless. Maybe we should add some presets (rather than aaa, aaaa, custom) in the analysis window.
For example, for PPC those commands are very useful for analysis:
```
e!asm.emu
aaa
aeim
aae
```
I believe it is also useful for ARM and such.
While for x86, `aaa` is most of the time enough.

**Comment by thestr4ng3r** [comment]
Good idea. I think the analysis dialog should be revised a bit in general. It should be more clearly separated what belongs to file loading and what to analysis. Then the analysis part should be able to be split off to also be able to be used after the file has been opened without duplicating code.

**Comment by xarkes** [comment]
Sorry fail in issue number...

**Comment by xarkes** [comment]
Here's a pad to regroup different analysis presets:
https://hackmd.io/LF7lUpxdQx-MT3Zb_gtZdA

**Comment by Maijin** [comment]
That's for radare2 not cutter, we need to change aaa to reflects this hackmd ONCE this is decided

**Comment by xarkes** [comment]
What do you mean? I think r2 is not ready to have such presets, so I wanted to put that in Cutter only.

**Comment by Maijin** [comment]
I think IS ready, but we just need to define them.

**Comment by ITAYC0HEN** [comment]
this is tracked in radare2, closing here
