### ISSUE TITLE
Strings offsets are wrong

### ISSUE THREAD

**Issue by xarkes** [radareorg/cutter#516]
I loaded a binary with `-m` and it looks like the strings offsets are wrong (it points to unmapped memory)

**Comment by xarkes** [comment]
Plus it doesn't print all strings (when dealing with multiple files)

**Comment by xarkes** [comment]
The issue lies in radare2. The matter is that the virtual address is wrong for some sections.

**Comment by ITAYC0HEN** [comment]
Do we have an open issue for this in the radare2 repository?

**Comment by XVilka** [comment]
Should be transferred to radare2, @radare

**Comment by xarkes** [comment]
There's already an issue as you can see above, it's referenced as https://github.com/radare/radare2/issues/10722

**Comment by ITAYC0HEN** [comment]
Tracked in radareorg/radare2#10722
