### ISSUE TITLE
Empty and uninformative Graph on non-functions

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/cutter#518]
In cases where the seek is not in a function, like in this example (Disassembly widget):

![image](https://user-images.githubusercontent.com/20182642/40991837-adfddc4a-68fd-11e8-97c2-915a2dbac473.png)

We will get an emty graph on the Graph Widget:

![image](https://user-images.githubusercontent.com/20182642/40991880-cc2002c0-68fd-11e8-98e6-4fcead1504fd.png)

I'm suggesting to put a visible text in the middle of the widget saying: "Graph mode can only display instructions which belong to functions"

IDA chose to create a message box saying:

> IDA failed to display the program in graph mode.
> Only instructions belonging to functions can be displayed in graph mode.
> For other program items IDA uses the text representation.

----

At the code level, I think it is something simple to validate since `agj` will return an empty array when it is executed from outside a function. Thus, we can simply check the output of the following [line](https://github.com/radareorg/cutter/blob/0cea9e3287fa12a8a240834a7484c1a957f686c1/src/widgets/DisassemblerGraphView.cpp#L154) for an empty result:
```
QJsonDocument functionsDoc = Core()->cmdj("agJ " + RAddressString(seekable->getOffset()));
```

**Comment by xarkes** [comment]
Agreed.
By the why I wonder why there is black text?

**Comment by dharmangbhavsar** [comment]
Hi! This might be my first contribution so can you help me here? You just want to check the QJsonDocument object for emptiness right? And for the text in the window, I was not able to find the window handle for the setWindowText() function, if you're using that!

**Comment by xarkes** [comment]
Yes exactly @dharmangbhavsar, just make a pull request and we will guide you from here if anything is wrong.
For inspiration you can take a look at `JupyterWidget.cpp`, it also prints a text if Jupyter is not available.

**Comment by ITAYC0HEN** [comment]
Also, great to have you with us Dharmang (@dharmangbhavsar)! Welcome aboard!

**Comment by xarkes** [comment]
Waiting for https://github.com/radareorg/cutter/pull/537

**Comment by xarkes** [comment]
Fail in issue number, fixed in https://github.com/radareorg/cutter/commit/22465615a4cda2c9bf6a2efd5667b62dba1d8814
