### ISSUE TITLE
Add file->export as code->XXX

### ISSUE THREAD

**Issue by Maijin** [radareorg/cutter#54]
```
  e io.va = false
```

followed by:

```
  pc     C
  pc*    print 'wx' r2 commands
  pch    C half-words (2 byte)
  pcw    C words (4 byte)
  pcd    C dwords (8 byte)
  pca    GAS .byte blob
  pcA    .bytes with instructions in comments
  pcs    string
  pcS    shellscript that reconstructs the bin
  pcj    json
  pcJ    javascript
  pcp    python

 $s # for filesize
 @ 0 # for beginning of size
```

Into file -> exports -> code then in the save menu just give the user capability to choose formats in a droplist, adding the default extension accordingly.

Example python: `filename.py`

**Comment by Maijin** [comment]
@pelijah this one should be ok to do now without changes in r2

**Comment by pelijah** [comment]
Can you provide an example for using `$s # for filesize`?

**Comment by Maijin** [comment]
? $ are variable that holds values, you can do `pc $s @ XXX ` for example See ?$?
