### ISSUE TITLE
Can't see the switch statement graph after the jump statement

### ISSUE THREAD

**Issue by mien** [radareorg/cutter#544]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             |Ubuntu 18
| File format of the file you reverse (mandatory)      | ELF etc.
| Architecture/bits of the file (mandatory)            | x86
| Cutter and r2 version, See About Cutter (mandatory)  | Version 1.4 / Using r2 2.5.0-105-gc79874941

### Expected behavior
Should be showing further assembly code

### Actual behavior
Not showing any code after the jump statement

### Steps to reproduce the behavior 
- Please share the binary if it is shareable by drag and dropping it here in a zip archive (mandatory)
- Use code markdown `CODE` to make your code visible

### Additional Logs, screenshots, source-code,  configuration dump, ...
![screenshot from 2018-06-20 14-50-50](https://user-images.githubusercontent.com/4955894/41649803-10a3c646-749a-11e8-84f3-dc1306903a57.png)

**Comment by radare** [comment]
e anal.jmptbl=true

**Comment by mien** [comment]
sorry didn't get you !

**Comment by xarkes** [comment]
Try to manually set this setting in the Console.
`e anal.jmptbl=true`
After that refresh the view, it might fix it.

**Comment by mien** [comment]
Nope not working

**Comment by radare** [comment]
You have to set this option before analyzing the function

**Comment by radare** [comment]
Dunno if cutter have this option anywhere im just speaking about r2

**Comment by Maijin** [comment]
![image](https://user-images.githubusercontent.com/1408600/41665178-acc23370-74a7-11e8-8fbb-2508f21357fb.png)

**Comment by xarkes** [comment]
Closing as activating this jmptbl option fixes it.

**Comment by rdrpenguin04** [comment]
However, there is another switch pattern that this doesn't detect:
```
lea rcx, [0x000e8040]
movsxd rax, dword [rcx + rax*4]
add rax, rcx
jmp rax
```
I'm not sure if this is generated by GCC or Clang, I found it in a binary that references both.

**Comment by karliss** [comment]
@rdrpenguin04 This issue has been closed for more than 2 years.  If you have issues with current versions please create a new issue filling in all the requested information.
