### ISSUE TITLE
Add file -> save as 

### ISSUE THREAD

**Issue by Maijin** [radareorg/cutter#55]
To save the project in a different directory

**Comment by thestr4ng3r** [comment]
Projects should be re-done completely imo. My proposal:
- The file opening dialog shows the list of projects from `Pl` in addition to the last opened files.
- Regular save saves with `prj.name` or prompts for a name if it unset.
- "Save as" always prompts for a name
- Maybe add an additional dialog that lists all projects, so you can delete some.

That way, project management is transparently bound to r2 projects.

**Comment by Maijin** [comment]
Yep that sounds good to me

**Comment by xarkes** [comment]
Ok
