### ISSUE TITLE
Text highlighting in "Graph" mode

### ISSUE THREAD

**Issue by s0i37** [radareorg/cutter#558]
Hello.
May you please add highlighting some text in "graph" mode as well as in "Disassembly"?

**Comment by xarkes** [comment]
I think this is a duplicate for https://github.com/radareorg/cutter/issues/444

**Comment by s0i37** [comment]
No no no. In #444 I mean highligthing instruction like a "ecHi". But here I mean that then I select some var or register it will not highlighted in another instructions.

**Comment by xarkes** [comment]
Ah ok sorry.

**Comment by Maijin** [comment]
ok so this is already done in disassembly mode then

**Comment by s0i37** [comment]
I updated cutter and r2 today. But I have no highlighting in graph window

**Comment by Maijin** [comment]
i said in disassembly.

**Comment by pelijah** [comment]
Dup of #97
