### ISSUE TITLE
GUI Bug : Disassembly Window jumps to top on instruction click in Graph Window

### ISSUE THREAD

**Issue by gmastergreatee** [radareorg/cutter#560]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Windows 8.1 x86_64
| File format of the file you reverse (mandatory)      | any PE(*.exe) file
| Architecture/bits of the file (mandatory)            | x86/32 or x86/64
| Cutter and r2 version, See About Cutter (mandatory)  | Version 1.5 / Using r2 2.6.9-159d16b34550f4

### Info
In the standalone window mode, the disassembly window jumps to top view whenever any instruction on the graph view is selected.

Expected Result : The graph should be on the top whenever any instruction is selected on it.

![cutter_gui_bug](https://user-images.githubusercontent.com/17880848/42205860-303d8e3c-7ec3-11e8-9daa-cb94cbbb2438.gif)

**Comment by ITAYC0HEN** [comment]
Tested and it is now fixed :)
