### ISSUE TITLE
opcode description

### ISSUE THREAD

**Issue by Firpo7** [radareorg/cutter#562]
# I don't understand why in the opcode description there isn't any description...

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             |Ubuntu x86 64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| Cutter and r2 version, See About Cutter (mandatory)  | Version 1.5 / Using radare2 2.6.9 0 @ linux-x86-64 git.2.6.9

### Expected behavior
when i click a row I would see the description of the opcode..for example if I click a row where there is "add" I would see:
adds src and dst, stores result on dst

### Actual behavior
instead of it a see
\# Usage:
[.][times][cmd][~grep][@[@iter]addr!size][|>pipe] ; ...
Append '?' to any char command to get detailed help
Prefix with number to repeat command N times (f.ex
### Steps to reproduce the behavior 
- open a file with cutter and click a line

**Comment by xarkes** [comment]
Thanks for reporting the issue.
