### ISSUE TITLE
Remove QWebEngine dependency and Jupyter widget

### ISSUE THREAD

**Issue by pelijah** [radareorg/cutter#567]
Jupyter can be ran from web browser. I think no need to use this heavy QWebEngine that increases load time and distro size.

**Comment by XVilka** [comment]
Then there will be no integration with cutter. That was the point,
switching between Windows is an unneeded headache.

**Comment by xarkes** [comment]
Anyway this is already possible through the `CUTTER_ENABLE_JUPYTER` and `CUTTER_ENABLE_QTWEBENGINE` variables during compilation.
Maybe we can do different packages like one with it and one without it.

**Comment by pelijah** [comment]
What is main need of using Jupyter+WebEngine? Running Python scripts from Cutter?

**Comment by XVilka** [comment]
No, rich notebook for storing research notes, scripts results, mathematics
formulas, diagrams, sharing this kind of dashboard with other researchers.
