### ISSUE TITLE
Delete *.ui files for simple widgets

### ISSUE THREAD

**Issue by pelijah** [radareorg/cutter#568]
- [ ] BacktraceWidget

- [ ] BreakpointWidget

- [ ] ClassesWidget

- [ ] CommentsWidget

- [ ] ConsoleWidget

- [ ] EntrypointWidget

- [ ] ExportsWidget

- [ ] FlagsWidget

- [ ] FunctionsWidget

- [ ] HeadersWidget

- [ ] ImportsWidget

- [ ] MemoryMapWidget

- [ ] PseudocodeWidget

- [ ] RegisterRefsWidget

- [ ] RegistersWidget

- [ ] RelocsWidget

- [x] SectionsWidget

- [ ] StackWidget

- [ ] StringsWidget

- [ ] SymbolWidgets

- [ ] TypesWidget

- [ ] VTablesWidget

- [ ] ZignaturesWidget

**Comment by xarkes** [comment]
I agree with this issue, in my opinion there's no need to overload everything with `.ui` files. But I've been told that it's harder to understand the UI when those are not present and you have to read C++.

**Comment by pelijah** [comment]
I have added the list of suggestions.

**Comment by pelijah** [comment]
> I agree with this issue, in my opinion there's no need to overload everything with `.ui` files. But I've been told that it's harder to understand the UI when those are not present and you have to read C++.

We can add some layout templates. Most widgets share same layout (e.g. TreeView + QuickFilter). One polished function in `common` can help us to kill tens of UI files.

**Comment by ITAYC0HEN** [comment]
so what are the future steps here?

**Comment by ITAYC0HEN** [comment]
ping @xarkes @pelijah

**Comment by xarkes** [comment]
I don't know, after all I have arguments for and against this so I'm not sure what the best decision is.

**Comment by ITAYC0HEN** [comment]
a few days ago a new contributor got confused by the lack of UI file in the Segments widget. I personally enjoy working with UI files

**Comment by xarkes** [comment]
Then we can close it I believe.
