### ISSUE TITLE
No more functions into the functions windows with cutter 1.5 64 bits on windows 7

### ISSUE THREAD

**Issue by deckbsd** [radareorg/cutter#571]
Hello,

I just unziped the cutter 1.5 for win64, and not matter regarding which PE file i load, there is no more functions in the functions GUI window.

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Windows 7 64 bits
| File format of the file you reverse (mandatory)      | PE 32 - 64 bits
| Architecture/bits of the file (mandatory)            | x86/32, x86/64
| Cutter and r2 version, See About Cutter (mandatory)  | Version 1.5 / Using r2 2.6.9-159d16b34550f4

### Expected behavior
Be able to look the functions into the functions window.
### Steps to reproduce the behavior 
- After extracting cutter 1.5 (win 64)
- load a simple PE file
- The functions doesn't appear

PS : the 1.4 version is working fine if it can helps.

**Comment by xarkes** [comment]
Hi, it's a known issue which is fixed on master.
I will soon release new binaries.
