### ISSUE TITLE
Cutter 1.5 Windows Console not Working

### ISSUE THREAD

**Issue by SpenserStyles** [radareorg/cutter#572]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Windows 10 x64
| File format of the file you reverse (mandatory)      | BIN
| Architecture/bits of the file (mandatory)            | arm cortex-m 32-bit
| Cutter and r2 version, See About Cutter (mandatory)  | Version 1.5 / Using r2 2.6.9-159d16b34550f4
| Show version information **full output** (See About Cutter) in a pastebin document (mandatory) | https://gist.github.com/

### Expected behavior
console to work as command line

### Actual behavior
Console does not work on Windows 64-bit or 32-bit releases.  It does work on Mac release.

### Steps to reproduce the behavior 
Launch Cutter
Type '?' into console prompt and hit enter and nothing except prompt and ? is printed in output.

**Comment by pelijah** [comment]
Already fixed in master. @xarkes what about 1.5.1?

**Comment by pelijah** [comment]
You can download the latest Cutter build from AppVeyor.

**Comment by xarkes** [comment]
Yes it's planned.
