### ISSUE TITLE
Excessive spacing and lines in Disassembly/Graph view

### ISSUE THREAD

**Issue by Adikso** [radareorg/cutter#573]
When you try to make graph look minimal and you disable everything except disassembly you get this excessive spacing on the left side.
![screenshot_20180711_151957](https://user-images.githubusercontent.com/1407751/42574699-5630c980-851f-11e8-871d-157fa24ab965.png)

It would be nice if you could make it look like this:
![screenshot_20180711_151915](https://user-images.githubusercontent.com/1407751/42574712-5b5a9d64-851f-11e8-8bc7-59186a69e8c3.png)

But I see it's actually what `agJ` outputs. Also it could look more clear if comments like ; "Hello World!" would be on the right side of instruction and not above it. I couldn't find a way to force radare into making graph without this spacing (Just did `replace("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;", "");` for second example). 

I don't have idea what would be a suitable way of making changes like this

**Comment by xarkes** [comment]
Hi, I think it's the `agJ` command in radare2 which is not correct.
There must be an additionnal wrong printf when `e asm.offset=false`.
I think it's easy to fix (just add a if (json and offset=false)) if you find the correct place.

**Comment by xarkes** [comment]
Closing as #577 mostly solves it.

**Comment by xarkes** [comment]
But for the graph view we should use `graph.offset` config variable.
