### ISSUE TITLE
Graph with a Jump Table shows overlapping blocks without arrows

### ISSUE THREAD

**Issue by thestr4ng3r** [radareorg/cutter#574]
Binary: [ls.tar.gz](https://github.com/radareorg/cutter/files/2186001/ls.tar.gz)

Open with aaa in Cutter and display graph at sub.__overflow_ba0:
![bildschirmfoto vom 2018-07-11 21-51-03](https://user-images.githubusercontent.com/1460997/42596249-4a1bf3d2-8555-11e8-86c6-bd864ac90f2c.png)

Looks fine in VV.

**Comment by xarkes** [comment]
It's actually a jumptable. The `jmp rax` block has no `jump` attribute (from `agJ` output), which is why the graph doesn't print any arrow.
Maybe we should change the `jump` format to an array?

**Comment by ITAYC0HEN** [comment]
Another example: https://github.com/radareorg/cutter/issues/622

**Comment by CraftSpider** [comment]
Having the same issue here while disassembling a file with an unconditional jump to near the end of the function as the first instruction.
