### ISSUE TITLE
Update https://github.com/radareorg/cutter/issues/417

### ISSUE THREAD

**Issue by mohe2015** [radareorg/cutter#600]
As the conversation is locked can a collaborator please add the following note to https://github.com/radareorg/cutter/issues/417 for further users which stumble upon that error message: You need to install  python3-pkgconfig and python3-dev.

It's pretty obvious but maybe it saves somebody a few minutes.

Thanks

**Comment by Maijin** [comment]
Thanks, I have added it, don't forget you can use our pre-built binaries too - https://github.com/radareorg/cutter/releases.
