### ISSUE TITLE
Double clicking in the open button causes strange behaviour

### ISSUE THREAD

**Issue by radare** [radareorg/cutter#604]
In my mac i get a crash, but other people get double-guis in windows.

![image 2018-08-01 20 14 19](https://user-images.githubusercontent.com/917142/43540242-7a826c54-95c7-11e8-98a5-1e45189d8a8b.jpg)

**Comment by xarkes** [comment]
You didn't specify the version, how are we supposed to help you?

**Comment by xarkes** [comment]
Anyway I managed to reproduce. Will fix.

**Comment by radare** [comment]
I downloaded the 1.6 release. Sorry for being an asshole

**Comment by xarkes** [comment]
Typical radare2 contributor.
