### ISSUE TITLE
Implement afvn to rename argument/local

### ISSUE THREAD

**Issue by fabianMendez** [radareorg/cutter#605]
Implement an option for `afvn` to rename argument/local variables 
![image](https://user-images.githubusercontent.com/32204060/43552552-8bcafbb4-95b0-11e8-84e6-3f7068671853.png)

**Comment by xarkes** [comment]
This is already available when you click in the disassembly.
![2018-08-02-083741_1920x1080_scrot](https://user-images.githubusercontent.com/10772605/43566701-a0ca819a-962f-11e8-86f1-3c21b57eb6db.png)

**Comment by xarkes** [comment]
Well, we can discuss before closing, because it's true that this option should also be available when right clicking in the head of the block.
This requires to separate each line and only highlight one.

**Comment by Maijin** [comment]
Right

**Comment by thestr4ng3r** [comment]
yeah, needs some things in `pdJ`

**Comment by jamieb122** [comment]
@xarkes May not need to do that.  I am actually working a context menu item that will allow you to set types of local vars (could easily add re-name to it as well).  Context item is *basically* "Manage local vars (types/names)"  In the dialog, you can select the variable you are looking to manage and change the type.  Changing the name at the same time would just be another text box.  I have it working with type changes now, and should have the name change implemented by this weekend.

I'll submit a pull request by this weekend to see if it fits the need.

**Comment by jamieb122** [comment]
See pull request afvn Context Menu functionality #707

**Comment by jamieb122** [comment]
Suggest closing this issue, as the feature was inplemented in latest commit

**Comment by xarkes** [comment]
Yes indeed. Closed in #708.

**Comment by ITAYC0HEN** [comment]
Is it only me or we still can't rename local vars on the top of the first block?
Should be available using `Shift+N` or `right click-> rename var_4` as in other blocks 

@jamieb122 @xarkes 

![image](https://user-images.githubusercontent.com/20182642/46571919-3f52ed00-c986-11e8-89c2-cad32a2e63b5.png)

**Comment by ITAYC0HEN** [comment]
actually, I don't want a complicated dialog for renaming. I prefer `"Shift+N" -> (all text selected in the textbox) typing name -> enter`. I don't see why can't it be two different dialogs (same as IDA has)

**Comment by jamieb122** [comment]
> actually, I don't want a complicated dialog for renaming. I prefer `"Shift+N" -> (all text selected in the textbox) typing name -> enter`. I don't see why can't it be two different dialogs (same as IDA has)

To do this in the function header, the dissasembly needs to be changed so that each line is separately selectable...I think more processing would need to be done in the disassembly widget to determine if the address is at a function (not just in a function), and then somehow parse out which variable is referenced via which line.  Probably doable but I imagine the implementation might have to be a little hacky based on how the imformation is pulled from r2.  I could be way off the mark though
