### ISSUE TITLE
Local/argument variables not getting reflected in the assembly

### ISSUE THREAD

**Issue by fabianMendez** [radareorg/cutter#606]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Windows x86 32
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/32
| Cutter and r2 version, See About Cutter (mandatory)  | Version 1.6 / Using r2 2.7.0
| Show version information **full output** (See About Cutter) in a pastebin document (mandatory) | [Version information](https://gist.github.com/fabianMendez/709cedaf30b29714a18ce67976fdbffa)

### Expected behavior
If a base/stack pointer is flagged as an argument or local variable it should be reflected in the assembly code
### Actual behavior
Argument/local variables are not reflected in the assembly code

### Steps to reproduce the behavior 
- Open the given file
- Set the analisis level to Auto-Analysis
- Clic ok
- Seek to the main function at 0x08048208
- Local variables like local_4h are not getting reflected in the assembly code:
![image](https://user-images.githubusercontent.com/32204060/43553148-2d0e1338-95b3-11e8-8b1c-b5bdb7b018ee.png)
- If I open the same file with radare2 I get:
```asm
/ (fcn) main 306
|   main (int arg_8h, int arg_ch);
|           ; var int local_14h @ ebp-0x14
|           ; var int local_8h_2 @ ebp-0x8
|           ; var int local_4h @ ebp-0x4
|           ; arg int arg_8h @ ebp+0x8
|           ; arg int arg_ch @ ebp+0xc
|           ; var int local_4h_2 @ esp+0x4
|           ; var int local_8h @ esp+0x8
|           ; var int local_ch @ esp+0xc
|           ; DATA XREF from 0x08048127 (entry0)
|           0x08048208      55             push ebp
|           0x08048209      89e5           mov ebp, esp
|           0x0804820b      83ec28         sub esp, 0x28               ; '('
|           0x0804820e      83e4f0         and esp, 0xfffffff0
|           0x08048211      b800000000     mov eax, 0
|           0x08048216      83c00f         add eax, 0xf
|           0x08048219      83c00f         add eax, 0xf
|           0x0804821c      c1e804         shr eax, 4
|           0x0804821f      c1e004         shl eax, 4
|           0x08048222      29c4           sub esp, eax
|           0x08048224      c745fca03d7f.  mov dword [local_4h], 0x4b7f3da0
```

This is a file from [crackmes.de](https://crackmes.one/crackme/5ab77f5333c5d40ad448c0f4)
[qcrk5.zip](https://github.com/radareorg/cutter/files/2251347/qcrk5.zip)

**Comment by xarkes** [comment]
As seen in your other issue, I cannot reproduce that behaviour, even with default options.
Ok found the bug: in the preferences asm.var.sub is not checked by default, while the option is ON.
When check it nothing happens, and when unchecking it the local_4h is replaced by esp+4

**Comment by xarkes** [comment]
So for now you should manually click both options: `asm.var.sub` and `asm.var.subonly` in the preferences settings.

**Comment by fabianMendez** [comment]
@xarkes it works, thanks
