### ISSUE TITLE
Cannot assemble 'movl $1, %eax' at line 3

### ISSUE THREAD

**Issue by pangqingyuan1991** [radareorg/cutter#607]
When I change asm format to att, it can't write instruction any more. And says "Cannot assemble 'movl $1, %eax' at line 3".
Doesn't it support changing instruction when in att format?

**Comment by fcasal** [comment]
Yes, I believe there still isn't att assembler support in radare2 yet. Related issue on r2 side: https://github.com/radare/radare2/issues/8291

**Comment by pangqingyuan1991** [comment]
OK. So I close this issue.
