### ISSUE TITLE
Flags not created after loading PDBs

### ISSUE THREAD

**Issue by riverar** [radareorg/cutter#615]
## Environment
Windows 10 x64 17134.191 (RS4)
Visual Studio 2017 Preview 15.8

Version 1.6
Using r2-r2.8.0-64-g404e4a1b7

## Expected behavior
After loading symbols from the symbol store (or manually via `idpd`), I expect to see flags created for each symbol in the pdb.

## Actual behavior
Flags missing

## Steps to reproduce the behavior
1. Open C:\Windows\System32\Uxtheme.dll
2. `idpd` to ensure symbol store is populated or use UI to load .pdb manually
3. Note: `f~pdb.~?` returns 0 when it should be around 10401
4. Note: `f~CThemeMemStream::Stat` returns 0

[uxtheme_payloads.zip](https://github.com/radareorg/cutter/files/2281833/uxtheme_payloads.zip)

----

@WithinRafael in the Cutter Telegram group, if you need to chat.

**Comment by xarkes** [comment]
Did you try that within r2 cli? Does it work as expected there?

**Comment by riverar** [comment]
@xarkes I _thought_ I had it working in standalone R2 CLI but appears not. 😢 

Sounds like an r2 bug. Want me to repost the issue there?

```
radare2 2.9.0-git 19189 @ windows-x86-64 git.2.8.0-68-g1854ced04
commit: 1854ced04278b5af833a3e09223fcfb9b90e33c6 build: Mon 08/13/2018__ 0:38:25.56
```

**Comment by xarkes** [comment]
Yes please :)

**Comment by riverar** [comment]
User error; `idpd` only populates the symbol store. `idp` loads symbol information and populates flags. Thanks all.
