### ISSUE TITLE
Prettier function names

### ISSUE THREAD

**Issue by Adikso** [radareorg/cutter#620]
Make cutter show function name:
`sym.SomeClass::method_int_int_int_int_int_int`
as
`SomeClass::method(int,int,int,int,int,int)`
in Functions widget

**Comment by ITAYC0HEN** [comment]
This should be implemented in radare2 as eval variable and not in Cutter. See the discussion in this pull request (which rightly wasn't accepted) :
https://github.com/radareorg/cutter/pull/519
