### ISSUE TITLE
Graphing Bug

### ISSUE THREAD

**Issue by securitykitten** [radareorg/cutter#622]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Fedora 28 x86_64
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86/32
| Cutter and r2 version, See About Cutter (mandatory)  | Version 1.6 / Using r2 2.7.0-247 https://ghostbin.com/paste/36gj2

### Expected behavior
Graph to render properly

### Actual behavior
![screenshot from 2018-08-15 14-54-53](https://user-images.githubusercontent.com/5833122/44167429-160b9400-a09c-11e8-80ae-b762bbc9a809.png)

### Steps to reproduce the behavior 
1. Load the binary, open graph view, in the disassembler seek to 0x0040a941 

Caution malware
[testing.zip](https://github.com/radareorg/cutter/files/2291362/testing.zip)

**Comment by xarkes** [comment]
I think it is more or less the same as https://github.com/radareorg/cutter/issues/574
