### ISSUE TITLE
macOS Application Bundle loads system r2 libraries

### ISSUE THREAD

**Issue by thestr4ng3r** [radareorg/cutter#629]
present in 1.7 as reported by @radare

rpath doesn't seem to work properly:
![photo_2018-08-18_13-05-30](https://user-images.githubusercontent.com/1460997/44298671-6e82a180-a2e7-11e8-8533-0530693c15f1.jpg)
![photo_2018-08-18_13-02-23](https://user-images.githubusercontent.com/1460997/44298662-5c086800-a2e7-11e8-8429-164b358c59aa.jpg)

**Comment by trufae** [comment]
This is my workaround
```
$ cat Cutter
#!/bin/sh
export DYLD_LIBRARY_PATH=/Applications/Cutter.app/Contents/Frameworks
/Applications/Cutter.app/Contents/MacOS/Cutter.orig $*
$ pwd
/Applications/Cutter.app/Contents/MacOS
```
