### ISSUE TITLE
Fix color on Windows

### ISSUE THREAD

**Issue by xarkes** [radareorg/cutter#63]
I think it requires a fix of `ecj` on Windows, at least some investigation and a proper fix.

**Comment by radare** [comment]
What's the problem exactly? ecj output should be portable? is this an issue in r2?

**Comment by xarkes** [comment]
Well I pushed a small fixed already in radare2 https://github.com/radare/radare2/commit/0ee70731224cc59c064ff389d284d86bbfd58dd2 which seems to improve the colors but it's not perfect.
Anyway `ecj` is used to retrieve the current theme color codes, and it's parsing ANSI colorcodes to RGB which is why there are some issues on Windows.

**Comment by Maijin** [comment]
@skuater maybe ?

**Comment by skuater** [comment]
this seem be a problem parsing values from scheme, cutter are loading correctly the profile scheme?? plz check this.

**Comment by xarkes** [comment]
So I tested with `scr.ansicon=true` and it does not modify the output of `ecc` or `ecj`.

**Comment by xarkes** [comment]
Or we can stop relying on r2 for the colors and have our own themes and colors.

**Comment by xarkes** [comment]
Should be fixed with 84168cb340e620d38a1e80f044e85a1568715f58
