### ISSUE TITLE
debug/emulation buttons are too big

### ISSUE THREAD

**Issue by trufae** [radareorg/cutter#631]
(and they get bigger when you click them)

<img width="999" alt="screen shot 2018-08-18 at 13 05 22" src="https://user-images.githubusercontent.com/6431515/44298730-860e5a00-a2e8-11e8-9da9-beefee97efb6.png">

**Comment by ITAYC0HEN** [comment]
definitely too big. We're working on fixing this, current ones are bad
Thanks, closing as duplicate <3
