### ISSUE TITLE
Inconsistent interline spacing with utf8

### ISSUE THREAD

**Issue by trufae** [radareorg/cutter#633]
(and alien xe2x94x82 at left)
<img width="762" alt="screen shot 2018-08-18 at 13 14 49" src="https://user-images.githubusercontent.com/6431515/44298742-c5d54180-a2e8-11e8-8c3d-8a303651ead9.png">

**Comment by ITAYC0HEN** [comment]
yup, we are tracking it in #413. @xarkes found the fix but we have a problem with alignments.
Closing as duplicate
