### ISSUE TITLE
'u' key not handled in graphs

### ISSUE THREAD

**Issue by trufae** [radareorg/cutter#635]
Using 't' and 'f' is graphs is great. but would be better if cuttr handles 'u' to undo seek tot he previous selected basic block like in r2

**Comment by trufae** [comment]
ok that works, was expecting the same keys as in r2. what do you think
about having 'u' also in here?

**Comment by pelijah** [comment]
We shouldn't waste available shortcuts.

**Comment by Maijin** [comment]
agree with @pelijah esc is more natural too in graphical interface for this

**Comment by ITAYC0HEN** [comment]
I think it won't bring major benefit and Esc is a standard in GUI RE tools. We can keep 'u' for something else, maybe Undo-Editing when implemented

**Comment by xarkes** [comment]
I also agree with the others, we can keep 'u' for something else.
