### ISSUE TITLE
Add a button to close the side bar of the hexdump

### ISSUE THREAD

**Issue by trufae** [radareorg/cutter#636]
When having some splits in makes it unreadable

<img width="418" alt="screen shot 2018-08-18 at 13 19 33" src="https://user-images.githubusercontent.com/6431515/44298772-6d527400-a2e9-11e8-81f5-ab851f34b9ff.png">

**Comment by ITAYC0HEN** [comment]
why not both? :)
good idea

**Comment by pelijah** [comment]
You can hide it using splitter.
