### ISSUE TITLE
Add the ability to sync the seek between two widgets

### ISSUE THREAD

**Issue by trufae** [radareorg/cutter#637]
Scrolling in disasm may update the graph view if in sync (or hexdump, or whatever)

**Comment by trufae** [comment]
oh i think this is already done

<img width="324" alt="screen shot 2018-08-18 at 13 28 23" src="https://user-images.githubusercontent.com/6431515/44298824-9f180a80-a2ea-11e8-8290-731dc1cfd339.png">

**Comment by ITAYC0HEN** [comment]
Yup, already implemented :)
