### ISSUE TITLE
Context menu is missing in the graph view

### ISSUE THREAD

**Issue by trufae** [radareorg/cutter#638]
I would add options like this:

* [ ] toggle bytes
* [x] toggle offset

**Comment by pelijah** [comment]
I think we should add separate settings "Show offset"/"Show bytes" for GraphView to Preferences

**Comment by trufae** [comment]
sgtm

**Comment by ITAYC0HEN** [comment]
Show offset toggle for the graph is already available in the preferences menu.
I'm not sure we should split asm.bytes as well (which will require another eval in radare2 (iirc)

**Comment by pelijah** [comment]
Really?
![default](https://user-images.githubusercontent.com/16493991/44301270-c1c31700-a31c-11e8-9994-ad7f3a8da854.png)

**Comment by ITAYC0HEN** [comment]
You are probably not using latest release / version from git

![image](https://user-images.githubusercontent.com/20182642/44301464-02705f80-a320-11e8-9218-e3ae970f878e.png)

**Comment by xarkes** [comment]
It depends what you mean by "show comments"? I think we can enable that for all the analysis stuff, but keep user comments.

**Comment by Maijin** [comment]
Probably you can also add an option like:

- Show user comment
- Show automatic comment or something (don't think we need the level of granularity available in r2 for now)

**Comment by ITAYC0HEN** [comment]
Offset toggling is already implemented for graph in the preferences window. So this is nice :)

Bytes toggling isn't available in radare2 (there is no graph.bytes) and I don't think I want to separate it. Another extra configuration that people can live without
