### ISSUE TITLE
String panel don't show strings.

### ISSUE THREAD

**Issue by JorgeTebruski** [radareorg/cutter#643]
### Work environment

|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Windows 10 home 1803 x64
| File format of the file you reverse (mandatory)      | PE, ELF x86/64
| Architecture/bits of the file (mandatory)            | PPC, x86/32, x86/64 etc.
| Cutter and r2 version, See About Cutter (mandatory)  | Version 1.7 / Using r2 2.8.0

The search box shows the searched string but in the string pane does not show anything in any file format.

![bug](https://user-images.githubusercontent.com/38569298/44316223-e09ad980-a400-11e8-8ab0-3de56db2c439.png)

**Comment by Obaied** [comment]
Same problem reproduced

**Comment by xarkes** [comment]
Ah ok thx.

**Comment by xarkes** [comment]
The key is `string`, I see it with `izj` and `izzj`.

**Comment by Maijin** [comment]
Ok so that's because someone updated `izzj` for radeco iirc

**Comment by pelijah** [comment]
@xarkes 
![default](https://user-images.githubusercontent.com/16493991/44391519-c3692680-a538-11e8-80f6-6d3d8f31a83c.png)

**Comment by radare** [comment]
oh right, i think kazarmy changed this 2 weeks ago

**Comment by pelijah** [comment]
`is_array` is not set for `izzj` command.
https://github.com/radare/radare2/blob/master/libr/core/cmd_info.c#L344
