### ISSUE TITLE
require Qt 5

### ISSUE THREAD

**Issue by darcosion** [radareorg/cutter#645]
When I try to compile, that doesn't work with QT4.

Can y suggest to specify
`lessThan(QT_MAJOR_VERSION, 5): error("requires Qt 5")` 
?

It could be better to the compilation.

**Comment by Maijin** [comment]
Can you create a Pull request with your suggested solution ? You can use Github pencil - https://help.github.com/articles/editing-files-in-your-repository/

**Comment by darcosion** [comment]
Done.
https://github.com/radareorg/cutter/pull/646
