### ISSUE TITLE
Project ERROR: r_core development package not found

### ISSUE THREAD

**Issue by wilo17** [radareorg/cutter#648]
Project ERROR: r_core development package not found

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | FEDORA intel 64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64 
| Cutter and r2 version, See About Cutter (mandatory)  | Version 1.7 / Using r2 2.8.0
| Show version information **full output** (See About Cutter) in a pastebin document (mandatory) | https://gist.github.com/

### Expected behavior
./build.sh   ==> MakeFile
### Actual behavior

Correct radare2 version found, skipping...
mkdir: impossible de créer le répertoire « build »: File exists
Project MESSAGE: Jupyter support disabled.
Project MESSAGE: QtWebEngine support disabled.
Project ERROR: r_core development package not found
make: *** Pas de cible spécifiée et aucun makefile n'a été trouvé. Arrêt.
Something went wrong!

**Comment by Maijin** [comment]
Greetings @wilo17,

We are glad you are trying to compile Cutter and we are sorry to hear that the process failed.

If you want to compile the project yourself, please make sure you are following the instructions provided in the README and using the radare2 submodule provided, someone will check your problem shortly.

**PLEASE NOTE**. If you just want to use cutter: use our releases available for windows/OSX and Linux - https://github.com/radareorg/cutter/releases

**Comment by wilo17** [comment]
I tried Cutter-v1.7-x86_64.AppImage, there is segmentation fault when I try to open a file.

[wilo@localhost SECURITY_TOOLS]$ ./Cutter-v1.6-x86_64.AppImage 
Setting r2 prefix = "/tmp/.mount_CutterZD7OLq/usr"  for AppImage.
Setting PYTHONHOME = "/tmp/.mount_CutterZD7OLq/usr"  for AppImage.
PYTHONHOME = "/tmp/.mount_CutterZD7OLq/usr"
Segmentation fault (core dumped)

**Comment by xarkes** [comment]
ping @wilo17? And try again with `1.7.1` AppImage please. Thanks.

**Comment by xarkes** [comment]
For the compiling issue, your radare2 installation is probably wrong. Try removing any radare2 from your system, and installing it again from git with `./sys/install.sh`.

**Comment by xarkes** [comment]
ping @wilo17

**Comment by securitykitten** [comment]
I have a Fedora box where I was able to replicate this error.  

It can be solved by
```
PKG_CONFIG_PATH=/usr/lib/pkgconfig/
export PKG_CONFIG_PATH
./build.sh
```
