### ISSUE TITLE
feature request: api for colorizing basic blocks

### ISSUE THREAD

**Issue by crowell** [radareorg/cutter#651]
it would be useful to be able to set the background for specific basic blocks to a different color for something like visualizing traces, etc. similar to this: https://github.com/gaasedelen/lighthouse

**Comment by Maijin** [comment]
https://github.com/radare/radare2/pull/11224#discussion_r212830841 afbc got merged

**Comment by ITAYC0HEN** [comment]
Duplicate of https://github.com/radareorg/cutter/issues/444
@xarkes will solve this in it's commits for Lighthouse plugin
