### ISSUE TITLE
Cutter 1.7.1 Graph display block wrong place, over write by other block

### ISSUE THREAD

**Issue by dmknght** [radareorg/cutter#665]
# Hi! I am reversing a malware (please see zip file bellow) with normal Cutter analysis option. After go to main function, i saw a block of code on the top of graph, and it is over written by main block (please see screenshot)

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian 9 amd64
| File format of the file you reverse (mandatory)      | PE 32
| Architecture/bits of the file (mandatory)            | x86 i386
| Cutter and r2 version, See About Cutter (mandatory)  | Version 1.7.1 / Using r2 2.8.0-189

### Steps to reproduce the behavior 
[malware_r.exe_.zip](https://github.com/radareorg/cutter/files/2340924/malware_r.exe_.zip)

### Additional Logs, screenshots, source-code,  configuration dump, ...
Graph panel displays error
![screenshot from 2018-08-31 23-55-11](https://user-images.githubusercontent.com/29118926/44925984-33b64a00-ad7a-11e8-892e-a0e8ed6e2df1.png)

Code displays in disassembly panel (bug block is highlight code)
![screenshot from 2018-09-01 00-09-28](https://user-images.githubusercontent.com/29118926/44926359-56952e00-ad7b-11e8-8736-736a41e82139.png)

![screenshot from 2018-09-01 00-05-04](https://user-images.githubusercontent.com/29118926/44926246-03bb7680-ad7b-11e8-8f02-17deee272d16.png)

**Comment by xarkes** [comment]
Hi, thanks for reporting, I think this is clearly similar as https://github.com/radareorg/cutter/issues/574

**Comment by xarkes** [comment]
I am closing as duplicate. If not fixed after #574 is fixed, feel free to reopen.
