### ISSUE TITLE
How can I verify the integrity of Cutter?

### ISSUE THREAD

**Issue by jamieweb** [radareorg/cutter#666]
Is there somewhere that I can get GPG signatures of the releases, or even just plain hashes? Signed commits also don't seem to be used.

**Comment by xarkes** [comment]
About signed commits, I guess it shouldn't be an issue to sign them.

**Comment by jamieweb** [comment]
Yeah it looks like you're already signing your commits, but a lot of the other developers aren't. Maybe mandatory commit signing would be the way to go for now?

**Comment by pelijah** [comment]
Commit signing? Why?

**Comment by ITAYC0HEN** [comment]
How should we progress here?

**Comment by a1ext** [comment]
Thank you for the issue 
> ![image](https://user-images.githubusercontent.com/14978853/54236989-023aea00-4526-11e9-9cbf-118a5bdbe64a.png)

**Comment by Maijin** [comment]
@ITAYC0HEN r2 should be signed first

**Comment by ITAYC0HEN** [comment]
is this really needed? is the benefit is meaningful? because as you explain, it's not gonna happen.
If no, please close this issue

**Comment by Maijin** [comment]
It's not going to happen anytime soon and this should be tracked first in other project before Cutter. I think we can close it for now.
