### ISSUE TITLE
Java decompile duplicating function names

### ISSUE THREAD

**Issue by CraftSpider** [radareorg/cutter#679]
# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Windows 7
| File format of the file you reverse (mandatory)      | .class
| Architecture/bits of the file (mandatory)            | Java
| Cutter and r2 version, See About Cutter (mandatory)  | Version 1.7.1 / Using r2 2.8.0
| Show version information **full output** (See About Cutter) in a pastebin document (mandatory) | https://pastebin.com/aQZxXnTU

### Expected behavior
Each function/method appears only once on the list

### Actual behavior
Functions in the function widget are appearing multiple times, each one links to the same location, and going to one only highlights the bottom-most one.

### Steps to reproduce the behavior 
Get a java class file, open it with default settings, `aaa` analysis level

### Additional Logs, screenshots, source-code,  configuration dump, ...
![image](https://user-images.githubusercontent.com/13342132/45166113-45f21700-b1c4-11e8-8fee-9fa3816ff0d1.png)

**Comment by xarkes** [comment]
Hi,
This is very likely a bug in radare2 itself, not inside Cutter.
Can you paste `aflj` output?

**Comment by CraftSpider** [comment]
Yep, looks like a bug in radare2, assuming I'm reading the output correctly: https://pastebin.com/nDKZuNte

**Comment by xarkes** [comment]
Yep, better open an issue on r2 repo and close this one :)

**Comment by xarkes** [comment]
No problem, thanks :)
