### ISSUE TITLE
Split Cutter.h to fasten compilation time

### ISSUE THREAD

**Issue by xarkes** [radareorg/cutter#680]
Cutter.h file is included almost everywhere, and so when one does a simple modification to it, it has to recompile everything.
It would be awesome if someone could split Cutter.h header, into logical parts, so it only recompiles a few files, and fasten compilation times.

**Comment by deepanjali19** [comment]
I would like to work on this issue!

I will split the Cutter.h header file into multiple files and include those files in Cutter.h.

I will get a PR up for this issue soon.

**Comment by ITAYC0HEN** [comment]
Thank you, Deepanjali!
This would be wonderful :)

**Comment by deepanjali19** [comment]
@ITAYC0HEN I am just having a little trouble in building it from source.

**Comment by ITAYC0HEN** [comment]
Are you in the Cutter telegram group? 
https://t.me/r2cutter
We would happily help you there (or on IRC).

Just ping us with your question and we'll help :) 


It is preferred to keep the conversations here about the issue itself and not about other issues :)

**Comment by deepanjali19** [comment]
@ITAYC0HEN I am not in the Cutter telegram group or on IRC.

**Comment by ITAYC0HEN** [comment]
Can you join? :)
Simply click the link and log in from Telegram or if you prefer IRC just enter #cutter on irc.freenode.net

Telegram is easy-to-use mobile, desktop and web application

**Comment by xarkes** [comment]
I'm going to do it today.

**Comment by ITAYC0HEN** [comment]
This is done afaik, right @xarkes ?
Do you have anything left to do here? if so, re-open

**Comment by xarkes** [comment]
Yes this is partially done. Maybe it can be improved, but anyway everything has been moved to `core/` folde.r
