### ISSUE TITLE
Crash during ELF ARM64 aaa

### ISSUE THREAD

**Issue by michalmalik** [radareorg/cutter#683]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | MacOS 10.13.6
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | ARM64
| Cutter and r2 version, See About Cutter (mandatory)  | Version 1.7.1 / Using r2 2.8.0
| Show version information **full output** (See About Cutter) in a pastebin document (mandatory) | https://gist.github.com/michalmalik/5b8f2a59b35d7ca012cba68b100f9c90

### Expected behavior

Opened file

### Actual behavior

Crashes during analysis

### Steps to reproduce the behavior 
- Binary: https://github.com/JonathanSalwan/binary-samples/blob/master/elf-Linux-ARM64-bash

1. Open file
2. Load options: just press OK
3. Wait a bit
4. ???
5. "Cutter quit unexpectedly"

**Comment by Maijin** [comment]
Hello,

I can't reproduce this problem.

Ensure you are using radare2 from git, if you're unsure paste output of `r2 -v` here.
To install radare2 from git, first uninstall your version of radare2 and clean your distro. Then use `git clone https://github.com/radare/radare2 && cd radare2 && ./sys/install.sh`, verify your version and check if there is no error using `r2 -v`.

Could you also provide the backtrace/logs from the crash after building with ./sys/asan.sh

**Comment by xarkes** [comment]
Hi,
I cannot reproduce on Linux nor Mac. Can you please provide a backtrace?

**Comment by radare** [comment]
Is this a bug in cutter or r2?

**Comment by Maijin** [comment]
Works fine in r2 if opened/analyzed/graphed

**Comment by xarkes** [comment]
I don't know, according to the stacktrace, that's because of libr_core/libr_parse if I'm correct.

**Comment by michalmalik** [comment]
Maybe it got fixed since 2.8.0

**Comment by michalmalik** [comment]
During the analysis, if I press "Cancel" at the right moment, it opens without crashing :D

**Comment by xarkes** [comment]
Probably fixed in https://github.com/radareorg/cutter/commit/484cc632143cb3367f5679d1551db030f8f32854.

**Comment by ITAYC0HEN** [comment]
@michalmalik I can't reproduce now and it, probably fixed.
Can you try to build cutter from master and check if the issue still occur?

**Comment by michalmalik** [comment]
@ITAYC0HEN No, sorry, I am not going to build Cutter :)

**Comment by ITAYC0HEN** [comment]
Okay then :)
I think this issue was fixed already - thank you for informing us, appreciate it
