### ISSUE TITLE
Automatically open an issue

### ISSUE THREAD

**Issue by xarkes** [radareorg/cutter#685]
Automatically open https://github.com/radareorg/cutter/issues/new from a button

**Comment by Maijin** [comment]
Could automatically fill the template too for the basic infos

**Comment by philipmnelson** [comment]
I'm currently working on this issue.

**Comment by xarkes** [comment]
Maybe it would be better to say "Report an issue" rather than "Open issue" which might be less understandable for other people.

**Comment by ITAYC0HEN** [comment]
+1 "Report an issue"
