### ISSUE TITLE
Add font ratio option

### ISSUE THREAD

**Issue by xarkes** [radareorg/cutter#686]
Allow to increase/decrease global font size (not only disasm)

**Comment by xarkes** [comment]
Reopening because I think it's still useful anyway. People don't have to do hack through the command lines.

**Comment by xarkes** [comment]
Exactly, or directly in command line:
`QT_SCALE_FACTOR=2.0 ./Cutter`

**Comment by xarkes** [comment]
You can do the same in the cmd prompt:
```
set QT_SCALE_FACTOR=2.0
Cutter.exe
```

**Comment by karliss** [comment]
I am closing this. There is no need to "hack through the command lines". Every sane operating system has display scaling factor configuration and Qt respects that. 

Situation was a bit worse 2 years ago using an older Qt version and older desktop environment versions.  Using latest Qt everything is mostly working. Most of the remaining tasks are linked in high dpi project https://github.com/radareorg/cutter/projects/16 and also my attempt updating Qt #1868 (5.14 has better fractional scaling support on Windows).
