### ISSUE TITLE
Accelerate compilation times

### ISSUE THREAD

**Issue by xarkes** [radareorg/cutter#687]
Cutter now takes quite a while to compile, there's already https://github.com/radareorg/cutter/issues/680 which help compilation times during development, but I think there are some basic improvements we can do to fasten the process.

**Comment by ITAYC0HEN** [comment]
like what? this issue is too generic :(

**Comment by xarkes** [comment]
That's funny because I wanted to take care of it today :) I'll just do it no worries.

**Comment by xarkes** [comment]
As you said I think it's too generic, let's just close this.
