### ISSUE TITLE
Crash on macOS when selecting __stub_helper on Mach064 object file

### ISSUE THREAD

**Issue by watkipet** [radareorg/cutter#697]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | macOS 10.13.6 Intel x64
| File format of the file you reverse (mandatory)      | Mach064
| Architecture/bits of the file (mandatory)            | x86/64
| Cutter and r2 version, See About Cutter (mandatory)  | Version 1.7.1 / Using r2 2.8.0
| Show version information **full output** (See About Cutter) in a pastebin document (mandatory) | https://gist.github.com/watkipet/d17e1cb467e4d547d1b115ea97c4493f

### Expected behavior
Selecting a disassembly line in the `Disassembly` tab shows information in the UI.

### Actual behavior
The application crashes.

### Steps to reproduce the behavior 
1) Analyze the following file (aaa)
[CutterExample.zip](https://github.com/radareorg/cutter/files/2367563/CutterExample.zip)
2) In the `Disassembly` tab, select the lines in the screenshot below.

### Additional Logs, screenshots, source-code,  configuration dump, ...
Source code:

    #include <stdio.h>
    
    int getInt() {
        return 5;
    }
    
    int main(int argc, const char * argv[]) {
        // insert code here...
        int d;
        d = getInt();
        printf("Hello, World %d\n", d);
        return 0;
    }

<img width="684" alt="lines_which_crash" src="https://user-images.githubusercontent.com/969829/45314271-23267200-b4e6-11e8-8375-ef30eb944a1c.png">

macOS Crash log for main thread:

    Process:               Cutter [42928]
    Path:                  /Applications/Cutter.app/Contents/MacOS/Cutter
    Identifier:            com.yourcompany.Cutter
    Version:               0
    Code Type:             X86-64 (Native)
    Parent Process:        ??? [1]
    Responsible:           Cutter [42928]
    User ID:               503
    
    Date/Time:             2018-09-10 10:42:17.172 -0700
    OS Version:            Mac OS X 10.13.6 (17G65)
    Report Version:        12
    Anonymous UUID:        DB10D98D-2F45-69CA-151E-EE6C73BE8084
    
    Sleep/Wake UUID:       F1873D7E-2A57-4F86-AFDF-855E1D596B56
    
    Time Awake Since Boot: 250000 seconds
    Time Since Wake:       12000 seconds
    
    System Integrity Protection: disabled
    
    Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread
    
    Exception Type:        EXC_CRASH (SIGABRT)
    Exception Codes:       0x0000000000000000, 0x0000000000000000
    Exception Note:        EXC_CORPSE_NOTIFY
    
    Application Specific Information:
    detected source and destination buffer overlap
    
    Thread 0 Crashed:: CrBrowserMain  Dispatch queue: com.apple.main-thread
    0   libsystem_kernel.dylib        	0x00007fff7d14bb66 __pthread_kill + 10
    1   libsystem_pthread.dylib       	0x00007fff7d316080 pthread_kill + 333
    2   libsystem_c.dylib             	0x00007fff7d0a724d __abort + 144
    3   libsystem_c.dylib             	0x00007fff7d0a71bd abort + 142
    4   libsystem_c.dylib             	0x00007fff7d0a7321 abort_report_np + 177
    5   libsystem_c.dylib             	0x00007fff7d0cbbf5 __chk_fail + 48
    6   libsystem_c.dylib             	0x00007fff7d0cbc05 __chk_fail_overlap + 16
    7   libsystem_c.dylib             	0x00007fff7d0cbc36 __chk_overlap + 49
    8   libsystem_c.dylib             	0x00007fff7d0cbd89 __strncpy_chk + 81
    9   libr_parse.dylib              	0x000000010b9c1ab4 0x10b9bd000 + 19124
    10  libr_parse.dylib              	0x000000010b9bfff6 r_parse_filter + 70
    11  libr_core.dylib               	0x000000010ad11f9e 0x10ac98000 + 499614
    12  libr_core.dylib               	0x000000010acc8700 0x10ac98000 + 198400
    13  libr_core.dylib               	0x000000010ad9d5a4 r_cmd_call + 532
    14  libr_core.dylib               	0x000000010acf6c9c 0x10ac98000 + 388252
    15  libr_core.dylib               	0x000000010acbdd07 0x10ac98000 + 154887
    16  libr_core.dylib               	0x000000010acb9a90 r_core_cmd + 1056
    17  libr_core.dylib               	0x000000010acbaf0c r_core_cmd_str + 44
    18  com.yourcompany.Cutter        	0x000000010aa152fd CutterCore::cmdj(QString const&) + 77
    19  com.yourcompany.Cutter        	0x000000010aa30031 CutterCore::getXRefs(unsigned long long, bool, bool, QString const&) + 161
    20  com.yourcompany.Cutter        	0x000000010aac2d7f SidebarWidget::updateRefs(unsigned long long) + 143
    21  com.yourcompany.Cutter        	0x000000010aac2c41 SidebarWidget::refresh(unsigned long long) + 49
    22  org.qt-project.QtCore         	0x000000010d40519e QMetaObject::activate(QObject*, int, int, void**) + 2334
    23  com.yourcompany.Cutter        	0x000000010ab1dfdf CutterCore::seekChanged(unsigned long long) + 63
    24  com.yourcompany.Cutter        	0x000000010aa14e80 CutterCore::cmd(QString const&) + 176
    25  com.yourcompany.Cutter        	0x000000010aa187c0 CutterCore::seek(unsigned long long) + 112
    26  com.yourcompany.Cutter        	0x000000010aabf5ba DisassemblyWidget::cursorPositionChanged() + 186
    27  org.qt-project.QtCore         	0x000000010d40519e QMetaObject::activate(QObject*, int, int, void**) + 2334
    28  org.qt-project.QtWidgets      	0x000000010c8e7368 0x10c711000 + 1925992
    29  org.qt-project.QtCore         	0x000000010d40519e QMetaObject::activate(QObject*, int, int, void**) + 2334
    30  org.qt-project.QtWidgets      	0x000000010c90f140 0x10c711000 + 2089280
    31  org.qt-project.QtWidgets      	0x000000010c90e059 QWidgetTextControl::processEvent(QEvent*, QMatrix const&, QWidget*) + 2697
    32  org.qt-project.QtWidgets      	0x000000010c90d5c0 QWidgetTextControl::processEvent(QEvent*, QPointF const&, QWidget*) + 80
    33  org.qt-project.QtWidgets      	0x000000010c8e3fb2 QPlainTextEdit::mousePressEvent(QMouseEvent*) + 162
    34  com.yourcompany.Cutter        	0x000000010aac0498 DisassemblyTextEdit::mousePressEvent(QMouseEvent*) + 24
    35  org.qt-project.QtWidgets      	0x000000010c75b4ab QWidget::event(QEvent*) + 427
    36  org.qt-project.QtWidgets      	0x000000010c8055bd QFrame::event(QEvent*) + 45
    37  org.qt-project.QtCore         	0x000000010d3d4214 QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) + 148
    38  org.qt-project.QtWidgets      	0x000000010c721458 QApplicationPrivate::notify_helper(QObject*, QEvent*) + 248
    39  org.qt-project.QtWidgets      	0x000000010c7243e0 QApplication::notify(QObject*, QEvent*) + 7568
    40  org.qt-project.QtCore         	0x000000010d3d3f64 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 164
    41  org.qt-project.QtWidgets      	0x000000010c721dd0 QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) + 928
    42  org.qt-project.QtWidgets      	0x000000010c77b693 0x10c711000 + 435859
    43  org.qt-project.QtWidgets      	0x000000010c77a355 0x10c711000 + 430933
    44  org.qt-project.QtWidgets      	0x000000010c72146d QApplicationPrivate::notify_helper(QObject*, QEvent*) + 269
    45  org.qt-project.QtWidgets      	0x000000010c722897 QApplication::notify(QObject*, QEvent*) + 583
    46  org.qt-project.QtCore         	0x000000010d3d3f64 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 164
    47  org.qt-project.QtGui          	0x000000010ccedb92 QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) + 3714
    48  org.qt-project.QtGui          	0x000000010ccd513b QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 219
    49  libqcocoa.dylib               	0x000000011646aec0 0x11643f000 + 179904
    50  libqcocoa.dylib               	0x000000011646b770 0x11643f000 + 182128
    51  com.apple.CoreFoundation      	0x00007fff5513fd31 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
    52  com.apple.CoreFoundation      	0x00007fff551f760c __CFRunLoopDoSource0 + 108
    53  com.apple.CoreFoundation      	0x00007fff55122ce0 __CFRunLoopDoSources0 + 208
    54  com.apple.CoreFoundation      	0x00007fff5512215d __CFRunLoopRun + 1293
    55  com.apple.CoreFoundation      	0x00007fff551219b7 CFRunLoopRunSpecific + 487
    56  com.apple.HIToolbox           	0x00007fff54401d96 RunCurrentEventLoopInMode + 286
    57  com.apple.HIToolbox           	0x00007fff54401a0f ReceiveNextEventCommon + 366
    58  com.apple.HIToolbox           	0x00007fff54401884 _BlockUntilNextEventMatchingListInModeWithFilter + 64
    59  com.apple.AppKit              	0x00007fff526b2a73 _DPSNextEvent + 2085
    60  com.apple.AppKit              	0x00007fff52e48e34 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 3044
    61  com.apple.AppKit              	0x00007fff526a7885 -[NSApplication run] + 764
    62  libqcocoa.dylib               	0x000000011646a5bf 0x11643f000 + 177599
    63  org.qt-project.QtCore         	0x000000010d3cf3de QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 430
    64  org.qt-project.QtCore         	0x000000010d3d4552 QCoreApplication::exec() + 130
    65  com.yourcompany.Cutter        	0x000000010aa1220e main + 46
    66  libdyld.dylib                 	0x00007fff7cffb015 start + 1

### Comments
It looks to me like this is a problem within `libr` itself. Unfortunately, I'm not familiar enough with radare2 to reproduce it on the console. If you could tell me how to do what Cutter is doing (getting Xrefs, I assume) in radre2 I can try filing a bug against radare2.

**Comment by xarkes** [comment]
Is it a bug on OS X? Can anyone confirm? I cannot reproduce with master on Linux.

**Comment by Maijin** [comment]
Can't reproduce on master.
