### ISSUE TITLE
Format combo box in OptionsDialog (load dialog) does nothing

### ISSUE THREAD

**Issue by thestr4ng3r** [radareorg/cutter#7]
The format option is not implemented yet. I suppose it should set `file.type`. Does that make sense?

**Comment by Maijin** [comment]
it should set -F at the opening of the file

**Comment by Maijin** [comment]
`-F avr` etc.

**Comment by Maijin** [comment]
The values can be retrieved from `iLj`

**Comment by thestr4ng3r** [comment]
Are xtr plugins of interest here too or only bin?

**Comment by Maijin** [comment]
Just use the list in iLj

**Comment by Maijin** [comment]
we can always get it better latter
