### ISSUE TITLE
Editing stack values show instruction preview

### ISSUE THREAD

**Issue by Vasco-jofra** [radareorg/cutter#700]
### Expected behavior
In the stack view we are editing hex values so no preview of instruction should be shown.
![screenshot from 2018-09-11 08-12-52](https://user-images.githubusercontent.com/11303847/45344321-56770880-b59b-11e8-9316-879d454bf928.png)

### Actual behavior
Editing stack values now shows instruction preview after #696.

### The fix
EditInstructionDialog should not be used for editing stack values or it should be customizable to have no preview.

**Comment by ITAYC0HEN** [comment]
@CraftSpider can you please have a look at this? You did a great job fixing #329 :)

**Comment by CraftSpider** [comment]
I'll take a look, shouldn't be too hard of a fix

**Comment by ITAYC0HEN** [comment]
great! Thank you :)

**Comment by ITAYC0HEN** [comment]
ping @CraftSpider , are you on it?

**Comment by CraftSpider** [comment]
Apologies, got busy with life. Will have a pull request up by midnight EST today.
