### ISSUE TITLE
Linux crash on file load

### ISSUE THREAD

**Issue by yarjor** [radareorg/cutter#703]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits                              | Arch Linux 64bit kernel ver. 4.18.6 (VMWare VM)
| File format of the file you reverse     | Occured on both PE and ELF
| Architecture/bits of the file           | x86/32 & x86/64
| Cutter and r2 version, See About Cutter | Version 1.7.1 / Using r2 2.9.0
| Show version information **full output** (See About Cutter) in a pastebin document| https://gist.github.com/yarjor/e7a059ec8cc9678b98390c7b1011c13a

### Bug Description

Cutter's file choose gui works okay, but whenever I try to load a binary (whether using the GUI or using cutter -A), the program segfaults after analyzing the binary. I tried this with both PE & ELF files, 64 and 32 bit, with different analysis levels / no analysis and was never able to actually progress.
Attached is an example stack trace, it was different with each binary type / loading method but the top 4 calls are always the same.
[cutter_crash.txt](https://github.com/radareorg/cutter/files/2371961/cutter_crash.txt)
If relevant - r2 cli works perfectly well.

:smile:

**Comment by yarjor** [comment]
I have now tried it with 1 more exe I had, /bin/ls, /bin/true, vim and python3, segfaulted on all of them.
It is worth mentioning that out of the many runs (I ran each binary ~5 times) a few loads actually succeeded without segfaulting (about 10% chance of successful run...?)

**Comment by xarkes** [comment]
Ok I have to investigate more...

**Comment by xarkes** [comment]
Not fixed apparently. I will work more on it tonight.

**Comment by ITAYC0HEN** [comment]
@yarjor, the bug should be fixed on master now.
If after compiling from master you still experience the bug, please write here and we'll reopen the issue.
Thank you :)
