### ISSUE TITLE
Add opened file-name to Cutter's title

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/cutter#711]
Would be nice to have the name of the opened file in the program's title:

Something like `Cutter - /tmp/hello_world` or `Cutter - hello_world`

It would be helpful in cases where multiple instances of Cutter are opened which is quite a common case while reversing

**Comment by Maijin** [comment]
Radare2 is able to disassemble multiple file in the same environment, thus not sure if this appropriate. Maybe we could do that in the name of the tabs instead?

**Comment by Maijin** [comment]
Probably ok for now because we don't use a lot of this multiple file opening
