### ISSUE TITLE
Don't show the "Load Options" dialog when choosing "Don't open any file"

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/cutter#712]
No good reason to show this dialog when no file is going to be opened since "Don't open any file" is checked in the Open File dialog:

![image](https://user-images.githubusercontent.com/20182642/45619986-ec230400-ba83-11e8-9c44-2f42ac5f0985.png)

**Comment by xarkes** [comment]
Well I think one cannot change architecture after loading the file, so that might be the current reason.

**Comment by ITAYC0HEN** [comment]
Via GUI you mean? Since typing `e asm.arch` should do
If this the case, it should be added to the menu option.
