### ISSUE TITLE
Cutter has too many files in its Root directory (Windows)

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/cutter#729]
On Windows release the directory is a mess and we have too many files on the root folder. 
This is something that needs reordering IMHO.

![image](https://user-images.githubusercontent.com/20182642/46244700-9e938900-c3eb-11e8-8fb8-15f3de353284.png)

I'd prefer something more clean, for example:

```
|./Cutter
|__ Cutter.exe
|__ ./Libs
|______ X.dll
|______ B.dll
|__ ./Icons
|______ Cutter.png
|__ ./Python36
...
...
```

Also, we have tons of DLLS that I;m not sure required and we have 22 `r_*.dll` files which probably can be merged into a single DLL - `libr.dll`.

We have several QT folders which I don't know what their role - `platforms, position, imageformats` and more, as well as **15** QT dlls in the root directory.  Just to compare - Binary Ninja has about 4 QT dll files and IDA has ~4 as well.

**Comment by pelijah** [comment]
After removing QtWebEngine we have only 5 `Qt5*.dll` files.

**Comment by XVilka** [comment]
I don't see why this is a problem at all. IDA also has "platforms" directory.

**Comment by ITAYC0HEN** [comment]
What do you think? any way to move all these libraries to a "libs" folder and close this?
@thestr4ng3r @xarkes @pelijah

**Comment by pelijah** [comment]
It is only possible if you create special app launcher

**Comment by a1ext** [comment]
This issue can be closed IMO, not an issue at all. Let’s spendctime on more useful ones

**Comment by ITAYC0HEN** [comment]
disagree. it's a mess to find cutter.exe inside. I need to scroll until I find it or sort by name, etc. 
THIS IS NOT USER-FRIENDLY

**Comment by a1ext** [comment]
Why did you not create a shortcut?

**Comment by ITAYC0HEN** [comment]
I do for myself because I use and test Cutter all the time, but I don't enter this mess directory and user a finder to locate the recent "cutter.exe".
a user shouldn't create a shortcut every release...

**Comment by a1ext** [comment]
Then solution can be the following:
- move everything in `cutter` folder and 
- create a shortcut next to it

**Comment by a1ext** [comment]
In an AppVeyor

**Comment by ITAYC0HEN** [comment]
since I am a loner here, I will close this issue

**Comment by pelijah** [comment]
Since you have full control over backend repo now, you can combine all rizin libs in one. I see no reason to distribute multiple libs at least for Windows.
