### ISSUE TITLE
Connection to remote gdbserver hangs

### ISSUE THREAD

**Issue by reijin90** [radareorg/cutter#752]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x64_86 and Windows 10 Pro 64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| Cutter and r2 version, See About Cutter (mandatory)  | Version 1.7.1 / Using r2 2.8.0 (current?)
| Show version information **full output** (See About Cutter) in a pastebin document (mandatory) | https://gist.github.com/reijin90/0728552d235240045633b55f0e2dc30a

### Expected behavior
I tried to connect to my remote gdbserver instance in an Ubuntu VM via the IO dialog of cutter (gdb://MYIP:8585). I was hoping I could interact with the gdbserver instance and use it for binary delivery and debugging.

### Actual behavior
The connection is seemingly esablished, but the dialog hangs at "Loading Binary....". I can see that gdbserver recognizes the connection as: "Remote debugging from host WIN10_IP". 

### Steps to reproduce the behavior 
Start gdbserver:
`gdbserver host:8585 main`
Start cutter.
Select "gdb" as connector
Enter VM_IP:8585 as file 
Click "Open"

**Comment by ITAYC0HEN** [comment]
We should blacklist debug IO such as (bochs, gdb, ptrace, qnx, windbg) until we implement debugging support

The relevant code is implemented here:
https://github.com/radareorg/cutter/blob/e3bc7440243648b643d1d3b034549bd26fb4f607/src/Cutter.cpp#L1352-L1371

and being called here:
https://github.com/radareorg/cutter/blob/e3bc7440243648b643d1d3b034549bd26fb4f607/src/dialogs/NewFileDialog.cpp#L323-L336

**Comment by reijin90** [comment]
I'm not sure if this issue is actually related to your implementation. As I just discovered, I have the same behaviour when trying to connect to my remote gdbserver via the Windows version of Radare. I've created an issue there too: https://github.com/radare/radare2/issues/11722

**Comment by xarkes** [comment]
On one side, there is a mistake, we should not provide debugging IO (such as `gdb://`) in Cutter because the debugger is not complete yet.
On the other side, it seems there's a bug in radare2 as you stated here so, I'm gonna close this issue.
Thanks for creating the issue on radare2.
