### ISSUE TITLE
Show number of items in QTreeView widgets (Functions, Strings, etc.)

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/cutter#754]
Naturally, we have many QTreeViews implemented for our widgets. The problem is that the user can't know how many items are shown in the widget in a given time.

![image](https://user-images.githubusercontent.com/20182642/46404509-09a3cf00-c70e-11e8-85f8-56c1a49a624d.png)

For example, I wanted to know how many functions a binary have and I had no other option except executing `afl~?` in the Console widget.

I'd like the widgets to show me how many items (lines) there are in each widget, and this number should be changed when filtering the view (i.e to show the number of items which currently showed in the widget).

**Comment by smhaziq** [comment]
Any suggestion on the count display location?
How about adding in a status footer for each QTreeView widgets?

**Comment by Maijin** [comment]
Probably in the title like `Functions (123)` or `(123) Functions`

**Comment by ITAYC0HEN** [comment]
I prefer a tiny and solid status bar at the footer actually
