### ISSUE TITLE
Show currently open file

### ISSUE THREAD

**Issue by mirh** [radareorg/cutter#768]
Either the full path or just the name would be fine for me. 
And either in the title bar, or somewhere else in the UI too. 

It's really a mess to work with more than a couple files, when you can't remember which window is what.

**Comment by xarkes** [comment]
I think this was fixed here: https://github.com/radareorg/cutter/pull/726
It's not available in the latest release, but next one is coming very soon.

**Comment by ITAYC0HEN** [comment]
Hey, thanks for the feedback! 

It's already implemented on Master branch and will be released soon in the new release. 

I pushed it at #726
https://github.com/radareorg/cutter/pull/726

If you'll work on Cutter from source it is available for you :) 

Closing this issue. Please let me know if you tried using Cutter from git and it's not available for you.

**Comment by mirh** [comment]
Duh, thanks
