### ISSUE TITLE
Make only one "nightly" release on "releases" tab

### ISSUE THREAD

**Issue by XVilka** [radareorg/cutter#77]
Like Neovim did: https://github.com/neovim/neovim/releases

Somehow they are able to push changes to the only one release instead of creating new ones every commit.

**Comment by Maijin** [comment]
it's because they do it manually, there is no way to automate this with github release.
Once the 1.0 is release we will just kill this functionality.

**Comment by xarkes** [comment]
Actually they use a bot which does this automatically:
https://github.com/neovim/bot-ci
https://github.com/neovim/bot-ci/blob/master/ci/nightly.sh

**Comment by Maijin** [comment]
ok noted but we better focus on the release than this

**Comment by xarkes** [comment]
True
