### ISSUE TITLE
Cutter UI color scheme in text fields is broken in macOS mojave Dark Mode

### ISSUE THREAD

**Issue by marcograss** [radareorg/cutter#772]
### Work environment
OS: macOS 10.14 mojave dark mode
File Format -  Architecture: Any
Cutter and r2 version: latest

### Expected behavior

The UI elements should be visible in dark mode, see the attached screenshot in the function list panel,

there are other instances, basically in every text field

### Actual behavior

![image](https://user-images.githubusercontent.com/1010159/46578468-982c8f00-ca33-11e8-8606-07a65d467042.png)

**Comment by thestr4ng3r** [comment]
Ok, so the problem only appears when Cutter is built on a Mojave system. The Travis builds still use Travis' default High Sierra Image, so they don't have the issue. I'll temporarily explicitly disable the dark mode in the Info.plist until Qt 5.12 is released. Then, if you build with qmake and execute Cutter inside the generated application bundle, it will only use the light mode.

**Comment by marcograss** [comment]
qt 5.12 just landed in brew FYI
