### ISSUE TITLE
Unaligned graph node

### ISSUE THREAD

**Issue by trufae** [radareorg/cutter#781]
thats in the entrypoint of mac's ls

<img width="755" alt="screenshot 2018-10-08 at 12 01 29" src="https://user-images.githubusercontent.com/6431515/46604622-2584e780-caf7-11e8-943d-499f16f45710.png">

**Comment by a1ext** [comment]
Hi @trufae, could you provide a binary? If I understand correctly, you've run Cutter at MAC, right? Does it behave the same on Linux?

**Comment by ITAYC0HEN** [comment]
@trufae can you upload this `ls` file from your MAC?
@a1ext can you have a look later?

**Comment by ITAYC0HEN** [comment]
@trufae can you upload this ls file from your MAC?

**Comment by karliss** [comment]
The problem should still be there, this is result of using grid based layout. I have some ideas for mitigating this without major rewrite.

**Comment by ITAYC0HEN** [comment]
That would be fantastic!

**Comment by ITAYC0HEN** [comment]
Solved partially by #1460 :) Still more to go

**Comment by ITAYC0HEN** [comment]
@trufae are you still experience this?

**Comment by Maijin** [comment]
<img width="1238" alt="image" src="https://user-images.githubusercontent.com/1408600/60564258-46fdc180-9d5f-11e9-8adc-107588c434ab.png">
cannot reproduce - closing.

**Comment by a1ext** [comment]
`/bin/ls` on my mac shows nice graph. Good job guys!

**Comment by trufae** [comment]
/bin/ls FTW! :D

**Comment by a1ext** [comment]
> /bin/ls FTW! :D

lol) that's the sample with huge graph 
<img width="1273" alt="Screen Shot 2019-07-04 at 00 25 18" src="https://user-images.githubusercontent.com/14978853/60622852-59750b00-9df2-11e9-8e19-1389f24fd680.png">
which previously was drawn wrong. 

Actually, all the nodes and arrows are aligned good
