### ISSUE TITLE
Add errors autoreport

### ISSUE THREAD

**Issue by XVilka** [radareorg/cutter#782]
With Sentry or any other similar service/software https://blog.sentry.io/2018/03/06/the-sentry-workflow

**Comment by xarkes** [comment]
Yeah good idea, I thought about it but never opened an issue.

**Comment by ITAYC0HEN** [comment]
Tracked here:
https://github.com/radareorg/cutter/issues/1002

And PR is in progress here:
https://github.com/radareorg/cutter/pull/1157
