### ISSUE TITLE
Graph: on PowerPC, the graph prematurely stops on or behave weirdly with branches

### ISSUE THREAD

**Issue by aldelaro5** [radareorg/cutter#786]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch Linux x64
| File format of the file you reverse (mandatory)      | DOL, ELF
| Architecture/bits of the file (mandatory)            | PPC
| Cutter and r2 version, See About Cutter (mandatory)  | Version 1.7.1 / Using r2-2.9.0
| Show version information **full output** (See About Cutter) in a pastebin document (mandatory) | https://pastebin.com/ujGKurCt

### Expected behavior
The graph being displayed correctly with all branches of the function
### Actual behavior
The graph abruptly stops, does not render some blocks or is in general incorrect for functions with decent amount branches
### Steps to reproduce the behavior 
1. Open either of the binary provided (the DOL is a GameCube homebrew that just prints the clock values on screen while the ELF is the Wii version of the same program, both were both compiled using devkitPPC)
2. Go to a function/address (the elf has symbols in it so you can go to say sym.strnlen for a good examples, but there's so many you could pick at random and find different effects, the dol doesn't have symbols, but you can go to say 0x0x8000fc7c for a good example)
3. Go to the graph view (create function if necessary), you may try a refresh as I noticed it can change the contents once.

[binaries.zip](https://github.com/radareorg/cutter/files/2460637/binaries.zip)

**Comment by ITAYC0HEN** [comment]
@aldelaro5 does it still exist?
These images are the functions you named as test candidates:

![image](https://user-images.githubusercontent.com/20182642/52910494-d6b73d80-32a0-11e9-9806-ebf0a0be8f1d.png)

![image](https://user-images.githubusercontent.com/20182642/52910509-344b8a00-32a1-11e9-9131-1e49cf5bdce3.png)
