### ISSUE TITLE
Cutter loads everything as a plugin if there is no `plugins` directory next to it

### ISSUE THREAD

**Issue by a1ext** [radareorg/cutter#795]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits                              | Windows 7 x64
| File format of the file you reverse      | not related
| Architecture/bits of the file            | not related
| Cutter and r2 version, See About Cutter (mandatory)  | Version 1.7.2 / Using r2-2.9.0-310-gcb62c376b

### Expected behavior
Cutter don't load some extra libraries/files from other than `plugins` direcotry while looking for plugins.

### Actual behavior
In case, there is no `plugins` directory, it starts enumerating files in the current cutter's directory and tries to load them as a plugin (library), might be a security issue.

### Steps to reproduce the behavior 
- make sure there is no `plugins` directory in Cutters's folder (that's default, after fresh `git clone` and build)
- Put some big file in Cutters directory (next step it will be loaded into memory, so if it is big enough you will see Cutter freeze after popping up NewFileDialog.

### Additional Logs, screenshots, source-code,  configuration dump, ...

![image](https://user-images.githubusercontent.com/14978853/46699448-8230f100-cc22-11e8-88f6-317743decae7.png)

**Comment by xarkes** [comment]
Oh right, why is that a `cd`? :(

**Comment by xarkes** [comment]
Yeah we just need to get the cd return value and handle it.
