### ISSUE TITLE
Graph mouse click highlight wrong position

### ISSUE THREAD

**Issue by dmknght** [radareorg/cutter#798]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Parrot 4.2 64 bit
| File format of the file you reverse (mandatory)      | ELF (happens to any format)
| Architecture/bits of the file (mandatory)            | x86_64 (happens to any architecture)
| Cutter and r2 version, See About Cutter (mandatory)  | Version 1.7.2 / Using r2 3.0.0
| Show version information **full output** (See About Cutter) in a pastebin document (mandatory) | https://pastebin.com/MSfrUAY6

### Expected behavior
Cutter should display highlight color under selected object
### Actual behavior
Cutter shows color from previous character: `space`, `[` or any character before object; object last character does not have highlight color

### Additional Logs, screenshots, source-code,  configuration dump, ...
Screenshot:
![screenshot at 2018-10-11 00-48-05](https://user-images.githubusercontent.com/29118926/46755476-5a5b8f00-ccef-11e8-99c2-a2bbd0bf271d.png)
Tested binary file
[hello.zip](https://github.com/radareorg/cutter/files/2465809/hello.zip)

**Comment by ITAYC0HEN** [comment]
Sadly, I can't reproduce on:

| Cutter Version  | OS                |
|-----------------|-------------------|
| Release (1.7.2) | Windows 10 64-bit |
| Release (1.7.2) | Arch Linux 64-bit |
| Master (git)    | Windows 10 64-bit |
| Master (git)    | Arch Linux 64-bit |


Screenshot, same binary:

![image](https://user-images.githubusercontent.com/20182642/46757039-a3044f80-ccd1-11e8-9379-9c7f0adfbdec.png)


I also tried with different binaries.

**Comment by dmknght** [comment]
That is super weird. I am using release version and it happens to me from previous versions.
Here is a picture with Cutter 1.7.1, Debian 9 amd64 inside Virtualbox.
![screenshot at 2018-10-11 01-43-19](https://user-images.githubusercontent.com/29118926/46758487-1ff5f000-ccf7-11e8-9a3f-a58d1053a7af.png)
![screenshot at 2018-10-11 01-46-38](https://user-images.githubusercontent.com/29118926/46758634-8418b400-ccf7-11e8-869b-ad3e67c511c9.png)

**Comment by ITAYC0HEN** [comment]
Indeed weird, and I totally believe you - thanks for letting us know!
Sadly I can't reproduce on the machines stated above and never heard of similar complains. 😕

Any chance you can debug it from source on your end and try to figure out what causes it?

**Comment by ITAYC0HEN** [comment]
Okay I was able to reproduce indeed! :)

Cutter version from git, another Arch64 machine

![image](https://user-images.githubusercontent.com/20182642/46759437-16a95b00-ccd8-11e8-937c-83a8fb60741f.png)

**Comment by dmknght** [comment]
Wow i am about cloning and building it. Hope you fix it soon. Thanks for fast supporting <3

**Comment by Adikso** [comment]
I wrote this highlighting code and from what I see this is happening with non-mono fonts. It is calculating position as if all "tokens" have same width. I can fix it

**Comment by dmknght** [comment]
I've created a git version of cutter, and this problem has new issues
![screenshot from 2018-10-16 15-46-59](https://user-images.githubusercontent.com/29118926/47004012-cd835c00-d15a-11e8-9774-44a8eec35127.png)
![screenshot from 2018-10-16 15-47-04](https://user-images.githubusercontent.com/29118926/47004013-ce1bf280-d15a-11e8-8244-0c49016c55aa.png)
![screenshot from 2018-10-16 15-47-16](https://user-images.githubusercontent.com/29118926/47004014-ce1bf280-d15a-11e8-9b32-5b141ffc513c.png)
![screenshot from 2018-10-16 15-49-21](https://user-images.githubusercontent.com/29118926/47004141-14715180-d15b-11e8-9d33-d7c0e8259e2b.png)

My font setting inside cutter
![screenshot from 2018-10-16 15-48-09](https://user-images.githubusercontent.com/29118926/47004071-f3a8fc00-d15a-11e8-9496-050259a69d4f.png)

**Comment by ITAYC0HEN** [comment]
thanks @dmknght :)
@Adikso, any idea what failed here?

**Comment by Adikso** [comment]
This is probably problem with width calculation or rendering graph but I am not sure. You can see invalid width calculation on "[local_4h ]"

**Comment by dmknght** [comment]
Ah rendering graph is having some problem too. I don't know what is it called (screenshot). Should i create new issue for this?
![screenshot from 2018-10-20 19-57-40](https://user-images.githubusercontent.com/29118926/47255957-69d29900-d4a2-11e8-9406-5f284338ba07.png)

**Comment by Adikso** [comment]
![2018-10-20_16-04](https://user-images.githubusercontent.com/1407751/47256525-31bb5e00-d482-11e8-91f3-136f2dcd3127.png)
![2018-10-20_16-04_1](https://user-images.githubusercontent.com/1407751/47256524-31bb5e00-d482-11e8-8757-094a4f95d6ac.png)
![2018-10-20_16-05](https://user-images.githubusercontent.com/1407751/47256522-31bb5e00-d482-11e8-84e2-239df89a3f46.png)

From my observations there is problem with long "tokens". The more I increase asm.tabs the more off is highlight. It might be problem with width calculation as highlighting needs precise calculations but RichTextPainer don't as it is just drawing text and it does not care :')

**Comment by Adikso** [comment]
![2018-10-20_16-31](https://user-images.githubusercontent.com/1407751/47256788-a80d8f80-d485-11e8-999f-50e9db9d428c.png)
I forced it to use QFontMetrics directly rather than CachedFontMetrics and it works perfectly (it breaks token selection but it can be fixed).. so yes caching font width is broken.

**Comment by ITAYC0HEN** [comment]
great! would you be able to solve this and send PR, please? :)

**Comment by Adikso** [comment]
I don't know how to fix CachedFontMetrics. Every few characters width is 1px off. Like width of the same character can be later smaller. These 1px offs are accumulating and results later in big offset. I could make it use QFontMetrics but I understand that somebody created CachedFontMetrics for some performance reasons. Even if I could replace it with direct QFontMetrics->width() call I don't know what would be good option to find which letter was pressed. QFontMetrics don't have function to get text position at specified pixel offset so I would have to make something like binary search to find it.

**Comment by xarkes** [comment]
Hello,
I didn't understand the bug in CachedFontMetrics?

**Comment by dmknght** [comment]
I've built cutter after pulling it, with radare2 3.1 and i found something similar this issue: i set `asm.tabs = 11` and 2 screenshots bellow shows line `call sym.imp.printf` and `jecxz ....` stays wrong position. I think this is alignment problem.
![screenshot from 2018-10-28 04-32-44](https://user-images.githubusercontent.com/29118926/47609530-a9811e00-da6a-11e8-90e0-9aa4e789a39c.png)
![screenshot from 2018-10-28 04-32-51](https://user-images.githubusercontent.com/29118926/47609531-a9811e00-da6a-11e8-84a2-13fd13dd2f6d.png)
Here is an other block where instruction has no address in it stays at wrong position too:
![screenshot from 2018-10-28 04-37-40](https://user-images.githubusercontent.com/29118926/47609562-61163000-da6b-11e8-83ff-8543187137eb.png)
I think this problem is not only drawing highlight color wrong width but characters have alignment problem too.
@ITAYC0HEN  @Adikso  @xarkes

**Comment by Adikso** [comment]
If you would copy this disassembly into eg. LibreOffice Write and change font to some non-mono one you will see this:
![2018-10-27_23-53](https://user-images.githubusercontent.com/1407751/47609690-d241ed00-da43-11e8-90e2-78c5cba784ab.png)

You see how incorrect is this "mov" aligned? We are just pasting exact output out of radare into this graph and radare2 is command line tool - it can't move text by few pixels, so in order to align text it is placing spaces. There is the same amount of spaces before both mov and lea above. The problem is that you use non-mono font so the text before this "mov" is not of the same width as text before "lea".

With mono font it looks like this (perfectly): 
![2018-10-27_23-59](https://user-images.githubusercontent.com/1407751/47609719-6c099a00-da44-11e8-87ff-47428316379f.png)

And I don't think that there is a need for making Cutter-side text alignment. Just change font to mono one.

**Comment by xarkes** [comment]
So I think this can be closed :)
Feel free to reopen if not.

**Comment by dmknght** [comment]
I've built it. There are still some wrong positions.
![screenshot from 2018-11-02 18-53-45](https://user-images.githubusercontent.com/29118926/47914034-b372a900-ded0-11e8-866d-d21f9533a07b.png)
![screenshot from 2018-11-02 18-53-41](https://user-images.githubusercontent.com/29118926/47914036-b40b3f80-ded0-11e8-8582-798b1943ed39.png)

**Comment by Adikso** [comment]
@xarkes Referenced pull request is for DisassemblyWidget not for DisassemblerGraphView

**Comment by Maijin** [comment]
@Adikso thanks, reopened

**Comment by a1ext** [comment]
> @xarkes Referenced pull request is for DisassemblyWidget not for DisassemblerGraphView. Problem is not solved. This can be easily fixed but might slow down already slow graph rendering.

Yep, I've noticed that in the PR description, just Disassembly widget :)

**Comment by a1ext** [comment]
@Adikso Have you figured out the problem? We can discuss that if you want

**Comment by ITAYC0HEN** [comment]
ping @a1ext and @Adikso , do you have solutions? I know you two worked on this

**Comment by a1ext** [comment]
Didn’t take a look

**Comment by ITAYC0HEN** [comment]
@dmknght some improvements were made, are you still experiencing the same?

**Comment by dmknght** [comment]
No it is still the same. Plus widget panels seems buggy in latest version

**Comment by ITAYC0HEN** [comment]
> No it is still the same. Plus widget panels seems buggy in latest version

@dmknght not buggy, but changed the way you drag and drop. to support dragging groups. So to drag a widget you should do this from the tab. and to drag a group of widgets do this from the top bar

**Comment by dmknght** [comment]
> > No it is still the same. Plus widget panels seems buggy in latest version
> 
> @dmknght not buggy, but changed the way you drag and drop. to support dragging groups. So to drag a widget you should do this from the tab. and to drag a group of widgets do this from the top bar

I'm sure what do you mean because this is about text highlighting error.

**Comment by ITAYC0HEN** [comment]
You mentioned Widget Panels. What did you refer to?
