### ISSUE TITLE
Enable X-refs in Strings panel and X-refs can not find strings

### ISSUE THREAD

**Issue by dmknght** [radareorg/cutter#801]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian 10 amd64
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | i386
| Cutter and r2 version, See About Cutter (mandatory)  | Version 1.7.2 / Using r2 3.0.0
| Show version information **full output**  | https://pastebin.com/MSfrUAY6

### Expected behavior
X-refs strings easily
### Actual behavior
1. I have to double click on the string -> move string panel to disassembly panel, select string object in text field and use X-refs
2. Graph panel will display `No function detected. Can not display graph.`  after panel move to disassembly panel.
3. Sometimes X-refs can not find string in functions
### Steps to reproduce the behavior 
Tested binary file (This is a malware)
[r.zip](https://github.com/radareorg/cutter/files/2468160/r.zip)

### Additional Logs, screenshots, source-code,  configuration dump, ...
1. A string is called in main function
![screenshot from 2018-10-11 16-00-59](https://user-images.githubusercontent.com/29118926/46793016-e2cd4480-cd6e-11e8-8936-b46e520a5605.png)
2. Search for that string in `Strings` panel
![screenshot from 2018-10-11 16-01-53](https://user-images.githubusercontent.com/29118926/46793074-0a241180-cd6f-11e8-9dfc-1da480a57815.png)
3. I have to move to disassembly panel to use X-refs
![screenshot from 2018-10-11 16-02-40](https://user-images.githubusercontent.com/29118926/46793107-1f993b80-cd6f-11e8-8d16-6d9ad8422b81.png)
X-refs can not find addr for this string
![screenshot from 2018-10-11 16-03-16](https://user-images.githubusercontent.com/29118926/46793151-393a8300-cd6f-11e8-98ed-25e7e2e5bd66.png)
(X-refs some other strings work good)
![screenshot from 2018-10-11 16-03-56](https://user-images.githubusercontent.com/29118926/46793214-58d1ab80-cd6f-11e8-885d-a16a14375a0c.png)

**Comment by xarkes** [comment]
I think the reason for that is the same as here: https://github.com/radareorg/cutter/issues/516

**Comment by dmknght** [comment]
Can you guys add X-refs to Strings panel? It would be a lot easier to find strings.

**Comment by kernelm0de** [comment]
![strxref](https://user-images.githubusercontent.com/30472260/46819227-d4981c00-cda0-11e8-8017-296ffd1f51ff.PNG)

With "0x" before the address i am able to get xrefs. getXrefs function inside Cutter.cpp doesn't use "0x" before the address. That might be causing the problem?

https://github.com/radareorg/cutter/blob/master/src/Cutter.cpp#L2037

**Comment by dmknght** [comment]
> Hmm you mean right click -> xrefs?

I think so. Because strings panel is using key filtering so i guess hotkey will not okay in here.

**Comment by ITAYC0HEN** [comment]
Ctrl+X?

**Comment by ITAYC0HEN** [comment]
Right, makes sense :)

**Comment by dmknght** [comment]
I've had a new idea about X-refs: Sidebar has x-refs panel, but it shows many information. So if you guys create a stand-alone x-refs panel, user can put xref like this (sreenshot). 
![screenshot from 2018-10-16 14-09-19](https://user-images.githubusercontent.com/29118926/46998577-24823480-d14d-11e8-872f-5a232c852d54.png)

**Comment by xarkes** [comment]
Yeah I think it's quite a good idea, and easy to do.

**Comment by dmknght** [comment]
So I think click string object in string panel should show value in Xreft table too. I've tested and it worked for graph panel and disassembly only.

**Comment by xarkes** [comment]
Yeah that's probably because it's not the same signal sent/catched. In disas/graph it is likely "seekChanged" while in strings it's nothing (for now) afair.

**Comment by ITAYC0HEN** [comment]
Fixed in #817

**Comment by dmknght** [comment]
I've tested latest git version with binary file `r.exe` again. Some strings are not showing in xref. Turned out it is radare2's problem.

**Comment by Maijin** [comment]
@dmknght can you open an issue?

**Comment by Maijin** [comment]
Yep ok thanks

**Comment by reallyuniquename** [comment]
https://user-images.githubusercontent.com/29118926/46998577-24823480-d14d-11e8-872f-5a232c852d54.png

I'm looking at this screenshot from 2018. How do I open X-Refs in the sidebar in the modern Cutter? Every time I press `x` a new modal window pops up. This is extremely frustrating since I need to go back and forth through every reference while looking at fully fledged dissassembly.
