### ISSUE TITLE
Function summary displaying has bad disasm preview formatting (-monospace font)

### ISSUE THREAD

**Issue by a1ext** [radareorg/cutter#807]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Windows 7 x64
| File format of the file you reverse (mandatory)      | not related
| Architecture/bits of the file (mandatory)            | not related
| Cutter and r2 version, See About Cutter (mandatory)  | Version 1.7.2 / Using r2-2.9.0-310-gcb62c376b

### Expected behavior
Function's summary `Disasm preview` and the tooltip in general have to look good and be easily readable

### Actual behavior
Currently `Disasm preview` is not well formatted due to non monospace font is set. Some instructions don't fit the tooltip (see the second screenshot)

### Steps to reproduce the behavior 
- Open some binary, make sure there any function in `Functions` view
- Point the mouse on some non-empty function and wait for the tooltip appears

Examples:
![image](https://user-images.githubusercontent.com/14978853/46840037-d0ccbf80-cdc9-11e8-9e73-96205347e4ba.png)

![image](https://user-images.githubusercontent.com/14978853/46840311-0aea9100-cdcb-11e8-9e44-23a088e499c7.png)

**Comment by ITAYC0HEN** [comment]
In addition to the mentioned problems, there is no width limit for the tool tip. Whenever there's a long flag in the disas preview, the width of the tool tip will fit to the text. In some cases the tool tip was so width that it covered my two monitors.

**Comment by a1ext** [comment]
@xarkes Why? it is good to have it... It saves the time, if a func is short and you don't have to click there to look at it.

**Comment by a1ext** [comment]
@xarkes is it possible to get disasm preview colored?

**Comment by xarkes** [comment]
It saves time, really? From my point of view, it's faster to click on it than waiting for the tooltip to appear.
I don't know if QToolTip supports html.

**Comment by a1ext** [comment]
I could fix that, it does I think. How to get colored output of `pdi 10 @ func_name`?

**Comment by xarkes** [comment]
I think you will need to use `pdJ`.

**Comment by kernelm0de** [comment]
Is anyone working on this? And imo strings shouldn't be displayed in tooltip. Some functions have too many strings which makes tooltip height too big.

**Comment by a1ext** [comment]
I’m working on it

**Comment by kernelm0de** [comment]
Tooltip supports html, so a <pre> tag will format disasm preview same as it appears on console :)

**Comment by a1ext** [comment]
Yes, I know. Currently the work in progress and it looks like the following:
![f91e66ff-70be-449f-80ea-0e5ee1226386](https://user-images.githubusercontent.com/14978853/46919838-03570200-cfee-11e8-85e8-70baa60586e4.jpeg)

**Comment by a1ext** [comment]
Hey guys, the question:
Currently we could crop a tooltip specifying its max width, but in this case lots of long names are being cropped, usually cropped is useful part, and useless (`sub.api_ms_win_crt_runtime_l1_1_0.dll__...`) is left, so the information displayed on tooltip becomes less useful than it has to be...

![image](https://user-images.githubusercontent.com/14978853/46951533-ef181100-d090-11e8-8c26-54c022214e73.png)

Is there a way to get rid of these prefixes, at least for displaying in these tooltips?

**Comment by xarkes** [comment]
Hi,
We are planning to remove it from any disas view to make the disassembly better, so I suggest you to keep it as it is now, and we will modify it once we managed to remove it from the disas widget.
