### ISSUE TITLE
Menu displays "Rename local variable" wrong after re-open saved project

### ISSUE THREAD

**Issue by dmknght** [radareorg/cutter#809]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian 10 amd64
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | i386
| Cutter and r2 version, See About Cutter (mandatory)  | Version 1.7.2 / Using r2 3.0.0
| Show version information **full output**  | https://pastebin.com/MSfrUAY6

### Expected behavior
Menu should display like this: Open brand new file.
![right](https://user-images.githubusercontent.com/29118926/46859213-5cc90080-ce37-11e8-8127-a70b6ed1703b.png)

### Actual behavior
Line `Rename <local_variable>` is `Add flag at <address>`
![wrong](https://user-images.githubusercontent.com/29118926/46859233-6e120d00-ce37-11e8-942e-4ffdaf4f1cb9.png)

### Steps to reproduce the behavior 
1. Reverse binary file, save to project folder
2. Open saved project folder in menu

### Additional Logs, screenshots, source-code,  configuration dump, ...
Binary file (Malware)
[r.zip](https://github.com/radareorg/cutter/files/2472354/r.zip)
Project folder
[spyware.zip](https://github.com/radareorg/cutter/files/2472358/spyware.zip)

**Comment by ITAYC0HEN** [comment]
CC: @jamieb122 maybe you'll have any insight here

**Comment by jamieb122** [comment]
That actually is not related to what was implemented in pull request #708 and looks to be a separate bug.  That pull request used the verbiage "Re-type function local vars."  This bug looks like it is related to the context menu item associated with "Rename Flag/Fcn/Var Used Here" in DisassemblyContextMenu.cpp (line 41).

**Comment by dmknght** [comment]
More information: Both clicking on menu and using hotkey `Shift + N` gives me `add flag` menu so i think this is a bug that calling wrong function.

**Comment by dmknght** [comment]
I think the problem is from https://github.com/radareorg/cutter/blob/2105b1fba21df25971f29c85b90ee3ceaf2182cd/src/menus/DisassemblyContextMenu.cpp#L287
```
        if (thingUsedHere["type"] == "address") {
            RVA offset = thingUsedHere["offset"].toVariant().toULongLong();
            actionRenameUsedHere.setText(tr("Add flag at %1 (used here)").arg(RAddressString(offset)));
        } else {
            actionRenameUsedHere.setText(tr("Rename \"%1\" (used here)").arg(thingUsedHere["name"].toString()));
}
```

**Comment by dmknght** [comment]
After playing, I think this problem comes from saving project (radare2 problem). Project does not save variable address -> reopening does not analysis binary file -> no information

**Comment by ITAYC0HEN** [comment]
ping @dmknght @jamieb122 , any idea how to continue now?

**Comment by dmknght** [comment]
I didn't test this error on latest version. I will test it in next few hours

**Comment by dmknght** [comment]
I've created a quick test. This problem is likely fixed. I will re-open it if I see this error again.
