### ISSUE TITLE
Reopen project use default asm.tabs and asm.tabs.off automatically

### ISSUE THREAD

**Issue by dmknght** [radareorg/cutter#815]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian 10 amd64
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | i386
| Cutter and r2 version, See About Cutter (mandatory)  | Version 1.7.2 / Using r2 3.0.0
| Show version information **full output**  | https://pastebin.com/MSfrUAY6

### Expected behavior
Cutter (after open saved project) should use user settings (Screenshot from a new random binary)
![screenshot from 2018-10-13 01-56-09](https://user-images.githubusercontent.com/29118926/46888679-5feddc00-ce8b-11e8-9338-09edd8a55b97.png)

### Actual behavior
Cutter is using default `asm.tabs` and `asm.tabs.off` options. Configuration in `/home/<user>/.conf/Cutter/cutter.conf` is different.
![screenshot from 2018-10-13 01-52-01](https://user-images.githubusercontent.com/29118926/46888410-a1ca5280-ce8a-11e8-82de-6ecb16c43c98.png)

### Steps to reproduce the behavior 
1. Open a binary file, set `asm.tabs`
2. Save project
3. Close Cutter, open it with saved project
4. Check settings
(I didn't compare other setting)

### Additional Logs, screenshots, source-code,  configuration dump, ...

Binary and project file is as same as #809

**Comment by xarkes** [comment]
Yeah I think because for now projects are only r2 projects (not Cutter).
We'll have to rework that, once the projects on r2 are fixed/more stable.

**Comment by ITAYC0HEN** [comment]
does this issue originated in @radare? if so, need to track it there and close here.

**Comment by xarkes** [comment]
I'm not sure, maybe we force `asm.tabs.off` somewhere in Cutter.

**Comment by ITAYC0HEN** [comment]
only set it to default

**Comment by xarkes** [comment]
Yep but maybe that is not done correctly and happens even after a project is loaded? I don't know, I need to check the code.

**Comment by dmknght** [comment]
Hey guys I've checked this issue following steps above. Everything seems okay now.
