### ISSUE TITLE
Color Themes: show only those which relevant to selected Dark\Light Qt Theme

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/cutter#816]
#### First terms definition:
**Color Theme:** The color of the text of the disassembly
**QT Theme:**  The color of the interface. Either "Default" (light) or "Dark"

---

Currently, we have too many Color themes and some (most?) of them are useless because:
1. super ugly
2. invisible or partially invisible in either or both of our QT Themes

For example, look at this combination of themes in which you can't see 80% of the text (offsets, instructions, branch arrows):
<kbd>
![image](https://user-images.githubusercontent.com/20182642/46905086-13d88100-cef7-11e8-9d21-9188f254e0a1.png)
</kbd>

If we'll use the same Color Theme with the "Dark" QT Theme it'd be better but still - theme is ugly and the `call func` instructions have black foreground color which is almost invisible:
<kbd>
![image](https://user-images.githubusercontent.com/20182642/46905131-f22bc980-cef7-11e8-9cde-8ae87028f55f.png)

</kbd>

---
These were just examples, there are many ugly color schemes as well as useless ones.

I suggest we choose ~5 color schemes for each QT Theme and show only these. Now after that #709 was implemented by @optizone8 the user have more control over their interface and they can create their own color schemes.

**Comment by optizone8** [comment]
I think, we should add light QT theme as well. Because default is not always light.

**Comment by kernelm0de** [comment]
- **dark** - default, ayu, zenburn, darkda, rasta, solarized, monokai, onedark, cga, lima
- **default** - cutter, white, dark, matrix
- **should remove** - defragger, consonance, pink, behelit, xvilka, white2, sepia, tango, focus, bold, smyck, ogray, basic

took a quick look at all the color themes, what do you think?

**Comment by ITAYC0HEN** [comment]
@kernelm0de overall good :)
Maybe we should remove more from the "dark" list. And we MUST add "consonance" to the dark list. It's great!

**Comment by ITAYC0HEN** [comment]
fixed in #846
