### ISSUE TITLE
Add a menu option to load a PDB

### ISSUE THREAD

**Issue by Maijin** [radareorg/cutter#82]
Additionally to the loader menu already done:

![image](https://user-images.githubusercontent.com/1408600/32372125-d762c504-c093-11e7-9ad3-014ecb0a8508.png)

Add a menu option to load a PDB after the binary have been loaded

**Comment by XVilka** [comment]
Maybe just specify path for multiple PDBs?

**Comment by xarkes** [comment]
Well no because you should still be able to load it after. Anyway I don't think this issue is a priority because you can simply call idp without using the GUI if this is really needed. But yeah good issue if you wanna start to contribute.

**Comment by Maijin** [comment]
not priority yep, just good to have it recorded
