### ISSUE TITLE
Improve preferences dialog

### ISSUE THREAD

**Issue by optizone8** [radareorg/cutter#820]
Now preferences dialog don't have 'apply' button, that usually presences in that type of widgets, maybe we should add one.

Also I think we should add new category related to color themes (like "Disassembly view") and keep "General" category to Qt themes, fonts, languages (I'll do it soon) and something more "general".

So, what do you think?

**Comment by ITAYC0HEN** [comment]
Adding a "Apply" button is a great idea! Good :) and 

I believe that anything about design should be at the same place (qt theme, color theme, fonts, etc). We can call it "appearance"/"interface" or something similar.

**Comment by ITAYC0HEN** [comment]
I think yes

**Comment by ITAYC0HEN** [comment]
Yeah, but maybe "appearance" is more popular
