### ISSUE TITLE
Undirected Graph Edge displayed for a jump that goes out of the current function

### ISSUE THREAD

**Issue by kernelm0de** [radareorg/cutter#824]
![graph](https://user-images.githubusercontent.com/30472260/46915388-c0366800-cfc8-11e8-9832-fe48650b8c56.PNG)

I think there should not be any edge displayed for a jump that goes out of the current function

**Comment by Maijin** [comment]
It probably should be highlighted too somehow.

**Comment by xarkes** [comment]
What should be highlighted? The last block?

**Comment by Maijin** [comment]
I think the instruction should be highlighted or something else that shows this behavior

**Comment by xarkes** [comment]
Probably but I didn't investigate.

**Comment by ITAYC0HEN** [comment]
@kernelm0de can you share the binary? does it exist in radare2 as well?

**Comment by kernelm0de** [comment]
@ITAYC0HEN Sorry for the late reply, the issue does not exist radare2.
[ls.zip](https://github.com/radareorg/cutter/files/2896729/ls.zip)

**Comment by karliss** [comment]
Fixed by  #1582
