### ISSUE TITLE
Add more C++ classes documentation and include it in the new docs

### ISSUE THREAD

**Issue by xarkes** [radareorg/cutter#833]
We must have some API documentation, so we should find a way to do this.
The easiest is to add them as comments and generate it with doxygen, now I don't know how easily it can be integrated on https://radareorg.github.io/cutter/

**Comment by ITAYC0HEN** [comment]
I think this is done @xarkes , right?
If so, please close this issue :)

**Comment by xarkes** [comment]
Indeed :)
