### ISSUE TITLE
"Save as..." does not work in the Cutter

### ISSUE THREAD

**Issue by rootbsd** [radareorg/cutter#835]
**Environment information**
* Operating System: Windows 10
* Cutter version: 1.7.2
* File format: PE32

**Describe the bug**
If I use the user interface to save my project it simply does not work.
I need to use the command line (Ps projectname) in order to save my work.

**Expected behavior**
Saving.

P.

**Comment by xarkes** [comment]
We discussed that already, and decided to remove the "Save project" UI for next releases, as projects are very badly supported in radare2 (see examples below):
- https://github.com/radareorg/cutter/issues/501
- https://github.com/radareorg/cutter/issues/282

I'm aware it is a "must have" feature, but this requires some heavy changes in radare2 that will be discussed soon.

**Comment by xarkes** [comment]
I think the specific issue you mentioned should have been fixed thanks to: https://github.com/radareorg/cutter/pull/900
I am closing this issue as there are other issues for the problems I mentioned before.
Feel free to reopen if not fixed :)
