### ISSUE TITLE
Color Palette not displayed

### ISSUE THREAD

**Issue by Maijin** [radareorg/cutter#841]
**Environment information**
* Operating System: OSX
* Cutter version: r2 and cutter from git
* File format: n/a

**Describe the bug**

When clicking on the color in preference, the palette doesn't show up

**Expected behavior**
When clicking on the color in preference, the palette show up

**Comment by xarkes** [comment]
Maybe it doesn't work because you didn't copy an existing theme?
You cannot modify a native theme, you have to copy it first.

**Comment by Maijin** [comment]
Don't believe this would have an impact on opening the palette

**Comment by a1ext** [comment]
Opening a palette without opportunity to store a new color has not meaning. btw, duplication of existing code has fixed in #970

**Comment by ITAYC0HEN** [comment]
@Maijin can you verify issue solved?
