### ISSUE TITLE
Strings panel section filtering

### ISSUE THREAD

**Issue by Maijin** [radareorg/cutter#845]
**Is your feature request related to a problem? Please describe.**
Too much strings in strings panel, would be nice to be able to filter by sections

**Describe the solution you'd like**
Add section column and ability to filter in the search bar

See - [ch2(1).zip](https://github.com/radareorg/cutter/files/2486505/ch2.1.zip)

**Comment by kernelm0de** [comment]
I agree with the section column, but i am curious how will the filtering on based of sections work?? Add another filter? Maybe we could add a dropdown menu which shows an option to choose sections of the binary from which to show the strings.

**Comment by Maijin** [comment]
maybe the filter should be both applied to sections and strings

**Comment by Maijin** [comment]
@pelijah did work on something for this one
