### ISSUE TITLE
Add a library to resolve symbols 

### ISSUE THREAD

**Issue by sebdraven** [radareorg/cutter#850]
The goal is to have a pop up or menu when a binary uses a library.  It's useful  when your reverse vb executable or delphi executable. 
With the library you can resolv the symbol and put it in the assemby or graph view.

**Comment by ITAYC0HEN** [comment]
Hi, thanks for the suggestion! :) 
Can you please elaborate more on how would you want to see this feature implemented?
Screenshots from other frameworks would be good as well.

**Comment by xift** [comment]
I imagine it being like the "modules" tab in Visual Studio.
What do you think?

![image](https://user-images.githubusercontent.com/1312047/47269664-7d910480-d561-11e8-925a-ed6f5644ef97.png)

**Comment by Maijin** [comment]
I guess like the load additional file in ida?

**Comment by ITAYC0HEN** [comment]
ping @sebdraven , we need your input here :) Do you mean something like loading Type-Libraries from IDA? To autodetect library functions such as Delphi's?

**Comment by sebdraven** [comment]
Yes exactly, for making easy the reverse of this kind of binaries :)

**Comment by Maijin** [comment]
ok so that's basically zignatures then, i think it can be closed here because it's tracked in r2 side
