### ISSUE TITLE
Coverity builds

### ISSUE THREAD

**Issue by XVilka** [radareorg/cutter#855]
Currently there is opened Coverity account for Cutter, but we have to setup periodic builds.

**Comment by xarkes** [comment]
ping @XVilka I think you started on ci.rada.re but I don't know the status?

**Comment by XVilka** [comment]
@xarkes I uber busy these days, will finish the setup (it is mostly done) as soon as I have some free time.

**Comment by ITAYC0HEN** [comment]
@XVilka any update about this?

**Comment by xarkes** [comment]
Yes we are waiting for the new infrastructure.

**Comment by XVilka** [comment]
The Coverity itself was having problems until a week ago or so. Now you
need to wait a bit since I move CI on a new physical server.

**Comment by XVilka** [comment]
See https://community.synopsys.com/s/article/Coverity-Scan-Update

**Comment by XVilka** [comment]
This one is better now - you can setup it with GitHub Actions: https://github.com/ruby/actions-coverity-scan/blob/master/.github/workflows/coverity-scan.yml

**Comment by XVilka** [comment]
Once we check that radare2 GitHub Actions work, we can copy them to the Cutter: https://github.com/radareorg/radare2/blob/master/.github/workflows/coverity-scan.yml

**Comment by XVilka** [comment]
Solved in https://github.com/radareorg/cutter/actions?query=workflow%3Acoverity-scan

**Comment by ITAYC0HEN** [comment]
fantastic! thanks @XVilka!
