### ISSUE TITLE
Debug-related widgets shouldn't be available outside Debug\Emulation mode

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/cutter#859]
**Describe the bug**
Currently, a user can open the debug-related widgets even if they aren't in debug mode. This will obviously show wrong information and might cause confusions.

**To Reproduce**

Click on the "Windows" menu item, choose "Debug..." and select a debug-related widget

**Expected behavior**
When not in debug\emulation mode, I expect the "Debug" item to be grayed out.

![image](https://user-images.githubusercontent.com/20182642/47252286-e8035100-d44a-11e8-8e93-81612a7f23f7.png)

**Comment by xift** [comment]
Hi, 

I found cutter while browsing the Hacktoberfest issues. 
Just submitted a pull request for this issue. Hope that is fine. If you have any specific protocol I should follow, please let me know. I hope to contribute more to cutter in the future.
Keep up the good work!

Best regards,
Michael
