### ISSUE TITLE
Can't save project to file

### ISSUE THREAD

**Issue by samvdkris** [radareorg/cutter#865]
**Environment information**
* Operating System: Windows 10
* Cutter version: 1.7.2
* File format: Any

**Describe the bug**
When I try to save a project using CTRL + S (or save as in menu), it opens the "save project" windows, but when I click save (with default settings, but I tried some other settings as well), the windows just closes but the file isn't saved anywhere.

**To Reproduce**
1. Open a file in Cutter
2. Press CTRL + S
3. Try to save the project with default settings

**Expected behavior**
The project is saved to a file.

**Screenshots**
![screenshot 5](https://user-images.githubusercontent.com/22723225/47271975-63661f00-d57f-11e8-9339-e2d9bfb44311.png)

Sorry for the kind of vague description, but this is all I know. I'd be happy to provide an error log or additional info if needed.

**Comment by ITAYC0HEN** [comment]
This is now fixed on master. Thank you :)
Please let us know if you still encounter the problem.
