### ISSUE TITLE
Segfault when clicking "Edit Function" outside\middle of a function

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/cutter#867]
**Environment information**
* Operating System: Arch Linux
* Cutter version: 1.7.2 - Master
* File format: PE, ELF

**Describe the bug**
When using `Right-Click -> Edit Function` in a middle of a function or outside of a function, Cutter is crushing.

**To Reproduce**
1. Open /bin/ls in Cutter
2. Choose a function and Right-Click in the middle of it
3. Click "Edit Function"
4. Get segfault

**Expected behavior**
the "Edit Function" menu-item shouldn't be displayed when clicking outside of a function. And should be shown (and work) whenever you click inside a function.

Probably, it is hapening because `r_anal_get_fcn_at` returns NULL since the clicked address does not correspond to any function. It just compares the current offset with all the function addresses
so it only works when we open "Edit Function" from the head of that function. It crashes due to dereferencing a null pointer as `r_anal_get_fcn` returns NULL.

**Screenshots**

![ezgif-2-91fc487876ff](https://user-images.githubusercontent.com/20182642/47302822-1f305880-d62b-11e8-90f9-3ac8fc0f2a41.gif)

**Additional context**

Backtrace: https://pastebin.com/zRvXdqwJ

**Thanks to @kernelm0de for reporting this issue and sharing his backtrace and screen record.  <3**

**Comment by ITAYC0HEN** [comment]
ping @sajattack -- would you please take a look at this?

**Comment by sajattack** [comment]
A quick stopgap measure should be to wrap 698-728 in `if (fcn)`. I'm not sure how to make the menu hidden outside a function or work in the middle.

**Comment by ITAYC0HEN** [comment]
To detect a click in the middle of a function use `r_anal_get_fcn_in (core->anal, offset, 0)` instead of `r_anal_get_fcn_at (core->anal, offset, R_ANAL_FCN_TYPE_NULL)`.


And to see how to hide the "Edit Function" when not in function , check similar implementations to get inspiration from. For example, the renaming of local variables ("used here").
