### ISSUE TITLE
Check default font

### ISSUE THREAD

**Issue by xarkes** [radareorg/cutter#87]
Monospace is not a valid font for stock Mac.
Use "Andale Mono" for Mac, or Courier or maybe use the ones that were bundled with iaito before.
Or just use `QFontDatabase::systemFont(QFontDatabase::FixedFont)` if it works

**Comment by xarkes** [comment]
Also we must have at most 1 or 2 fonts (one for disasm one for UI), and that they are all synchronized (size and font face)

**Comment by thestr4ng3r** [comment]
I would not change the normal UI font at all, that should be defined by the system.

**Comment by xarkes** [comment]
Ok then we have to sync the disassembly font for Hex/Graph/Disas and use the system font for any other thing.

**Comment by thestr4ng3r** [comment]
Using `QFontDatabase::systemFont(QFontDatabase::FixedFont)` since https://github.com/radareorg/cutter/commit/a454ca68f8ab060b3f41c6aada16b175fc46e6b5.
I tested on Linux Mint (Cinnamon), macOS and Windows 10 and get a nice monotype font on each of them.
