### ISSUE TITLE
s 0xADDR dont work

### ISSUE THREAD

**Issue by s0i37** [radareorg/cutter#872]
**Environment information**
* Operating System:
kali rolling amd64
* Cutter version:
Cutter 1.7.2 (Fri Oct 19 15:11:37 2018 +0300)
radare2 3.0.0 19993 @ linux-x86-64 git.2.9.0-407-g734b3d73b
commit: 734b3d73ba3987e3213ca53e9715c3da63196b9b build: 2018-10-19__23:16:33
* File format:
elf64 (/bin/ls)

**Describe the bug**
Dont work jump via "s ADDRESS" command in command bar. This feature worked a couple of month ago.

**To Reproduce**
Just type "s 0xaddress"

**Expected behavior**
I expected immediate jump in Graph or Disassembly views

**Comment by xarkes** [comment]
You are talking about the Console Widget right?
Yes it seems you now have to manually refresh the views with View->Refresh Contents and it is indeed a regression.

**Comment by xarkes** [comment]
Actually it looks harder than expected.
I think because of CutterSeekableWidget, the widgets do not catch the `seekChanged` signal from Core.
I think that part should be rewritten.
