### ISSUE TITLE
Highlight elements on hover when creating theme

### ISSUE THREAD

**Issue by Adikso** [radareorg/cutter#882]
**Is your feature request related to a problem? Please describe.**
Creating new theme in Appearance is really tiring for me as you have to search and guess what does each color is responsible for when I just want to change single thing.

**Describe the solution you'd like**
Cutter could highlight (change color to eg. pink) elements with color that we hover mouse on or when we select color from the list.

**Comment by ITAYC0HEN** [comment]
Do you have any idea for this? Sounds hard to implement since it doesn't available from r2.

I think we would eventually implement a small demo-function with as many examples as possible for colors, and let the user tweak it. This will be some kind of a quick preview for the theme

**Comment by ITAYC0HEN** [comment]
@optizone will solve this in his upcoming PR :)

**Comment by ITAYC0HEN** [comment]
This is now implemented in the new Theme Editor :)
Well done @optizone
