### ISSUE TITLE
Visual SDB browser

### ISSUE THREAD

**Issue by XVilka** [radareorg/cutter#884]
To be able navigate through all internal SDBs (like within radare2 with `k` commands).

See also the corresponding bug for radare2: https://github.com/radare/radare2/issues/11979

**Comment by xarkes** [comment]
There is already an SDB browser?
Or I didn't understand the issue maybe?

**Comment by Maijin** [comment]
Already there yep

**Comment by radare** [comment]
Iaito had it. Ragui had it.. so all the private guis i did had one. U probably removed it from cutter

**Comment by radare** [comment]
Nvm its there

**Comment by xarkes** [comment]
Yes, please test it on latest release before opening an issue :)
