### ISSUE TITLE
Correct `Rename function` menu

### ISSUE THREAD

**Issue by dmknght** [radareorg/cutter#887]
**Environment information**
* Operating System: Parrot OS 4.2
* Cutter version: git, pulled 29/10/2018
* File format: ELF 64

**Describe the bug**
`Rename function` in `Graph panel` menu displayed `(used here)` (rename it in local function) but it renames function globally.

**To Reproduce**
1. Right click on function -> choose `Rename function (used here)`
![screenshot at 2018-10-30 16-31-59](https://user-images.githubusercontent.com/29118926/47708918-c2075900-dc61-11e8-8e66-4676e52f664a.png)

2. Click on `Rename function` and rename it
![screenshot at 2018-10-30 16-32-22](https://user-images.githubusercontent.com/29118926/47708916-c16ec280-dc61-11e8-962e-331c02b17de8.png)

3. Submit result. Now function name has been renamed globally
![screenshot at 2018-10-30 16-32-37](https://user-images.githubusercontent.com/29118926/47708947-d3506580-dc61-11e8-9c7e-b01020c459d7.png)

**Expected behavior**
`Rename function` line in menu does not have `(used here)`

**Additional context**
`Rename function` and `Rename variable` are using same condition to display text.

**Comment by ITAYC0HEN** [comment]
Hi @dmknght, thank you for filling an issue :) 
Please follow our [Bug Report](https://github.com/radareorg/cutter/issues/new?template=bug_report.md) template so we would be able to understand the issue perfectly. Please edit your issue, describing it thorughly.

**Comment by dmknght** [comment]
Thanks for reply. I tested with code (link bellow) and everything seems good. 
https://github.com/radareorg/cutter/compare/master...dmknght:patch-1

**Comment by xarkes** [comment]
Then, open a PR :+1:
