### ISSUE TITLE
Fix dark theme

### ISSUE THREAD

**Issue by xarkes** [radareorg/cutter#89]
The dark theme option is still present, but it's not very reliable. It should update every widget and set it's style to the dark one. Also it should change the disassembly colors, etc.

- [ ] The arrow buttons are white/black (On the darker background, they look inverted.).
- [x] Most list's selected item/hover colors are explicitly set and don't necessarily match dark themes.
- [x] Disassembly color presets are not perfect yet. Specified in `Configuration::loadDefaultTheme()` and `Configuration::loadDarkTheme()`
- [x] The background of the window borders within Cutter is gray/white.
- [x] Tabbed views (e.g. Dashboard | Disassembly | Graph..., or Sections | Comments) are gray/white.
- [x] The dashboard is gray/white.
- [x] The headers of the lists with multiple columns (e.g. the sections window in the bottom left) are gray/white.
- [x] The sections chart has a white background.
- [x] The opcode description is white/black.

**Comment by TheKoopaKingdom** [comment]
+1, this is what Cutter using the Dark theme looks like with the `Arc-Dark` GTK theme on XFCE:
![](https://i.imgur.com/6jBwM4M.png)
And Cutter with the default theme, with the `Arc` GTK theme:
![](https://i.imgur.com/F0jZbPL.png)

**Comment by xarkes** [comment]
The white buttons on the top left with default theme is weird.

**Comment by thestr4ng3r** [comment]
@TheKoopaKingdom could it be that you don't have Qt's SVG support? How did you build cutter or did you use the builds from the GitHub releases?

I think we will also have to add that to the .pro file:
```
QT += svg
```

**Comment by TheKoopaKingdom** [comment]
I built it myself. I followed [the instructions to install Radare2](https://github.com/radareorg/cutter#requirements), and, in [src](https://github.com/radareorg/cutter/tree/master/src), ran the usual `mkdir build && cd build`, `cmake ..`, and `make`.

**Comment by thestr4ng3r** [comment]
So I suppose you used Qt from your distribution's packages? What distribution+version is this?

**Comment by xarkes** [comment]
@TheKoopaKingdom Can you test with the latest version and tell what's broken exactly?

**Comment by TheKoopaKingdom** [comment]
>So I suppose you used Qt from your distribution's packages? What distribution+version is this?

Yep. This is Arch Linux, [Qt version 5.9.2](https://www.archlinux.org/packages/extra/x86_64/qt5-base/).

>Can you test with the latest version and tell what's broken exactly?

Rebuilt with the latest version, some of it is better now.
Issues that still persist:
- The disassembly has dark text on a dark background in some cases.
- The background of the window borders within Cutter is gray/white.
- Tabbed views (e.g. `Dashboard | Disassembly | Graph`..., or `Sections | Comments`) are gray/white.
- The dashboard is gray/white.
- The headers of the lists with multiple columns (e.g. the sections window in the bottom left) are gray/white.
- The sections chart has a white background.
- The opcode description is white/black.
- The arrow buttons are white/black (On the darker background, they look inverted.).
- The function list's highlight color is white (Should be blue, like the offset info of the sidebar.)
![screenshot_2017-11-20_20-05-39](https://user-images.githubusercontent.com/13039555/33049464-3b65ae52-ce2e-11e7-8043-7de14beb46c9.png)
![screenshot_2017-11-20_20-06-19](https://user-images.githubusercontent.com/13039555/33049476-5020ef0a-ce2e-11e7-96a0-7290f0930baf.png)
![screenshot_2017-11-20_20-06-57](https://user-images.githubusercontent.com/13039555/33049490-6538b2ce-ce2e-11e7-8601-136cbf2d02bd.png)

**Comment by thestr4ng3r** [comment]
I could reproduce the white icons when QtSvg is not installed. It is now requred as of https://github.com/radareorg/cutter/commit/9927f2cf206a92b1b63b41adf36c179297811f7b.

**Comment by thestr4ng3r** [comment]
Fixed most of the issues:
![bildschirmfoto vom 2017-11-25 15-58-24](https://user-images.githubusercontent.com/1460997/33231680-b54641ea-d1f9-11e7-8d51-c72b1783df11.png)
Note the different highlight colors in functions on the left (explicitly set) and offset info on the right (system default). In my opinion, we could just use system colors for all lists.

By the way, I found out it is possible to refer to palette colors from stylesheets: http://doc.qt.io/qt-5/stylesheet-reference.html#paletterole
