### ISSUE TITLE
Some graph improvement requests

### ISSUE THREAD

**Issue by dmknght** [radareorg/cutter#891]
**Environment information**
* Operating System: Debian 10 amd 64
* Cutter version: git version, pulled 31/10/2018; radare2 3.1 git pulled 31/10/2018
* File format: elf 32

**Is your feature request related to a problem? Please describe.**
Cutter graph panel is still hard to read in some case. There are some thing must be improved. And there are my ideas i'd like to show

**Describe the solution you'd like**
1. Add offset address or label to block code (i think creating a header for block is very good).
Current cutter block, I think adding address is a lot easier to read
![screenshot from 2018-10-30 23-55-12](https://user-images.githubusercontent.com/29118926/47735543-504e0000-dc9f-11e8-8e2c-1eded17fb3b8.png)
Comparing to IDA (free), they added custom name as label
![screenshot from 2018-10-30 23-55-59](https://user-images.githubusercontent.com/29118926/47735605-6c51a180-dc9f-11e8-803e-6a677daf3ab3.png)
Hopper (image from google)
![screenshot from 2018-10-30 23-58-21](https://user-images.githubusercontent.com/29118926/47735754-b9357800-dc9f-11e8-88f8-2cf314b02899.png)
Radare2 visual mode
![screenshot from 2018-10-31 00-19-38](https://user-images.githubusercontent.com/29118926/47737099-b5572500-dca2-11e8-8c76-f716ede2f694.png)

2. Improving graph links (I don't know what to call it here LoL, sorry about that)
In cutter, it is a little bit hard to track the code. In this case, 2 links are in the same side.
![screenshot from 2018-10-31 00-00-43](https://user-images.githubusercontent.com/29118926/47735896-06194e80-dca0-11e8-9130-4d55164808df.png)
In Ida free, all code blocks display better:
![screenshot from 2018-10-31 00-01-30](https://user-images.githubusercontent.com/29118926/47735940-2812d100-dca0-11e8-88b5-a75f10b6105e.png)
In radare2 (3.1 git version), that 2 links display in 2 side
![screenshot from 2018-10-31 00-04-04](https://user-images.githubusercontent.com/29118926/47736116-89d33b00-dca0-11e8-9c2a-b955cd9063c3.png)
![screenshot from 2018-10-31 00-04-35](https://user-images.githubusercontent.com/29118926/47736127-8fc91c00-dca0-11e8-8229-c0422d62e4db.png)
3. Saving graph space by showing comments in mouse highlight box? (#784)
![screenshot from 2018-10-31 00-07-26](https://user-images.githubusercontent.com/29118926/47736281-f8b09400-dca0-11e8-8763-53a4ce4b882c.png)
This 2 blocks can save 40 - 50% of width.
Again, ida has good block size
![screenshot from 2018-10-31 00-08-56](https://user-images.githubusercontent.com/29118926/47736412-39101200-dca1-11e8-93d0-9374a6aa321a.png)
4. asm.bytes option is in `meta` tab by now, other options for bytes displaying (asm.bytespace and asm.lbyte) are in `style` tab. I think move them to 1 tab, make asm.bytespace and asm.lbyte as asm.bytes's sub option is easier for setting
5. A bug that `Set immediate base to` is missing for `0x21` value misses in menu.
![screenshot from 2018-10-31 00-14-08](https://user-images.githubusercontent.com/29118926/47736798-0adf0200-dca2-11e8-8578-b55d283c8a0f.png)
![screenshot from 2018-10-31 00-13-56](https://user-images.githubusercontent.com/29118926/47736799-0b779880-dca2-11e8-8f24-4357a778e2e4.png)

My tested binary 
[binary.zip](https://github.com/radareorg/cutter/files/2530803/binary.zip)

Sorry for my bad English. I know i am asking a lot features right now but i think some of them are useful for users. I believe Cutter is the best free disassembler right now and i hope my ideas will improve it.
Big thanks to dev team <3

**Comment by ITAYC0HEN** [comment]
@Maijin are these issues split?

**Comment by Maijin** [comment]
No that needs to be split indeed @ITAYC0HEN, are you doing it?

**Comment by ITAYC0HEN** [comment]
@dmknght may I ask your help with testing the current state of the graph against these issues and open a separate issue for each of the problems you find? This would be very helpful <3

**Comment by dmknght** [comment]
Hi! I am building latest cutter with latest radare2 version and i got this error `/usr/bin/ld: Cutter.o: in function `CutterCore::loadFile(QString, unsigned long long, unsigned long long, int, int, bool, QString const&)':`. Am i doing something wrong :'(

**Comment by ITAYC0HEN** [comment]
Do you use "build.sh"?

**Comment by dmknght** [comment]
No i used cmake. Let me try qmake (I follow installation steps in wiki as same as before)

**Comment by ITAYC0HEN** [comment]
Both will build Cutter but not the required r2 version. Try using "build.sh" thy will build r2 in the right version :)

**Comment by dmknght** [comment]
Okay please give me minutes i am doing it right now

**Comment by dmknght** [comment]
Still have that error. I am thinking i didn't install enough libs for qt (i am using new system)

**Comment by dmknght** [comment]
Latest build completed. Close, test and create new issue as dev requested
