### ISSUE TITLE
Packaging status

### ISSUE THREAD

**Issue by XVilka** [radareorg/cutter#908]
Like for radare2 page, but not sure how to align it https://repology.org/metapackage/radare2-cutter/versions

**Comment by ITAYC0HEN** [comment]
Sorry, I don't like this feature in the radare2 README. It is too noisy and will get noisier with time.
Also, I find it quite useless. Currently, we should discourage people to use distribution packages instead of downloading Cutter from the Releases tab. And in the future, from the website.
