### ISSUE TITLE
MacOS Application Bundle doesn't start at all

### ISSUE THREAD

**Issue by kassi** [radareorg/cutter#912]
**Environment information**
* Operating System: MacOS High Sierra 10.13.6 (17G65)
* Cutter version: v1.7.2 and deploy-test (both not working)
* File format: dmg

**Describe the bug**
When opening the app bundle (after copying to /Applications folder and confirming unsigned app), the app crashes.

**To Reproduce**
1. Open downloaded App bundle
2. Copy Cutter.app to /Applications
3. CTRL-Click app icon, choose "Open" and click "Open" (for unsigned, downloaded app)
4. See app icon bumping 3 times and disappearing
5. See apple bug report screen appearing.

**Expected behavior**
App should start, no bug report.

**Additional context**
`/var/log/system.log` states:
```
Nov  9 18:33:03 ... com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x1000014a.Cutter[68505]): Service exited with abnormal code: 139
```

Content of bug report: https://gist.github.com/kassi/59f7876505735e09183c6cb866462728

**Comment by xarkes** [comment]
Thanks for reporting, this is a known issue, we'll fix it for next release which is coming soon :)

**Comment by ITAYC0HEN** [comment]
Fixed now I think :)
Please re-open if you still encounter the bug
