### ISSUE TITLE
Overwritten several immediate functions to 00 bytes

### ISSUE THREAD

**Issue by partoftheworlD** [radareorg/cutter#914]
**Environment information**
* Operating System: Windows 10
* Cutter version: 1.7.2
* File format: dylib

**Describe the bug**
After using r2dec and pdc file is completely overwritten by 00 bytes

**To Reproduce**
1. Select pseudocode
2. Select r2dec
3. Press button refresh
4. Select pdc
5. Press button refresh

**Expected behavior**
Getting pseudo code

**Screenshots**
https://youtu.be/QzjmlNVvqF4

**Comment by pelijah** [comment]
I don't think that it is Cutter bug. Can you reproduce it in r2?

**Comment by partoftheworlD** [comment]
yes, radar2 has the same bug.

1.pdd
2.pdc

https://imgur.com/a/A8iOVdy

radare2 3.1.0-git 19997 @ linux-x86-64 git.3.0.1-184-g2683db470
commit: 2683db4708daaa5cea093618a289fb1cc3497a22 build: 2018-11-11__16:31:42

**Comment by wargio** [comment]
Wtf. This should not happen.
It smells more like a r2 bug. @radare

**Comment by radare** [comment]
Sounds like new maps filled with zeros or different offsets buti cant see this in the video.r2dec and pdc work fine in r2, the thing ia what is cutter doing? Can you try om commands to see if the memory is overlapped or theres a caching

**Comment by partoftheworlD** [comment]
before
![2018-11-11 19-32-02](https://user-images.githubusercontent.com/6013494/48315536-a8163080-e5e8-11e8-9a36-d87094caa6a4.png)

after
![2018-11-11 19-32-39](https://user-images.githubusercontent.com/6013494/48315540-afd5d500-e5e8-11e8-854b-5cc60ebf0504.png)

**Comment by wargio** [comment]
Can you just call pdd and see if the map has been added?

**Comment by partoftheworlD** [comment]
New map added after pdc

**Comment by wargio** [comment]
That's super weird! @radare this is a regression for sure

**Comment by radare** [comment]
should be fixed in r2, just bump the version of r2

**Comment by partoftheworlD** [comment]
Fixed in most cases, but with one file this bug happens all time, can it be that bug arises because of the file? Please, check this file, It's the Pwnie Island: Pwn Adventure 3 library of game logic

[libGameLogic.zip](https://github.com/radareorg/cutter/files/2599941/libGameLogic.zip)

**Comment by radare** [comment]
this file works fine in r2, no issues here

**Comment by ITAYC0HEN** [comment]
@partoftheworlD can you test it on recent Cutter version from git?

**Comment by partoftheworlD** [comment]
@ITAYC0HEN Sure. 5 minutes.

**Comment by partoftheworlD** [comment]
@ITAYC0HEN Completely fixed.

**Comment by ITAYC0HEN** [comment]
Great! Thank you for reporting! Appreciate it
