### ISSUE TITLE
Add Types/Enum/Structure right click and panels

### ISSUE THREAD

**Issue by Maijin** [radareorg/cutter#918]
**Is your feature request related to a problem? Please describe.**
A way to manipulate types/structures/enum in disassembly and graph 

**Describe the solution you'd like**

Here is the list of steps:

- [x] Add panel for listing types #254  
- [ ] Move type panel in the windows drop-down instead of windows/info
- [ ] Add filter capability in the panel
- [ ] Add listing enum in the panel `tej`
- [ ] Add listing union in the panel `tuj`
- [ ] Add listing structures in the panel `tsj`
- [ ] Add listing typedefs in the panel `ttj` (require https://github.com/radare/radare2/issues/12119)
- [ ] Add right click to add element in the panel
- [ ] Add right click to edit element in the panel
- [ ] Add right click to remove element in the panel
- [ ] Add right click to which open a windows where you can paste or open an header file in the panel
- [ ] Add right click apply structure in the disassembly 
- [ ] Add right click apply structure in the graph
- [ ] Add export everything in C format `tc`

**Comment by XVilka** [comment]
Also interface for changing type parameters, like constraints for example https://github.com/radare/radare2/issues/11828

**Comment by Maijin** [comment]
Splitted into issues.

**Comment by ITAYC0HEN** [comment]
Project can be found here: https://github.com/radareorg/cutter/projects/11
