### ISSUE TITLE
Provide C++ API documentation for developers and UML

### ISSUE THREAD

**Issue by xarkes** [radareorg/cutter#919]
* Provide UML graph of our classes to have a better view on the project
* Provide C++ documentation with something like doxygen and integrate it to https://radareorg.github.io/cutter/

**Comment by ICEBERG98** [comment]
Hey, I put the project through doxygen. The docs still require a lot of work, I wonder if anybody else would be willing to contribute??

**Comment by xarkes** [comment]
I can work on providing the functions documentation, but the main issue is the second point, to find a way to integrate those with our current sphinx blog.

**Comment by xarkes** [comment]
To markdown yes, if possible.

**Comment by ICEBERG98** [comment]
Hey @xarkes, I tried some things and got a markdown file containing documentation for the files, but the problem is that it is extremely huge(21 MB) for a .md file.
Here's a link to it-
https://drive.google.com/open?id=1c8-GqjWzsxZhVLCp5XOlmZET0Kz6ptem

**Comment by xarkes** [comment]
The file you linked is 244K and refers to macros that are not used (directly) in Cutter.

**Comment by ICEBERG98** [comment]
Yeah, it parsed the includes in the /radare/ directory. Is there anyway i could geta look at the source code for the sphynx blog?

**Comment by xarkes** [comment]
You can contact me on IRC or Telegram.

**Comment by xarkes** [comment]
Can be closed too.
