### ISSUE TITLE
Context menus in symbols, strings, imports, entrypoints, ...

### ISSUE THREAD

**Issue by radare** [radareorg/cutter#923]
Add the following entries:

* [x] Seek in hexdump
* [x] Seek in disassembly
* [x] Show X-Refs
* [x] Copy address in clipboard
* [x] Copy name to clipboard
* [ ] Toggle Highlight

**Comment by karliss** [comment]
I don't see how seek in hexdump and disassembly would work with current UI.
* For synchronized memory widgets it is just seek in all widgets which should be already implemented, no need for "seek in X".
* There be multiple copies of unsynchronized hexdump, disasembly widgets. How to display it in usable way?

**Comment by ITAYC0HEN** [comment]
I think that what it means is to:

1. Perform a seek to the address
2. Set focus to the opened hexdump\disas widgets. If none exists, open one and focus to it

In IDA, when you open an address in new (hex\disas\graph) widget, the new widget it unsynced -- and I like it

**Jump in new Window**

![image](https://user-images.githubusercontent.com/20182642/58028129-c3777080-7b22-11e9-93a2-55631c4faf7c.png)



**New window is not synced with current seek, and not changes the current seek for all widgets**

![image](https://user-images.githubusercontent.com/20182642/58028216-eefa5b00-7b22-11e9-8b83-c8c7c8c4afe6.png)

**Comment by karliss** [comment]
Seek+focus and new unsynced window both make sense.

**Comment by karliss** [comment]
I am thinking of creating AddressableItemContextMenu,  maybe AddressableItemModel and AddressableItemListWidget.

**Comment by karliss** [comment]
Remaining work:
* Decide what to do with keyboard search
* Consider if synchronized seek behaviour for "show in" menu can be improved
* Add some notes about AddressableItemX in developer documentation
* Test if ListDockWidget can be used from python plugin
* Add or Replace comment -> Add or Edit comment
* Remaining widgets with list
   * TODO
* Stack widget
* Xrefs widget

**Comment by ITAYC0HEN** [comment]
fixed in #1718

**Comment by karliss** [comment]
There are a few remaining tasks:  debug widgets, documentation an testing if it can be used from python.
