### ISSUE TITLE
Add more hashes in the hexdump side panel

### ISSUE THREAD

**Issue by radare** [radareorg/cutter#925]
Add more hashes: (not just md5 and sha1), ideally this list of hashes should be configurable by the user. (rahash2 -L)
* sha256
* crc32
* md4
* pcprint
* ...

**Comment by radare** [comment]
This also applies to the Dashboard, can we consider this dupped info?

**Comment by philipmnelson** [comment]
I'm working on this one. What is a sufficient number of hashes? And would allowing a user to choose a hash instead of having a couple of preset ones be preferable?

**Comment by karliss** [comment]
You can query the full list supported by r2 using `ph=` or `ph?` and populate the list using that at run time. That way there is no hassle with manual entry or not knowing which functions are available without drawbacks of harcoded list.

Calculating and showing all of them would probably be to much which needs that the set currently displayed needs to be user configurable.

**Comment by philipmnelson** [comment]
Okay, it's just going to take me some time to get the UI for that up and running because I'm doing the UI by hand instead of using QT Creator. But that sounds good

**Comment by ITAYC0HEN** [comment]
@philipmnelson any progress? :)
