### ISSUE TITLE
Disassembly view feature requests

### ISSUE THREAD

**Issue by XVilka** [radareorg/cutter#933]
I found no issues about it strangely.

- [ ]     Reference and cross-reference lines like in graph view
- [ ]     Different font for function names
- [ ]     Different color for strings in comments
- [ ]     Ability to text-select disassembly without selecting reflines and addresses
- [ ]     Ability to fold and unfold functions and basic blocks
- [ ]     Quick text search by either Ctrl-F or pressing '/'
- [ ]     Hotkeys for "Undo Seek" and "Redo Seek" menu options

**Comment by Maijin** [comment]
Individual issues created. Closing here - Please provide additional information for the following task  https://github.com/radareorg/cutter/issues/1297
