### ISSUE TITLE
3D graph widget

### ISSUE THREAD

**Issue by XVilka** [radareorg/cutter#934]
It would be nice to have the same graph visualisation capability, but in 3D

It will allow to observe more complex graphs that looks very badly while flattened.

See https://reverseengineering.stackexchange.com/questions/1471/3d-control-flow-graphs-in-ida

![image](https://user-images.githubusercontent.com/203261/48465063-94531000-e81c-11e8-9e46-3ab704700182.png)
![image](https://user-images.githubusercontent.com/203261/48465071-99b05a80-e81c-11e8-8d08-73fbfbd416c3.png)

**Comment by ITAYC0HEN** [comment]
Thanks for the feature request. As discussed by the maintainers, this is not on the road-map of Cutter and currently, we won't implement this feature. However, this might be relevant in the long run and if so, we will revisit this issue
