### ISSUE TITLE
Cutter crashes when using gdb

### ISSUE THREAD

**Issue by Rieselhilfe** [radareorg/cutter#937]
**Environment information**
* Operating System: Manjaro 64 bit
* Cutter version: 1.7.2 using r2 3.0.1
* File format: ELF 64-bit LSB pie executable

**Describe the bug**
When selecting gdb as a debug plugin, Cutter gives the error "ERROR: Underlaying IO descriptor is not a GDB one.." two times in the terminal but gives no error in the gui and continues to work. When starting the emulation, Cutter crashes silently with a seg fault.

**To Reproduce**
1. Select gdb as debug plugin
2. See error in terminal
2. Click on "Start Emulation"
4. Cutter crashes

**Expected behavior**
The emulation starts.

**Additional context**
gdb is installed on my system and works just fine. With native as debug plugin no error occurs.

**Comment by ITAYC0HEN** [comment]
Currently, there is no debugging support in Cutter. This is a work-in-progress and we hope to release a beta-feature in the next few weeks. What you see in Cutter now is not a debugger, it is emulation. It uses the emulation functionality of radare2 -- don't expect results similar to debugging.

Thus, debugging using GDB as a backend would not work as well. When debugging would be implemented, GDB support should be there as well. Stay tuned.

Thank you for opening the issue, I'm closing it for now.
