### ISSUE TITLE
XREF for variables

### ISSUE THREAD

**Issue by Maijin** [radareorg/cutter#948]
The functionnality is now available in radare2 - https://github.com/radare/radare2/pull/12205#issuecomment-440142593

**Comment by radare** [comment]
The functionality was already there. It was just under a different command to make clear that stack refs and global refs are difrerent things

**Comment by Maijin** [comment]
it may be already there, but now it's under the proper command

**Comment by ITAYC0HEN** [comment]
Requiring adding JSON support for `afvx` command (radareorg/radare2#17108) before moving forward. After that, it will be possible to finish this issue

**Comment by ITAYC0HEN** [comment]
Json support added in https://github.com/radareorg/radare2/pull/17218, makes it possible to solve this one :)

**Comment by Maijin** [comment]
Awesome!
