### ISSUE TITLE
Change colors for DisasmGraph (default theme)

### ISSUE THREAD

**Issue by pelijah** [radareorg/cutter#95]
Some instructions and bytes in Disassembly and Graph are the same color as background
![screenshot from 2017-11-05 16-44-39](https://user-images.githubusercontent.com/16493991/32415300-b708ddaa-c248-11e7-8ff4-7c86494c342d.png)
.

**Comment by xarkes** [comment]
Hmm this is unexpected, those are not the default colors.

**Comment by xarkes** [comment]
Are you using the AppImage?

**Comment by pelijah** [comment]
I have built cutter from sources on Ubuntu.

**Comment by xarkes** [comment]
So I believe cutter is not able to find radare2 share directory. Try calling ./sys/install.sh in radare2 directory, this should fix it.

**Comment by pelijah** [comment]
Full r2 reinstallation gives no result. I have no other r2 installations. Version of used r2 is "2.0.1".

**Comment by xarkes** [comment]
Run strace and check where it's looking for the share folder

**Comment by Maijin** [comment]
2.0.1 is not the latest git version

**Comment by xarkes** [comment]
Ah yes the theme used in cutter came with 2.1 iirc

**Comment by Maijin** [comment]
yep

**Comment by pelijah** [comment]
So now line selection is the same color as some text in DiasmGraph.
![screenshot from 2017-11-05 18-25-24](https://user-images.githubusercontent.com/16493991/32416198-bccf4f68-c256-11e7-9b47-3bbec92a2ae5.png)

**Comment by xarkes** [comment]
Hmm strange, please change title I'll check later
