### ISSUE TITLE
Disassembly panel: asm.lines disappear when scrolling down

### ISSUE THREAD

**Issue by dmknght** [radareorg/cutter#952]
**Environment information**
* Operating System: Parrot 4.4 amd 64
* Cutter version: 1.7.2 (git build version)
* File format: ELF 64

**Describe the bug**
A `jump line` (asm.lines) in `Disassembly Panel` disappears from screen if its start position is out of screen. This happens when user scroll down.

**To Reproduce**
1. Reverse binary file (lab2) with default analysis option
2. Use xrefts to find `Enter password` string in memory.
3. Move Panel to Disassembly panel
4. Scroll down and see line disappeared.

**Expected behavior**
Jump line shouldn't disappear

**Screenshots**
1. I have a jump line starts from `0x08048550`
![screenshot at 2018-11-21 17-36-05](https://user-images.githubusercontent.com/29118926/48835951-0c3caf80-edb4-11e8-86d4-980b19029123.png)

2. Its destination points to `0x80485b8`. (Please not that this `jump line` is long
![screenshot at 2018-11-21 17-38-10](https://user-images.githubusercontent.com/29118926/48836029-3aba8a80-edb4-11e8-8c1f-083b6b76f9a1.png)

3. This line disappears when i scroll down (`0x08048550` is out of `Disassembly Panel`)
![screenshot at 2018-11-21 17-38-34](https://user-images.githubusercontent.com/29118926/48836121-72293700-edb4-11e8-85ee-89699872b133.png)

4. If i scroll down more, this jump line appears as dot
![screenshot at 2018-11-21 17-52-17](https://user-images.githubusercontent.com/29118926/48836769-460eb580-edb6-11e8-9111-1c34ef530a25.png)

**Additional context**
* I didn't test any other binary file on other system
* This issue happens to short `jump lines` as well.
* Binary file: 
[binary.zip](https://github.com/radareorg/cutter/files/2603892/binary.zip)

**Comment by securitykitten** [comment]
I recently encountered this issue as well.  

Cutter version (using the AppImage)
```
Version 1.7.2
Using r2-3.1.2
```

To reproduce:
Unzip and open the following NES binary default settings are fine.
[HackingTime_03e852ace386388eb88c39a02f88c773.zip](https://github.com/radareorg/cutter/files/2691073/HackingTime_03e852ace386388eb88c39a02f88c773.zip)

Browse to `fcn.000082f1` in the disassembly window and start scrolling down, text will disappear.

When using the R2 window, the whole function displays just fine.
```
> s 0x000082f1


[0x000082f1]> pdf
/ (fcn) fcn.000082f1 88
|   fcn.000082f1 (int arg_101h);
|           ; arg int arg_101h @ sp+0x101
|           0x000082f1 a000                   ldy #0x00 ; load index y with memory
...snipped...
```

**Comment by ITAYC0HEN** [comment]
can you two try the same in radare2 with the following commands:

```

# open file with r2
$ r2 file

# basic analysis
aaa

# seek to the desired address
s 0xsomething

# open visual disassembly mode
Vp

# now start scrolling using 'j'
```

**Comment by radare** [comment]
this is a bug in asm.bbline

**Comment by radare** [comment]
can you please open the issue in r2 instead?

**Comment by radare** [comment]
tired of waiting

**Comment by radare** [comment]
https://github.com/radare/radare2/issues/12516

**Comment by dmknght** [comment]
I'm sorry i was busy and i didn't check mail. Thanks for the fix.
