### ISSUE TITLE
ARM/Thumb function updating

### ISSUE THREAD

**Issue by matbrik** [radareorg/cutter#953]
**Environment information**
* Operating System: Ubuntu 18
* Cutter version: 1.7.2
* File format: ELF ARM
**Describe the bug**
If Cutter does not detect that a function is thumb code and I set manually the bits to 16 I obtain the correct code but it does not update the boundaries of the function making impossible to use the graph mode. 

tested binary 
[libtmessages.29.zip](https://github.com/radareorg/cutter/files/2604978/libtmessages.29.zip)

Screenshots: 
![s1](https://user-images.githubusercontent.com/6418737/48854261-c252ca00-edb1-11e8-8f89-78ceed2658cd.png)
![s2](https://user-images.githubusercontent.com/6418737/48854266-c4b52400-edb1-11e8-9d78-7e77e3a85919.png)

**Comment by xarkes** [comment]
I'd say it's a bug in radare2.

**Comment by ITAYC0HEN** [comment]
tracked in radare/radare2#12271
