### ISSUE TITLE
Fail to duplicate a theme on Windows

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/cutter#965]
**Environment information**
* Operating System: Windows 10, 64bit
* Cutter version: Newest from GIT
* File format: Any

**Describe the bug**
When trying to copy an existing theme and modifying it, nothing happens. No new theme is created. This works on Linux.

**To Reproduce**
1. Click on Edit in the main menu
2. Click Prefences
3. Choose Appearance 
4. Choose your favorite Color Theme 
5. Click Copy
6. Give it a name
7. Nothing happens

**Expected behavior**
A new theme should be added.

**Screenshots**
![2018-11-28_19-25-15](https://user-images.githubusercontent.com/20182642/49169822-5e954780-f343-11e8-94cd-5cb220e1c1b1.gif)

**Comment by xarkes** [comment]
Also we should switch to this new theme automatically.
