### ISSUE TITLE
Console output should be in Cutter (Console widget) and not in the executing Terminal

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/cutter#966]
**Environment information**
* Operating System: Any
* Cutter version: GIT Version
* File format: ANY

**Describe the bug**
1. Too much useless (debug?) information is printed to the terminal instead of to Cutter's console widget.
2. Many r2 commands' results are printed to the Terminal and not to Cutter's console widget. 
3. Usually on Windows user executes Cutter by double-clicking the exe file so no Terminal involves. This cause them to miss all the information printed to the terminal.

**To Reproduce**
1. Open Cutter from a terminal `./Cutter"
2. Play with Cutter for awhile
3. Look at the output on the terminal

**Expected behavior**
1. All information should be printed to Cutter console's widget and not to the terminal.
2. There is too many noise created by both r2 and Cutter which is not relevant to the user.

**Screenshots**

Analysis info:
![image](https://user-images.githubusercontent.com/20182642/49170629-3dcdf180-f345-11e8-857c-97a9531d34a6.png)

Tasks info:
![image](https://user-images.githubusercontent.com/20182642/49170644-48888680-f345-11e8-95fc-189e1f7fb8fe.png)

Command errors:
![image](https://user-images.githubusercontent.com/20182642/49170672-5a6a2980-f345-11e8-8b96-2d0b2d92391e.png)

Command output:
![image](https://user-images.githubusercontent.com/20182642/49170695-65bd5500-f345-11e8-883b-87afd28a2299.png)

r2 noise:
![image](https://user-images.githubusercontent.com/20182642/49170709-6ce46300-f345-11e8-88c2-3f5e1173a08e.png)

**Comment by yossizap** [comment]
Working on this issue in PR #1821. If you have any additional suggestions or recommendations based on your experience please add them there.
