### ISSUE TITLE
Performance issues with disassembly widget

### ISSUE THREAD

**Issue by xarkes** [radareorg/cutter#972]
**Environment information**
* Operating System: ArchLinux
* Cutter version: 26d985c9dc03f9e14f28e7df6a045feca310ad60
* File format: ELF (7.4MB)

**Describe the bug**
It seems seeking is very slow, unless no disassembly widget is focused.
E.g. in graph view it's smooth, until I switch to disassembly widget or open the xref widget (which uses a disassembly widget)

**To Reproduce**
1. Open a binary such as 010Editor for linux trial version
2. Wait for analysis to complete (afta is quite long there)
3. Seek with disassembly widget focused

**Expected behavior**
Instant seek

**Additional context**
Maybe related to https://github.com/radareorg/cutter/issues/498

**Comment by xarkes** [comment]
Just a thought: maybe it was because of `asm.slow`, need to check again.

**Comment by ITAYC0HEN** [comment]
this wasn't reproducable anymore
