### ISSUE TITLE
Tooltip background is dark-gray even with light themes

### ISSUE THREAD

**Issue by ITAYC0HEN** [radareorg/cutter#983]
**Environment information**
* Operating System: Win10 64bit, Arch Linux 64bit
* Cutter version: Newest from git
* File format: Any

**Describe the bug**

Seems like the tooltip's background is dark-gray even when the QT-theme is native and light. This makes it hard to read the text

![image](https://user-images.githubusercontent.com/20182642/49381468-ab4e9900-f71c-11e8-9d72-4610f8101d17.png)

**To Reproduce**
1. Choose default QT-Theme on light OS theme
2. Hover a function name in the function's window

**Expected behavior**
Tooltip's background color should fit the chosen theme

**Comment by a1ext** [comment]
The tooltip content doesn't have any theme/color-specific code. I think problem is with style sheets.

**Comment by karliss** [comment]
Can this be closed now?

**Comment by ITAYC0HEN** [comment]
return True;
